/* Generated by Together */

#ifndef CLINKPORT_H
#define CLINKPORT_H
class CLinkPort {
public:

	virtual short Open(short port);

	virtual short Close();

	virtual BOOL ReadByte(BYTE& by);

	~CLinkPort();

	CLinkPort();
};
#endif //CLINKPORT_H
