/* Generated by Together */

#ifndef CMSGITEM_H
#define CMSGITEM_H

// #include "..\IPC\SMHdr.h"
#include "..\IPC\SMOL.h"

//#include "CQueue.h"
#include "RtnCode.h"

class CMsgItem {
public:
	BOOL Get(CString& str);
	BOOL Set(CSMOL& SM);
	BOOL Set(CString msg);
	long GetLength();
	long Binary(char* msg);
	BOOL Conv(char* msg);
	long GetSize();
	short Alloc(int size);

	CMsgItem();

	~CMsgItem();

	CRtnCode::RCODE SetAlloc(char* msg, int len);

	enum STSLOC {
		NOTDEF, CASIN1, CASIN2, ALGNR1, ALGNR2, SCALE, CHMBR1, CHMBR2, CASOUT1, CASOUT2
	};
	short STSLocFrom, STSLocTo;
	CSubstObj* pSTSSubstObj;

	int Len;	// This is the length of the message only
	int IDIdx;	/*ID*/	// Incremental message count, change when a message is added to CQueue::AddTail()
	short bRpy;
	char* pMsg;
	HANDLE hEvent;	// This attribute is not send across

	int Unit;
	int AckWnd, Ack, Nak, Ret;
	enum MSGEVENT { MENONE, MEDONE };
	int MsgEvent;
	enum MSGSRC { MSNONE, MSE95, MSB900, MSB128, MSB413 };
	int MsgSrc; // THe originator of the message
	enum MSGDES { MDNONE, MSRBT };
	int MsgDes;	// The intended receiver of the message
	enum DATATYPE {
		SIMPLEDATA, SCANDATA, RECIPEDATA, CASSETTEDATA, ROBOTCMD,
		ROBOTEVENT, EVENTDATA, DATAREQ, DATAREQACK, COMMAND, COMMANDACK,
		SMOLMSG, EQPMSG
	};
	int DataTyp;
	enum DATAID {
		IDNONE, HELLO, HELLOACK, PROCESSCOMPLETE, SV, SV1, TV, WAFERSTATUS, LTwr,
		PROCESSFAILED, PROCESSHALT, OPENCHAMBER, STOPPROCESS, ABORTPROCESS, FFUFAIL, RESETTABLE,
		DONERECOVERY, WAFERPRESENTCHECK
	};
	int DataID;	// Mainly used by EVENTDATA

	/** @link dependency */
	/*# CQueue lnkCQueue; */
};
#endif //CMSGITEM_H
