/* Generated by Together */

#include "stdafx.h"
#include "RbtState.h"
#include "..\..\SRC\DOSUtil.h"

CRbtState::CRbtState()
{
	State = NOTCOMMUNICATING;
	if (!Load())
	{
		Save();
	}
}

CRbtState::~CRbtState()
{
	Save();
}

BOOL CRbtState::Load()
{
	CSingleLock Lock(& CS);
	Lock.Lock();
	CString savefile;
	DosUtil.GetProgramDir(savefile);
	savefile += "\\RbtState.bin";
	CFile theFile;
	if (theFile.Open(savefile, CFile::modeRead))
	{
		CArchive archive(& theFile, CArchive::load);
		Serialize(archive);
		archive.Close();
		theFile.Close();
		return TRUE;
	}
	return FALSE;
}

void CRbtState::Save()
{
	CSingleLock Lock(&CS);
	Lock.Lock();
	CString savefile;

	DosUtil.GetProgramDir(savefile);
	savefile += "\\RbtState.bin";

	CFile theFile;
	if (theFile.Open(savefile, CFile::modeCreate | CFile::modeWrite))
	{
		CArchive archive(&theFile, CArchive::store);
		Serialize(archive);
		archive.Close();
		theFile.Close();
		return ;
	}
}

void CRbtState::Serialize(CArchive & ar)
{
	int val;
	short magic;
	if (ar.IsStoring())
	{
		magic = 1;
		ar << magic;
		val = (int)State;
		ar << val;
	}
	else
	{
		ar >> magic;
		ar >> val;
		State = (STATE)val;
	}
}

void CRbtState::Set(CRbtState::STATE st)
{
	State = st;
	Save();
}

CRbtState::STATE  CRbtState::GetState()
{
	return State;
}

CString CRbtState::GetStateStr()
{
	switch(State)
	{
	case IDLE:
		return "Idle";
		break;
	case MOVING:
		return "Moving";
		break;
	case DOWNED:
		return "Down";
	case NOTCOMMUNICATING:
		return "Not communicating";
		break;
	}
	return "No state";
}

BOOL CRbtState::IsIdle()
{
	return State == IDLE;
}

BOOL CRbtState::SetBusy()
{
	if (State == IDLE)
	{
		State = MOVING;
		return TRUE;
	}
	return FALSE;
}

// LYF Use with care, do not call if robot is moving [9/7/2005]
BOOL CRbtState::SetIdle()
{
	if (State == MOVING)
	{
		State = IDLE;
		return TRUE;
	}
	return FALSE;
}
