/**
 * File: AcquisitionPropertiesListener.h
 * Autogenerated on Mon Nov 16 11:53:35 EST 2009 based on
 * AcquisitionPropertiesListener.java
 * for the Java class
 * com/oceanoptics/omnidriver/interfaces/AcquisitionPropertiesListener
 * Copyright (C) 2006 - 2008 Ocean Optics, Inc.  All rights reserved.
 */


#ifndef ACQUISITIONPROPERTIESLISTENER_H
#define ACQUISITIONPROPERTIESLISTENER_H
#include "BaseJavaClass.h"

#ifdef __cplusplus

#ifdef INCLUDES_IN_HEADER
#endif /* INCLUDES_IN_HEADER */


CLASS_TOKEN EXPORTED AcquisitionPropertiesListener : public BaseJavaClass // CPPClass.getClassDeclaration
{
public: 
	void acquisitionPropertiesChange();
	~AcquisitionPropertiesListener();
	// No public default Java constructor; creating one:
	AcquisitionPropertiesListener();
	// No public Java copy constructor; creating one:
	AcquisitionPropertiesListener(const AcquisitionPropertiesListener &that);
	// Creating assignment operator declaration:
	AcquisitionPropertiesListener &operator=(const AcquisitionPropertiesListener &that);

private:
	jmethodID mid_acquisitionPropertiesChange1300;
	void init_ids(JNIEnv* pJNIEnv);
};

extern "C" {
#endif /* __cplusplus */
#ifndef EXTERN_TYPEDEF_ACQUISITIONPROPERTIESLISTENER_T
#define EXTERN_TYPEDEF_ACQUISITIONPROPERTIESLISTENER_T
	typedef void* ACQUISITIONPROPERTIESLISTENER_T;
#endif /* EXTERN_TYPEDEF_ACQUISITIONPROPERTIESLISTENER_T */

	// No public default Java constructor; creating one:
	EXPORTED ACQUISITIONPROPERTIESLISTENER_T AcquisitionPropertiesListener_Create();
	EXPORTED void AcquisitionPropertiesListener_acquisitionPropertiesChange(ACQUISITIONPROPERTIESLISTENER_T c_acquisition_properties_listener);
	EXPORTED void AcquisitionPropertiesListener_Destroy(ACQUISITIONPROPERTIESLISTENER_T acquisition_properties_listener);

#ifdef WIN32
	// Use the following function prototypes when calling functions from Visual Basic 6
	EXPORTED void STDCALL AcquisitionPropertiesListener_acquisitionPropertiesChange_stdcall(ACQUISITIONPROPERTIESLISTENER_T c_acquisition_properties_listener);
	EXPORTED void STDCALL AcquisitionPropertiesListener_Destroy_stdcall(ACQUISITIONPROPERTIESLISTENER_T acquisition_properties_listener);
#endif /* WIN32 */
#ifdef __cplusplus
};
#endif /* __cplusplus */
#endif /* ACQUISITIONPROPERTIESLISTENER_H */
