/**
 * File: AdvancedIrradianceCalibration.h
 * Autogenerated on Mon Nov 16 11:53:51 EST 2009 based on
 * AdvancedIrradianceCalibration.java
 * for the Java class
 * com/oceanoptics/spam/advancedprocessing/AdvancedIrradianceCalibration
 * Copyright (C) 2006 - 2008 Ocean Optics, Inc.  All rights reserved.
 */


#ifndef ADVANCEDIRRADIANCECALIBRATION_H
#define ADVANCEDIRRADIANCECALIBRATION_H
#include "BaseJavaClass.h"

#ifdef __cplusplus

#ifdef INCLUDES_IN_HEADER
#include "CoreBase.h"
#endif /* INCLUDES_IN_HEADER */

/* Pre-declarations for circular dependencies in header files */
#ifdef CLASS_PREDECLARATIONS
class CoreBase;
#endif /* CLASS_PREDECLARATIONS */

CLASS_TOKEN EXPORTED AdvancedIrradianceCalibration : public CoreBase // CPPClass.getClassDeclaration
{
public: 
	AdvancedIrradianceCalibration();
	DoubleArray processSpectrum(DoubleArray& dark, DoubleArray& light, DoubleArray& wavelengths, DoubleArray& interpolatedLampCalibration, double integrationTimeSeconds, double collectionArea, unsigned char integratingSphere);
	~AdvancedIrradianceCalibration();
	// No public Java copy constructor; creating one:
	AdvancedIrradianceCalibration(const AdvancedIrradianceCalibration &that);
	// Creating assignment operator declaration:
	AdvancedIrradianceCalibration &operator=(const AdvancedIrradianceCalibration &that);

private:
	jmethodID mid_AdvancedIrradianceCalibration4;
	jmethodID mid_processSpectrum5;
	void init_ids(JNIEnv* pJNIEnv);
};

extern "C" {
#endif /* __cplusplus */
#ifndef EXTERN_TYPEDEF_COREBASE_T
#define EXTERN_TYPEDEF_COREBASE_T
	typedef void* COREBASE_T;
#endif /* EXTERN_TYPEDEF_COREBASE_T */
#ifndef EXTERN_TYPEDEF_ADVANCEDIRRADIANCECALIBRATION_T
#define EXTERN_TYPEDEF_ADVANCEDIRRADIANCECALIBRATION_T
	typedef void* ADVANCEDIRRADIANCECALIBRATION_T;
#endif /* EXTERN_TYPEDEF_ADVANCEDIRRADIANCECALIBRATION_T */

	EXPORTED ADVANCEDIRRADIANCECALIBRATION_T AdvancedIrradianceCalibration_Create();
	EXPORTED void AdvancedIrradianceCalibration_processSpectrum(ADVANCEDIRRADIANCECALIBRATION_T c_advanced_irradiance_calibration, DOUBLEARRAY_T dark, DOUBLEARRAY_T light, DOUBLEARRAY_T wavelengths, DOUBLEARRAY_T interpolatedLampCalibration, double integrationTimeSeconds, double collectionArea, unsigned char integratingSphere, DOUBLEARRAY_T retval);
	EXPORTED void AdvancedIrradianceCalibration_Destroy(ADVANCEDIRRADIANCECALIBRATION_T advanced_irradiance_calibration);

#ifdef WIN32
	// Use the following function prototypes when calling functions from Visual Basic 6
	EXPORTED ADVANCEDIRRADIANCECALIBRATION_T STDCALL AdvancedIrradianceCalibration_Create_stdcall();
	EXPORTED void STDCALL AdvancedIrradianceCalibration_processSpectrum_stdcall(ADVANCEDIRRADIANCECALIBRATION_T c_advanced_irradiance_calibration, DOUBLEARRAY_T dark, DOUBLEARRAY_T light, DOUBLEARRAY_T wavelengths, DOUBLEARRAY_T interpolatedLampCalibration, double integrationTimeSeconds, double collectionArea, unsigned char integratingSphere, DOUBLEARRAY_T retval);
	EXPORTED void STDCALL AdvancedIrradianceCalibration_Destroy_stdcall(ADVANCEDIRRADIANCECALIBRATION_T advanced_irradiance_calibration);
#endif /* WIN32 */
#ifdef __cplusplus
};
#endif /* __cplusplus */
#endif /* ADVANCEDIRRADIANCECALIBRATION_H */
