/**
 * File: ArrayMath.h
 * Autogenerated on Mon Nov 16 11:53:52 EST 2009 based on
 * ArrayMath.java
 * for the Java class
 * com/oceanoptics/spam/arraymath/ArrayMath
 * Copyright (C) 2006 - 2008 Ocean Optics, Inc.  All rights reserved.
 */


#ifndef ARRAYMATH_H
#define ARRAYMATH_H
#include "BaseJavaClass.h"

#ifdef __cplusplus

#ifdef INCLUDES_IN_HEADER
#endif /* INCLUDES_IN_HEADER */


CLASS_TOKEN EXPORTED ArrayMath : public BaseJavaClass // CPPClass.getClassDeclaration
{
public: 
	ArrayMath();
	DoubleArray clipArray(DoubleArray& inputArray, double minimumValue, double maximumValue);
	DoubleArray multiplyArray(DoubleArray& a, DoubleArray& b);
	DoubleArray addArray(DoubleArray& a, DoubleArray& b);
	DoubleArray subtractArray(DoubleArray& a, DoubleArray& b);
	DoubleArray divideArray(DoubleArray& a, DoubleArray& b);
	DoubleArray multiplyConstant(DoubleArray& a, double num);
	DoubleArray addConstant(DoubleArray& a, double num);
	DoubleArray subtractConstant(DoubleArray& a, double num);
	DoubleArray divideConstant(DoubleArray& a, double num);
	DoubleArray log10Array(DoubleArray& a);
	~ArrayMath();
	// No public Java copy constructor; creating one:
	ArrayMath(const ArrayMath &that);
	// Creating assignment operator declaration:
	ArrayMath &operator=(const ArrayMath &that);

private:
	jmethodID mid_ArrayMath158;
	jmethodID mid_clipArray159;
	jmethodID mid_multiplyArray160;
	jmethodID mid_addArray161;
	jmethodID mid_subtractArray162;
	jmethodID mid_divideArray163;
	jmethodID mid_multiplyConstant164;
	jmethodID mid_addConstant165;
	jmethodID mid_subtractConstant166;
	jmethodID mid_divideConstant167;
	jmethodID mid_log10Array168;
	void init_ids(JNIEnv* pJNIEnv);
};

extern "C" {
#endif /* __cplusplus */
#ifndef EXTERN_TYPEDEF_ARRAYMATH_T
#define EXTERN_TYPEDEF_ARRAYMATH_T
	typedef void* ARRAYMATH_T;
#endif /* EXTERN_TYPEDEF_ARRAYMATH_T */

	EXPORTED ARRAYMATH_T ArrayMath_Create();
	EXPORTED void ArrayMath_clipArray(ARRAYMATH_T c_array_math, DOUBLEARRAY_T inputArray, double minimumValue, double maximumValue, DOUBLEARRAY_T retval);
	EXPORTED void ArrayMath_multiplyArray(ARRAYMATH_T c_array_math, DOUBLEARRAY_T a, DOUBLEARRAY_T b, DOUBLEARRAY_T retval);
	EXPORTED void ArrayMath_addArray(ARRAYMATH_T c_array_math, DOUBLEARRAY_T a, DOUBLEARRAY_T b, DOUBLEARRAY_T retval);
	EXPORTED void ArrayMath_subtractArray(ARRAYMATH_T c_array_math, DOUBLEARRAY_T a, DOUBLEARRAY_T b, DOUBLEARRAY_T retval);
	EXPORTED void ArrayMath_divideArray(ARRAYMATH_T c_array_math, DOUBLEARRAY_T a, DOUBLEARRAY_T b, DOUBLEARRAY_T retval);
	EXPORTED void ArrayMath_multiplyConstant(ARRAYMATH_T c_array_math, DOUBLEARRAY_T a, double num, DOUBLEARRAY_T retval);
	EXPORTED void ArrayMath_addConstant(ARRAYMATH_T c_array_math, DOUBLEARRAY_T a, double num, DOUBLEARRAY_T retval);
	EXPORTED void ArrayMath_subtractConstant(ARRAYMATH_T c_array_math, DOUBLEARRAY_T a, double num, DOUBLEARRAY_T retval);
	EXPORTED void ArrayMath_divideConstant(ARRAYMATH_T c_array_math, DOUBLEARRAY_T a, double num, DOUBLEARRAY_T retval);
	EXPORTED void ArrayMath_log10Array(ARRAYMATH_T c_array_math, DOUBLEARRAY_T a, DOUBLEARRAY_T retval);
	EXPORTED void ArrayMath_Destroy(ARRAYMATH_T array_math);

#ifdef WIN32
	// Use the following function prototypes when calling functions from Visual Basic 6
	EXPORTED ARRAYMATH_T STDCALL ArrayMath_Create_stdcall();
	EXPORTED void STDCALL ArrayMath_clipArray_stdcall(ARRAYMATH_T c_array_math, DOUBLEARRAY_T inputArray, double minimumValue, double maximumValue, DOUBLEARRAY_T retval);
	EXPORTED void STDCALL ArrayMath_multiplyArray_stdcall(ARRAYMATH_T c_array_math, DOUBLEARRAY_T a, DOUBLEARRAY_T b, DOUBLEARRAY_T retval);
	EXPORTED void STDCALL ArrayMath_addArray_stdcall(ARRAYMATH_T c_array_math, DOUBLEARRAY_T a, DOUBLEARRAY_T b, DOUBLEARRAY_T retval);
	EXPORTED void STDCALL ArrayMath_subtractArray_stdcall(ARRAYMATH_T c_array_math, DOUBLEARRAY_T a, DOUBLEARRAY_T b, DOUBLEARRAY_T retval);
	EXPORTED void STDCALL ArrayMath_divideArray_stdcall(ARRAYMATH_T c_array_math, DOUBLEARRAY_T a, DOUBLEARRAY_T b, DOUBLEARRAY_T retval);
	EXPORTED void STDCALL ArrayMath_multiplyConstant_stdcall(ARRAYMATH_T c_array_math, DOUBLEARRAY_T a, double num, DOUBLEARRAY_T retval);
	EXPORTED void STDCALL ArrayMath_addConstant_stdcall(ARRAYMATH_T c_array_math, DOUBLEARRAY_T a, double num, DOUBLEARRAY_T retval);
	EXPORTED void STDCALL ArrayMath_subtractConstant_stdcall(ARRAYMATH_T c_array_math, DOUBLEARRAY_T a, double num, DOUBLEARRAY_T retval);
	EXPORTED void STDCALL ArrayMath_divideConstant_stdcall(ARRAYMATH_T c_array_math, DOUBLEARRAY_T a, double num, DOUBLEARRAY_T retval);
	EXPORTED void STDCALL ArrayMath_log10Array_stdcall(ARRAYMATH_T c_array_math, DOUBLEARRAY_T a, DOUBLEARRAY_T retval);
	EXPORTED void STDCALL ArrayMath_Destroy_stdcall(ARRAYMATH_T array_math);
#endif /* WIN32 */
#ifdef __cplusplus
};
#endif /* __cplusplus */
#endif /* ARRAYMATH_H */
