/**
 * File: BoardTemperatureImpl_QE65000.h
 * Autogenerated on Mon Nov 16 11:53:33 EST 2009 based on
 * BoardTemperatureImpl_QE65000.java
 * for the Java class
 * com/oceanoptics/omnidriver/features/boardtemperature/BoardTemperatureImpl_QE65000
 * Copyright (C) 2006 - 2008 Ocean Optics, Inc.  All rights reserved.
 */


#ifndef BOARDTEMPERATUREIMPL_QE65000_H
#define BOARDTEMPERATUREIMPL_QE65000_H
#include "BaseJavaClass.h"

#ifdef __cplusplus

#ifdef INCLUDES_IN_HEADER
#include "BoardTemperatureImpl.h"
#include "USBInterface.h"
#include "JStringArray.h"
#endif /* INCLUDES_IN_HEADER */

/* Pre-declarations for circular dependencies in header files */
#ifdef CLASS_PREDECLARATIONS
class BoardTemperatureImpl;
class USBInterface;
class JStringArray;
#endif /* CLASS_PREDECLARATIONS */

CLASS_TOKEN EXPORTED BoardTemperatureImpl_QE65000 : public BoardTemperatureImpl // CPPClass.getClassDeclaration
{
public: 
	BoardTemperatureImpl_QE65000(USBInterface& usbInt);
	double getBoardTemperatureCelsius();
	JStringArray getFeatureGUIClassnames();
	~BoardTemperatureImpl_QE65000();
	// No public default Java constructor; creating one:
	BoardTemperatureImpl_QE65000();
	// No public Java copy constructor; creating one:
	BoardTemperatureImpl_QE65000(const BoardTemperatureImpl_QE65000 &that);
	// Creating assignment operator declaration:
	BoardTemperatureImpl_QE65000 &operator=(const BoardTemperatureImpl_QE65000 &that);

private:
	jmethodID mid_BoardTemperatureImpl_QE65000597;
	jmethodID mid_getBoardTemperatureCelsius598;
	jmethodID mid_getFeatureGUIClassnames599;
	void init_ids(JNIEnv* pJNIEnv);
};

extern "C" {
#endif /* __cplusplus */
#ifndef EXTERN_TYPEDEF_BOARDTEMPERATUREIMPL_T
#define EXTERN_TYPEDEF_BOARDTEMPERATUREIMPL_T
	typedef void* BOARDTEMPERATUREIMPL_T;
#endif /* EXTERN_TYPEDEF_BOARDTEMPERATUREIMPL_T */
#ifndef EXTERN_TYPEDEF_USBINTERFACE_T
#define EXTERN_TYPEDEF_USBINTERFACE_T
	typedef void* USBINTERFACE_T;
#endif /* EXTERN_TYPEDEF_USBINTERFACE_T */
#ifndef EXTERN_TYPEDEF_JSTRINGARRAY_T
#define EXTERN_TYPEDEF_JSTRINGARRAY_T
	typedef void* JSTRINGARRAY_T;
#endif /* EXTERN_TYPEDEF_JSTRINGARRAY_T */
#ifndef EXTERN_TYPEDEF_BOARDTEMPERATUREIMPL_QE65000_T
#define EXTERN_TYPEDEF_BOARDTEMPERATUREIMPL_QE65000_T
	typedef void* BOARDTEMPERATUREIMPL_QE65000_T;
#endif /* EXTERN_TYPEDEF_BOARDTEMPERATUREIMPL_QE65000_T */

	// No public default Java constructor; creating one:
	EXPORTED BOARDTEMPERATUREIMPL_QE65000_T BoardTemperatureImpl_QE65000_Create();
	EXPORTED BOARDTEMPERATUREIMPL_QE65000_T BoardTemperatureImpl_QE65000_Create_1(USBINTERFACE_T usbInt);
	EXPORTED double BoardTemperatureImpl_QE65000_getBoardTemperatureCelsius(BOARDTEMPERATUREIMPL_QE65000_T c_board_temperature_impl_q_e65000);
	EXPORTED void BoardTemperatureImpl_QE65000_getFeatureGUIClassnames(BOARDTEMPERATUREIMPL_QE65000_T c_board_temperature_impl_q_e65000, JSTRINGARRAY_T retval);
	EXPORTED void BoardTemperatureImpl_QE65000_Destroy(BOARDTEMPERATUREIMPL_QE65000_T board_temperature_impl_q_e65000);

#ifdef WIN32
	// Use the following function prototypes when calling functions from Visual Basic 6
	EXPORTED BOARDTEMPERATUREIMPL_QE65000_T STDCALL BoardTemperatureImpl_QE65000_Create_stdcall_1(USBINTERFACE_T usbInt);
	EXPORTED double STDCALL BoardTemperatureImpl_QE65000_getBoardTemperatureCelsius_stdcall(BOARDTEMPERATUREIMPL_QE65000_T c_board_temperature_impl_q_e65000);
	EXPORTED void STDCALL BoardTemperatureImpl_QE65000_getFeatureGUIClassnames_stdcall(BOARDTEMPERATUREIMPL_QE65000_T c_board_temperature_impl_q_e65000, JSTRINGARRAY_T retval);
	EXPORTED void STDCALL BoardTemperatureImpl_QE65000_Destroy_stdcall(BOARDTEMPERATUREIMPL_QE65000_T board_temperature_impl_q_e65000);
#endif /* WIN32 */
#ifdef __cplusplus
};
#endif /* __cplusplus */
#endif /* BOARDTEMPERATUREIMPL_QE65000_H */
