/**
 * File: CCDShutterGUIProvider.h
 * Autogenerated on Mon Nov 16 11:53:38 EST 2009 based on
 * CCDShutterGUIProvider.java
 * for the Java class
 * com/oceanoptics/omnidriver/spectrometer/mmsraman/features/ccdshutter/CCDShutterGUIProvider
 * Copyright (C) 2006 - 2008 Ocean Optics, Inc.  All rights reserved.
 */


#ifndef CCDSHUTTERGUIPROVIDER_H
#define CCDSHUTTERGUIPROVIDER_H
#include "BaseJavaClass.h"

#ifdef __cplusplus

#ifdef INCLUDES_IN_HEADER
#endif /* INCLUDES_IN_HEADER */


CLASS_TOKEN EXPORTED CCDShutterGUIProvider : public BaseJavaClass // CPPClass.getClassDeclaration
{
public: 
	~CCDShutterGUIProvider();
	// No public default Java constructor; creating one:
	CCDShutterGUIProvider();
	// No public Java copy constructor; creating one:
	CCDShutterGUIProvider(const CCDShutterGUIProvider &that);
	// Creating assignment operator declaration:
	CCDShutterGUIProvider &operator=(const CCDShutterGUIProvider &that);

private:
	void init_ids(JNIEnv* pJNIEnv);
};

extern "C" {
#endif /* __cplusplus */
#ifndef EXTERN_TYPEDEF_CCDSHUTTERGUIPROVIDER_T
#define EXTERN_TYPEDEF_CCDSHUTTERGUIPROVIDER_T
	typedef void* CCDSHUTTERGUIPROVIDER_T;
#endif /* EXTERN_TYPEDEF_CCDSHUTTERGUIPROVIDER_T */

	// No public default Java constructor; creating one:
	EXPORTED CCDSHUTTERGUIPROVIDER_T CCDShutterGUIProvider_Create();
	EXPORTED void CCDShutterGUIProvider_Destroy(CCDSHUTTERGUIPROVIDER_T ccdshutterguiprovider);

#ifdef WIN32
	// Use the following function prototypes when calling functions from Visual Basic 6
	EXPORTED void STDCALL CCDShutterGUIProvider_Destroy_stdcall(CCDSHUTTERGUIPROVIDER_T ccdshutterguiprovider);
#endif /* WIN32 */
#ifdef __cplusplus
};
#endif /* __cplusplus */
#endif /* CCDSHUTTERGUIPROVIDER_H */
