/**
 * File: CIEConstants.h
 * Autogenerated on Mon Nov 16 11:53:52 EST 2009 based on
 * CIEConstants.java
 * for the Java class
 * com/oceanoptics/spam/constants/CIEConstants
 * Copyright (C) 2006 - 2008 Ocean Optics, Inc.  All rights reserved.
 */


#ifndef CIECONSTANTS_H
#define CIECONSTANTS_H
#include "BaseJavaClass.h"

#ifdef __cplusplus

#ifdef INCLUDES_IN_HEADER
#include "CIEDaylightSPDFactors.h"
#include "CIETestColorSample.h"
#include "CIETestColorSampleArray.h"
#include "JString.h"
#include "CIEIlluminant.h"
#include "Illuminant.h"
#include "CIEIlluminantArray.h"
#include "CIEObserver.h"
#include "CIEObserverArray.h"
#endif /* INCLUDES_IN_HEADER */

/* Pre-declarations for circular dependencies in header files */
#ifdef CLASS_PREDECLARATIONS
class CIEDaylightSPDFactors;
class CIETestColorSample;
class CIETestColorSampleArray;
class JString;
class CIEIlluminant;
class Illuminant;
class CIEIlluminantArray;
class CIEObserver;
class CIEObserverArray;
#endif /* CLASS_PREDECLARATIONS */

CLASS_TOKEN EXPORTED CIEConstants : public BaseJavaClass // CPPClass.getClassDeclaration
{
public: 
	CIEConstants();
	CIEDaylightSPDFactors getDaylightSPDFactors();
	CIETestColorSample getTestColorSample(int cieIndex);
	CIETestColorSampleArray getTestColorSamples();
	CIEIlluminant getIlluminant(JString& name);
	Illuminant getIlluminantByName(JString& name);
	CIEIlluminantArray getIlluminants();
	int getNumberOfIlluminants();
	CIEIlluminant getCIEIlluminantByIndex(int index);
	Illuminant getIlluminantByIndex(int index);
	CIEObserver getObserver(JString& name);
	CIEObserverArray getObservers();
	int getNumberOfObservers();
	CIEObserver getCIEObserverByIndex(int index);
	void loadAllConstants();
	~CIEConstants();
	// No public Java copy constructor; creating one:
	CIEConstants(const CIEConstants &that);
	// Creating assignment operator declaration:
	CIEConstants &operator=(const CIEConstants &that);

private:
	jmethodID mid_CIEConstants177;
	jmethodID mid_getDaylightSPDFactors178;
	jmethodID mid_getTestColorSample179;
	jmethodID mid_getTestColorSamples180;
	jmethodID mid_getIlluminant181;
	jmethodID mid_getIlluminantByName182;
	jmethodID mid_getIlluminants183;
	jmethodID mid_getNumberOfIlluminants184;
	jmethodID mid_getCIEIlluminantByIndex185;
	jmethodID mid_getIlluminantByIndex186;
	jmethodID mid_getObserver187;
	jmethodID mid_getObservers188;
	jmethodID mid_getNumberOfObservers189;
	jmethodID mid_getCIEObserverByIndex190;
	jmethodID mid_loadAllConstants191;
	void init_ids(JNIEnv* pJNIEnv);
};

extern "C" {
#endif /* __cplusplus */
#ifndef EXTERN_TYPEDEF_CIEDAYLIGHTSPDFACTORS_T
#define EXTERN_TYPEDEF_CIEDAYLIGHTSPDFACTORS_T
	typedef void* CIEDAYLIGHTSPDFACTORS_T;
#endif /* EXTERN_TYPEDEF_CIEDAYLIGHTSPDFACTORS_T */
#ifndef EXTERN_TYPEDEF_CIETESTCOLORSAMPLE_T
#define EXTERN_TYPEDEF_CIETESTCOLORSAMPLE_T
	typedef void* CIETESTCOLORSAMPLE_T;
#endif /* EXTERN_TYPEDEF_CIETESTCOLORSAMPLE_T */
#ifndef EXTERN_TYPEDEF_CIETESTCOLORSAMPLEARRAY_T
#define EXTERN_TYPEDEF_CIETESTCOLORSAMPLEARRAY_T
	typedef void* CIETESTCOLORSAMPLEARRAY_T;
#endif /* EXTERN_TYPEDEF_CIETESTCOLORSAMPLEARRAY_T */
#ifndef EXTERN_TYPEDEF_JSTRING_T
#define EXTERN_TYPEDEF_JSTRING_T
	typedef void* JSTRING_T;
#endif /* EXTERN_TYPEDEF_JSTRING_T */
#ifndef EXTERN_TYPEDEF_CIEILLUMINANT_T
#define EXTERN_TYPEDEF_CIEILLUMINANT_T
	typedef void* CIEILLUMINANT_T;
#endif /* EXTERN_TYPEDEF_CIEILLUMINANT_T */
#ifndef EXTERN_TYPEDEF_ILLUMINANT_T
#define EXTERN_TYPEDEF_ILLUMINANT_T
	typedef void* ILLUMINANT_T;
#endif /* EXTERN_TYPEDEF_ILLUMINANT_T */
#ifndef EXTERN_TYPEDEF_CIEILLUMINANTARRAY_T
#define EXTERN_TYPEDEF_CIEILLUMINANTARRAY_T
	typedef void* CIEILLUMINANTARRAY_T;
#endif /* EXTERN_TYPEDEF_CIEILLUMINANTARRAY_T */
#ifndef EXTERN_TYPEDEF_CIEOBSERVER_T
#define EXTERN_TYPEDEF_CIEOBSERVER_T
	typedef void* CIEOBSERVER_T;
#endif /* EXTERN_TYPEDEF_CIEOBSERVER_T */
#ifndef EXTERN_TYPEDEF_CIEOBSERVERARRAY_T
#define EXTERN_TYPEDEF_CIEOBSERVERARRAY_T
	typedef void* CIEOBSERVERARRAY_T;
#endif /* EXTERN_TYPEDEF_CIEOBSERVERARRAY_T */
#ifndef EXTERN_TYPEDEF_CIECONSTANTS_T
#define EXTERN_TYPEDEF_CIECONSTANTS_T
	typedef void* CIECONSTANTS_T;
#endif /* EXTERN_TYPEDEF_CIECONSTANTS_T */

	EXPORTED CIECONSTANTS_T CIEConstants_Create();
	EXPORTED void CIEConstants_getDaylightSPDFactors(CIECONSTANTS_T c_cieconstants, CIEDAYLIGHTSPDFACTORS_T retval);
	EXPORTED void CIEConstants_getTestColorSample(CIECONSTANTS_T c_cieconstants, int cieIndex, CIETESTCOLORSAMPLE_T retval);
	EXPORTED void CIEConstants_getTestColorSamples(CIECONSTANTS_T c_cieconstants, CIETESTCOLORSAMPLEARRAY_T retval);
	EXPORTED void CIEConstants_getIlluminant(CIECONSTANTS_T c_cieconstants, JSTRING_T name, CIEILLUMINANT_T retval);
	EXPORTED void CIEConstants_getIlluminantByName(CIECONSTANTS_T c_cieconstants, JSTRING_T name, ILLUMINANT_T retval);
	EXPORTED void CIEConstants_getIlluminants(CIECONSTANTS_T c_cieconstants, CIEILLUMINANTARRAY_T retval);
	EXPORTED int CIEConstants_getNumberOfIlluminants(CIECONSTANTS_T c_cieconstants);
	EXPORTED void CIEConstants_getCIEIlluminantByIndex(CIECONSTANTS_T c_cieconstants, int index, CIEILLUMINANT_T retval);
	EXPORTED void CIEConstants_getIlluminantByIndex(CIECONSTANTS_T c_cieconstants, int index, ILLUMINANT_T retval);
	EXPORTED void CIEConstants_getObserver(CIECONSTANTS_T c_cieconstants, JSTRING_T name, CIEOBSERVER_T retval);
	EXPORTED void CIEConstants_getObservers(CIECONSTANTS_T c_cieconstants, CIEOBSERVERARRAY_T retval);
	EXPORTED int CIEConstants_getNumberOfObservers(CIECONSTANTS_T c_cieconstants);
	EXPORTED void CIEConstants_getCIEObserverByIndex(CIECONSTANTS_T c_cieconstants, int index, CIEOBSERVER_T retval);
	EXPORTED void CIEConstants_loadAllConstants(CIECONSTANTS_T c_cieconstants);
	EXPORTED void CIEConstants_Destroy(CIECONSTANTS_T cieconstants);

#ifdef WIN32
	// Use the following function prototypes when calling functions from Visual Basic 6
	EXPORTED CIECONSTANTS_T STDCALL CIEConstants_Create_stdcall();
	EXPORTED void STDCALL CIEConstants_getDaylightSPDFactors_stdcall(CIECONSTANTS_T c_cieconstants, CIEDAYLIGHTSPDFACTORS_T retval);
	EXPORTED void STDCALL CIEConstants_getTestColorSample_stdcall(CIECONSTANTS_T c_cieconstants, int cieIndex, CIETESTCOLORSAMPLE_T retval);
	EXPORTED void STDCALL CIEConstants_getTestColorSamples_stdcall(CIECONSTANTS_T c_cieconstants, CIETESTCOLORSAMPLEARRAY_T retval);
	EXPORTED void STDCALL CIEConstants_getIlluminant_stdcall(CIECONSTANTS_T c_cieconstants, JSTRING_T name, CIEILLUMINANT_T retval);
	EXPORTED void STDCALL CIEConstants_getIlluminantByName_stdcall(CIECONSTANTS_T c_cieconstants, JSTRING_T name, ILLUMINANT_T retval);
	EXPORTED void STDCALL CIEConstants_getIlluminants_stdcall(CIECONSTANTS_T c_cieconstants, CIEILLUMINANTARRAY_T retval);
	EXPORTED int STDCALL CIEConstants_getNumberOfIlluminants_stdcall(CIECONSTANTS_T c_cieconstants);
	EXPORTED void STDCALL CIEConstants_getCIEIlluminantByIndex_stdcall(CIECONSTANTS_T c_cieconstants, int index, CIEILLUMINANT_T retval);
	EXPORTED void STDCALL CIEConstants_getIlluminantByIndex_stdcall(CIECONSTANTS_T c_cieconstants, int index, ILLUMINANT_T retval);
	EXPORTED void STDCALL CIEConstants_getObserver_stdcall(CIECONSTANTS_T c_cieconstants, JSTRING_T name, CIEOBSERVER_T retval);
	EXPORTED void STDCALL CIEConstants_getObservers_stdcall(CIECONSTANTS_T c_cieconstants, CIEOBSERVERARRAY_T retval);
	EXPORTED int STDCALL CIEConstants_getNumberOfObservers_stdcall(CIECONSTANTS_T c_cieconstants);
	EXPORTED void STDCALL CIEConstants_getCIEObserverByIndex_stdcall(CIECONSTANTS_T c_cieconstants, int index, CIEOBSERVER_T retval);
	EXPORTED void STDCALL CIEConstants_loadAllConstants_stdcall(CIECONSTANTS_T c_cieconstants);
	EXPORTED void STDCALL CIEConstants_Destroy_stdcall(CIECONSTANTS_T cieconstants);
#endif /* WIN32 */
#ifdef __cplusplus
};
#endif /* __cplusplus */
#endif /* CIECONSTANTS_H */
