/**
 * File: EnableProgramImpl.h
 * Autogenerated on Mon Nov 16 11:53:29 EST 2009 based on
 * EnableProgramImpl.java
 * for the Java class
 * com/oceanoptics/omnidriver/accessories/mikropack/commands/enableprogram/EnableProgramImpl
 * Copyright (C) 2006 - 2008 Ocean Optics, Inc.  All rights reserved.
 */


#ifndef ENABLEPROGRAMIMPL_H
#define ENABLEPROGRAMIMPL_H
#include "BaseJavaClass.h"

#ifdef __cplusplus

#ifdef INCLUDES_IN_HEADER
#include "FaulhaberCommandOnly.h"
#include "UniRS232.h"
#include "Node.h"
#endif /* INCLUDES_IN_HEADER */

/* Pre-declarations for circular dependencies in header files */
#ifdef CLASS_PREDECLARATIONS
class FaulhaberCommandOnly;
class UniRS232;
class Node;
#endif /* CLASS_PREDECLARATIONS */

CLASS_TOKEN EXPORTED EnableProgramImpl : public FaulhaberCommandOnly // CPPClass.getClassDeclaration
{
public: 
	EnableProgramImpl(UniRS232& serPort);
	void enableProgram(Node& node);
	~EnableProgramImpl();
	// No public default Java constructor; creating one:
	EnableProgramImpl();
	// No public Java copy constructor; creating one:
	EnableProgramImpl(const EnableProgramImpl &that);
	// Creating assignment operator declaration:
	EnableProgramImpl &operator=(const EnableProgramImpl &that);

private:
	jmethodID mid_EnableProgramImpl53;
	jmethodID mid_enableProgram54;
	void init_ids(JNIEnv* pJNIEnv);
};

extern "C" {
#endif /* __cplusplus */
#ifndef EXTERN_TYPEDEF_FAULHABERCOMMANDONLY_T
#define EXTERN_TYPEDEF_FAULHABERCOMMANDONLY_T
	typedef void* FAULHABERCOMMANDONLY_T;
#endif /* EXTERN_TYPEDEF_FAULHABERCOMMANDONLY_T */
#ifndef EXTERN_TYPEDEF_UNIRS232_T
#define EXTERN_TYPEDEF_UNIRS232_T
	typedef void* UNIRS232_T;
#endif /* EXTERN_TYPEDEF_UNIRS232_T */
#ifndef EXTERN_TYPEDEF_NODE_T
#define EXTERN_TYPEDEF_NODE_T
	typedef void* NODE_T;
#endif /* EXTERN_TYPEDEF_NODE_T */
#ifndef EXTERN_TYPEDEF_ENABLEPROGRAMIMPL_T
#define EXTERN_TYPEDEF_ENABLEPROGRAMIMPL_T
	typedef void* ENABLEPROGRAMIMPL_T;
#endif /* EXTERN_TYPEDEF_ENABLEPROGRAMIMPL_T */

	// No public default Java constructor; creating one:
	EXPORTED ENABLEPROGRAMIMPL_T EnableProgramImpl_Create();
	EXPORTED ENABLEPROGRAMIMPL_T EnableProgramImpl_Create_1(UNIRS232_T serPort);
	EXPORTED void EnableProgramImpl_enableProgram(ENABLEPROGRAMIMPL_T c_enable_program_impl, NODE_T node);
	EXPORTED void EnableProgramImpl_Destroy(ENABLEPROGRAMIMPL_T enable_program_impl);

#ifdef WIN32
	// Use the following function prototypes when calling functions from Visual Basic 6
	EXPORTED ENABLEPROGRAMIMPL_T STDCALL EnableProgramImpl_Create_stdcall_1(UNIRS232_T serPort);
	EXPORTED void STDCALL EnableProgramImpl_enableProgram_stdcall(ENABLEPROGRAMIMPL_T c_enable_program_impl, NODE_T node);
	EXPORTED void STDCALL EnableProgramImpl_Destroy_stdcall(ENABLEPROGRAMIMPL_T enable_program_impl);
#endif /* WIN32 */
#ifdef __cplusplus
};
#endif /* __cplusplus */
#endif /* ENABLEPROGRAMIMPL_H */
