/**
 * File: ExternalTriggerDelayImpl_Jaz.h
 * Autogenerated on Mon Nov 16 11:53:33 EST 2009 based on
 * ExternalTriggerDelayImpl_Jaz.java
 * for the Java class
 * com/oceanoptics/omnidriver/features/externaltriggerdelay/ExternalTriggerDelayImpl_Jaz
 * Copyright (C) 2006 - 2008 Ocean Optics, Inc.  All rights reserved.
 */


#ifndef EXTERNALTRIGGERDELAYIMPL_JAZ_H
#define EXTERNALTRIGGERDELAYIMPL_JAZ_H
#include "BaseJavaClass.h"

#ifdef __cplusplus

#ifdef INCLUDES_IN_HEADER
#include "JStringArray.h"
#endif /* INCLUDES_IN_HEADER */

/* Pre-declarations for circular dependencies in header files */
#ifdef CLASS_PREDECLARATIONS
class JStringArray;
#endif /* CLASS_PREDECLARATIONS */

CLASS_TOKEN EXPORTED ExternalTriggerDelayImpl_Jaz : public BaseJavaClass // CPPClass.getClassDeclaration
{
public: 
	double triggerDelayCountsToMicroseconds(int counts);
	void setExternalTriggerDelay(int counts);
	JStringArray getFeatureGUIClassnames();
	int getExternalTriggerDelayMinimum();
	int getExternalTriggerDelayMaximum();
	int getExternalTriggerDelayIncrement();
	~ExternalTriggerDelayImpl_Jaz();
	// No public default Java constructor; creating one:
	ExternalTriggerDelayImpl_Jaz();
	// No public Java copy constructor; creating one:
	ExternalTriggerDelayImpl_Jaz(const ExternalTriggerDelayImpl_Jaz &that);
	// Creating assignment operator declaration:
	ExternalTriggerDelayImpl_Jaz &operator=(const ExternalTriggerDelayImpl_Jaz &that);

private:
	jmethodID mid_triggerDelayCountsToMicroseconds691;
	jmethodID mid_setExternalTriggerDelay692;
	jmethodID mid_getFeatureGUIClassnames693;
	jmethodID mid_getExternalTriggerDelayMinimum694;
	jmethodID mid_getExternalTriggerDelayMaximum695;
	jmethodID mid_getExternalTriggerDelayIncrement696;
	void init_ids(JNIEnv* pJNIEnv);
};

extern "C" {
#endif /* __cplusplus */
#ifndef EXTERN_TYPEDEF_JSTRINGARRAY_T
#define EXTERN_TYPEDEF_JSTRINGARRAY_T
	typedef void* JSTRINGARRAY_T;
#endif /* EXTERN_TYPEDEF_JSTRINGARRAY_T */
#ifndef EXTERN_TYPEDEF_EXTERNALTRIGGERDELAYIMPL_JAZ_T
#define EXTERN_TYPEDEF_EXTERNALTRIGGERDELAYIMPL_JAZ_T
	typedef void* EXTERNALTRIGGERDELAYIMPL_JAZ_T;
#endif /* EXTERN_TYPEDEF_EXTERNALTRIGGERDELAYIMPL_JAZ_T */

	// No public default Java constructor; creating one:
	EXPORTED EXTERNALTRIGGERDELAYIMPL_JAZ_T ExternalTriggerDelayImpl_Jaz_Create();
	EXPORTED double ExternalTriggerDelayImpl_Jaz_triggerDelayCountsToMicroseconds(EXTERNALTRIGGERDELAYIMPL_JAZ_T c_external_trigger_delay_impl_jaz, int counts);
	EXPORTED void ExternalTriggerDelayImpl_Jaz_setExternalTriggerDelay(EXTERNALTRIGGERDELAYIMPL_JAZ_T c_external_trigger_delay_impl_jaz, int counts);
	EXPORTED void ExternalTriggerDelayImpl_Jaz_getFeatureGUIClassnames(EXTERNALTRIGGERDELAYIMPL_JAZ_T c_external_trigger_delay_impl_jaz, JSTRINGARRAY_T retval);
	EXPORTED int ExternalTriggerDelayImpl_Jaz_getExternalTriggerDelayMinimum(EXTERNALTRIGGERDELAYIMPL_JAZ_T c_external_trigger_delay_impl_jaz);
	EXPORTED int ExternalTriggerDelayImpl_Jaz_getExternalTriggerDelayMaximum(EXTERNALTRIGGERDELAYIMPL_JAZ_T c_external_trigger_delay_impl_jaz);
	EXPORTED int ExternalTriggerDelayImpl_Jaz_getExternalTriggerDelayIncrement(EXTERNALTRIGGERDELAYIMPL_JAZ_T c_external_trigger_delay_impl_jaz);
	EXPORTED void ExternalTriggerDelayImpl_Jaz_Destroy(EXTERNALTRIGGERDELAYIMPL_JAZ_T external_trigger_delay_impl_jaz);

#ifdef WIN32
	// Use the following function prototypes when calling functions from Visual Basic 6
	EXPORTED double STDCALL ExternalTriggerDelayImpl_Jaz_triggerDelayCountsToMicroseconds_stdcall(EXTERNALTRIGGERDELAYIMPL_JAZ_T c_external_trigger_delay_impl_jaz, int counts);
	EXPORTED void STDCALL ExternalTriggerDelayImpl_Jaz_setExternalTriggerDelay_stdcall(EXTERNALTRIGGERDELAYIMPL_JAZ_T c_external_trigger_delay_impl_jaz, int counts);
	EXPORTED void STDCALL ExternalTriggerDelayImpl_Jaz_getFeatureGUIClassnames_stdcall(EXTERNALTRIGGERDELAYIMPL_JAZ_T c_external_trigger_delay_impl_jaz, JSTRINGARRAY_T retval);
	EXPORTED int STDCALL ExternalTriggerDelayImpl_Jaz_getExternalTriggerDelayMinimum_stdcall(EXTERNALTRIGGERDELAYIMPL_JAZ_T c_external_trigger_delay_impl_jaz);
	EXPORTED int STDCALL ExternalTriggerDelayImpl_Jaz_getExternalTriggerDelayMaximum_stdcall(EXTERNALTRIGGERDELAYIMPL_JAZ_T c_external_trigger_delay_impl_jaz);
	EXPORTED int STDCALL ExternalTriggerDelayImpl_Jaz_getExternalTriggerDelayIncrement_stdcall(EXTERNALTRIGGERDELAYIMPL_JAZ_T c_external_trigger_delay_impl_jaz);
	EXPORTED void STDCALL ExternalTriggerDelayImpl_Jaz_Destroy_stdcall(EXTERNALTRIGGERDELAYIMPL_JAZ_T external_trigger_delay_impl_jaz);
#endif /* WIN32 */
#ifdef __cplusplus
};
#endif /* __cplusplus */
#endif /* EXTERNALTRIGGERDELAYIMPL_JAZ_H */
