/**
 * File: ExternalTemperatureGUIProvider.h
 * Autogenerated on Mon Nov 16 11:53:33 EST 2009 based on
 * ExternalTemperatureGUIProvider.java
 * for the Java class
 * com/oceanoptics/omnidriver/features/externaltemperature/ExternalTemperatureGUIProvider
 * Copyright (C) 2006 - 2008 Ocean Optics, Inc.  All rights reserved.
 */


#ifndef EXTERNALTEMPERATUREGUIPROVIDER_H
#define EXTERNALTEMPERATUREGUIPROVIDER_H
#include "BaseJavaClass.h"

#ifdef __cplusplus

#ifdef INCLUDES_IN_HEADER
#endif /* INCLUDES_IN_HEADER */


CLASS_TOKEN EXPORTED ExternalTemperatureGUIProvider : public BaseJavaClass // CPPClass.getClassDeclaration
{
public: 
	~ExternalTemperatureGUIProvider();
	// No public default Java constructor; creating one:
	ExternalTemperatureGUIProvider();
	// No public Java copy constructor; creating one:
	ExternalTemperatureGUIProvider(const ExternalTemperatureGUIProvider &that);
	// Creating assignment operator declaration:
	ExternalTemperatureGUIProvider &operator=(const ExternalTemperatureGUIProvider &that);

private:
	void init_ids(JNIEnv* pJNIEnv);
};

extern "C" {
#endif /* __cplusplus */
#ifndef EXTERN_TYPEDEF_EXTERNALTEMPERATUREGUIPROVIDER_T
#define EXTERN_TYPEDEF_EXTERNALTEMPERATUREGUIPROVIDER_T
	typedef void* EXTERNALTEMPERATUREGUIPROVIDER_T;
#endif /* EXTERN_TYPEDEF_EXTERNALTEMPERATUREGUIPROVIDER_T */

	// No public default Java constructor; creating one:
	EXPORTED EXTERNALTEMPERATUREGUIPROVIDER_T ExternalTemperatureGUIProvider_Create();
	EXPORTED void ExternalTemperatureGUIProvider_Destroy(EXTERNALTEMPERATUREGUIPROVIDER_T external_temperature_g_u_i_provider);

#ifdef WIN32
	// Use the following function prototypes when calling functions from Visual Basic 6
	EXPORTED void STDCALL ExternalTemperatureGUIProvider_Destroy_stdcall(EXTERNALTEMPERATUREGUIPROVIDER_T external_temperature_g_u_i_provider);
#endif /* WIN32 */
#ifdef __cplusplus
};
#endif /* __cplusplus */
#endif /* EXTERNALTEMPERATUREGUIPROVIDER_H */
