/**
 * File: FindBoundIndexException.h
 * Autogenerated on Mon Nov 16 11:53:52 EST 2009 based on
 * FindBoundIndexException.java
 * for the Java class
 * com/oceanoptics/spam/numericalmethods/FindBoundIndexException
 * Copyright (C) 2006 - 2008 Ocean Optics, Inc.  All rights reserved.
 */


#ifndef FINDBOUNDINDEXEXCEPTION_H
#define FINDBOUNDINDEXEXCEPTION_H
#include "BaseJavaClass.h"

#ifdef __cplusplus

#ifdef INCLUDES_IN_HEADER
#include "JString.h"
#endif /* INCLUDES_IN_HEADER */

/* Pre-declarations for circular dependencies in header files */
#ifdef CLASS_PREDECLARATIONS
class JString;
#endif /* CLASS_PREDECLARATIONS */

CLASS_TOKEN EXPORTED FindBoundIndexException : public BaseJavaClass // CPPClass.getClassDeclaration
{
public: 
	FindBoundIndexException();
	FindBoundIndexException(JString& s);
	~FindBoundIndexException();
	// No public Java copy constructor; creating one:
	FindBoundIndexException(const FindBoundIndexException &that);
	// Creating assignment operator declaration:
	FindBoundIndexException &operator=(const FindBoundIndexException &that);

private:
	jmethodID mid_FindBoundIndexException299;
	jmethodID mid_FindBoundIndexException300;
	void init_ids(JNIEnv* pJNIEnv);
};

extern "C" {
#endif /* __cplusplus */
#ifndef EXTERN_TYPEDEF_JSTRING_T
#define EXTERN_TYPEDEF_JSTRING_T
	typedef void* JSTRING_T;
#endif /* EXTERN_TYPEDEF_JSTRING_T */
#ifndef EXTERN_TYPEDEF_FINDBOUNDINDEXEXCEPTION_T
#define EXTERN_TYPEDEF_FINDBOUNDINDEXEXCEPTION_T
	typedef void* FINDBOUNDINDEXEXCEPTION_T;
#endif /* EXTERN_TYPEDEF_FINDBOUNDINDEXEXCEPTION_T */

	EXPORTED FINDBOUNDINDEXEXCEPTION_T FindBoundIndexException_Create();
	EXPORTED FINDBOUNDINDEXEXCEPTION_T FindBoundIndexException_Create_1(JSTRING_T s);
	EXPORTED void FindBoundIndexException_Destroy(FINDBOUNDINDEXEXCEPTION_T find_bound_index_exception);

#ifdef WIN32
	// Use the following function prototypes when calling functions from Visual Basic 6
	EXPORTED FINDBOUNDINDEXEXCEPTION_T STDCALL FindBoundIndexException_Create_stdcall();
	EXPORTED FINDBOUNDINDEXEXCEPTION_T STDCALL FindBoundIndexException_Create_stdcall_1(JSTRING_T s);
	EXPORTED void STDCALL FindBoundIndexException_Destroy_stdcall(FINDBOUNDINDEXEXCEPTION_T find_bound_index_exception);
#endif /* WIN32 */
#ifdef __cplusplus
};
#endif /* __cplusplus */
#endif /* FINDBOUNDINDEXEXCEPTION_H */
