/**
 * File: GetOperationStatusGUIProvider.h
 * Autogenerated on Mon Nov 16 11:53:30 EST 2009 based on
 * GetOperationStatusGUIProvider.java
 * for the Java class
 * com/oceanoptics/omnidriver/accessories/mikropack/commands/getoperationstatus/GetOperationStatusGUIProvider
 * Copyright (C) 2006 - 2008 Ocean Optics, Inc.  All rights reserved.
 */


#ifndef GETOPERATIONSTATUSGUIPROVIDER_H
#define GETOPERATIONSTATUSGUIPROVIDER_H
#include "BaseJavaClass.h"

#ifdef __cplusplus

#ifdef INCLUDES_IN_HEADER
#endif /* INCLUDES_IN_HEADER */


CLASS_TOKEN EXPORTED GetOperationStatusGUIProvider : public BaseJavaClass // CPPClass.getClassDeclaration
{
public: 
	~GetOperationStatusGUIProvider();
	// No public default Java constructor; creating one:
	GetOperationStatusGUIProvider();
	// No public Java copy constructor; creating one:
	GetOperationStatusGUIProvider(const GetOperationStatusGUIProvider &that);
	// Creating assignment operator declaration:
	GetOperationStatusGUIProvider &operator=(const GetOperationStatusGUIProvider &that);

private:
	void init_ids(JNIEnv* pJNIEnv);
};

extern "C" {
#endif /* __cplusplus */
#ifndef EXTERN_TYPEDEF_GETOPERATIONSTATUSGUIPROVIDER_T
#define EXTERN_TYPEDEF_GETOPERATIONSTATUSGUIPROVIDER_T
	typedef void* GETOPERATIONSTATUSGUIPROVIDER_T;
#endif /* EXTERN_TYPEDEF_GETOPERATIONSTATUSGUIPROVIDER_T */

	// No public default Java constructor; creating one:
	EXPORTED GETOPERATIONSTATUSGUIPROVIDER_T GetOperationStatusGUIProvider_Create();
	EXPORTED void GetOperationStatusGUIProvider_Destroy(GETOPERATIONSTATUSGUIPROVIDER_T get_operation_status_g_u_i_provider);

#ifdef WIN32
	// Use the following function prototypes when calling functions from Visual Basic 6
	EXPORTED void STDCALL GetOperationStatusGUIProvider_Destroy_stdcall(GETOPERATIONSTATUSGUIPROVIDER_T get_operation_status_g_u_i_provider);
#endif /* WIN32 */
#ifdef __cplusplus
};
#endif /* __cplusplus */
#endif /* GETOPERATIONSTATUSGUIPROVIDER_H */
