/**
 * File: GetPositionImpl.h
 * Autogenerated on Mon Nov 16 11:53:30 EST 2009 based on
 * GetPositionImpl.java
 * for the Java class
 * com/oceanoptics/omnidriver/accessories/mikropack/commands/getposition/GetPositionImpl
 * Copyright (C) 2006 - 2008 Ocean Optics, Inc.  All rights reserved.
 */


#ifndef GETPOSITIONIMPL_H
#define GETPOSITIONIMPL_H
#include "BaseJavaClass.h"

#ifdef __cplusplus

#ifdef INCLUDES_IN_HEADER
#include "FaulhaberCommandIntegerResponse.h"
#include "UniRS232.h"
#include "Node.h"
#endif /* INCLUDES_IN_HEADER */

/* Pre-declarations for circular dependencies in header files */
#ifdef CLASS_PREDECLARATIONS
class FaulhaberCommandIntegerResponse;
class UniRS232;
class Node;
#endif /* CLASS_PREDECLARATIONS */

CLASS_TOKEN EXPORTED GetPositionImpl : public FaulhaberCommandIntegerResponse // CPPClass.getClassDeclaration
{
public: 
	GetPositionImpl(UniRS232& serPort);
	int getPosition(Node& node);
	~GetPositionImpl();
	// No public default Java constructor; creating one:
	GetPositionImpl();
	// No public Java copy constructor; creating one:
	GetPositionImpl(const GetPositionImpl &that);
	// Creating assignment operator declaration:
	GetPositionImpl &operator=(const GetPositionImpl &that);

private:
	jmethodID mid_GetPositionImpl90;
	jmethodID mid_getPosition91;
	void init_ids(JNIEnv* pJNIEnv);
};

extern "C" {
#endif /* __cplusplus */
#ifndef EXTERN_TYPEDEF_FAULHABERCOMMANDINTEGERRESPONSE_T
#define EXTERN_TYPEDEF_FAULHABERCOMMANDINTEGERRESPONSE_T
	typedef void* FAULHABERCOMMANDINTEGERRESPONSE_T;
#endif /* EXTERN_TYPEDEF_FAULHABERCOMMANDINTEGERRESPONSE_T */
#ifndef EXTERN_TYPEDEF_UNIRS232_T
#define EXTERN_TYPEDEF_UNIRS232_T
	typedef void* UNIRS232_T;
#endif /* EXTERN_TYPEDEF_UNIRS232_T */
#ifndef EXTERN_TYPEDEF_NODE_T
#define EXTERN_TYPEDEF_NODE_T
	typedef void* NODE_T;
#endif /* EXTERN_TYPEDEF_NODE_T */
#ifndef EXTERN_TYPEDEF_GETPOSITIONIMPL_T
#define EXTERN_TYPEDEF_GETPOSITIONIMPL_T
	typedef void* GETPOSITIONIMPL_T;
#endif /* EXTERN_TYPEDEF_GETPOSITIONIMPL_T */

	// No public default Java constructor; creating one:
	EXPORTED GETPOSITIONIMPL_T GetPositionImpl_Create();
	EXPORTED GETPOSITIONIMPL_T GetPositionImpl_Create_1(UNIRS232_T serPort);
	EXPORTED int GetPositionImpl_getPosition(GETPOSITIONIMPL_T c_get_position_impl, NODE_T node);
	EXPORTED void GetPositionImpl_Destroy(GETPOSITIONIMPL_T get_position_impl);

#ifdef WIN32
	// Use the following function prototypes when calling functions from Visual Basic 6
	EXPORTED GETPOSITIONIMPL_T STDCALL GetPositionImpl_Create_stdcall_1(UNIRS232_T serPort);
	EXPORTED int STDCALL GetPositionImpl_getPosition_stdcall(GETPOSITIONIMPL_T c_get_position_impl, NODE_T node);
	EXPORTED void STDCALL GetPositionImpl_Destroy_stdcall(GETPOSITIONIMPL_T get_position_impl);
#endif /* WIN32 */
#ifdef __cplusplus
};
#endif /* __cplusplus */
#endif /* GETPOSITIONIMPL_H */
