/**
 * File: GetVelocityImpl.h
 * Autogenerated on Mon Nov 16 11:53:30 EST 2009 based on
 * GetVelocityImpl.java
 * for the Java class
 * com/oceanoptics/omnidriver/accessories/mikropack/commands/getvelocity/GetVelocityImpl
 * Copyright (C) 2006 - 2008 Ocean Optics, Inc.  All rights reserved.
 */


#ifndef GETVELOCITYIMPL_H
#define GETVELOCITYIMPL_H
#include "BaseJavaClass.h"

#ifdef __cplusplus

#ifdef INCLUDES_IN_HEADER
#include "FaulhaberCommandIntegerResponse.h"
#include "UniRS232.h"
#include "Node.h"
#endif /* INCLUDES_IN_HEADER */

/* Pre-declarations for circular dependencies in header files */
#ifdef CLASS_PREDECLARATIONS
class FaulhaberCommandIntegerResponse;
class UniRS232;
class Node;
#endif /* CLASS_PREDECLARATIONS */

CLASS_TOKEN EXPORTED GetVelocityImpl : public FaulhaberCommandIntegerResponse // CPPClass.getClassDeclaration
{
public: 
	GetVelocityImpl(UniRS232& serPort);
	int getVelocity(Node& node);
	~GetVelocityImpl();
	// No public default Java constructor; creating one:
	GetVelocityImpl();
	// No public Java copy constructor; creating one:
	GetVelocityImpl(const GetVelocityImpl &that);
	// Creating assignment operator declaration:
	GetVelocityImpl &operator=(const GetVelocityImpl &that);

private:
	jmethodID mid_GetVelocityImpl112;
	jmethodID mid_getVelocity113;
	void init_ids(JNIEnv* pJNIEnv);
};

extern "C" {
#endif /* __cplusplus */
#ifndef EXTERN_TYPEDEF_FAULHABERCOMMANDINTEGERRESPONSE_T
#define EXTERN_TYPEDEF_FAULHABERCOMMANDINTEGERRESPONSE_T
	typedef void* FAULHABERCOMMANDINTEGERRESPONSE_T;
#endif /* EXTERN_TYPEDEF_FAULHABERCOMMANDINTEGERRESPONSE_T */
#ifndef EXTERN_TYPEDEF_UNIRS232_T
#define EXTERN_TYPEDEF_UNIRS232_T
	typedef void* UNIRS232_T;
#endif /* EXTERN_TYPEDEF_UNIRS232_T */
#ifndef EXTERN_TYPEDEF_NODE_T
#define EXTERN_TYPEDEF_NODE_T
	typedef void* NODE_T;
#endif /* EXTERN_TYPEDEF_NODE_T */
#ifndef EXTERN_TYPEDEF_GETVELOCITYIMPL_T
#define EXTERN_TYPEDEF_GETVELOCITYIMPL_T
	typedef void* GETVELOCITYIMPL_T;
#endif /* EXTERN_TYPEDEF_GETVELOCITYIMPL_T */

	// No public default Java constructor; creating one:
	EXPORTED GETVELOCITYIMPL_T GetVelocityImpl_Create();
	EXPORTED GETVELOCITYIMPL_T GetVelocityImpl_Create_1(UNIRS232_T serPort);
	EXPORTED int GetVelocityImpl_getVelocity(GETVELOCITYIMPL_T c_get_velocity_impl, NODE_T node);
	EXPORTED void GetVelocityImpl_Destroy(GETVELOCITYIMPL_T get_velocity_impl);

#ifdef WIN32
	// Use the following function prototypes when calling functions from Visual Basic 6
	EXPORTED GETVELOCITYIMPL_T STDCALL GetVelocityImpl_Create_stdcall_1(UNIRS232_T serPort);
	EXPORTED int STDCALL GetVelocityImpl_getVelocity_stdcall(GETVELOCITYIMPL_T c_get_velocity_impl, NODE_T node);
	EXPORTED void STDCALL GetVelocityImpl_Destroy_stdcall(GETVELOCITYIMPL_T get_velocity_impl);
#endif /* WIN32 */
#ifdef __cplusplus
};
#endif /* __cplusplus */
#endif /* GETVELOCITYIMPL_H */
