/**
 * File: GetVersionImpl.h
 * Autogenerated on Mon Nov 16 11:53:30 EST 2009 based on
 * GetVersionImpl.java
 * for the Java class
 * com/oceanoptics/omnidriver/accessories/mikropack/commands/getversion/GetVersionImpl
 * Copyright (C) 2006 - 2008 Ocean Optics, Inc.  All rights reserved.
 */


#ifndef GETVERSIONIMPL_H
#define GETVERSIONIMPL_H
#include "BaseJavaClass.h"

#ifdef __cplusplus

#ifdef INCLUDES_IN_HEADER
#include "FaulhaberCommandStringResponse.h"
#include "UniRS232.h"
#include "Node.h"
#include "JString.h"
#endif /* INCLUDES_IN_HEADER */

/* Pre-declarations for circular dependencies in header files */
#ifdef CLASS_PREDECLARATIONS
class FaulhaberCommandStringResponse;
class UniRS232;
class Node;
class JString;
#endif /* CLASS_PREDECLARATIONS */

CLASS_TOKEN EXPORTED GetVersionImpl : public FaulhaberCommandStringResponse // CPPClass.getClassDeclaration
{
public: 
	GetVersionImpl(UniRS232& serPort);
	JString getVersion(Node& node);
	~GetVersionImpl();
	// No public default Java constructor; creating one:
	GetVersionImpl();
	// No public Java copy constructor; creating one:
	GetVersionImpl(const GetVersionImpl &that);
	// Creating assignment operator declaration:
	GetVersionImpl &operator=(const GetVersionImpl &that);

private:
	jmethodID mid_GetVersionImpl115;
	jmethodID mid_getVersion116;
	void init_ids(JNIEnv* pJNIEnv);
};

extern "C" {
#endif /* __cplusplus */
#ifndef EXTERN_TYPEDEF_FAULHABERCOMMANDSTRINGRESPONSE_T
#define EXTERN_TYPEDEF_FAULHABERCOMMANDSTRINGRESPONSE_T
	typedef void* FAULHABERCOMMANDSTRINGRESPONSE_T;
#endif /* EXTERN_TYPEDEF_FAULHABERCOMMANDSTRINGRESPONSE_T */
#ifndef EXTERN_TYPEDEF_UNIRS232_T
#define EXTERN_TYPEDEF_UNIRS232_T
	typedef void* UNIRS232_T;
#endif /* EXTERN_TYPEDEF_UNIRS232_T */
#ifndef EXTERN_TYPEDEF_NODE_T
#define EXTERN_TYPEDEF_NODE_T
	typedef void* NODE_T;
#endif /* EXTERN_TYPEDEF_NODE_T */
#ifndef EXTERN_TYPEDEF_JSTRING_T
#define EXTERN_TYPEDEF_JSTRING_T
	typedef void* JSTRING_T;
#endif /* EXTERN_TYPEDEF_JSTRING_T */
#ifndef EXTERN_TYPEDEF_GETVERSIONIMPL_T
#define EXTERN_TYPEDEF_GETVERSIONIMPL_T
	typedef void* GETVERSIONIMPL_T;
#endif /* EXTERN_TYPEDEF_GETVERSIONIMPL_T */

	// No public default Java constructor; creating one:
	EXPORTED GETVERSIONIMPL_T GetVersionImpl_Create();
	EXPORTED GETVERSIONIMPL_T GetVersionImpl_Create_1(UNIRS232_T serPort);
	EXPORTED void GetVersionImpl_getVersion(GETVERSIONIMPL_T c_get_version_impl, NODE_T node, JSTRING_T retval);
	EXPORTED void GetVersionImpl_Destroy(GETVERSIONIMPL_T get_version_impl);

#ifdef WIN32
	// Use the following function prototypes when calling functions from Visual Basic 6
	EXPORTED GETVERSIONIMPL_T STDCALL GetVersionImpl_Create_stdcall_1(UNIRS232_T serPort);
	EXPORTED void STDCALL GetVersionImpl_getVersion_stdcall(GETVERSIONIMPL_T c_get_version_impl, NODE_T node, JSTRING_T retval);
	EXPORTED void STDCALL GetVersionImpl_Destroy_stdcall(GETVERSIONIMPL_T get_version_impl);
#endif /* WIN32 */
#ifdef __cplusplus
};
#endif /* __cplusplus */
#endif /* GETVERSIONIMPL_H */
