/**
 * File: HL2000HP232.h
 * Autogenerated on Mon Nov 16 11:53:30 EST 2009 based on
 * HL2000HP232.java
 * for the Java class
 * com/oceanoptics/omnidriver/accessories/mikropack/devices/HL2000HP232
 * Copyright (C) 2006 - 2008 Ocean Optics, Inc.  All rights reserved.
 */


#ifndef HL2000HP232_H
#define HL2000HP232_H
#include "BaseJavaClass.h"

#ifdef __cplusplus

#ifdef INCLUDES_IN_HEADER
#endif /* INCLUDES_IN_HEADER */


CLASS_TOKEN EXPORTED HL2000HP232 : public BaseJavaClass // CPPClass.getClassDeclaration
{
public: 
	HL2000HP232();
	~HL2000HP232();
	// No public Java copy constructor; creating one:
	HL2000HP232(const HL2000HP232 &that);
	// Creating assignment operator declaration:
	HL2000HP232 &operator=(const HL2000HP232 &that);

private:
	jmethodID mid_HL2000HP232175;
	void init_ids(JNIEnv* pJNIEnv);
};

extern "C" {
#endif /* __cplusplus */
#ifndef EXTERN_TYPEDEF_HL2000HP232_T
#define EXTERN_TYPEDEF_HL2000HP232_T
	typedef void* HL2000HP232_T;
#endif /* EXTERN_TYPEDEF_HL2000HP232_T */

	EXPORTED HL2000HP232_T HL2000HP232_Create();
	EXPORTED void HL2000HP232_Destroy(HL2000HP232_T hl2000hp232);

#ifdef WIN32
	// Use the following function prototypes when calling functions from Visual Basic 6
	EXPORTED HL2000HP232_T STDCALL HL2000HP232_Create_stdcall();
	EXPORTED void STDCALL HL2000HP232_Destroy_stdcall(HL2000HP232_T hl2000hp232);
#endif /* WIN32 */
#ifdef __cplusplus
};
#endif /* __cplusplus */
#endif /* HL2000HP232_H */
