/**
 * File: Illuminant.h
 * Autogenerated on Mon Nov 16 11:53:52 EST 2009 based on
 * Illuminant.java
 * for the Java class
 * com/oceanoptics/spam/constants/Illuminant
 * Copyright (C) 2006 - 2008 Ocean Optics, Inc.  All rights reserved.
 */


#ifndef ILLUMINANT_H
#define ILLUMINANT_H
#include "BaseJavaClass.h"

#ifdef __cplusplus

#ifdef INCLUDES_IN_HEADER
#include "JString.h"
#endif /* INCLUDES_IN_HEADER */

/* Pre-declarations for circular dependencies in header files */
#ifdef CLASS_PREDECLARATIONS
class JString;
#endif /* CLASS_PREDECLARATIONS */

CLASS_TOKEN EXPORTED Illuminant : public BaseJavaClass // CPPClass.getClassDeclaration
{
public: 
	Illuminant(DoubleArray& wl, DoubleArray& vals, JString& shortDescOrLocalizer, JString& longDescOrLocalizer);
	JString getShortDescription();
	JString getLongDescription();
	DoubleArray getWavelengths();
	void setWavelengths(DoubleArray& newWl);
	DoubleArray getValues();
	JString getCreator();
	unsigned char isFromOOI();
	JString toString();
	~Illuminant();
	// No public default Java constructor; creating one:
	Illuminant();
	// No public Java copy constructor; creating one:
	Illuminant(const Illuminant &that);
	// Creating assignment operator declaration:
	Illuminant &operator=(const Illuminant &that);

private:
	jmethodID mid_Illuminant220;
	jmethodID mid_getShortDescription221;
	jmethodID mid_getLongDescription222;
	jmethodID mid_getWavelengths223;
	jmethodID mid_setWavelengths224;
	jmethodID mid_getValues225;
	jmethodID mid_getCreator226;
	jmethodID mid_isFromOOI227;
	jmethodID mid_toString228;
	void init_ids(JNIEnv* pJNIEnv);
};

extern "C" {
#endif /* __cplusplus */
#ifndef EXTERN_TYPEDEF_JSTRING_T
#define EXTERN_TYPEDEF_JSTRING_T
	typedef void* JSTRING_T;
#endif /* EXTERN_TYPEDEF_JSTRING_T */
#ifndef EXTERN_TYPEDEF_ILLUMINANT_T
#define EXTERN_TYPEDEF_ILLUMINANT_T
	typedef void* ILLUMINANT_T;
#endif /* EXTERN_TYPEDEF_ILLUMINANT_T */

	// No public default Java constructor; creating one:
	EXPORTED ILLUMINANT_T Illuminant_Create();
	EXPORTED ILLUMINANT_T Illuminant_Create_1(DOUBLEARRAY_T wl, DOUBLEARRAY_T vals, JSTRING_T shortDescOrLocalizer, JSTRING_T longDescOrLocalizer);
	EXPORTED void Illuminant_getShortDescription(ILLUMINANT_T c_illuminant, JSTRING_T retval);
	EXPORTED void Illuminant_getLongDescription(ILLUMINANT_T c_illuminant, JSTRING_T retval);
	EXPORTED void Illuminant_getWavelengths(ILLUMINANT_T c_illuminant, DOUBLEARRAY_T retval);
	EXPORTED void Illuminant_setWavelengths(ILLUMINANT_T c_illuminant, DOUBLEARRAY_T newWl);
	EXPORTED void Illuminant_getValues(ILLUMINANT_T c_illuminant, DOUBLEARRAY_T retval);
	EXPORTED void Illuminant_getCreator(ILLUMINANT_T c_illuminant, JSTRING_T retval);
	EXPORTED unsigned char Illuminant_isFromOOI(ILLUMINANT_T c_illuminant);
	EXPORTED void Illuminant_toString(ILLUMINANT_T c_illuminant, JSTRING_T retval);
	EXPORTED void Illuminant_Destroy(ILLUMINANT_T illuminant);

#ifdef WIN32
	// Use the following function prototypes when calling functions from Visual Basic 6
	EXPORTED ILLUMINANT_T STDCALL Illuminant_Create_stdcall_1(DOUBLEARRAY_T wl, DOUBLEARRAY_T vals, JSTRING_T shortDescOrLocalizer, JSTRING_T longDescOrLocalizer);
	EXPORTED void STDCALL Illuminant_getShortDescription_stdcall(ILLUMINANT_T c_illuminant, JSTRING_T retval);
	EXPORTED void STDCALL Illuminant_getLongDescription_stdcall(ILLUMINANT_T c_illuminant, JSTRING_T retval);
	EXPORTED void STDCALL Illuminant_getWavelengths_stdcall(ILLUMINANT_T c_illuminant, DOUBLEARRAY_T retval);
	EXPORTED void STDCALL Illuminant_setWavelengths_stdcall(ILLUMINANT_T c_illuminant, DOUBLEARRAY_T newWl);
	EXPORTED void STDCALL Illuminant_getValues_stdcall(ILLUMINANT_T c_illuminant, DOUBLEARRAY_T retval);
	EXPORTED void STDCALL Illuminant_getCreator_stdcall(ILLUMINANT_T c_illuminant, JSTRING_T retval);
	EXPORTED unsigned char STDCALL Illuminant_isFromOOI_stdcall(ILLUMINANT_T c_illuminant);
	EXPORTED void STDCALL Illuminant_toString_stdcall(ILLUMINANT_T c_illuminant, JSTRING_T retval);
	EXPORTED void STDCALL Illuminant_Destroy_stdcall(ILLUMINANT_T illuminant);
#endif /* WIN32 */
#ifdef __cplusplus
};
#endif /* __cplusplus */
#endif /* ILLUMINANT_H */
