/**
 * File: IntegerList.h
 * Autogenerated on Mon Nov 16 11:53:52 EST 2009 based on
 * IntegerList.java
 * for the Java class
 * com/oceanoptics/spam/arraymath/IntegerList
 * Copyright (C) 2006 - 2008 Ocean Optics, Inc.  All rights reserved.
 */


#ifndef INTEGERLIST_H
#define INTEGERLIST_H
#include "BaseJavaClass.h"

#ifdef __cplusplus

#ifdef INCLUDES_IN_HEADER
#include "Vector.h"
#endif /* INCLUDES_IN_HEADER */

/* Pre-declarations for circular dependencies in header files */
#ifdef CLASS_PREDECLARATIONS
class Vector;
#endif /* CLASS_PREDECLARATIONS */

CLASS_TOKEN EXPORTED IntegerList : public Vector // CPPClass.getClassDeclaration
{
public: 
	IntegerList();
	void addValue(int i, int d);
	void addValue(int d);
	int getValue(int i);
	~IntegerList();
	// No public Java copy constructor; creating one:
	IntegerList(const IntegerList &that);
	// Creating assignment operator declaration:
	IntegerList &operator=(const IntegerList &that);

private:
	jmethodID mid_IntegerList173;
	jmethodID mid_addValue174;
	jmethodID mid_addValue175;
	jmethodID mid_getValue176;
	void init_ids(JNIEnv* pJNIEnv);
};

extern "C" {
#endif /* __cplusplus */
#ifndef EXTERN_TYPEDEF_VECTOR_T
#define EXTERN_TYPEDEF_VECTOR_T
	typedef void* VECTOR_T;
#endif /* EXTERN_TYPEDEF_VECTOR_T */
#ifndef EXTERN_TYPEDEF_INTEGERLIST_T
#define EXTERN_TYPEDEF_INTEGERLIST_T
	typedef void* INTEGERLIST_T;
#endif /* EXTERN_TYPEDEF_INTEGERLIST_T */

	EXPORTED INTEGERLIST_T IntegerList_Create();
	EXPORTED void IntegerList_addValue(INTEGERLIST_T c_integer_list, int i, int d);
	EXPORTED void IntegerList_addValue_1(INTEGERLIST_T c_integer_list, int d);
	EXPORTED int IntegerList_getValue(INTEGERLIST_T c_integer_list, int i);
	EXPORTED void IntegerList_Destroy(INTEGERLIST_T integer_list);

#ifdef WIN32
	// Use the following function prototypes when calling functions from Visual Basic 6
	EXPORTED INTEGERLIST_T STDCALL IntegerList_Create_stdcall();
	EXPORTED void STDCALL IntegerList_addValue_stdcall(INTEGERLIST_T c_integer_list, int i, int d);
	EXPORTED void STDCALL IntegerList_addValue_stdcall_1(INTEGERLIST_T c_integer_list, int d);
	EXPORTED int STDCALL IntegerList_getValue_stdcall(INTEGERLIST_T c_integer_list, int i);
	EXPORTED void STDCALL IntegerList_Destroy_stdcall(INTEGERLIST_T integer_list);
#endif /* WIN32 */
#ifdef __cplusplus
};
#endif /* __cplusplus */
#endif /* INTEGERLIST_H */
