/**
 * File: IntegrationMethod.h
 * Autogenerated on Mon Nov 16 11:53:52 EST 2009 based on
 * IntegrationMethod.java
 * for the Java class
 * com/oceanoptics/spam/numericalmethods/IntegrationMethod
 * Copyright (C) 2006 - 2008 Ocean Optics, Inc.  All rights reserved.
 */


#ifndef INTEGRATIONMETHOD_H
#define INTEGRATIONMETHOD_H
#include "BaseJavaClass.h"

#ifdef __cplusplus

#ifdef INCLUDES_IN_HEADER
#include "JString.h"
#endif /* INCLUDES_IN_HEADER */

/* Pre-declarations for circular dependencies in header files */
#ifdef CLASS_PREDECLARATIONS
class IntegrationMethod;
class JString;
#endif /* CLASS_PREDECLARATIONS */

CLASS_TOKEN EXPORTED IntegrationMethod : public BaseJavaClass // CPPClass.getClassDeclaration
{
public: 
	int getIntegrationMode();
	unsigned char equals(IntegrationMethod& that);
	JString toString();
	~IntegrationMethod();
	// No public default Java constructor; creating one:
	IntegrationMethod();
	// No public Java copy constructor; creating one:
	IntegrationMethod(const IntegrationMethod &that);
	// Creating assignment operator declaration:
	IntegrationMethod &operator=(const IntegrationMethod &that);
	int INTEGRAL_MODE_RECTANGULAR;
	int INTEGRAL_MODE_TRAPEZOID;
	int INTEGRAL_MODE_SIMPSONS;

private:
	jmethodID mid_getIntegrationMode301;
	jmethodID mid_equals302;
	jmethodID mid_toString303;
	jfieldID fid_INTEGRAL_MODE_RECTANGULAR;
	jfieldID fid_INTEGRAL_MODE_TRAPEZOID;
	jfieldID fid_INTEGRAL_MODE_SIMPSONS;
	jfieldID fid_INTEGRAL_RECTANGULAR;
	jfieldID fid_INTEGRAL_TRAPEZOID;
	jfieldID fid_INTEGRAL_SIMPSONS;
	void init_ids(JNIEnv* pJNIEnv);
};

extern "C" {
#endif /* __cplusplus */
#ifndef EXTERN_TYPEDEF_INTEGRATIONMETHOD_T
#define EXTERN_TYPEDEF_INTEGRATIONMETHOD_T
	typedef void* INTEGRATIONMETHOD_T;
#endif /* EXTERN_TYPEDEF_INTEGRATIONMETHOD_T */
#ifndef EXTERN_TYPEDEF_JSTRING_T
#define EXTERN_TYPEDEF_JSTRING_T
	typedef void* JSTRING_T;
#endif /* EXTERN_TYPEDEF_JSTRING_T */

	// No public default Java constructor; creating one:
	EXPORTED INTEGRATIONMETHOD_T IntegrationMethod_Create();
	EXPORTED int IntegrationMethod_getIntegrationMode(INTEGRATIONMETHOD_T c_integration_method);
	EXPORTED unsigned char IntegrationMethod_equals(INTEGRATIONMETHOD_T c_integration_method, INTEGRATIONMETHOD_T that);
	EXPORTED void IntegrationMethod_toString(INTEGRATIONMETHOD_T c_integration_method, JSTRING_T retval);
	EXPORTED void IntegrationMethod_Destroy(INTEGRATIONMETHOD_T integration_method);

#ifdef WIN32
	// Use the following function prototypes when calling functions from Visual Basic 6
	EXPORTED int STDCALL IntegrationMethod_getIntegrationMode_stdcall(INTEGRATIONMETHOD_T c_integration_method);
	EXPORTED unsigned char STDCALL IntegrationMethod_equals_stdcall(INTEGRATIONMETHOD_T c_integration_method, INTEGRATIONMETHOD_T that);
	EXPORTED void STDCALL IntegrationMethod_toString_stdcall(INTEGRATIONMETHOD_T c_integration_method, JSTRING_T retval);
	EXPORTED void STDCALL IntegrationMethod_Destroy_stdcall(INTEGRATIONMETHOD_T integration_method);
#endif /* WIN32 */
#ifdef __cplusplus
};
#endif /* __cplusplus */
#endif /* INTEGRATIONMETHOD_H */
