/**
 * File: JazStatus.h
 * Autogenerated on Mon Nov 16 11:53:37 EST 2009 based on
 * JazStatus.java
 * for the Java class
 * com/oceanoptics/omnidriver/spectrometer/jaz/JazStatus
 * Copyright (C) 2006 - 2008 Ocean Optics, Inc.  All rights reserved.
 */


#ifndef JAZSTATUS_H
#define JAZSTATUS_H
#include "BaseJavaClass.h"

#ifdef __cplusplus

#ifdef INCLUDES_IN_HEADER
#include "SpectrometerStatus.h"
#include "JString.h"
#endif /* INCLUDES_IN_HEADER */

/* Pre-declarations for circular dependencies in header files */
#ifdef CLASS_PREDECLARATIONS
class SpectrometerStatus;
class JString;
#endif /* CLASS_PREDECLARATIONS */

CLASS_TOKEN EXPORTED JazStatus : public SpectrometerStatus // CPPClass.getClassDeclaration
{
public: 
	JazStatus();
	JString toString();
	~JazStatus();
	// No public Java copy constructor; creating one:
	JazStatus(const JazStatus &that);
	// Creating assignment operator declaration:
	JazStatus &operator=(const JazStatus &that);
	signed char numPacketsInSpectra;
	int powerDownFlag;
	signed char packetCount;
	int usbSpeed;

private:
	jmethodID mid_JazStatus2269;
	jmethodID mid_toString2270;
	jfieldID fid_numPacketsInSpectra;
	jfieldID fid_powerDownFlag;
	jfieldID fid_packetCount;
	jfieldID fid_usbSpeed;
	void init_ids(JNIEnv* pJNIEnv);
};

extern "C" {
#endif /* __cplusplus */
#ifndef EXTERN_TYPEDEF_SPECTROMETERSTATUS_T
#define EXTERN_TYPEDEF_SPECTROMETERSTATUS_T
	typedef void* SPECTROMETERSTATUS_T;
#endif /* EXTERN_TYPEDEF_SPECTROMETERSTATUS_T */
#ifndef EXTERN_TYPEDEF_JSTRING_T
#define EXTERN_TYPEDEF_JSTRING_T
	typedef void* JSTRING_T;
#endif /* EXTERN_TYPEDEF_JSTRING_T */
#ifndef EXTERN_TYPEDEF_JAZSTATUS_T
#define EXTERN_TYPEDEF_JAZSTATUS_T
	typedef void* JAZSTATUS_T;
#endif /* EXTERN_TYPEDEF_JAZSTATUS_T */

	EXPORTED JAZSTATUS_T JazStatus_Create();
	EXPORTED void JazStatus_toString(JAZSTATUS_T c_jaz_status, JSTRING_T retval);
	EXPORTED void JazStatus_Destroy(JAZSTATUS_T jaz_status);

#ifdef WIN32
	// Use the following function prototypes when calling functions from Visual Basic 6
	EXPORTED JAZSTATUS_T STDCALL JazStatus_Create_stdcall();
	EXPORTED void STDCALL JazStatus_toString_stdcall(JAZSTATUS_T c_jaz_status, JSTRING_T retval);
	EXPORTED void STDCALL JazStatus_Destroy_stdcall(JAZSTATUS_T jaz_status);
#endif /* WIN32 */
#ifdef __cplusplus
};
#endif /* __cplusplus */
#endif /* JAZSTATUS_H */
