/**
 * File: JSocket.h
 * Autogenerated on Mon Nov 16 11:53:35 EST 2009 based on
 * JSocket.java
 * for the Java class
 * com/oceanoptics/omnidriver/jwrappers/JSocket
 * Copyright (C) 2006 - 2008 Ocean Optics, Inc.  All rights reserved.
 */


#ifndef JSOCKET_H
#define JSOCKET_H
#include "BaseJavaClass.h"

#ifdef __cplusplus

#ifdef INCLUDES_IN_HEADER
#include "JString.h"
#endif /* INCLUDES_IN_HEADER */

/* Pre-declarations for circular dependencies in header files */
#ifdef CLASS_PREDECLARATIONS
class JString;
#endif /* CLASS_PREDECLARATIONS */

CLASS_TOKEN EXPORTED JSocket : public BaseJavaClass // CPPClass.getClassDeclaration
{
public: 
	JSocket(JString& hostName, int portNumber);
	unsigned char isClosed();
	unsigned char isConnected();
	unsigned char isBound();
	~JSocket();
	// No public default Java constructor; creating one:
	JSocket();
	// No public Java copy constructor; creating one:
	JSocket(const JSocket &that);
	// Creating assignment operator declaration:
	JSocket &operator=(const JSocket &that);

private:
	jmethodID mid_JSocket1390;
	jmethodID mid_isClosed1391;
	jmethodID mid_isConnected1392;
	jmethodID mid_isBound1393;
	void init_ids(JNIEnv* pJNIEnv);
};

extern "C" {
#endif /* __cplusplus */
#ifndef EXTERN_TYPEDEF_JSTRING_T
#define EXTERN_TYPEDEF_JSTRING_T
	typedef void* JSTRING_T;
#endif /* EXTERN_TYPEDEF_JSTRING_T */
#ifndef EXTERN_TYPEDEF_JSOCKET_T
#define EXTERN_TYPEDEF_JSOCKET_T
	typedef void* JSOCKET_T;
#endif /* EXTERN_TYPEDEF_JSOCKET_T */

	// No public default Java constructor; creating one:
	EXPORTED JSOCKET_T JSocket_Create();
	EXPORTED JSOCKET_T JSocket_Create_1(JSTRING_T hostName, int portNumber);
	EXPORTED unsigned char JSocket_isClosed(JSOCKET_T c_jsocket);
	EXPORTED unsigned char JSocket_isConnected(JSOCKET_T c_jsocket);
	EXPORTED unsigned char JSocket_isBound(JSOCKET_T c_jsocket);
	EXPORTED void JSocket_Destroy(JSOCKET_T jsocket);

#ifdef WIN32
	// Use the following function prototypes when calling functions from Visual Basic 6
	EXPORTED JSOCKET_T STDCALL JSocket_Create_stdcall_1(JSTRING_T hostName, int portNumber);
	EXPORTED unsigned char STDCALL JSocket_isClosed_stdcall(JSOCKET_T c_jsocket);
	EXPORTED unsigned char STDCALL JSocket_isConnected_stdcall(JSOCKET_T c_jsocket);
	EXPORTED unsigned char STDCALL JSocket_isBound_stdcall(JSOCKET_T c_jsocket);
	EXPORTED void STDCALL JSocket_Destroy_stdcall(JSOCKET_T jsocket);
#endif /* WIN32 */
#ifdef __cplusplus
};
#endif /* __cplusplus */
#endif /* JSOCKET_H */
