/**
 * File: LoadAbsolutePositionGUIProvider.h
 * Autogenerated on Mon Nov 16 11:53:30 EST 2009 based on
 * LoadAbsolutePositionGUIProvider.java
 * for the Java class
 * com/oceanoptics/omnidriver/accessories/mikropack/commands/loadabsoluteposition/LoadAbsolutePositionGUIProvider
 * Copyright (C) 2006 - 2008 Ocean Optics, Inc.  All rights reserved.
 */


#ifndef LOADABSOLUTEPOSITIONGUIPROVIDER_H
#define LOADABSOLUTEPOSITIONGUIPROVIDER_H
#include "BaseJavaClass.h"

#ifdef __cplusplus

#ifdef INCLUDES_IN_HEADER
#endif /* INCLUDES_IN_HEADER */


CLASS_TOKEN EXPORTED LoadAbsolutePositionGUIProvider : public BaseJavaClass // CPPClass.getClassDeclaration
{
public: 
	~LoadAbsolutePositionGUIProvider();
	// No public default Java constructor; creating one:
	LoadAbsolutePositionGUIProvider();
	// No public Java copy constructor; creating one:
	LoadAbsolutePositionGUIProvider(const LoadAbsolutePositionGUIProvider &that);
	// Creating assignment operator declaration:
	LoadAbsolutePositionGUIProvider &operator=(const LoadAbsolutePositionGUIProvider &that);

private:
	void init_ids(JNIEnv* pJNIEnv);
};

extern "C" {
#endif /* __cplusplus */
#ifndef EXTERN_TYPEDEF_LOADABSOLUTEPOSITIONGUIPROVIDER_T
#define EXTERN_TYPEDEF_LOADABSOLUTEPOSITIONGUIPROVIDER_T
	typedef void* LOADABSOLUTEPOSITIONGUIPROVIDER_T;
#endif /* EXTERN_TYPEDEF_LOADABSOLUTEPOSITIONGUIPROVIDER_T */

	// No public default Java constructor; creating one:
	EXPORTED LOADABSOLUTEPOSITIONGUIPROVIDER_T LoadAbsolutePositionGUIProvider_Create();
	EXPORTED void LoadAbsolutePositionGUIProvider_Destroy(LOADABSOLUTEPOSITIONGUIPROVIDER_T load_absolute_position_g_u_i_provider);

#ifdef WIN32
	// Use the following function prototypes when calling functions from Visual Basic 6
	EXPORTED void STDCALL LoadAbsolutePositionGUIProvider_Destroy_stdcall(LOADABSOLUTEPOSITIONGUIPROVIDER_T load_absolute_position_g_u_i_provider);
#endif /* WIN32 */
#ifdef __cplusplus
};
#endif /* __cplusplus */
#endif /* LOADABSOLUTEPOSITIONGUIPROVIDER_H */
