/**
 * File: LS450_FunctionsImpl_4000.h
 * Autogenerated on Mon Nov 16 11:53:34 EST 2009 based on
 * LS450_FunctionsImpl_4000.java
 * for the Java class
 * com/oceanoptics/omnidriver/features/ls450functions/LS450_FunctionsImpl_4000
 * Copyright (C) 2006 - 2008 Ocean Optics, Inc.  All rights reserved.
 */


#ifndef LS450_FUNCTIONSIMPL_4000_H
#define LS450_FUNCTIONSIMPL_4000_H
#include "BaseJavaClass.h"

#ifdef __cplusplus

#ifdef INCLUDES_IN_HEADER
#include "LS450_FunctionsImpl.h"
#include "USBInterface.h"
#include "SpectrometerPlugIn.h"
#endif /* INCLUDES_IN_HEADER */

/* Pre-declarations for circular dependencies in header files */
#ifdef CLASS_PREDECLARATIONS
class LS450_FunctionsImpl;
class USBInterface;
class SpectrometerPlugIn;
#endif /* CLASS_PREDECLARATIONS */

CLASS_TOKEN EXPORTED LS450_FunctionsImpl_4000 : public LS450_FunctionsImpl // CPPClass.getClassDeclaration
{
public: 
	LS450_FunctionsImpl_4000(USBInterface& usbInt, SpectrometerPlugIn& plugin);
	~LS450_FunctionsImpl_4000();
	// No public default Java constructor; creating one:
	LS450_FunctionsImpl_4000();
	// No public Java copy constructor; creating one:
	LS450_FunctionsImpl_4000(const LS450_FunctionsImpl_4000 &that);
	// Creating assignment operator declaration:
	LS450_FunctionsImpl_4000 &operator=(const LS450_FunctionsImpl_4000 &that);

private:
	jmethodID mid_LS450_FunctionsImpl_4000845;
	void init_ids(JNIEnv* pJNIEnv);
};

extern "C" {
#endif /* __cplusplus */
#ifndef EXTERN_TYPEDEF_LS450_FUNCTIONSIMPL_T
#define EXTERN_TYPEDEF_LS450_FUNCTIONSIMPL_T
	typedef void* LS450_FUNCTIONSIMPL_T;
#endif /* EXTERN_TYPEDEF_LS450_FUNCTIONSIMPL_T */
#ifndef EXTERN_TYPEDEF_USBINTERFACE_T
#define EXTERN_TYPEDEF_USBINTERFACE_T
	typedef void* USBINTERFACE_T;
#endif /* EXTERN_TYPEDEF_USBINTERFACE_T */
#ifndef EXTERN_TYPEDEF_SPECTROMETERPLUGIN_T
#define EXTERN_TYPEDEF_SPECTROMETERPLUGIN_T
	typedef void* SPECTROMETERPLUGIN_T;
#endif /* EXTERN_TYPEDEF_SPECTROMETERPLUGIN_T */
#ifndef EXTERN_TYPEDEF_LS450_FUNCTIONSIMPL_4000_T
#define EXTERN_TYPEDEF_LS450_FUNCTIONSIMPL_4000_T
	typedef void* LS450_FUNCTIONSIMPL_4000_T;
#endif /* EXTERN_TYPEDEF_LS450_FUNCTIONSIMPL_4000_T */

	// No public default Java constructor; creating one:
	EXPORTED LS450_FUNCTIONSIMPL_4000_T LS450_FunctionsImpl_4000_Create();
	EXPORTED LS450_FUNCTIONSIMPL_4000_T LS450_FunctionsImpl_4000_Create_1(USBINTERFACE_T usbInt, SPECTROMETERPLUGIN_T plugin);
	EXPORTED void LS450_FunctionsImpl_4000_Destroy(LS450_FUNCTIONSIMPL_4000_T ls450_functionsimpl_4000);

#ifdef WIN32
	// Use the following function prototypes when calling functions from Visual Basic 6
	EXPORTED LS450_FUNCTIONSIMPL_4000_T STDCALL LS450_FunctionsImpl_4000_Create_stdcall_1(USBINTERFACE_T usbInt, SPECTROMETERPLUGIN_T plugin);
	EXPORTED void STDCALL LS450_FunctionsImpl_4000_Destroy_stdcall(LS450_FUNCTIONSIMPL_4000_T ls450_functionsimpl_4000);
#endif /* WIN32 */
#ifdef __cplusplus
};
#endif /* __cplusplus */
#endif /* LS450_FUNCTIONSIMPL_4000_H */
