/**
 * File: LUDecomposition.h
 * Autogenerated on Mon Nov 16 11:53:52 EST 2009 based on
 * LUDecomposition.java
 * for the Java class
 * com/oceanoptics/spam/numericalmethods/LUDecomposition
 * Copyright (C) 2006 - 2008 Ocean Optics, Inc.  All rights reserved.
 */


#ifndef LUDECOMPOSITION_H
#define LUDECOMPOSITION_H
#include "BaseJavaClass.h"

#ifdef __cplusplus

#ifdef INCLUDES_IN_HEADER
#include "Matrix.h"
#endif /* INCLUDES_IN_HEADER */

/* Pre-declarations for circular dependencies in header files */
#ifdef CLASS_PREDECLARATIONS
class Matrix;
#endif /* CLASS_PREDECLARATIONS */

CLASS_TOKEN EXPORTED LUDecomposition : public BaseJavaClass // CPPClass.getClassDeclaration
{
public: 
	LUDecomposition(Matrix& matrix);
	unsigned char isMatrixSingular();
	double getDeterminant();
	Matrix getL();
	Matrix getU();
	IntArray getPivot();
	Matrix solveForMatrix(Matrix& B);
	~LUDecomposition();
	// No public default Java constructor; creating one:
	LUDecomposition();
	// No public Java copy constructor; creating one:
	LUDecomposition(const LUDecomposition &that);
	// Creating assignment operator declaration:
	LUDecomposition &operator=(const LUDecomposition &that);

private:
	jmethodID mid_LUDecomposition304;
	jmethodID mid_isMatrixSingular305;
	jmethodID mid_getDeterminant306;
	jmethodID mid_getL307;
	jmethodID mid_getU308;
	jmethodID mid_getPivot309;
	jmethodID mid_solveForMatrix310;
	void init_ids(JNIEnv* pJNIEnv);
};

extern "C" {
#endif /* __cplusplus */
#ifndef EXTERN_TYPEDEF_MATRIX_T
#define EXTERN_TYPEDEF_MATRIX_T
	typedef void* MATRIX_T;
#endif /* EXTERN_TYPEDEF_MATRIX_T */
#ifndef EXTERN_TYPEDEF_LUDECOMPOSITION_T
#define EXTERN_TYPEDEF_LUDECOMPOSITION_T
	typedef void* LUDECOMPOSITION_T;
#endif /* EXTERN_TYPEDEF_LUDECOMPOSITION_T */

	// No public default Java constructor; creating one:
	EXPORTED LUDECOMPOSITION_T LUDecomposition_Create();
	EXPORTED LUDECOMPOSITION_T LUDecomposition_Create_1(MATRIX_T matrix);
	EXPORTED unsigned char LUDecomposition_isMatrixSingular(LUDECOMPOSITION_T c_ludecomposition);
	EXPORTED double LUDecomposition_getDeterminant(LUDECOMPOSITION_T c_ludecomposition);
	EXPORTED void LUDecomposition_getL(LUDECOMPOSITION_T c_ludecomposition, MATRIX_T retval);
	EXPORTED void LUDecomposition_getU(LUDECOMPOSITION_T c_ludecomposition, MATRIX_T retval);
	EXPORTED void LUDecomposition_getPivot(LUDECOMPOSITION_T c_ludecomposition, INTARRAY_T retval);
	EXPORTED void LUDecomposition_solveForMatrix(LUDECOMPOSITION_T c_ludecomposition, MATRIX_T B, MATRIX_T retval);
	EXPORTED void LUDecomposition_Destroy(LUDECOMPOSITION_T ludecomposition);

#ifdef WIN32
	// Use the following function prototypes when calling functions from Visual Basic 6
	EXPORTED LUDECOMPOSITION_T STDCALL LUDecomposition_Create_stdcall_1(MATRIX_T matrix);
	EXPORTED unsigned char STDCALL LUDecomposition_isMatrixSingular_stdcall(LUDECOMPOSITION_T c_ludecomposition);
	EXPORTED double STDCALL LUDecomposition_getDeterminant_stdcall(LUDECOMPOSITION_T c_ludecomposition);
	EXPORTED void STDCALL LUDecomposition_getL_stdcall(LUDECOMPOSITION_T c_ludecomposition, MATRIX_T retval);
	EXPORTED void STDCALL LUDecomposition_getU_stdcall(LUDECOMPOSITION_T c_ludecomposition, MATRIX_T retval);
	EXPORTED void STDCALL LUDecomposition_getPivot_stdcall(LUDECOMPOSITION_T c_ludecomposition, INTARRAY_T retval);
	EXPORTED void STDCALL LUDecomposition_solveForMatrix_stdcall(LUDECOMPOSITION_T c_ludecomposition, MATRIX_T B, MATRIX_T retval);
	EXPORTED void STDCALL LUDecomposition_Destroy_stdcall(LUDECOMPOSITION_T ludecomposition);
#endif /* WIN32 */
#ifdef __cplusplus
};
#endif /* __cplusplus */
#endif /* LUDECOMPOSITION_H */
