/**
 * File: MMSRaman.h
 * Autogenerated on Mon Nov 16 11:53:38 EST 2009 based on
 * MMSRaman.java
 * for the Java class
 * com/oceanoptics/omnidriver/spectrometer/mmsraman/ramanspectrometer/MMSRaman
 * Copyright (C) 2006 - 2008 Ocean Optics, Inc.  All rights reserved.
 */


#ifndef MMSRAMAN_H
#define MMSRAMAN_H
#include "BaseJavaClass.h"

#ifdef __cplusplus

#ifdef INCLUDES_IN_HEADER
#include "MMSRamanSpectrometer.h"
#include "GUIProviderArray.h"
#include "JString.h"
#include "SpectrometerExposure.h"
#include "SpectrometerReconstruction.h"
#include "Spectrum.h"
#include "MMSRamanCalibration.h"
#include "Laser.h"
#include "LaserArray.h"
#include "CoefficientsArray.h"
#include "JStringArray.h"
#include "ExposureListener.h"
#include "IntegrationTimeChangeListener.h"
#endif /* INCLUDES_IN_HEADER */

/* Pre-declarations for circular dependencies in header files */
#ifdef CLASS_PREDECLARATIONS
class MMSRamanSpectrometer;
class GUIProviderArray;
class JString;
class SpectrometerExposure;
class SpectrometerReconstruction;
class Spectrum;
class MMSRamanCalibration;
class Laser;
class LaserArray;
class CoefficientsArray;
class MMSRaman;
class JStringArray;
class ExposureListener;
class IntegrationTimeChangeListener;
#endif /* CLASS_PREDECLARATIONS */

CLASS_TOKEN EXPORTED MMSRaman : public MMSRamanSpectrometer // CPPClass.getClassDeclaration
{
public: 
	MMSRaman();
	MMSRaman(int i);
	void openSpectrometer(int index);
	GUIProviderArray getGUIFeatures();
	JString getSerialNumber();
	JString getModelNumber();
	void getSpectrometerInfo();
	float getIntegrationTime();
	void setIntegrationTime(int intTime);
	SpectrometerExposure getSpectrometerExposure(signed char shutter, signed char type);
	void startExposure(signed char shutter, signed char type);
	unsigned char queryExposure();
	SpectrometerExposure getExposure();
	void endExposure();
	void endExposure(signed char shutterState);
	SpectrometerReconstruction getReconstruction(signed char type);
	void reset();
	signed char getReconstructionType();
	void setReconstructionType(signed char reconstructionType);
	Spectrum getSpectrum(Spectrum& spectrum);
	void getDarkExposure();
	void getLightExposure();
	int getCcdWidth();
	int getCcdHeight();
	unsigned char isExposureInProgress();
	void setStrobeEnable(unsigned char laserOn);
	void readCalibrationFromSpectrometer();
	void writeCalibrationToSpectrometer(MMSRamanCalibration& cal);
	MMSRamanCalibration getCalibration();
	Laser getLaser(int laserIndex);
	LaserArray getLasers();
	void setLasers(LaserArray& lasers);
	int getNumberOfEnabledLasers();
	void setLaserInfo(int laserIndex);
	void getLaserInfo(int laserIndex);
	int getNumberOfSupportedLasers();
	void setNumberOfSupportedLasers(int numberOfSupportedLasers);
	void setDefaultLaser(int laserIndex);
	int getDefaultLaser();
	unsigned char isLaserTemperatureRegulation();
	void setLaserTemperatureRegulation(unsigned char laserTemperatureRegulation);
	void getLaserTemperatureInfo();
	void setLaserTemperatureInfo();
	int getMinimumLaserSetpoint();
	void setMinimumLaserSetpoint(int minimumLaserSetpoint);
	int getMaximumLaserSetpoint();
	void setMaximumLaserSetpoint(int maximumLaserSetpoint);
	void setLaserPowerInfo(int power);
	int getLaserPowerInfo();
	unsigned char isLaserPowerRegulation();
	void setLaserPowerRegulation(unsigned char laserPowerRegulation);
	int getMinimumLaserPowerSetpoint();
	void setMinimumLaserPowerSetpoint(int minimumLaserPowerSetpoint);
	int getMaximumLaserPowerSetpoint();
	void setMaximumLaserPowerSetpoint(int maximumLaserPowerSetpoint);
	void getCCDTemperatureInfo();
	void setCCDTemperatureInfo(unsigned char regulation, float setpoint);
	unsigned char isTemperatureRegulation();
	void setTemperatureRegulation(unsigned char temperatureRegulation);
	float getCCDSetpoint();
	void setCCDSetpoint(float setpoint);
	int getMinimumCCDSetpoint();
	void setMinimumCCDSetpoint(int min);
	int getMaximumCCDSetpoint();
	void setMaximumCCDSetpoint(int max);
	float getThermistor();
	unsigned char isThermFault();
	unsigned char isTempLock();
	signed char getShutterState();
	unsigned char isShutterOpen();
	void openShutter();
	void closeShutter();
	CoefficientsArray readWavelengthCalibrationCoefficientsFromSpectrometer();
	void writeWavelengthCoefficientsToSpectrometer(CoefficientsArray& coefficients);
	CoefficientsArray getWavelengthCalibrationCoefficients();
	void setWavelengthCalibrationCoefficients(CoefficientsArray& coefficients);
	DoubleArray getWavelengths(int index);
	void setWavelengths(DoubleArray& wl, int index);
	JString getFirmwareVersion();
	void setDSPFirmwareVersion(JString& dsp);
	JString getDSPFirmwareVersion();
	void setFPGAFirmwareVersion(JString& fpga);
	JString getFPGAFirmwareVersion();
	void setUSBFirmwareVersion(JString& usb);
	JString getUSBFirmwareVersion();
	MMSRaman getSpectrometer();
	void setMasterClock(int rate);
	JStringArray getLEDFlashCodes();
	JString toString();
	void addExposureListener(ExposureListener& listener);
	void removeExposureListener(ExposureListener& listener);
	SpectrometerExposure getLastExposure();
	unsigned char has1DMode();
	void set2DMode(int channel);
	void set1DMode(int channel);
	unsigned char is2DMode();
	unsigned char is1DMode();
	int get2DintegrationTime();
	void addIntegrationTimeChangeListener(IntegrationTimeChangeListener& listener);
	void removeIntegrationTimeChangeListener(IntegrationTimeChangeListener& listener);
	void fireIntegrationTimeChanged(int time);
	~MMSRaman();
	// No public Java copy constructor; creating one:
	MMSRaman(const MMSRaman &that);
	// Creating assignment operator declaration:
	MMSRaman &operator=(const MMSRaman &that);

private:
	jmethodID mid_MMSRaman2697;
	jmethodID mid_MMSRaman2698;
	jmethodID mid_openSpectrometer2699;
	jmethodID mid_getGUIFeatures2700;
	jmethodID mid_getSerialNumber2701;
	jmethodID mid_getModelNumber2702;
	jmethodID mid_getSpectrometerInfo2703;
	jmethodID mid_getIntegrationTime2704;
	jmethodID mid_setIntegrationTime2705;
	jmethodID mid_getSpectrometerExposure2706;
	jmethodID mid_startExposure2707;
	jmethodID mid_queryExposure2708;
	jmethodID mid_getExposure2709;
	jmethodID mid_endExposure2710;
	jmethodID mid_endExposure2711;
	jmethodID mid_getReconstruction2712;
	jmethodID mid_reset2713;
	jmethodID mid_getReconstructionType2714;
	jmethodID mid_setReconstructionType2715;
	jmethodID mid_getSpectrum2716;
	jmethodID mid_getDarkExposure2717;
	jmethodID mid_getLightExposure2718;
	jmethodID mid_getCcdWidth2719;
	jmethodID mid_getCcdHeight2720;
	jmethodID mid_isExposureInProgress2721;
	jmethodID mid_setStrobeEnable2722;
	jmethodID mid_readCalibrationFromSpectrometer2723;
	jmethodID mid_writeCalibrationToSpectrometer2724;
	jmethodID mid_getCalibration2725;
	jmethodID mid_getLaser2726;
	jmethodID mid_getLasers2727;
	jmethodID mid_setLasers2728;
	jmethodID mid_getNumberOfEnabledLasers2729;
	jmethodID mid_setLaserInfo2730;
	jmethodID mid_getLaserInfo2731;
	jmethodID mid_getNumberOfSupportedLasers2732;
	jmethodID mid_setNumberOfSupportedLasers2733;
	jmethodID mid_setDefaultLaser2734;
	jmethodID mid_getDefaultLaser2735;
	jmethodID mid_isLaserTemperatureRegulation2736;
	jmethodID mid_setLaserTemperatureRegulation2737;
	jmethodID mid_getLaserTemperatureInfo2738;
	jmethodID mid_setLaserTemperatureInfo2739;
	jmethodID mid_getMinimumLaserSetpoint2740;
	jmethodID mid_setMinimumLaserSetpoint2741;
	jmethodID mid_getMaximumLaserSetpoint2742;
	jmethodID mid_setMaximumLaserSetpoint2743;
	jmethodID mid_setLaserPowerInfo2744;
	jmethodID mid_getLaserPowerInfo2745;
	jmethodID mid_isLaserPowerRegulation2746;
	jmethodID mid_setLaserPowerRegulation2747;
	jmethodID mid_getMinimumLaserPowerSetpoint2748;
	jmethodID mid_setMinimumLaserPowerSetpoint2749;
	jmethodID mid_getMaximumLaserPowerSetpoint2750;
	jmethodID mid_setMaximumLaserPowerSetpoint2751;
	jmethodID mid_getCCDTemperatureInfo2752;
	jmethodID mid_setCCDTemperatureInfo2753;
	jmethodID mid_isTemperatureRegulation2754;
	jmethodID mid_setTemperatureRegulation2755;
	jmethodID mid_getCCDSetpoint2756;
	jmethodID mid_setCCDSetpoint2757;
	jmethodID mid_getMinimumCCDSetpoint2758;
	jmethodID mid_setMinimumCCDSetpoint2759;
	jmethodID mid_getMaximumCCDSetpoint2760;
	jmethodID mid_setMaximumCCDSetpoint2761;
	jmethodID mid_getThermistor2762;
	jmethodID mid_isThermFault2763;
	jmethodID mid_isTempLock2764;
	jmethodID mid_getShutterState2765;
	jmethodID mid_isShutterOpen2766;
	jmethodID mid_openShutter2767;
	jmethodID mid_closeShutter2768;
	jmethodID mid_readWavelengthCalibrationCoefficientsFromSpectrometer2769;
	jmethodID mid_writeWavelengthCoefficientsToSpectrometer2770;
	jmethodID mid_getWavelengthCalibrationCoefficients2771;
	jmethodID mid_setWavelengthCalibrationCoefficients2772;
	jmethodID mid_getWavelengths2773;
	jmethodID mid_setWavelengths2774;
	jmethodID mid_getFirmwareVersion2775;
	jmethodID mid_setDSPFirmwareVersion2776;
	jmethodID mid_getDSPFirmwareVersion2777;
	jmethodID mid_setFPGAFirmwareVersion2778;
	jmethodID mid_getFPGAFirmwareVersion2779;
	jmethodID mid_setUSBFirmwareVersion2780;
	jmethodID mid_getUSBFirmwareVersion2781;
	jmethodID mid_getSpectrometer2782;
	jmethodID mid_setMasterClock2783;
	jmethodID mid_getLEDFlashCodes2784;
	jmethodID mid_toString2785;
	jmethodID mid_addExposureListener2786;
	jmethodID mid_removeExposureListener2787;
	jmethodID mid_getLastExposure2788;
	jmethodID mid_has1DMode2789;
	jmethodID mid_set2DMode2790;
	jmethodID mid_set1DMode2791;
	jmethodID mid_is2DMode2792;
	jmethodID mid_is1DMode2793;
	jmethodID mid_get2DintegrationTime2794;
	jmethodID mid_addIntegrationTimeChangeListener2795;
	jmethodID mid_removeIntegrationTimeChangeListener2796;
	jmethodID mid_fireIntegrationTimeChanged2797;
	void init_ids(JNIEnv* pJNIEnv);
};

extern "C" {
#endif /* __cplusplus */
#ifndef EXTERN_TYPEDEF_MMSRAMANSPECTROMETER_T
#define EXTERN_TYPEDEF_MMSRAMANSPECTROMETER_T
	typedef void* MMSRAMANSPECTROMETER_T;
#endif /* EXTERN_TYPEDEF_MMSRAMANSPECTROMETER_T */
#ifndef EXTERN_TYPEDEF_GUIPROVIDERARRAY_T
#define EXTERN_TYPEDEF_GUIPROVIDERARRAY_T
	typedef void* GUIPROVIDERARRAY_T;
#endif /* EXTERN_TYPEDEF_GUIPROVIDERARRAY_T */
#ifndef EXTERN_TYPEDEF_JSTRING_T
#define EXTERN_TYPEDEF_JSTRING_T
	typedef void* JSTRING_T;
#endif /* EXTERN_TYPEDEF_JSTRING_T */
#ifndef EXTERN_TYPEDEF_SPECTROMETEREXPOSURE_T
#define EXTERN_TYPEDEF_SPECTROMETEREXPOSURE_T
	typedef void* SPECTROMETEREXPOSURE_T;
#endif /* EXTERN_TYPEDEF_SPECTROMETEREXPOSURE_T */
#ifndef EXTERN_TYPEDEF_SPECTROMETERRECONSTRUCTION_T
#define EXTERN_TYPEDEF_SPECTROMETERRECONSTRUCTION_T
	typedef void* SPECTROMETERRECONSTRUCTION_T;
#endif /* EXTERN_TYPEDEF_SPECTROMETERRECONSTRUCTION_T */
#ifndef EXTERN_TYPEDEF_SPECTRUM_T
#define EXTERN_TYPEDEF_SPECTRUM_T
	typedef void* SPECTRUM_T;
#endif /* EXTERN_TYPEDEF_SPECTRUM_T */
#ifndef EXTERN_TYPEDEF_MMSRAMANCALIBRATION_T
#define EXTERN_TYPEDEF_MMSRAMANCALIBRATION_T
	typedef void* MMSRAMANCALIBRATION_T;
#endif /* EXTERN_TYPEDEF_MMSRAMANCALIBRATION_T */
#ifndef EXTERN_TYPEDEF_LASER_T
#define EXTERN_TYPEDEF_LASER_T
	typedef void* LASER_T;
#endif /* EXTERN_TYPEDEF_LASER_T */
#ifndef EXTERN_TYPEDEF_LASERARRAY_T
#define EXTERN_TYPEDEF_LASERARRAY_T
	typedef void* LASERARRAY_T;
#endif /* EXTERN_TYPEDEF_LASERARRAY_T */
#ifndef EXTERN_TYPEDEF_COEFFICIENTSARRAY_T
#define EXTERN_TYPEDEF_COEFFICIENTSARRAY_T
	typedef void* COEFFICIENTSARRAY_T;
#endif /* EXTERN_TYPEDEF_COEFFICIENTSARRAY_T */
#ifndef EXTERN_TYPEDEF_MMSRAMAN_T
#define EXTERN_TYPEDEF_MMSRAMAN_T
	typedef void* MMSRAMAN_T;
#endif /* EXTERN_TYPEDEF_MMSRAMAN_T */
#ifndef EXTERN_TYPEDEF_JSTRINGARRAY_T
#define EXTERN_TYPEDEF_JSTRINGARRAY_T
	typedef void* JSTRINGARRAY_T;
#endif /* EXTERN_TYPEDEF_JSTRINGARRAY_T */
#ifndef EXTERN_TYPEDEF_EXPOSURELISTENER_T
#define EXTERN_TYPEDEF_EXPOSURELISTENER_T
	typedef void* EXPOSURELISTENER_T;
#endif /* EXTERN_TYPEDEF_EXPOSURELISTENER_T */
#ifndef EXTERN_TYPEDEF_INTEGRATIONTIMECHANGELISTENER_T
#define EXTERN_TYPEDEF_INTEGRATIONTIMECHANGELISTENER_T
	typedef void* INTEGRATIONTIMECHANGELISTENER_T;
#endif /* EXTERN_TYPEDEF_INTEGRATIONTIMECHANGELISTENER_T */

	EXPORTED MMSRAMAN_T MMSRaman_Create();
	EXPORTED MMSRAMAN_T MMSRaman_Create_1(int i);
	EXPORTED void MMSRaman_openSpectrometer(MMSRAMAN_T c_mmsraman, int index);
	EXPORTED void MMSRaman_getGUIFeatures(MMSRAMAN_T c_mmsraman, GUIPROVIDERARRAY_T retval);
	EXPORTED void MMSRaman_getSerialNumber(MMSRAMAN_T c_mmsraman, JSTRING_T retval);
	EXPORTED void MMSRaman_getModelNumber(MMSRAMAN_T c_mmsraman, JSTRING_T retval);
	EXPORTED void MMSRaman_getSpectrometerInfo(MMSRAMAN_T c_mmsraman);
	EXPORTED float MMSRaman_getIntegrationTime(MMSRAMAN_T c_mmsraman);
	EXPORTED void MMSRaman_setIntegrationTime(MMSRAMAN_T c_mmsraman, int intTime);
	EXPORTED void MMSRaman_getSpectrometerExposure(MMSRAMAN_T c_mmsraman, signed char shutter, signed char type, SPECTROMETEREXPOSURE_T retval);
	EXPORTED void MMSRaman_startExposure(MMSRAMAN_T c_mmsraman, signed char shutter, signed char type);
	EXPORTED unsigned char MMSRaman_queryExposure(MMSRAMAN_T c_mmsraman);
	EXPORTED void MMSRaman_getExposure(MMSRAMAN_T c_mmsraman, SPECTROMETEREXPOSURE_T retval);
	EXPORTED void MMSRaman_endExposure(MMSRAMAN_T c_mmsraman);
	EXPORTED void MMSRaman_endExposure_1(MMSRAMAN_T c_mmsraman, signed char shutterState);
	EXPORTED void MMSRaman_getReconstruction(MMSRAMAN_T c_mmsraman, signed char type, SPECTROMETERRECONSTRUCTION_T retval);
	EXPORTED void MMSRaman_reset(MMSRAMAN_T c_mmsraman);
	EXPORTED signed char MMSRaman_getReconstructionType(MMSRAMAN_T c_mmsraman);
	EXPORTED void MMSRaman_setReconstructionType(MMSRAMAN_T c_mmsraman, signed char reconstructionType);
	EXPORTED void MMSRaman_getSpectrum(MMSRAMAN_T c_mmsraman, SPECTRUM_T spectrum, SPECTRUM_T retval);
	EXPORTED void MMSRaman_getDarkExposure(MMSRAMAN_T c_mmsraman);
	EXPORTED void MMSRaman_getLightExposure(MMSRAMAN_T c_mmsraman);
	EXPORTED int MMSRaman_getCcdWidth(MMSRAMAN_T c_mmsraman);
	EXPORTED int MMSRaman_getCcdHeight(MMSRAMAN_T c_mmsraman);
	EXPORTED unsigned char MMSRaman_isExposureInProgress(MMSRAMAN_T c_mmsraman);
	EXPORTED void MMSRaman_setStrobeEnable(MMSRAMAN_T c_mmsraman, unsigned char laserOn);
	EXPORTED void MMSRaman_readCalibrationFromSpectrometer(MMSRAMAN_T c_mmsraman);
	EXPORTED void MMSRaman_writeCalibrationToSpectrometer(MMSRAMAN_T c_mmsraman, MMSRAMANCALIBRATION_T cal);
	EXPORTED void MMSRaman_getCalibration(MMSRAMAN_T c_mmsraman, MMSRAMANCALIBRATION_T retval);
	EXPORTED void MMSRaman_getLaser(MMSRAMAN_T c_mmsraman, int laserIndex, LASER_T retval);
	EXPORTED void MMSRaman_getLasers(MMSRAMAN_T c_mmsraman, LASERARRAY_T retval);
	EXPORTED void MMSRaman_setLasers(MMSRAMAN_T c_mmsraman, LASERARRAY_T lasers);
	EXPORTED int MMSRaman_getNumberOfEnabledLasers(MMSRAMAN_T c_mmsraman);
	EXPORTED void MMSRaman_setLaserInfo(MMSRAMAN_T c_mmsraman, int laserIndex);
	EXPORTED void MMSRaman_getLaserInfo(MMSRAMAN_T c_mmsraman, int laserIndex);
	EXPORTED int MMSRaman_getNumberOfSupportedLasers(MMSRAMAN_T c_mmsraman);
	EXPORTED void MMSRaman_setNumberOfSupportedLasers(MMSRAMAN_T c_mmsraman, int numberOfSupportedLasers);
	EXPORTED void MMSRaman_setDefaultLaser(MMSRAMAN_T c_mmsraman, int laserIndex);
	EXPORTED int MMSRaman_getDefaultLaser(MMSRAMAN_T c_mmsraman);
	EXPORTED unsigned char MMSRaman_isLaserTemperatureRegulation(MMSRAMAN_T c_mmsraman);
	EXPORTED void MMSRaman_setLaserTemperatureRegulation(MMSRAMAN_T c_mmsraman, unsigned char laserTemperatureRegulation);
	EXPORTED void MMSRaman_getLaserTemperatureInfo(MMSRAMAN_T c_mmsraman);
	EXPORTED void MMSRaman_setLaserTemperatureInfo(MMSRAMAN_T c_mmsraman);
	EXPORTED int MMSRaman_getMinimumLaserSetpoint(MMSRAMAN_T c_mmsraman);
	EXPORTED void MMSRaman_setMinimumLaserSetpoint(MMSRAMAN_T c_mmsraman, int minimumLaserSetpoint);
	EXPORTED int MMSRaman_getMaximumLaserSetpoint(MMSRAMAN_T c_mmsraman);
	EXPORTED void MMSRaman_setMaximumLaserSetpoint(MMSRAMAN_T c_mmsraman, int maximumLaserSetpoint);
	EXPORTED void MMSRaman_setLaserPowerInfo(MMSRAMAN_T c_mmsraman, int power);
	EXPORTED int MMSRaman_getLaserPowerInfo(MMSRAMAN_T c_mmsraman);
	EXPORTED unsigned char MMSRaman_isLaserPowerRegulation(MMSRAMAN_T c_mmsraman);
	EXPORTED void MMSRaman_setLaserPowerRegulation(MMSRAMAN_T c_mmsraman, unsigned char laserPowerRegulation);
	EXPORTED int MMSRaman_getMinimumLaserPowerSetpoint(MMSRAMAN_T c_mmsraman);
	EXPORTED void MMSRaman_setMinimumLaserPowerSetpoint(MMSRAMAN_T c_mmsraman, int minimumLaserPowerSetpoint);
	EXPORTED int MMSRaman_getMaximumLaserPowerSetpoint(MMSRAMAN_T c_mmsraman);
	EXPORTED void MMSRaman_setMaximumLaserPowerSetpoint(MMSRAMAN_T c_mmsraman, int maximumLaserPowerSetpoint);
	EXPORTED void MMSRaman_getCCDTemperatureInfo(MMSRAMAN_T c_mmsraman);
	EXPORTED void MMSRaman_setCCDTemperatureInfo(MMSRAMAN_T c_mmsraman, unsigned char regulation, float setpoint);
	EXPORTED unsigned char MMSRaman_isTemperatureRegulation(MMSRAMAN_T c_mmsraman);
	EXPORTED void MMSRaman_setTemperatureRegulation(MMSRAMAN_T c_mmsraman, unsigned char temperatureRegulation);
	EXPORTED float MMSRaman_getCCDSetpoint(MMSRAMAN_T c_mmsraman);
	EXPORTED void MMSRaman_setCCDSetpoint(MMSRAMAN_T c_mmsraman, float setpoint);
	EXPORTED int MMSRaman_getMinimumCCDSetpoint(MMSRAMAN_T c_mmsraman);
	EXPORTED void MMSRaman_setMinimumCCDSetpoint(MMSRAMAN_T c_mmsraman, int min);
	EXPORTED int MMSRaman_getMaximumCCDSetpoint(MMSRAMAN_T c_mmsraman);
	EXPORTED void MMSRaman_setMaximumCCDSetpoint(MMSRAMAN_T c_mmsraman, int max);
	EXPORTED float MMSRaman_getThermistor(MMSRAMAN_T c_mmsraman);
	EXPORTED unsigned char MMSRaman_isThermFault(MMSRAMAN_T c_mmsraman);
	EXPORTED unsigned char MMSRaman_isTempLock(MMSRAMAN_T c_mmsraman);
	EXPORTED signed char MMSRaman_getShutterState(MMSRAMAN_T c_mmsraman);
	EXPORTED unsigned char MMSRaman_isShutterOpen(MMSRAMAN_T c_mmsraman);
	EXPORTED void MMSRaman_openShutter(MMSRAMAN_T c_mmsraman);
	EXPORTED void MMSRaman_closeShutter(MMSRAMAN_T c_mmsraman);
	EXPORTED void MMSRaman_readWavelengthCalibrationCoefficientsFromSpectrometer(MMSRAMAN_T c_mmsraman, COEFFICIENTSARRAY_T retval);
	EXPORTED void MMSRaman_writeWavelengthCoefficientsToSpectrometer(MMSRAMAN_T c_mmsraman, COEFFICIENTSARRAY_T coefficients);
	EXPORTED void MMSRaman_getWavelengthCalibrationCoefficients(MMSRAMAN_T c_mmsraman, COEFFICIENTSARRAY_T retval);
	EXPORTED void MMSRaman_setWavelengthCalibrationCoefficients(MMSRAMAN_T c_mmsraman, COEFFICIENTSARRAY_T coefficients);
	EXPORTED void MMSRaman_getWavelengths(MMSRAMAN_T c_mmsraman, int index, DOUBLEARRAY_T retval);
	EXPORTED void MMSRaman_setWavelengths(MMSRAMAN_T c_mmsraman, DOUBLEARRAY_T wl, int index);
	EXPORTED void MMSRaman_getFirmwareVersion(MMSRAMAN_T c_mmsraman, JSTRING_T retval);
	EXPORTED void MMSRaman_setDSPFirmwareVersion(MMSRAMAN_T c_mmsraman, JSTRING_T dsp);
	EXPORTED void MMSRaman_getDSPFirmwareVersion(MMSRAMAN_T c_mmsraman, JSTRING_T retval);
	EXPORTED void MMSRaman_setFPGAFirmwareVersion(MMSRAMAN_T c_mmsraman, JSTRING_T fpga);
	EXPORTED void MMSRaman_getFPGAFirmwareVersion(MMSRAMAN_T c_mmsraman, JSTRING_T retval);
	EXPORTED void MMSRaman_setUSBFirmwareVersion(MMSRAMAN_T c_mmsraman, JSTRING_T usb);
	EXPORTED void MMSRaman_getUSBFirmwareVersion(MMSRAMAN_T c_mmsraman, JSTRING_T retval);
	EXPORTED void MMSRaman_getSpectrometer(MMSRAMAN_T c_mmsraman, MMSRAMAN_T retval);
	EXPORTED void MMSRaman_setMasterClock(MMSRAMAN_T c_mmsraman, int rate);
	EXPORTED void MMSRaman_getLEDFlashCodes(MMSRAMAN_T c_mmsraman, JSTRINGARRAY_T retval);
	EXPORTED void MMSRaman_toString(MMSRAMAN_T c_mmsraman, JSTRING_T retval);
	EXPORTED void MMSRaman_addExposureListener(MMSRAMAN_T c_mmsraman, EXPOSURELISTENER_T listener);
	EXPORTED void MMSRaman_removeExposureListener(MMSRAMAN_T c_mmsraman, EXPOSURELISTENER_T listener);
	EXPORTED void MMSRaman_getLastExposure(MMSRAMAN_T c_mmsraman, SPECTROMETEREXPOSURE_T retval);
	EXPORTED unsigned char MMSRaman_has1DMode(MMSRAMAN_T c_mmsraman);
	EXPORTED void MMSRaman_set2DMode(MMSRAMAN_T c_mmsraman, int channel);
	EXPORTED void MMSRaman_set1DMode(MMSRAMAN_T c_mmsraman, int channel);
	EXPORTED unsigned char MMSRaman_is2DMode(MMSRAMAN_T c_mmsraman);
	EXPORTED unsigned char MMSRaman_is1DMode(MMSRAMAN_T c_mmsraman);
	EXPORTED int MMSRaman_get2DintegrationTime(MMSRAMAN_T c_mmsraman);
	EXPORTED void MMSRaman_addIntegrationTimeChangeListener(MMSRAMAN_T c_mmsraman, INTEGRATIONTIMECHANGELISTENER_T listener);
	EXPORTED void MMSRaman_removeIntegrationTimeChangeListener(MMSRAMAN_T c_mmsraman, INTEGRATIONTIMECHANGELISTENER_T listener);
	EXPORTED void MMSRaman_fireIntegrationTimeChanged(MMSRAMAN_T c_mmsraman, int time);
	EXPORTED void MMSRaman_Destroy(MMSRAMAN_T mmsraman);

#ifdef WIN32
	// Use the following function prototypes when calling functions from Visual Basic 6
	EXPORTED MMSRAMAN_T STDCALL MMSRaman_Create_stdcall();
	EXPORTED MMSRAMAN_T STDCALL MMSRaman_Create_stdcall_1(int i);
	EXPORTED void STDCALL MMSRaman_openSpectrometer_stdcall(MMSRAMAN_T c_mmsraman, int index);
	EXPORTED void STDCALL MMSRaman_getGUIFeatures_stdcall(MMSRAMAN_T c_mmsraman, GUIPROVIDERARRAY_T retval);
	EXPORTED void STDCALL MMSRaman_getSerialNumber_stdcall(MMSRAMAN_T c_mmsraman, JSTRING_T retval);
	EXPORTED void STDCALL MMSRaman_getModelNumber_stdcall(MMSRAMAN_T c_mmsraman, JSTRING_T retval);
	EXPORTED void STDCALL MMSRaman_getSpectrometerInfo_stdcall(MMSRAMAN_T c_mmsraman);
	EXPORTED float STDCALL MMSRaman_getIntegrationTime_stdcall(MMSRAMAN_T c_mmsraman);
	EXPORTED void STDCALL MMSRaman_setIntegrationTime_stdcall(MMSRAMAN_T c_mmsraman, int intTime);
	EXPORTED void STDCALL MMSRaman_getSpectrometerExposure_stdcall(MMSRAMAN_T c_mmsraman, signed char shutter, signed char type, SPECTROMETEREXPOSURE_T retval);
	EXPORTED void STDCALL MMSRaman_startExposure_stdcall(MMSRAMAN_T c_mmsraman, signed char shutter, signed char type);
	EXPORTED unsigned char STDCALL MMSRaman_queryExposure_stdcall(MMSRAMAN_T c_mmsraman);
	EXPORTED void STDCALL MMSRaman_getExposure_stdcall(MMSRAMAN_T c_mmsraman, SPECTROMETEREXPOSURE_T retval);
	EXPORTED void STDCALL MMSRaman_endExposure_stdcall(MMSRAMAN_T c_mmsraman);
	EXPORTED void STDCALL MMSRaman_endExposure_stdcall_1(MMSRAMAN_T c_mmsraman, signed char shutterState);
	EXPORTED void STDCALL MMSRaman_getReconstruction_stdcall(MMSRAMAN_T c_mmsraman, signed char type, SPECTROMETERRECONSTRUCTION_T retval);
	EXPORTED void STDCALL MMSRaman_reset_stdcall(MMSRAMAN_T c_mmsraman);
	EXPORTED signed char STDCALL MMSRaman_getReconstructionType_stdcall(MMSRAMAN_T c_mmsraman);
	EXPORTED void STDCALL MMSRaman_setReconstructionType_stdcall(MMSRAMAN_T c_mmsraman, signed char reconstructionType);
	EXPORTED void STDCALL MMSRaman_getSpectrum_stdcall(MMSRAMAN_T c_mmsraman, SPECTRUM_T spectrum, SPECTRUM_T retval);
	EXPORTED void STDCALL MMSRaman_getDarkExposure_stdcall(MMSRAMAN_T c_mmsraman);
	EXPORTED void STDCALL MMSRaman_getLightExposure_stdcall(MMSRAMAN_T c_mmsraman);
	EXPORTED int STDCALL MMSRaman_getCcdWidth_stdcall(MMSRAMAN_T c_mmsraman);
	EXPORTED int STDCALL MMSRaman_getCcdHeight_stdcall(MMSRAMAN_T c_mmsraman);
	EXPORTED unsigned char STDCALL MMSRaman_isExposureInProgress_stdcall(MMSRAMAN_T c_mmsraman);
	EXPORTED void STDCALL MMSRaman_setStrobeEnable_stdcall(MMSRAMAN_T c_mmsraman, unsigned char laserOn);
	EXPORTED void STDCALL MMSRaman_readCalibrationFromSpectrometer_stdcall(MMSRAMAN_T c_mmsraman);
	EXPORTED void STDCALL MMSRaman_writeCalibrationToSpectrometer_stdcall(MMSRAMAN_T c_mmsraman, MMSRAMANCALIBRATION_T cal);
	EXPORTED void STDCALL MMSRaman_getCalibration_stdcall(MMSRAMAN_T c_mmsraman, MMSRAMANCALIBRATION_T retval);
	EXPORTED void STDCALL MMSRaman_getLaser_stdcall(MMSRAMAN_T c_mmsraman, int laserIndex, LASER_T retval);
	EXPORTED void STDCALL MMSRaman_getLasers_stdcall(MMSRAMAN_T c_mmsraman, LASERARRAY_T retval);
	EXPORTED void STDCALL MMSRaman_setLasers_stdcall(MMSRAMAN_T c_mmsraman, LASERARRAY_T lasers);
	EXPORTED int STDCALL MMSRaman_getNumberOfEnabledLasers_stdcall(MMSRAMAN_T c_mmsraman);
	EXPORTED void STDCALL MMSRaman_setLaserInfo_stdcall(MMSRAMAN_T c_mmsraman, int laserIndex);
	EXPORTED void STDCALL MMSRaman_getLaserInfo_stdcall(MMSRAMAN_T c_mmsraman, int laserIndex);
	EXPORTED int STDCALL MMSRaman_getNumberOfSupportedLasers_stdcall(MMSRAMAN_T c_mmsraman);
	EXPORTED void STDCALL MMSRaman_setNumberOfSupportedLasers_stdcall(MMSRAMAN_T c_mmsraman, int numberOfSupportedLasers);
	EXPORTED void STDCALL MMSRaman_setDefaultLaser_stdcall(MMSRAMAN_T c_mmsraman, int laserIndex);
	EXPORTED int STDCALL MMSRaman_getDefaultLaser_stdcall(MMSRAMAN_T c_mmsraman);
	EXPORTED unsigned char STDCALL MMSRaman_isLaserTemperatureRegulation_stdcall(MMSRAMAN_T c_mmsraman);
	EXPORTED void STDCALL MMSRaman_setLaserTemperatureRegulation_stdcall(MMSRAMAN_T c_mmsraman, unsigned char laserTemperatureRegulation);
	EXPORTED void STDCALL MMSRaman_getLaserTemperatureInfo_stdcall(MMSRAMAN_T c_mmsraman);
	EXPORTED void STDCALL MMSRaman_setLaserTemperatureInfo_stdcall(MMSRAMAN_T c_mmsraman);
	EXPORTED int STDCALL MMSRaman_getMinimumLaserSetpoint_stdcall(MMSRAMAN_T c_mmsraman);
	EXPORTED void STDCALL MMSRaman_setMinimumLaserSetpoint_stdcall(MMSRAMAN_T c_mmsraman, int minimumLaserSetpoint);
	EXPORTED int STDCALL MMSRaman_getMaximumLaserSetpoint_stdcall(MMSRAMAN_T c_mmsraman);
	EXPORTED void STDCALL MMSRaman_setMaximumLaserSetpoint_stdcall(MMSRAMAN_T c_mmsraman, int maximumLaserSetpoint);
	EXPORTED void STDCALL MMSRaman_setLaserPowerInfo_stdcall(MMSRAMAN_T c_mmsraman, int power);
	EXPORTED int STDCALL MMSRaman_getLaserPowerInfo_stdcall(MMSRAMAN_T c_mmsraman);
	EXPORTED unsigned char STDCALL MMSRaman_isLaserPowerRegulation_stdcall(MMSRAMAN_T c_mmsraman);
	EXPORTED void STDCALL MMSRaman_setLaserPowerRegulation_stdcall(MMSRAMAN_T c_mmsraman, unsigned char laserPowerRegulation);
	EXPORTED int STDCALL MMSRaman_getMinimumLaserPowerSetpoint_stdcall(MMSRAMAN_T c_mmsraman);
	EXPORTED void STDCALL MMSRaman_setMinimumLaserPowerSetpoint_stdcall(MMSRAMAN_T c_mmsraman, int minimumLaserPowerSetpoint);
	EXPORTED int STDCALL MMSRaman_getMaximumLaserPowerSetpoint_stdcall(MMSRAMAN_T c_mmsraman);
	EXPORTED void STDCALL MMSRaman_setMaximumLaserPowerSetpoint_stdcall(MMSRAMAN_T c_mmsraman, int maximumLaserPowerSetpoint);
	EXPORTED void STDCALL MMSRaman_getCCDTemperatureInfo_stdcall(MMSRAMAN_T c_mmsraman);
	EXPORTED void STDCALL MMSRaman_setCCDTemperatureInfo_stdcall(MMSRAMAN_T c_mmsraman, unsigned char regulation, float setpoint);
	EXPORTED unsigned char STDCALL MMSRaman_isTemperatureRegulation_stdcall(MMSRAMAN_T c_mmsraman);
	EXPORTED void STDCALL MMSRaman_setTemperatureRegulation_stdcall(MMSRAMAN_T c_mmsraman, unsigned char temperatureRegulation);
	EXPORTED float STDCALL MMSRaman_getCCDSetpoint_stdcall(MMSRAMAN_T c_mmsraman);
	EXPORTED void STDCALL MMSRaman_setCCDSetpoint_stdcall(MMSRAMAN_T c_mmsraman, float setpoint);
	EXPORTED int STDCALL MMSRaman_getMinimumCCDSetpoint_stdcall(MMSRAMAN_T c_mmsraman);
	EXPORTED void STDCALL MMSRaman_setMinimumCCDSetpoint_stdcall(MMSRAMAN_T c_mmsraman, int min);
	EXPORTED int STDCALL MMSRaman_getMaximumCCDSetpoint_stdcall(MMSRAMAN_T c_mmsraman);
	EXPORTED void STDCALL MMSRaman_setMaximumCCDSetpoint_stdcall(MMSRAMAN_T c_mmsraman, int max);
	EXPORTED float STDCALL MMSRaman_getThermistor_stdcall(MMSRAMAN_T c_mmsraman);
	EXPORTED unsigned char STDCALL MMSRaman_isThermFault_stdcall(MMSRAMAN_T c_mmsraman);
	EXPORTED unsigned char STDCALL MMSRaman_isTempLock_stdcall(MMSRAMAN_T c_mmsraman);
	EXPORTED signed char STDCALL MMSRaman_getShutterState_stdcall(MMSRAMAN_T c_mmsraman);
	EXPORTED unsigned char STDCALL MMSRaman_isShutterOpen_stdcall(MMSRAMAN_T c_mmsraman);
	EXPORTED void STDCALL MMSRaman_openShutter_stdcall(MMSRAMAN_T c_mmsraman);
	EXPORTED void STDCALL MMSRaman_closeShutter_stdcall(MMSRAMAN_T c_mmsraman);
	EXPORTED void STDCALL MMSRaman_readWavelengthCalibrationCoefficientsFromSpectrometer_stdcall(MMSRAMAN_T c_mmsraman, COEFFICIENTSARRAY_T retval);
	EXPORTED void STDCALL MMSRaman_writeWavelengthCoefficientsToSpectrometer_stdcall(MMSRAMAN_T c_mmsraman, COEFFICIENTSARRAY_T coefficients);
	EXPORTED void STDCALL MMSRaman_getWavelengthCalibrationCoefficients_stdcall(MMSRAMAN_T c_mmsraman, COEFFICIENTSARRAY_T retval);
	EXPORTED void STDCALL MMSRaman_setWavelengthCalibrationCoefficients_stdcall(MMSRAMAN_T c_mmsraman, COEFFICIENTSARRAY_T coefficients);
	EXPORTED void STDCALL MMSRaman_getWavelengths_stdcall(MMSRAMAN_T c_mmsraman, int index, DOUBLEARRAY_T retval);
	EXPORTED void STDCALL MMSRaman_setWavelengths_stdcall(MMSRAMAN_T c_mmsraman, DOUBLEARRAY_T wl, int index);
	EXPORTED void STDCALL MMSRaman_getFirmwareVersion_stdcall(MMSRAMAN_T c_mmsraman, JSTRING_T retval);
	EXPORTED void STDCALL MMSRaman_setDSPFirmwareVersion_stdcall(MMSRAMAN_T c_mmsraman, JSTRING_T dsp);
	EXPORTED void STDCALL MMSRaman_getDSPFirmwareVersion_stdcall(MMSRAMAN_T c_mmsraman, JSTRING_T retval);
	EXPORTED void STDCALL MMSRaman_setFPGAFirmwareVersion_stdcall(MMSRAMAN_T c_mmsraman, JSTRING_T fpga);
	EXPORTED void STDCALL MMSRaman_getFPGAFirmwareVersion_stdcall(MMSRAMAN_T c_mmsraman, JSTRING_T retval);
	EXPORTED void STDCALL MMSRaman_setUSBFirmwareVersion_stdcall(MMSRAMAN_T c_mmsraman, JSTRING_T usb);
	EXPORTED void STDCALL MMSRaman_getUSBFirmwareVersion_stdcall(MMSRAMAN_T c_mmsraman, JSTRING_T retval);
	EXPORTED void STDCALL MMSRaman_getSpectrometer_stdcall(MMSRAMAN_T c_mmsraman, MMSRAMAN_T retval);
	EXPORTED void STDCALL MMSRaman_setMasterClock_stdcall(MMSRAMAN_T c_mmsraman, int rate);
	EXPORTED void STDCALL MMSRaman_getLEDFlashCodes_stdcall(MMSRAMAN_T c_mmsraman, JSTRINGARRAY_T retval);
	EXPORTED void STDCALL MMSRaman_toString_stdcall(MMSRAMAN_T c_mmsraman, JSTRING_T retval);
	EXPORTED void STDCALL MMSRaman_addExposureListener_stdcall(MMSRAMAN_T c_mmsraman, EXPOSURELISTENER_T listener);
	EXPORTED void STDCALL MMSRaman_removeExposureListener_stdcall(MMSRAMAN_T c_mmsraman, EXPOSURELISTENER_T listener);
	EXPORTED void STDCALL MMSRaman_getLastExposure_stdcall(MMSRAMAN_T c_mmsraman, SPECTROMETEREXPOSURE_T retval);
	EXPORTED unsigned char STDCALL MMSRaman_has1DMode_stdcall(MMSRAMAN_T c_mmsraman);
	EXPORTED void STDCALL MMSRaman_set2DMode_stdcall(MMSRAMAN_T c_mmsraman, int channel);
	EXPORTED void STDCALL MMSRaman_set1DMode_stdcall(MMSRAMAN_T c_mmsraman, int channel);
	EXPORTED unsigned char STDCALL MMSRaman_is2DMode_stdcall(MMSRAMAN_T c_mmsraman);
	EXPORTED unsigned char STDCALL MMSRaman_is1DMode_stdcall(MMSRAMAN_T c_mmsraman);
	EXPORTED int STDCALL MMSRaman_get2DintegrationTime_stdcall(MMSRAMAN_T c_mmsraman);
	EXPORTED void STDCALL MMSRaman_addIntegrationTimeChangeListener_stdcall(MMSRAMAN_T c_mmsraman, INTEGRATIONTIMECHANGELISTENER_T listener);
	EXPORTED void STDCALL MMSRaman_removeIntegrationTimeChangeListener_stdcall(MMSRAMAN_T c_mmsraman, INTEGRATIONTIMECHANGELISTENER_T listener);
	EXPORTED void STDCALL MMSRaman_fireIntegrationTimeChanged_stdcall(MMSRAMAN_T c_mmsraman, int time);
	EXPORTED void STDCALL MMSRaman_Destroy_stdcall(MMSRAMAN_T mmsraman);
#endif /* WIN32 */
#ifdef __cplusplus
};
#endif /* __cplusplus */
#endif /* MMSRAMAN_H */
