/**
 * File: Move.h
 * Autogenerated on Mon Nov 16 11:53:30 EST 2009 based on
 * Move.java
 * for the Java class
 * com/oceanoptics/omnidriver/accessories/mikropack/commands/move/Move
 * Copyright (C) 2006 - 2008 Ocean Optics, Inc.  All rights reserved.
 */


#ifndef MOVE_H
#define MOVE_H
#include "BaseJavaClass.h"

#ifdef __cplusplus

#ifdef INCLUDES_IN_HEADER
#include "Node.h"
#endif /* INCLUDES_IN_HEADER */

/* Pre-declarations for circular dependencies in header files */
#ifdef CLASS_PREDECLARATIONS
class Node;
#endif /* CLASS_PREDECLARATIONS */

CLASS_TOKEN EXPORTED Move : public BaseJavaClass // CPPClass.getClassDeclaration
{
public: 
	void move(Node& param0);
	~Move();
	// No public default Java constructor; creating one:
	Move();
	// No public Java copy constructor; creating one:
	Move(const Move &that);
	// Creating assignment operator declaration:
	Move &operator=(const Move &that);

private:
	jmethodID mid_move123;
	void init_ids(JNIEnv* pJNIEnv);
};

extern "C" {
#endif /* __cplusplus */
#ifndef EXTERN_TYPEDEF_NODE_T
#define EXTERN_TYPEDEF_NODE_T
	typedef void* NODE_T;
#endif /* EXTERN_TYPEDEF_NODE_T */
#ifndef EXTERN_TYPEDEF_MOVE_T
#define EXTERN_TYPEDEF_MOVE_T
	typedef void* MOVE_T;
#endif /* EXTERN_TYPEDEF_MOVE_T */

	// No public default Java constructor; creating one:
	EXPORTED MOVE_T Move_Create();
	EXPORTED void Move_move(MOVE_T c_move, NODE_T param0);
	EXPORTED void Move_Destroy(MOVE_T move);

#ifdef WIN32
	// Use the following function prototypes when calling functions from Visual Basic 6
	EXPORTED void STDCALL Move_move_stdcall(MOVE_T c_move, NODE_T param0);
	EXPORTED void STDCALL Move_Destroy_stdcall(MOVE_T move);
#endif /* WIN32 */
#ifdef __cplusplus
};
#endif /* __cplusplus */
#endif /* MOVE_H */
