/**
 * File: MultiChannelProvider.h
 * Autogenerated on Mon Nov 16 11:53:34 EST 2009 based on
 * MultiChannelProvider.java
 * for the Java class
 * com/oceanoptics/omnidriver/features/multichannelprovider/MultiChannelProvider
 * Copyright (C) 2006 - 2008 Ocean Optics, Inc.  All rights reserved.
 */


#ifndef MULTICHANNELPROVIDER_H
#define MULTICHANNELPROVIDER_H
#include "BaseJavaClass.h"

#ifdef __cplusplus

#ifdef INCLUDES_IN_HEADER
#include "SpectrometerChannelArray.h"
#include "MultiChannelListener.h"
#endif /* INCLUDES_IN_HEADER */

/* Pre-declarations for circular dependencies in header files */
#ifdef CLASS_PREDECLARATIONS
class SpectrometerChannelArray;
class MultiChannelListener;
#endif /* CLASS_PREDECLARATIONS */

CLASS_TOKEN EXPORTED MultiChannelProvider : public BaseJavaClass // CPPClass.getClassDeclaration
{
public: 
	int getNumberOfChannels();
	IntArray getChannelsPresent();
	unsigned char isChannelPresent(int param0);
	int getNumberOfEnabledChannels();
	void setChannels(SpectrometerChannelArray& param0);
	IntArray getChannelIndices();
	void setChannelMux(int param0);
	void setChannelStatus(int param0, unsigned char param1);
	void setDeepWellStatus(unsigned char param0);
	void setChannelPresent(int param0, unsigned char param1);
	unsigned char isRotatorEnabled();
	unsigned char isDeepWell();
	void setRotatorEnabled(unsigned char param0);
	unsigned char isInterpolationEnabled();
	void setInterpolationEnabled(unsigned char param0);
	void addChannelListener(MultiChannelListener& param0);
	void removeChannelListener(MultiChannelListener& param0);
	~MultiChannelProvider();
	// No public default Java constructor; creating one:
	MultiChannelProvider();
	// No public Java copy constructor; creating one:
	MultiChannelProvider(const MultiChannelProvider &that);
	// Creating assignment operator declaration:
	MultiChannelProvider &operator=(const MultiChannelProvider &that);

private:
	jmethodID mid_getNumberOfChannels917;
	jmethodID mid_getChannelsPresent918;
	jmethodID mid_isChannelPresent919;
	jmethodID mid_getNumberOfEnabledChannels920;
	jmethodID mid_setChannels921;
	jmethodID mid_getChannelIndices922;
	jmethodID mid_setChannelMux923;
	jmethodID mid_setChannelStatus924;
	jmethodID mid_setDeepWellStatus925;
	jmethodID mid_setChannelPresent926;
	jmethodID mid_isRotatorEnabled927;
	jmethodID mid_isDeepWell928;
	jmethodID mid_setRotatorEnabled929;
	jmethodID mid_isInterpolationEnabled930;
	jmethodID mid_setInterpolationEnabled931;
	jmethodID mid_addChannelListener932;
	jmethodID mid_removeChannelListener933;
	void init_ids(JNIEnv* pJNIEnv);
};

extern "C" {
#endif /* __cplusplus */
#ifndef EXTERN_TYPEDEF_SPECTROMETERCHANNELARRAY_T
#define EXTERN_TYPEDEF_SPECTROMETERCHANNELARRAY_T
	typedef void* SPECTROMETERCHANNELARRAY_T;
#endif /* EXTERN_TYPEDEF_SPECTROMETERCHANNELARRAY_T */
#ifndef EXTERN_TYPEDEF_MULTICHANNELLISTENER_T
#define EXTERN_TYPEDEF_MULTICHANNELLISTENER_T
	typedef void* MULTICHANNELLISTENER_T;
#endif /* EXTERN_TYPEDEF_MULTICHANNELLISTENER_T */
#ifndef EXTERN_TYPEDEF_MULTICHANNELPROVIDER_T
#define EXTERN_TYPEDEF_MULTICHANNELPROVIDER_T
	typedef void* MULTICHANNELPROVIDER_T;
#endif /* EXTERN_TYPEDEF_MULTICHANNELPROVIDER_T */

	// No public default Java constructor; creating one:
	EXPORTED MULTICHANNELPROVIDER_T MultiChannelProvider_Create();
	EXPORTED int MultiChannelProvider_getNumberOfChannels(MULTICHANNELPROVIDER_T c_multi_channel_provider);
	EXPORTED void MultiChannelProvider_getChannelsPresent(MULTICHANNELPROVIDER_T c_multi_channel_provider, INTARRAY_T retval);
	EXPORTED unsigned char MultiChannelProvider_isChannelPresent(MULTICHANNELPROVIDER_T c_multi_channel_provider, int param0);
	EXPORTED int MultiChannelProvider_getNumberOfEnabledChannels(MULTICHANNELPROVIDER_T c_multi_channel_provider);
	EXPORTED void MultiChannelProvider_setChannels(MULTICHANNELPROVIDER_T c_multi_channel_provider, SPECTROMETERCHANNELARRAY_T param0);
	EXPORTED void MultiChannelProvider_getChannelIndices(MULTICHANNELPROVIDER_T c_multi_channel_provider, INTARRAY_T retval);
	EXPORTED void MultiChannelProvider_setChannelMux(MULTICHANNELPROVIDER_T c_multi_channel_provider, int param0);
	EXPORTED void MultiChannelProvider_setChannelStatus(MULTICHANNELPROVIDER_T c_multi_channel_provider, int param0, unsigned char param1);
	EXPORTED void MultiChannelProvider_setDeepWellStatus(MULTICHANNELPROVIDER_T c_multi_channel_provider, unsigned char param0);
	EXPORTED void MultiChannelProvider_setChannelPresent(MULTICHANNELPROVIDER_T c_multi_channel_provider, int param0, unsigned char param1);
	EXPORTED unsigned char MultiChannelProvider_isRotatorEnabled(MULTICHANNELPROVIDER_T c_multi_channel_provider);
	EXPORTED unsigned char MultiChannelProvider_isDeepWell(MULTICHANNELPROVIDER_T c_multi_channel_provider);
	EXPORTED void MultiChannelProvider_setRotatorEnabled(MULTICHANNELPROVIDER_T c_multi_channel_provider, unsigned char param0);
	EXPORTED unsigned char MultiChannelProvider_isInterpolationEnabled(MULTICHANNELPROVIDER_T c_multi_channel_provider);
	EXPORTED void MultiChannelProvider_setInterpolationEnabled(MULTICHANNELPROVIDER_T c_multi_channel_provider, unsigned char param0);
	EXPORTED void MultiChannelProvider_addChannelListener(MULTICHANNELPROVIDER_T c_multi_channel_provider, MULTICHANNELLISTENER_T param0);
	EXPORTED void MultiChannelProvider_removeChannelListener(MULTICHANNELPROVIDER_T c_multi_channel_provider, MULTICHANNELLISTENER_T param0);
	EXPORTED void MultiChannelProvider_Destroy(MULTICHANNELPROVIDER_T multi_channel_provider);

#ifdef WIN32
	// Use the following function prototypes when calling functions from Visual Basic 6
	EXPORTED int STDCALL MultiChannelProvider_getNumberOfChannels_stdcall(MULTICHANNELPROVIDER_T c_multi_channel_provider);
	EXPORTED void STDCALL MultiChannelProvider_getChannelsPresent_stdcall(MULTICHANNELPROVIDER_T c_multi_channel_provider, INTARRAY_T retval);
	EXPORTED unsigned char STDCALL MultiChannelProvider_isChannelPresent_stdcall(MULTICHANNELPROVIDER_T c_multi_channel_provider, int param0);
	EXPORTED int STDCALL MultiChannelProvider_getNumberOfEnabledChannels_stdcall(MULTICHANNELPROVIDER_T c_multi_channel_provider);
	EXPORTED void STDCALL MultiChannelProvider_setChannels_stdcall(MULTICHANNELPROVIDER_T c_multi_channel_provider, SPECTROMETERCHANNELARRAY_T param0);
	EXPORTED void STDCALL MultiChannelProvider_getChannelIndices_stdcall(MULTICHANNELPROVIDER_T c_multi_channel_provider, INTARRAY_T retval);
	EXPORTED void STDCALL MultiChannelProvider_setChannelMux_stdcall(MULTICHANNELPROVIDER_T c_multi_channel_provider, int param0);
	EXPORTED void STDCALL MultiChannelProvider_setChannelStatus_stdcall(MULTICHANNELPROVIDER_T c_multi_channel_provider, int param0, unsigned char param1);
	EXPORTED void STDCALL MultiChannelProvider_setDeepWellStatus_stdcall(MULTICHANNELPROVIDER_T c_multi_channel_provider, unsigned char param0);
	EXPORTED void STDCALL MultiChannelProvider_setChannelPresent_stdcall(MULTICHANNELPROVIDER_T c_multi_channel_provider, int param0, unsigned char param1);
	EXPORTED unsigned char STDCALL MultiChannelProvider_isRotatorEnabled_stdcall(MULTICHANNELPROVIDER_T c_multi_channel_provider);
	EXPORTED unsigned char STDCALL MultiChannelProvider_isDeepWell_stdcall(MULTICHANNELPROVIDER_T c_multi_channel_provider);
	EXPORTED void STDCALL MultiChannelProvider_setRotatorEnabled_stdcall(MULTICHANNELPROVIDER_T c_multi_channel_provider, unsigned char param0);
	EXPORTED unsigned char STDCALL MultiChannelProvider_isInterpolationEnabled_stdcall(MULTICHANNELPROVIDER_T c_multi_channel_provider);
	EXPORTED void STDCALL MultiChannelProvider_setInterpolationEnabled_stdcall(MULTICHANNELPROVIDER_T c_multi_channel_provider, unsigned char param0);
	EXPORTED void STDCALL MultiChannelProvider_addChannelListener_stdcall(MULTICHANNELPROVIDER_T c_multi_channel_provider, MULTICHANNELLISTENER_T param0);
	EXPORTED void STDCALL MultiChannelProvider_removeChannelListener_stdcall(MULTICHANNELPROVIDER_T c_multi_channel_provider, MULTICHANNELLISTENER_T param0);
	EXPORTED void STDCALL MultiChannelProvider_Destroy_stdcall(MULTICHANNELPROVIDER_T multi_channel_provider);
#endif /* WIN32 */
#ifdef __cplusplus
};
#endif /* __cplusplus */
#endif /* MULTICHANNELPROVIDER_H */
