/**
 * File: NetworkSourceGUIProvider.h
 * Autogenerated on Mon Nov 16 11:53:34 EST 2009 based on
 * NetworkSourceGUIProvider.java
 * for the Java class
 * com/oceanoptics/omnidriver/features/networksource/NetworkSourceGUIProvider
 * Copyright (C) 2006 - 2008 Ocean Optics, Inc.  All rights reserved.
 */


#ifndef NETWORKSOURCEGUIPROVIDER_H
#define NETWORKSOURCEGUIPROVIDER_H
#include "BaseJavaClass.h"

#ifdef __cplusplus

#ifdef INCLUDES_IN_HEADER
#endif /* INCLUDES_IN_HEADER */


CLASS_TOKEN EXPORTED NetworkSourceGUIProvider : public BaseJavaClass // CPPClass.getClassDeclaration
{
public: 
	~NetworkSourceGUIProvider();
	// No public default Java constructor; creating one:
	NetworkSourceGUIProvider();
	// No public Java copy constructor; creating one:
	NetworkSourceGUIProvider(const NetworkSourceGUIProvider &that);
	// Creating assignment operator declaration:
	NetworkSourceGUIProvider &operator=(const NetworkSourceGUIProvider &that);

private:
	void init_ids(JNIEnv* pJNIEnv);
};

extern "C" {
#endif /* __cplusplus */
#ifndef EXTERN_TYPEDEF_NETWORKSOURCEGUIPROVIDER_T
#define EXTERN_TYPEDEF_NETWORKSOURCEGUIPROVIDER_T
	typedef void* NETWORKSOURCEGUIPROVIDER_T;
#endif /* EXTERN_TYPEDEF_NETWORKSOURCEGUIPROVIDER_T */

	// No public default Java constructor; creating one:
	EXPORTED NETWORKSOURCEGUIPROVIDER_T NetworkSourceGUIProvider_Create();
	EXPORTED void NetworkSourceGUIProvider_Destroy(NETWORKSOURCEGUIPROVIDER_T network_source_g_u_i_provider);

#ifdef WIN32
	// Use the following function prototypes when calling functions from Visual Basic 6
	EXPORTED void STDCALL NetworkSourceGUIProvider_Destroy_stdcall(NETWORKSOURCEGUIPROVIDER_T network_source_g_u_i_provider);
#endif /* WIN32 */
#ifdef __cplusplus
};
#endif /* __cplusplus */
#endif /* NETWORKSOURCEGUIPROVIDER_H */
