/**
 * File: NotifyPositionEnableImpl.h
 * Autogenerated on Mon Nov 16 11:53:30 EST 2009 based on
 * NotifyPositionEnableImpl.java
 * for the Java class
 * com/oceanoptics/omnidriver/accessories/mikropack/commands/notifypositionenable/NotifyPositionEnableImpl
 * Copyright (C) 2006 - 2008 Ocean Optics, Inc.  All rights reserved.
 */


#ifndef NOTIFYPOSITIONENABLEIMPL_H
#define NOTIFYPOSITIONENABLEIMPL_H
#include "BaseJavaClass.h"

#ifdef __cplusplus

#ifdef INCLUDES_IN_HEADER
#include "FaulhaberCommandOnly.h"
#include "UniRS232.h"
#include "Node.h"
#endif /* INCLUDES_IN_HEADER */

/* Pre-declarations for circular dependencies in header files */
#ifdef CLASS_PREDECLARATIONS
class FaulhaberCommandOnly;
class UniRS232;
class Node;
#endif /* CLASS_PREDECLARATIONS */

CLASS_TOKEN EXPORTED NotifyPositionEnableImpl : public FaulhaberCommandOnly // CPPClass.getClassDeclaration
{
public: 
	NotifyPositionEnableImpl(UniRS232& serPort);
	void notifyPositionEnable(Node& node);
	~NotifyPositionEnableImpl();
	// No public default Java constructor; creating one:
	NotifyPositionEnableImpl();
	// No public Java copy constructor; creating one:
	NotifyPositionEnableImpl(const NotifyPositionEnableImpl &that);
	// Creating assignment operator declaration:
	NotifyPositionEnableImpl &operator=(const NotifyPositionEnableImpl &that);

private:
	jmethodID mid_NotifyPositionEnableImpl133;
	jmethodID mid_notifyPositionEnable134;
	void init_ids(JNIEnv* pJNIEnv);
};

extern "C" {
#endif /* __cplusplus */
#ifndef EXTERN_TYPEDEF_FAULHABERCOMMANDONLY_T
#define EXTERN_TYPEDEF_FAULHABERCOMMANDONLY_T
	typedef void* FAULHABERCOMMANDONLY_T;
#endif /* EXTERN_TYPEDEF_FAULHABERCOMMANDONLY_T */
#ifndef EXTERN_TYPEDEF_UNIRS232_T
#define EXTERN_TYPEDEF_UNIRS232_T
	typedef void* UNIRS232_T;
#endif /* EXTERN_TYPEDEF_UNIRS232_T */
#ifndef EXTERN_TYPEDEF_NODE_T
#define EXTERN_TYPEDEF_NODE_T
	typedef void* NODE_T;
#endif /* EXTERN_TYPEDEF_NODE_T */
#ifndef EXTERN_TYPEDEF_NOTIFYPOSITIONENABLEIMPL_T
#define EXTERN_TYPEDEF_NOTIFYPOSITIONENABLEIMPL_T
	typedef void* NOTIFYPOSITIONENABLEIMPL_T;
#endif /* EXTERN_TYPEDEF_NOTIFYPOSITIONENABLEIMPL_T */

	// No public default Java constructor; creating one:
	EXPORTED NOTIFYPOSITIONENABLEIMPL_T NotifyPositionEnableImpl_Create();
	EXPORTED NOTIFYPOSITIONENABLEIMPL_T NotifyPositionEnableImpl_Create_1(UNIRS232_T serPort);
	EXPORTED void NotifyPositionEnableImpl_notifyPositionEnable(NOTIFYPOSITIONENABLEIMPL_T c_notify_position_enable_impl, NODE_T node);
	EXPORTED void NotifyPositionEnableImpl_Destroy(NOTIFYPOSITIONENABLEIMPL_T notify_position_enable_impl);

#ifdef WIN32
	// Use the following function prototypes when calling functions from Visual Basic 6
	EXPORTED NOTIFYPOSITIONENABLEIMPL_T STDCALL NotifyPositionEnableImpl_Create_stdcall_1(UNIRS232_T serPort);
	EXPORTED void STDCALL NotifyPositionEnableImpl_notifyPositionEnable_stdcall(NOTIFYPOSITIONENABLEIMPL_T c_notify_position_enable_impl, NODE_T node);
	EXPORTED void STDCALL NotifyPositionEnableImpl_Destroy_stdcall(NOTIFYPOSITIONENABLEIMPL_T notify_position_enable_impl);
#endif /* WIN32 */
#ifdef __cplusplus
};
#endif /* __cplusplus */
#endif /* NOTIFYPOSITIONENABLEIMPL_H */
