/**
 * File: PollingTest.h
 * Autogenerated on Mon Nov 16 11:53:41 EST 2009 based on
 * PollingTest.java
 * for the Java class
 * com/oceanoptics/tests/PollingTest
 * Copyright (C) 2006 - 2008 Ocean Optics, Inc.  All rights reserved.
 */


#ifndef POLLINGTEST_H
#define POLLINGTEST_H
#include "BaseJavaClass.h"

#ifdef __cplusplus

#ifdef INCLUDES_IN_HEADER
#include "JStringArray.h"
#endif /* INCLUDES_IN_HEADER */

/* Pre-declarations for circular dependencies in header files */
#ifdef CLASS_PREDECLARATIONS
class JStringArray;
#endif /* CLASS_PREDECLARATIONS */

CLASS_TOKEN EXPORTED PollingTest : public BaseJavaClass // CPPClass.getClassDeclaration
{
public: 
	PollingTest();
	void main(JStringArray& args);
	~PollingTest();
	// No public Java copy constructor; creating one:
	PollingTest(const PollingTest &that);
	// Creating assignment operator declaration:
	PollingTest &operator=(const PollingTest &that);

private:
	jmethodID mid_PollingTest3988;
	jmethodID mid_main3989;
	void init_ids(JNIEnv* pJNIEnv);
};

extern "C" {
#endif /* __cplusplus */
#ifndef EXTERN_TYPEDEF_JSTRINGARRAY_T
#define EXTERN_TYPEDEF_JSTRINGARRAY_T
	typedef void* JSTRINGARRAY_T;
#endif /* EXTERN_TYPEDEF_JSTRINGARRAY_T */
#ifndef EXTERN_TYPEDEF_POLLINGTEST_T
#define EXTERN_TYPEDEF_POLLINGTEST_T
	typedef void* POLLINGTEST_T;
#endif /* EXTERN_TYPEDEF_POLLINGTEST_T */

	EXPORTED POLLINGTEST_T PollingTest_Create();
	EXPORTED void PollingTest_main(POLLINGTEST_T c_polling_test, JSTRINGARRAY_T args);
	EXPORTED void PollingTest_Destroy(POLLINGTEST_T polling_test);

#ifdef WIN32
	// Use the following function prototypes when calling functions from Visual Basic 6
	EXPORTED POLLINGTEST_T STDCALL PollingTest_Create_stdcall();
	EXPORTED void STDCALL PollingTest_main_stdcall(POLLINGTEST_T c_polling_test, JSTRINGARRAY_T args);
	EXPORTED void STDCALL PollingTest_Destroy_stdcall(POLLINGTEST_T polling_test);
#endif /* WIN32 */
#ifdef __cplusplus
};
#endif /* __cplusplus */
#endif /* POLLINGTEST_H */
