/**
 * File: QE65000.h
 * Autogenerated on Mon Nov 16 11:53:39 EST 2009 based on
 * QE65000.java
 * for the Java class
 * com/oceanoptics/omnidriver/spectrometer/qe65000/QE65000
 * Copyright (C) 2006 - 2008 Ocean Optics, Inc.  All rights reserved.
 */


#ifndef QE65000_H
#define QE65000_H
#include "BaseJavaClass.h"

#ifdef __cplusplus

#ifdef INCLUDES_IN_HEADER
#include "USBSpectrometer.h"
#include "JString.h"
#include "USBEndpointDescriptor.h"
#include "GUIProviderArray.h"
#include "SpectrometerPlugInArray.h"
#include "ExternalTriggerModeArray.h"
#include "BitSet.h"
#include "CoefficientsArray.h"
#include "AcquisitionListener.h"
#include "ExposureListener.h"
#include "SpectrometerExposure.h"
#include "Spectrum.h"
#include "IntegrationTimeChangeListener.h"
#endif /* INCLUDES_IN_HEADER */

/* Pre-declarations for circular dependencies in header files */
#ifdef CLASS_PREDECLARATIONS
class USBSpectrometer;
class JString;
class USBEndpointDescriptor;
class GUIProviderArray;
class SpectrometerPlugInArray;
class ExternalTriggerModeArray;
class BitSet;
class CoefficientsArray;
class AcquisitionListener;
class QE65000;
class ExposureListener;
class SpectrometerExposure;
class Spectrum;
class IntegrationTimeChangeListener;
#endif /* CLASS_PREDECLARATIONS */

CLASS_TOKEN EXPORTED QE65000 : public USBSpectrometer // CPPClass.getClassDeclaration
{
public: 
	QE65000();
	QE65000(int i);
	unsigned char setSaturationIntensity(int saturationIntensity, JString& key);
	int getSaturationIntensity();
	void setEndpoints();
	USBEndpointDescriptor getEndpoint(int endPoint);
	unsigned char allowWriteToEEPROM(int privilegeLevel, int slot);
	void openSpectrometer(int index);
	GUIProviderArray getGUIFeatures();
	void setStrobeDelay(int delay);
	int getActualIntegrationTime();
	SpectrometerPlugInArray getPlugIns();
	int getNumberOfPlugIns();
	unsigned char isPlugInDetected(int id);
	CharArray initializePlugIns();
	void detectPlugIns();
	int setI2CBytes(signed char address, signed char numBytes, CharArray& i2C);
	CharArray getI2CBytes(signed char address, signed char numBytes);
	CharArray getSPIBytes(CharArray& message, int length);
	JString getPSOCVersion();
	JString getFPGAFirmwareVersion();
	double continuousStrobeCountsToMicros(int counts);
	void setContinuousStrobeDelay(int delayMicros);
	int getContinuousStrobeDelayMinimum();
	int getContinuousStrobeDelayMaximum();
	int getContinuousStrobeDelayIncrement(int magnitude);
	void setAdvancedIntegrationTime(long long delayMicros);
	int getIntegrationTimeBaseClock();
	int getIntegrationClockTimer();
	long long getAdvancedIntegrationTimeMinimum();
	long long getAdvancedIntegrationTimeMaximum();
	long long getAdvancedIntegrationTimeIncrement();
	void setExternalTriggerMode(int mode);
	ExternalTriggerModeArray getExternalTriggerModes();
	void setShutterClock(int value);
	int getShutterClock();
	void setSingleStrobeLow(int value);
	void setSingleStrobeHigh(int value);
	double getSingleStrobeCountsToMicros(int counts);
	int getSingleStrobeLow();
	int getSingleStrobeHigh();
	int getSingleStrobeMinimum();
	int getSingleStrobeMaximum();
	int getSingleStrobeIncrement();
	void setDirectionAllBits(BitSet& bitSet);
	void setMuxAllBits(BitSet& bitSet);
	void setValueAllBits(BitSet& bitSet);
	void setDirectionBitmask(short bitmask);
	void setMuxBitmask(short bitmask);
	void setValueBitmask(short bitmask);
	void setDirectionBit(int bit, unsigned char value);
	void setMuxBit(int bit, unsigned char value);
	void setValueBit(int bit, unsigned char value);
	int getTotalGPIOBits();
	BitSet getDirectionBits();
	BitSet getMuxBits();
	BitSet getValueBits();
	int getValueBit(int bitNumber);
	int getNumberOfPins();
	double getBoardTemperatureCelsius();
	DoubleArray getIrradianceCalibrationFactors(signed char address);
	void setIrradianceCalibrationFactors(signed char address, DoubleArray& data);
	void setMasterClockDivisor(int value);
	int getMasterClockDivisor();
	void setExternalTriggerDelay(int counts);
	double triggerDelayCountsToMicroseconds(int counts);
	int getExternalTriggerDelayMinimum();
	int getExternalTriggerDelayMaximum();
	int getExternalTriggerDelayIncrement();
	void setTECEnable(unsigned char enable);
	void setFanEnable(unsigned char enable);
	double getDetectorTemperatureCelsius();
	double getDetectorTemperatureSetPointCelsius();
	void setDetectorSetPointCelsius(double point);
	double getSetPointMinimumCelsius();
	double getSetPointMaximumCelsius();
	double getSetPointIncrementCelsius();
	unsigned char isSaveTECStateEnabled();
	void saveTECState();
	CoefficientsArray readNonlinearityCoefficientsFromSpectrometer();
	void writeNonlinearityCoefficientsToSpectrometer(CoefficientsArray& coefficients);
	CoefficientsArray getNonlinearityCoefficients();
	void setNonlinearityCoefficients(CoefficientsArray& coefficients);
	DoubleArray getNonlinearityCoefficientsSingleChannel(int index);
	void setNonlinearityCoefficientsSingleChannel(DoubleArray& nl, int index);
	CoefficientsArray readWavelengthCalibrationCoefficientsFromSpectrometer();
	void writeWavelengthCoefficientsToSpectrometer(CoefficientsArray& coefficients);
	CoefficientsArray getWavelengthCalibrationCoefficients();
	void setWavelengthCalibrationCoefficients(CoefficientsArray& coefficients);
	DoubleArray getWavelengths(int index);
	void setWavelengths(DoubleArray& wl, int index);
	CoefficientsArray readStrayLightCorrectionCoefficientFromSpectrometer();
	void writeStrayLightCoefficientToSpectrometer(CoefficientsArray& coefficients);
	void setStrayLightCorrectionCoefficient(CoefficientsArray& coefficients);
	CoefficientsArray getStrayLightCorrectionCoefficient();
	void setStrayLight(double strayLight, int index);
	double getStrayLight(int index);
	unsigned char isAdvancedVersion();
	void addAcquisitionListener(AcquisitionListener& listener);
	void removeAcquisitionListener(AcquisitionListener& listener);
	QE65000 getSpectrometer();
	void addExposureListener(ExposureListener& listener);
	int getCcdWidth();
	int getCcdHeight();
	SpectrometerExposure getLastExposure();
	void removeExposureListener(ExposureListener& listener);
	SpectrometerExposure getQE65000Exposure(Spectrum& spectrum);
	void set2DMode(int channelIndex);
	void set1DMode(int channelIndex);
	Spectrum getSpectrum(Spectrum& spectrum);
	unsigned char has1DMode();
	unsigned char is1DMode();
	unsigned char is2DMode();
	int get2DintegrationTime();
	void addIntegrationTimeChangeListener(IntegrationTimeChangeListener& listener);
	void removeIntegrationTimeChangeListener(IntegrationTimeChangeListener& listener);
	~QE65000();
	// No public Java copy constructor; creating one:
	QE65000(const QE65000 &that);
	// Creating assignment operator declaration:
	QE65000 &operator=(const QE65000 &that);

private:
	jmethodID mid_QE650003055;
	jmethodID mid_QE650003056;
	jmethodID mid_setSaturationIntensity3057;
	jmethodID mid_getSaturationIntensity3058;
	jmethodID mid_setEndpoints3059;
	jmethodID mid_getEndpoint3060;
	jmethodID mid_allowWriteToEEPROM3061;
	jmethodID mid_openSpectrometer3062;
	jmethodID mid_getGUIFeatures3063;
	jmethodID mid_setStrobeDelay3064;
	jmethodID mid_getActualIntegrationTime3065;
	jmethodID mid_getPlugIns3066;
	jmethodID mid_getNumberOfPlugIns3067;
	jmethodID mid_isPlugInDetected3068;
	jmethodID mid_initializePlugIns3069;
	jmethodID mid_detectPlugIns3070;
	jmethodID mid_setI2CBytes3071;
	jmethodID mid_getI2CBytes3072;
	jmethodID mid_getSPIBytes3073;
	jmethodID mid_getPSOCVersion3074;
	jmethodID mid_getFPGAFirmwareVersion3075;
	jmethodID mid_continuousStrobeCountsToMicros3076;
	jmethodID mid_setContinuousStrobeDelay3077;
	jmethodID mid_getContinuousStrobeDelayMinimum3078;
	jmethodID mid_getContinuousStrobeDelayMaximum3079;
	jmethodID mid_getContinuousStrobeDelayIncrement3080;
	jmethodID mid_setAdvancedIntegrationTime3081;
	jmethodID mid_getIntegrationTimeBaseClock3082;
	jmethodID mid_getIntegrationClockTimer3083;
	jmethodID mid_getAdvancedIntegrationTimeMinimum3084;
	jmethodID mid_getAdvancedIntegrationTimeMaximum3085;
	jmethodID mid_getAdvancedIntegrationTimeIncrement3086;
	jmethodID mid_setExternalTriggerMode3087;
	jmethodID mid_getExternalTriggerModes3088;
	jmethodID mid_setShutterClock3089;
	jmethodID mid_getShutterClock3090;
	jmethodID mid_setSingleStrobeLow3091;
	jmethodID mid_setSingleStrobeHigh3092;
	jmethodID mid_getSingleStrobeCountsToMicros3093;
	jmethodID mid_getSingleStrobeLow3094;
	jmethodID mid_getSingleStrobeHigh3095;
	jmethodID mid_getSingleStrobeMinimum3096;
	jmethodID mid_getSingleStrobeMaximum3097;
	jmethodID mid_getSingleStrobeIncrement3098;
	jmethodID mid_setDirectionAllBits3099;
	jmethodID mid_setMuxAllBits3100;
	jmethodID mid_setValueAllBits3101;
	jmethodID mid_setDirectionBitmask3102;
	jmethodID mid_setMuxBitmask3103;
	jmethodID mid_setValueBitmask3104;
	jmethodID mid_setDirectionBit3105;
	jmethodID mid_setMuxBit3106;
	jmethodID mid_setValueBit3107;
	jmethodID mid_getTotalGPIOBits3108;
	jmethodID mid_getDirectionBits3109;
	jmethodID mid_getMuxBits3110;
	jmethodID mid_getValueBits3111;
	jmethodID mid_getValueBit3112;
	jmethodID mid_getNumberOfPins3113;
	jmethodID mid_getBoardTemperatureCelsius3114;
	jmethodID mid_getIrradianceCalibrationFactors3115;
	jmethodID mid_setIrradianceCalibrationFactors3116;
	jmethodID mid_setMasterClockDivisor3117;
	jmethodID mid_getMasterClockDivisor3118;
	jmethodID mid_setExternalTriggerDelay3119;
	jmethodID mid_triggerDelayCountsToMicroseconds3120;
	jmethodID mid_getExternalTriggerDelayMinimum3121;
	jmethodID mid_getExternalTriggerDelayMaximum3122;
	jmethodID mid_getExternalTriggerDelayIncrement3123;
	jmethodID mid_setTECEnable3124;
	jmethodID mid_setFanEnable3125;
	jmethodID mid_getDetectorTemperatureCelsius3126;
	jmethodID mid_getDetectorTemperatureSetPointCelsius3127;
	jmethodID mid_setDetectorSetPointCelsius3128;
	jmethodID mid_getSetPointMinimumCelsius3129;
	jmethodID mid_getSetPointMaximumCelsius3130;
	jmethodID mid_getSetPointIncrementCelsius3131;
	jmethodID mid_isSaveTECStateEnabled3132;
	jmethodID mid_saveTECState3133;
	jmethodID mid_readNonlinearityCoefficientsFromSpectrometer3134;
	jmethodID mid_writeNonlinearityCoefficientsToSpectrometer3135;
	jmethodID mid_getNonlinearityCoefficients3136;
	jmethodID mid_setNonlinearityCoefficients3137;
	jmethodID mid_getNonlinearityCoefficientsSingleChannel3138;
	jmethodID mid_setNonlinearityCoefficientsSingleChannel3139;
	jmethodID mid_readWavelengthCalibrationCoefficientsFromSpectrometer3140;
	jmethodID mid_writeWavelengthCoefficientsToSpectrometer3141;
	jmethodID mid_getWavelengthCalibrationCoefficients3142;
	jmethodID mid_setWavelengthCalibrationCoefficients3143;
	jmethodID mid_getWavelengths3144;
	jmethodID mid_setWavelengths3145;
	jmethodID mid_readStrayLightCorrectionCoefficientFromSpectrometer3146;
	jmethodID mid_writeStrayLightCoefficientToSpectrometer3147;
	jmethodID mid_setStrayLightCorrectionCoefficient3148;
	jmethodID mid_getStrayLightCorrectionCoefficient3149;
	jmethodID mid_setStrayLight3150;
	jmethodID mid_getStrayLight3151;
	jmethodID mid_isAdvancedVersion3152;
	jmethodID mid_addAcquisitionListener3153;
	jmethodID mid_removeAcquisitionListener3154;
	jmethodID mid_getSpectrometer3155;
	jmethodID mid_addExposureListener3156;
	jmethodID mid_getCcdWidth3157;
	jmethodID mid_getCcdHeight3158;
	jmethodID mid_getLastExposure3159;
	jmethodID mid_removeExposureListener3160;
	jmethodID mid_getQE65000Exposure3161;
	jmethodID mid_set2DMode3162;
	jmethodID mid_set1DMode3163;
	jmethodID mid_getSpectrum3164;
	jmethodID mid_has1DMode3165;
	jmethodID mid_is1DMode3166;
	jmethodID mid_is2DMode3167;
	jmethodID mid_get2DintegrationTime3168;
	jmethodID mid_addIntegrationTimeChangeListener3169;
	jmethodID mid_removeIntegrationTimeChangeListener3170;
	void init_ids(JNIEnv* pJNIEnv);
};

extern "C" {
#endif /* __cplusplus */
#ifndef EXTERN_TYPEDEF_USBSPECTROMETER_T
#define EXTERN_TYPEDEF_USBSPECTROMETER_T
	typedef void* USBSPECTROMETER_T;
#endif /* EXTERN_TYPEDEF_USBSPECTROMETER_T */
#ifndef EXTERN_TYPEDEF_JSTRING_T
#define EXTERN_TYPEDEF_JSTRING_T
	typedef void* JSTRING_T;
#endif /* EXTERN_TYPEDEF_JSTRING_T */
#ifndef EXTERN_TYPEDEF_USBENDPOINTDESCRIPTOR_T
#define EXTERN_TYPEDEF_USBENDPOINTDESCRIPTOR_T
	typedef void* USBENDPOINTDESCRIPTOR_T;
#endif /* EXTERN_TYPEDEF_USBENDPOINTDESCRIPTOR_T */
#ifndef EXTERN_TYPEDEF_GUIPROVIDERARRAY_T
#define EXTERN_TYPEDEF_GUIPROVIDERARRAY_T
	typedef void* GUIPROVIDERARRAY_T;
#endif /* EXTERN_TYPEDEF_GUIPROVIDERARRAY_T */
#ifndef EXTERN_TYPEDEF_SPECTROMETERPLUGINARRAY_T
#define EXTERN_TYPEDEF_SPECTROMETERPLUGINARRAY_T
	typedef void* SPECTROMETERPLUGINARRAY_T;
#endif /* EXTERN_TYPEDEF_SPECTROMETERPLUGINARRAY_T */
#ifndef EXTERN_TYPEDEF_EXTERNALTRIGGERMODEARRAY_T
#define EXTERN_TYPEDEF_EXTERNALTRIGGERMODEARRAY_T
	typedef void* EXTERNALTRIGGERMODEARRAY_T;
#endif /* EXTERN_TYPEDEF_EXTERNALTRIGGERMODEARRAY_T */
#ifndef EXTERN_TYPEDEF_BITSET_T
#define EXTERN_TYPEDEF_BITSET_T
	typedef void* BITSET_T;
#endif /* EXTERN_TYPEDEF_BITSET_T */
#ifndef EXTERN_TYPEDEF_COEFFICIENTSARRAY_T
#define EXTERN_TYPEDEF_COEFFICIENTSARRAY_T
	typedef void* COEFFICIENTSARRAY_T;
#endif /* EXTERN_TYPEDEF_COEFFICIENTSARRAY_T */
#ifndef EXTERN_TYPEDEF_ACQUISITIONLISTENER_T
#define EXTERN_TYPEDEF_ACQUISITIONLISTENER_T
	typedef void* ACQUISITIONLISTENER_T;
#endif /* EXTERN_TYPEDEF_ACQUISITIONLISTENER_T */
#ifndef EXTERN_TYPEDEF_QE65000_T
#define EXTERN_TYPEDEF_QE65000_T
	typedef void* QE65000_T;
#endif /* EXTERN_TYPEDEF_QE65000_T */
#ifndef EXTERN_TYPEDEF_EXPOSURELISTENER_T
#define EXTERN_TYPEDEF_EXPOSURELISTENER_T
	typedef void* EXPOSURELISTENER_T;
#endif /* EXTERN_TYPEDEF_EXPOSURELISTENER_T */
#ifndef EXTERN_TYPEDEF_SPECTROMETEREXPOSURE_T
#define EXTERN_TYPEDEF_SPECTROMETEREXPOSURE_T
	typedef void* SPECTROMETEREXPOSURE_T;
#endif /* EXTERN_TYPEDEF_SPECTROMETEREXPOSURE_T */
#ifndef EXTERN_TYPEDEF_SPECTRUM_T
#define EXTERN_TYPEDEF_SPECTRUM_T
	typedef void* SPECTRUM_T;
#endif /* EXTERN_TYPEDEF_SPECTRUM_T */
#ifndef EXTERN_TYPEDEF_INTEGRATIONTIMECHANGELISTENER_T
#define EXTERN_TYPEDEF_INTEGRATIONTIMECHANGELISTENER_T
	typedef void* INTEGRATIONTIMECHANGELISTENER_T;
#endif /* EXTERN_TYPEDEF_INTEGRATIONTIMECHANGELISTENER_T */

	EXPORTED QE65000_T QE65000_Create();
	EXPORTED QE65000_T QE65000_Create_1(int i);
	EXPORTED unsigned char QE65000_setSaturationIntensity(QE65000_T c_qe65000, int saturationIntensity, JSTRING_T key);
	EXPORTED int QE65000_getSaturationIntensity(QE65000_T c_qe65000);
	EXPORTED void QE65000_setEndpoints(QE65000_T c_qe65000);
	EXPORTED void QE65000_getEndpoint(QE65000_T c_qe65000, int endPoint, USBENDPOINTDESCRIPTOR_T retval);
	EXPORTED unsigned char QE65000_allowWriteToEEPROM(QE65000_T c_qe65000, int privilegeLevel, int slot);
	EXPORTED void QE65000_openSpectrometer(QE65000_T c_qe65000, int index);
	EXPORTED void QE65000_getGUIFeatures(QE65000_T c_qe65000, GUIPROVIDERARRAY_T retval);
	EXPORTED void QE65000_setStrobeDelay(QE65000_T c_qe65000, int delay);
	EXPORTED int QE65000_getActualIntegrationTime(QE65000_T c_qe65000);
	EXPORTED void QE65000_getPlugIns(QE65000_T c_qe65000, SPECTROMETERPLUGINARRAY_T retval);
	EXPORTED int QE65000_getNumberOfPlugIns(QE65000_T c_qe65000);
	EXPORTED unsigned char QE65000_isPlugInDetected(QE65000_T c_qe65000, int id);
	EXPORTED void QE65000_initializePlugIns(QE65000_T c_qe65000, CHARARRAY_T retval);
	EXPORTED void QE65000_detectPlugIns(QE65000_T c_qe65000);
	EXPORTED int QE65000_setI2CBytes(QE65000_T c_qe65000, signed char address, signed char numBytes, CHARARRAY_T i2C);
	EXPORTED void QE65000_getI2CBytes(QE65000_T c_qe65000, signed char address, signed char numBytes, CHARARRAY_T retval);
	EXPORTED void QE65000_getSPIBytes(QE65000_T c_qe65000, CHARARRAY_T message, int length, CHARARRAY_T retval);
	EXPORTED void QE65000_getPSOCVersion(QE65000_T c_qe65000, JSTRING_T retval);
	EXPORTED void QE65000_getFPGAFirmwareVersion(QE65000_T c_qe65000, JSTRING_T retval);
	EXPORTED double QE65000_continuousStrobeCountsToMicros(QE65000_T c_qe65000, int counts);
	EXPORTED void QE65000_setContinuousStrobeDelay(QE65000_T c_qe65000, int delayMicros);
	EXPORTED int QE65000_getContinuousStrobeDelayMinimum(QE65000_T c_qe65000);
	EXPORTED int QE65000_getContinuousStrobeDelayMaximum(QE65000_T c_qe65000);
	EXPORTED int QE65000_getContinuousStrobeDelayIncrement(QE65000_T c_qe65000, int magnitude);
	EXPORTED void QE65000_setAdvancedIntegrationTime(QE65000_T c_qe65000, long long delayMicros);
	EXPORTED int QE65000_getIntegrationTimeBaseClock(QE65000_T c_qe65000);
	EXPORTED int QE65000_getIntegrationClockTimer(QE65000_T c_qe65000);
	EXPORTED long long QE65000_getAdvancedIntegrationTimeMinimum(QE65000_T c_qe65000);
	EXPORTED long long QE65000_getAdvancedIntegrationTimeMaximum(QE65000_T c_qe65000);
	EXPORTED long long QE65000_getAdvancedIntegrationTimeIncrement(QE65000_T c_qe65000);
	EXPORTED void QE65000_setExternalTriggerMode(QE65000_T c_qe65000, int mode);
	EXPORTED void QE65000_getExternalTriggerModes(QE65000_T c_qe65000, EXTERNALTRIGGERMODEARRAY_T retval);
	EXPORTED void QE65000_setShutterClock(QE65000_T c_qe65000, int value);
	EXPORTED int QE65000_getShutterClock(QE65000_T c_qe65000);
	EXPORTED void QE65000_setSingleStrobeLow(QE65000_T c_qe65000, int value);
	EXPORTED void QE65000_setSingleStrobeHigh(QE65000_T c_qe65000, int value);
	EXPORTED double QE65000_getSingleStrobeCountsToMicros(QE65000_T c_qe65000, int counts);
	EXPORTED int QE65000_getSingleStrobeLow(QE65000_T c_qe65000);
	EXPORTED int QE65000_getSingleStrobeHigh(QE65000_T c_qe65000);
	EXPORTED int QE65000_getSingleStrobeMinimum(QE65000_T c_qe65000);
	EXPORTED int QE65000_getSingleStrobeMaximum(QE65000_T c_qe65000);
	EXPORTED int QE65000_getSingleStrobeIncrement(QE65000_T c_qe65000);
	EXPORTED void QE65000_setDirectionAllBits(QE65000_T c_qe65000, BITSET_T bitSet);
	EXPORTED void QE65000_setMuxAllBits(QE65000_T c_qe65000, BITSET_T bitSet);
	EXPORTED void QE65000_setValueAllBits(QE65000_T c_qe65000, BITSET_T bitSet);
	EXPORTED void QE65000_setDirectionBitmask(QE65000_T c_qe65000, short bitmask);
	EXPORTED void QE65000_setMuxBitmask(QE65000_T c_qe65000, short bitmask);
	EXPORTED void QE65000_setValueBitmask(QE65000_T c_qe65000, short bitmask);
	EXPORTED void QE65000_setDirectionBit(QE65000_T c_qe65000, int bit, unsigned char value);
	EXPORTED void QE65000_setMuxBit(QE65000_T c_qe65000, int bit, unsigned char value);
	EXPORTED void QE65000_setValueBit(QE65000_T c_qe65000, int bit, unsigned char value);
	EXPORTED int QE65000_getTotalGPIOBits(QE65000_T c_qe65000);
	EXPORTED void QE65000_getDirectionBits(QE65000_T c_qe65000, BITSET_T retval);
	EXPORTED void QE65000_getMuxBits(QE65000_T c_qe65000, BITSET_T retval);
	EXPORTED void QE65000_getValueBits(QE65000_T c_qe65000, BITSET_T retval);
	EXPORTED int QE65000_getValueBit(QE65000_T c_qe65000, int bitNumber);
	EXPORTED int QE65000_getNumberOfPins(QE65000_T c_qe65000);
	EXPORTED double QE65000_getBoardTemperatureCelsius(QE65000_T c_qe65000);
	EXPORTED void QE65000_getIrradianceCalibrationFactors(QE65000_T c_qe65000, signed char address, DOUBLEARRAY_T retval);
	EXPORTED void QE65000_setIrradianceCalibrationFactors(QE65000_T c_qe65000, signed char address, DOUBLEARRAY_T data);
	EXPORTED void QE65000_setMasterClockDivisor(QE65000_T c_qe65000, int value);
	EXPORTED int QE65000_getMasterClockDivisor(QE65000_T c_qe65000);
	EXPORTED void QE65000_setExternalTriggerDelay(QE65000_T c_qe65000, int counts);
	EXPORTED double QE65000_triggerDelayCountsToMicroseconds(QE65000_T c_qe65000, int counts);
	EXPORTED int QE65000_getExternalTriggerDelayMinimum(QE65000_T c_qe65000);
	EXPORTED int QE65000_getExternalTriggerDelayMaximum(QE65000_T c_qe65000);
	EXPORTED int QE65000_getExternalTriggerDelayIncrement(QE65000_T c_qe65000);
	EXPORTED void QE65000_setTECEnable(QE65000_T c_qe65000, unsigned char enable);
	EXPORTED void QE65000_setFanEnable(QE65000_T c_qe65000, unsigned char enable);
	EXPORTED double QE65000_getDetectorTemperatureCelsius(QE65000_T c_qe65000);
	EXPORTED double QE65000_getDetectorTemperatureSetPointCelsius(QE65000_T c_qe65000);
	EXPORTED void QE65000_setDetectorSetPointCelsius(QE65000_T c_qe65000, double point);
	EXPORTED double QE65000_getSetPointMinimumCelsius(QE65000_T c_qe65000);
	EXPORTED double QE65000_getSetPointMaximumCelsius(QE65000_T c_qe65000);
	EXPORTED double QE65000_getSetPointIncrementCelsius(QE65000_T c_qe65000);
	EXPORTED unsigned char QE65000_isSaveTECStateEnabled(QE65000_T c_qe65000);
	EXPORTED void QE65000_saveTECState(QE65000_T c_qe65000);
	EXPORTED void QE65000_readNonlinearityCoefficientsFromSpectrometer(QE65000_T c_qe65000, COEFFICIENTSARRAY_T retval);
	EXPORTED void QE65000_writeNonlinearityCoefficientsToSpectrometer(QE65000_T c_qe65000, COEFFICIENTSARRAY_T coefficients);
	EXPORTED void QE65000_getNonlinearityCoefficients(QE65000_T c_qe65000, COEFFICIENTSARRAY_T retval);
	EXPORTED void QE65000_setNonlinearityCoefficients(QE65000_T c_qe65000, COEFFICIENTSARRAY_T coefficients);
	EXPORTED void QE65000_getNonlinearityCoefficientsSingleChannel(QE65000_T c_qe65000, int index, DOUBLEARRAY_T retval);
	EXPORTED void QE65000_setNonlinearityCoefficientsSingleChannel(QE65000_T c_qe65000, DOUBLEARRAY_T nl, int index);
	EXPORTED void QE65000_readWavelengthCalibrationCoefficientsFromSpectrometer(QE65000_T c_qe65000, COEFFICIENTSARRAY_T retval);
	EXPORTED void QE65000_writeWavelengthCoefficientsToSpectrometer(QE65000_T c_qe65000, COEFFICIENTSARRAY_T coefficients);
	EXPORTED void QE65000_getWavelengthCalibrationCoefficients(QE65000_T c_qe65000, COEFFICIENTSARRAY_T retval);
	EXPORTED void QE65000_setWavelengthCalibrationCoefficients(QE65000_T c_qe65000, COEFFICIENTSARRAY_T coefficients);
	EXPORTED void QE65000_getWavelengths(QE65000_T c_qe65000, int index, DOUBLEARRAY_T retval);
	EXPORTED void QE65000_setWavelengths(QE65000_T c_qe65000, DOUBLEARRAY_T wl, int index);
	EXPORTED void QE65000_readStrayLightCorrectionCoefficientFromSpectrometer(QE65000_T c_qe65000, COEFFICIENTSARRAY_T retval);
	EXPORTED void QE65000_writeStrayLightCoefficientToSpectrometer(QE65000_T c_qe65000, COEFFICIENTSARRAY_T coefficients);
	EXPORTED void QE65000_setStrayLightCorrectionCoefficient(QE65000_T c_qe65000, COEFFICIENTSARRAY_T coefficients);
	EXPORTED void QE65000_getStrayLightCorrectionCoefficient(QE65000_T c_qe65000, COEFFICIENTSARRAY_T retval);
	EXPORTED void QE65000_setStrayLight(QE65000_T c_qe65000, double strayLight, int index);
	EXPORTED double QE65000_getStrayLight(QE65000_T c_qe65000, int index);
	EXPORTED unsigned char QE65000_isAdvancedVersion(QE65000_T c_qe65000);
	EXPORTED void QE65000_addAcquisitionListener(QE65000_T c_qe65000, ACQUISITIONLISTENER_T listener);
	EXPORTED void QE65000_removeAcquisitionListener(QE65000_T c_qe65000, ACQUISITIONLISTENER_T listener);
	EXPORTED void QE65000_getSpectrometer(QE65000_T c_qe65000, QE65000_T retval);
	EXPORTED void QE65000_addExposureListener(QE65000_T c_qe65000, EXPOSURELISTENER_T listener);
	EXPORTED int QE65000_getCcdWidth(QE65000_T c_qe65000);
	EXPORTED int QE65000_getCcdHeight(QE65000_T c_qe65000);
	EXPORTED void QE65000_getLastExposure(QE65000_T c_qe65000, SPECTROMETEREXPOSURE_T retval);
	EXPORTED void QE65000_removeExposureListener(QE65000_T c_qe65000, EXPOSURELISTENER_T listener);
	EXPORTED void QE65000_getQE65000Exposure(QE65000_T c_qe65000, SPECTRUM_T spectrum, SPECTROMETEREXPOSURE_T retval);
	EXPORTED void QE65000_set2DMode(QE65000_T c_qe65000, int channelIndex);
	EXPORTED void QE65000_set1DMode(QE65000_T c_qe65000, int channelIndex);
	EXPORTED void QE65000_getSpectrum(QE65000_T c_qe65000, SPECTRUM_T spectrum, SPECTRUM_T retval);
	EXPORTED unsigned char QE65000_has1DMode(QE65000_T c_qe65000);
	EXPORTED unsigned char QE65000_is1DMode(QE65000_T c_qe65000);
	EXPORTED unsigned char QE65000_is2DMode(QE65000_T c_qe65000);
	EXPORTED int QE65000_get2DintegrationTime(QE65000_T c_qe65000);
	EXPORTED void QE65000_addIntegrationTimeChangeListener(QE65000_T c_qe65000, INTEGRATIONTIMECHANGELISTENER_T listener);
	EXPORTED void QE65000_removeIntegrationTimeChangeListener(QE65000_T c_qe65000, INTEGRATIONTIMECHANGELISTENER_T listener);
	EXPORTED void QE65000_Destroy(QE65000_T qe65000);

#ifdef WIN32
	// Use the following function prototypes when calling functions from Visual Basic 6
	EXPORTED QE65000_T STDCALL QE65000_Create_stdcall();
	EXPORTED QE65000_T STDCALL QE65000_Create_stdcall_1(int i);
	EXPORTED unsigned char STDCALL QE65000_setSaturationIntensity_stdcall(QE65000_T c_qe65000, int saturationIntensity, JSTRING_T key);
	EXPORTED int STDCALL QE65000_getSaturationIntensity_stdcall(QE65000_T c_qe65000);
	EXPORTED void STDCALL QE65000_setEndpoints_stdcall(QE65000_T c_qe65000);
	EXPORTED void STDCALL QE65000_getEndpoint_stdcall(QE65000_T c_qe65000, int endPoint, USBENDPOINTDESCRIPTOR_T retval);
	EXPORTED unsigned char STDCALL QE65000_allowWriteToEEPROM_stdcall(QE65000_T c_qe65000, int privilegeLevel, int slot);
	EXPORTED void STDCALL QE65000_openSpectrometer_stdcall(QE65000_T c_qe65000, int index);
	EXPORTED void STDCALL QE65000_getGUIFeatures_stdcall(QE65000_T c_qe65000, GUIPROVIDERARRAY_T retval);
	EXPORTED void STDCALL QE65000_setStrobeDelay_stdcall(QE65000_T c_qe65000, int delay);
	EXPORTED int STDCALL QE65000_getActualIntegrationTime_stdcall(QE65000_T c_qe65000);
	EXPORTED void STDCALL QE65000_getPlugIns_stdcall(QE65000_T c_qe65000, SPECTROMETERPLUGINARRAY_T retval);
	EXPORTED int STDCALL QE65000_getNumberOfPlugIns_stdcall(QE65000_T c_qe65000);
	EXPORTED unsigned char STDCALL QE65000_isPlugInDetected_stdcall(QE65000_T c_qe65000, int id);
	EXPORTED void STDCALL QE65000_initializePlugIns_stdcall(QE65000_T c_qe65000, CHARARRAY_T retval);
	EXPORTED void STDCALL QE65000_detectPlugIns_stdcall(QE65000_T c_qe65000);
	EXPORTED int STDCALL QE65000_setI2CBytes_stdcall(QE65000_T c_qe65000, signed char address, signed char numBytes, CHARARRAY_T i2C);
	EXPORTED void STDCALL QE65000_getI2CBytes_stdcall(QE65000_T c_qe65000, signed char address, signed char numBytes, CHARARRAY_T retval);
	EXPORTED void STDCALL QE65000_getSPIBytes_stdcall(QE65000_T c_qe65000, CHARARRAY_T message, int length, CHARARRAY_T retval);
	EXPORTED void STDCALL QE65000_getPSOCVersion_stdcall(QE65000_T c_qe65000, JSTRING_T retval);
	EXPORTED void STDCALL QE65000_getFPGAFirmwareVersion_stdcall(QE65000_T c_qe65000, JSTRING_T retval);
	EXPORTED double STDCALL QE65000_continuousStrobeCountsToMicros_stdcall(QE65000_T c_qe65000, int counts);
	EXPORTED void STDCALL QE65000_setContinuousStrobeDelay_stdcall(QE65000_T c_qe65000, int delayMicros);
	EXPORTED int STDCALL QE65000_getContinuousStrobeDelayMinimum_stdcall(QE65000_T c_qe65000);
	EXPORTED int STDCALL QE65000_getContinuousStrobeDelayMaximum_stdcall(QE65000_T c_qe65000);
	EXPORTED int STDCALL QE65000_getContinuousStrobeDelayIncrement_stdcall(QE65000_T c_qe65000, int magnitude);
	EXPORTED void STDCALL QE65000_setAdvancedIntegrationTime_stdcall(QE65000_T c_qe65000, long long delayMicros);
	EXPORTED int STDCALL QE65000_getIntegrationTimeBaseClock_stdcall(QE65000_T c_qe65000);
	EXPORTED int STDCALL QE65000_getIntegrationClockTimer_stdcall(QE65000_T c_qe65000);
	EXPORTED long long STDCALL QE65000_getAdvancedIntegrationTimeMinimum_stdcall(QE65000_T c_qe65000);
	EXPORTED long long STDCALL QE65000_getAdvancedIntegrationTimeMaximum_stdcall(QE65000_T c_qe65000);
	EXPORTED long long STDCALL QE65000_getAdvancedIntegrationTimeIncrement_stdcall(QE65000_T c_qe65000);
	EXPORTED void STDCALL QE65000_setExternalTriggerMode_stdcall(QE65000_T c_qe65000, int mode);
	EXPORTED void STDCALL QE65000_getExternalTriggerModes_stdcall(QE65000_T c_qe65000, EXTERNALTRIGGERMODEARRAY_T retval);
	EXPORTED void STDCALL QE65000_setShutterClock_stdcall(QE65000_T c_qe65000, int value);
	EXPORTED int STDCALL QE65000_getShutterClock_stdcall(QE65000_T c_qe65000);
	EXPORTED void STDCALL QE65000_setSingleStrobeLow_stdcall(QE65000_T c_qe65000, int value);
	EXPORTED void STDCALL QE65000_setSingleStrobeHigh_stdcall(QE65000_T c_qe65000, int value);
	EXPORTED double STDCALL QE65000_getSingleStrobeCountsToMicros_stdcall(QE65000_T c_qe65000, int counts);
	EXPORTED int STDCALL QE65000_getSingleStrobeLow_stdcall(QE65000_T c_qe65000);
	EXPORTED int STDCALL QE65000_getSingleStrobeHigh_stdcall(QE65000_T c_qe65000);
	EXPORTED int STDCALL QE65000_getSingleStrobeMinimum_stdcall(QE65000_T c_qe65000);
	EXPORTED int STDCALL QE65000_getSingleStrobeMaximum_stdcall(QE65000_T c_qe65000);
	EXPORTED int STDCALL QE65000_getSingleStrobeIncrement_stdcall(QE65000_T c_qe65000);
	EXPORTED void STDCALL QE65000_setDirectionAllBits_stdcall(QE65000_T c_qe65000, BITSET_T bitSet);
	EXPORTED void STDCALL QE65000_setMuxAllBits_stdcall(QE65000_T c_qe65000, BITSET_T bitSet);
	EXPORTED void STDCALL QE65000_setValueAllBits_stdcall(QE65000_T c_qe65000, BITSET_T bitSet);
	EXPORTED void STDCALL QE65000_setDirectionBitmask_stdcall(QE65000_T c_qe65000, short bitmask);
	EXPORTED void STDCALL QE65000_setMuxBitmask_stdcall(QE65000_T c_qe65000, short bitmask);
	EXPORTED void STDCALL QE65000_setValueBitmask_stdcall(QE65000_T c_qe65000, short bitmask);
	EXPORTED void STDCALL QE65000_setDirectionBit_stdcall(QE65000_T c_qe65000, int bit, unsigned char value);
	EXPORTED void STDCALL QE65000_setMuxBit_stdcall(QE65000_T c_qe65000, int bit, unsigned char value);
	EXPORTED void STDCALL QE65000_setValueBit_stdcall(QE65000_T c_qe65000, int bit, unsigned char value);
	EXPORTED int STDCALL QE65000_getTotalGPIOBits_stdcall(QE65000_T c_qe65000);
	EXPORTED void STDCALL QE65000_getDirectionBits_stdcall(QE65000_T c_qe65000, BITSET_T retval);
	EXPORTED void STDCALL QE65000_getMuxBits_stdcall(QE65000_T c_qe65000, BITSET_T retval);
	EXPORTED void STDCALL QE65000_getValueBits_stdcall(QE65000_T c_qe65000, BITSET_T retval);
	EXPORTED int STDCALL QE65000_getValueBit_stdcall(QE65000_T c_qe65000, int bitNumber);
	EXPORTED int STDCALL QE65000_getNumberOfPins_stdcall(QE65000_T c_qe65000);
	EXPORTED double STDCALL QE65000_getBoardTemperatureCelsius_stdcall(QE65000_T c_qe65000);
	EXPORTED void STDCALL QE65000_getIrradianceCalibrationFactors_stdcall(QE65000_T c_qe65000, signed char address, DOUBLEARRAY_T retval);
	EXPORTED void STDCALL QE65000_setIrradianceCalibrationFactors_stdcall(QE65000_T c_qe65000, signed char address, DOUBLEARRAY_T data);
	EXPORTED void STDCALL QE65000_setMasterClockDivisor_stdcall(QE65000_T c_qe65000, int value);
	EXPORTED int STDCALL QE65000_getMasterClockDivisor_stdcall(QE65000_T c_qe65000);
	EXPORTED void STDCALL QE65000_setExternalTriggerDelay_stdcall(QE65000_T c_qe65000, int counts);
	EXPORTED double STDCALL QE65000_triggerDelayCountsToMicroseconds_stdcall(QE65000_T c_qe65000, int counts);
	EXPORTED int STDCALL QE65000_getExternalTriggerDelayMinimum_stdcall(QE65000_T c_qe65000);
	EXPORTED int STDCALL QE65000_getExternalTriggerDelayMaximum_stdcall(QE65000_T c_qe65000);
	EXPORTED int STDCALL QE65000_getExternalTriggerDelayIncrement_stdcall(QE65000_T c_qe65000);
	EXPORTED void STDCALL QE65000_setTECEnable_stdcall(QE65000_T c_qe65000, unsigned char enable);
	EXPORTED void STDCALL QE65000_setFanEnable_stdcall(QE65000_T c_qe65000, unsigned char enable);
	EXPORTED double STDCALL QE65000_getDetectorTemperatureCelsius_stdcall(QE65000_T c_qe65000);
	EXPORTED double STDCALL QE65000_getDetectorTemperatureSetPointCelsius_stdcall(QE65000_T c_qe65000);
	EXPORTED void STDCALL QE65000_setDetectorSetPointCelsius_stdcall(QE65000_T c_qe65000, double point);
	EXPORTED double STDCALL QE65000_getSetPointMinimumCelsius_stdcall(QE65000_T c_qe65000);
	EXPORTED double STDCALL QE65000_getSetPointMaximumCelsius_stdcall(QE65000_T c_qe65000);
	EXPORTED double STDCALL QE65000_getSetPointIncrementCelsius_stdcall(QE65000_T c_qe65000);
	EXPORTED unsigned char STDCALL QE65000_isSaveTECStateEnabled_stdcall(QE65000_T c_qe65000);
	EXPORTED void STDCALL QE65000_saveTECState_stdcall(QE65000_T c_qe65000);
	EXPORTED void STDCALL QE65000_readNonlinearityCoefficientsFromSpectrometer_stdcall(QE65000_T c_qe65000, COEFFICIENTSARRAY_T retval);
	EXPORTED void STDCALL QE65000_writeNonlinearityCoefficientsToSpectrometer_stdcall(QE65000_T c_qe65000, COEFFICIENTSARRAY_T coefficients);
	EXPORTED void STDCALL QE65000_getNonlinearityCoefficients_stdcall(QE65000_T c_qe65000, COEFFICIENTSARRAY_T retval);
	EXPORTED void STDCALL QE65000_setNonlinearityCoefficients_stdcall(QE65000_T c_qe65000, COEFFICIENTSARRAY_T coefficients);
	EXPORTED void STDCALL QE65000_getNonlinearityCoefficientsSingleChannel_stdcall(QE65000_T c_qe65000, int index, DOUBLEARRAY_T retval);
	EXPORTED void STDCALL QE65000_setNonlinearityCoefficientsSingleChannel_stdcall(QE65000_T c_qe65000, DOUBLEARRAY_T nl, int index);
	EXPORTED void STDCALL QE65000_readWavelengthCalibrationCoefficientsFromSpectrometer_stdcall(QE65000_T c_qe65000, COEFFICIENTSARRAY_T retval);
	EXPORTED void STDCALL QE65000_writeWavelengthCoefficientsToSpectrometer_stdcall(QE65000_T c_qe65000, COEFFICIENTSARRAY_T coefficients);
	EXPORTED void STDCALL QE65000_getWavelengthCalibrationCoefficients_stdcall(QE65000_T c_qe65000, COEFFICIENTSARRAY_T retval);
	EXPORTED void STDCALL QE65000_setWavelengthCalibrationCoefficients_stdcall(QE65000_T c_qe65000, COEFFICIENTSARRAY_T coefficients);
	EXPORTED void STDCALL QE65000_getWavelengths_stdcall(QE65000_T c_qe65000, int index, DOUBLEARRAY_T retval);
	EXPORTED void STDCALL QE65000_setWavelengths_stdcall(QE65000_T c_qe65000, DOUBLEARRAY_T wl, int index);
	EXPORTED void STDCALL QE65000_readStrayLightCorrectionCoefficientFromSpectrometer_stdcall(QE65000_T c_qe65000, COEFFICIENTSARRAY_T retval);
	EXPORTED void STDCALL QE65000_writeStrayLightCoefficientToSpectrometer_stdcall(QE65000_T c_qe65000, COEFFICIENTSARRAY_T coefficients);
	EXPORTED void STDCALL QE65000_setStrayLightCorrectionCoefficient_stdcall(QE65000_T c_qe65000, COEFFICIENTSARRAY_T coefficients);
	EXPORTED void STDCALL QE65000_getStrayLightCorrectionCoefficient_stdcall(QE65000_T c_qe65000, COEFFICIENTSARRAY_T retval);
	EXPORTED void STDCALL QE65000_setStrayLight_stdcall(QE65000_T c_qe65000, double strayLight, int index);
	EXPORTED double STDCALL QE65000_getStrayLight_stdcall(QE65000_T c_qe65000, int index);
	EXPORTED unsigned char STDCALL QE65000_isAdvancedVersion_stdcall(QE65000_T c_qe65000);
	EXPORTED void STDCALL QE65000_addAcquisitionListener_stdcall(QE65000_T c_qe65000, ACQUISITIONLISTENER_T listener);
	EXPORTED void STDCALL QE65000_removeAcquisitionListener_stdcall(QE65000_T c_qe65000, ACQUISITIONLISTENER_T listener);
	EXPORTED void STDCALL QE65000_getSpectrometer_stdcall(QE65000_T c_qe65000, QE65000_T retval);
	EXPORTED void STDCALL QE65000_addExposureListener_stdcall(QE65000_T c_qe65000, EXPOSURELISTENER_T listener);
	EXPORTED int STDCALL QE65000_getCcdWidth_stdcall(QE65000_T c_qe65000);
	EXPORTED int STDCALL QE65000_getCcdHeight_stdcall(QE65000_T c_qe65000);
	EXPORTED void STDCALL QE65000_getLastExposure_stdcall(QE65000_T c_qe65000, SPECTROMETEREXPOSURE_T retval);
	EXPORTED void STDCALL QE65000_removeExposureListener_stdcall(QE65000_T c_qe65000, EXPOSURELISTENER_T listener);
	EXPORTED void STDCALL QE65000_getQE65000Exposure_stdcall(QE65000_T c_qe65000, SPECTRUM_T spectrum, SPECTROMETEREXPOSURE_T retval);
	EXPORTED void STDCALL QE65000_set2DMode_stdcall(QE65000_T c_qe65000, int channelIndex);
	EXPORTED void STDCALL QE65000_set1DMode_stdcall(QE65000_T c_qe65000, int channelIndex);
	EXPORTED void STDCALL QE65000_getSpectrum_stdcall(QE65000_T c_qe65000, SPECTRUM_T spectrum, SPECTRUM_T retval);
	EXPORTED unsigned char STDCALL QE65000_has1DMode_stdcall(QE65000_T c_qe65000);
	EXPORTED unsigned char STDCALL QE65000_is1DMode_stdcall(QE65000_T c_qe65000);
	EXPORTED unsigned char STDCALL QE65000_is2DMode_stdcall(QE65000_T c_qe65000);
	EXPORTED int STDCALL QE65000_get2DintegrationTime_stdcall(QE65000_T c_qe65000);
	EXPORTED void STDCALL QE65000_addIntegrationTimeChangeListener_stdcall(QE65000_T c_qe65000, INTEGRATIONTIMECHANGELISTENER_T listener);
	EXPORTED void STDCALL QE65000_removeIntegrationTimeChangeListener_stdcall(QE65000_T c_qe65000, INTEGRATIONTIMECHANGELISTENER_T listener);
	EXPORTED void STDCALL QE65000_Destroy_stdcall(QE65000_T qe65000);
#endif /* WIN32 */
#ifdef __cplusplus
};
#endif /* __cplusplus */
#endif /* QE65000_H */
