/**
 * File: S8378Status.h
 * Autogenerated on Mon Nov 16 11:53:39 EST 2009 based on
 * S8378Status.java
 * for the Java class
 * com/oceanoptics/omnidriver/spectrometer/s8378Prototype/S8378Status
 * Copyright (C) 2006 - 2008 Ocean Optics, Inc.  All rights reserved.
 */


#ifndef S8378STATUS_H
#define S8378STATUS_H
#include "BaseJavaClass.h"

#ifdef __cplusplus

#ifdef INCLUDES_IN_HEADER
#include "SpectrometerStatus.h"
#include "JString.h"
#endif /* INCLUDES_IN_HEADER */

/* Pre-declarations for circular dependencies in header files */
#ifdef CLASS_PREDECLARATIONS
class SpectrometerStatus;
class JString;
#endif /* CLASS_PREDECLARATIONS */

CLASS_TOKEN EXPORTED S8378Status : public SpectrometerStatus // CPPClass.getClassDeclaration
{
public: 
	S8378Status();
	JString toString();
	~S8378Status();
	// No public Java copy constructor; creating one:
	S8378Status(const S8378Status &that);
	// Creating assignment operator declaration:
	S8378Status &operator=(const S8378Status &that);
	signed char numPacketsInSpectra;
	int powerDownFlag;
	signed char packetCount;
	int usbSpeed;

private:
	jmethodID mid_S8378Status3318;
	jmethodID mid_toString3319;
	jfieldID fid_numPacketsInSpectra;
	jfieldID fid_powerDownFlag;
	jfieldID fid_packetCount;
	jfieldID fid_usbSpeed;
	void init_ids(JNIEnv* pJNIEnv);
};

extern "C" {
#endif /* __cplusplus */
#ifndef EXTERN_TYPEDEF_SPECTROMETERSTATUS_T
#define EXTERN_TYPEDEF_SPECTROMETERSTATUS_T
	typedef void* SPECTROMETERSTATUS_T;
#endif /* EXTERN_TYPEDEF_SPECTROMETERSTATUS_T */
#ifndef EXTERN_TYPEDEF_JSTRING_T
#define EXTERN_TYPEDEF_JSTRING_T
	typedef void* JSTRING_T;
#endif /* EXTERN_TYPEDEF_JSTRING_T */
#ifndef EXTERN_TYPEDEF_S8378STATUS_T
#define EXTERN_TYPEDEF_S8378STATUS_T
	typedef void* S8378STATUS_T;
#endif /* EXTERN_TYPEDEF_S8378STATUS_T */

	EXPORTED S8378STATUS_T S8378Status_Create();
	EXPORTED void S8378Status_toString(S8378STATUS_T c_s8378status, JSTRING_T retval);
	EXPORTED void S8378Status_Destroy(S8378STATUS_T s8378status);

#ifdef WIN32
	// Use the following function prototypes when calling functions from Visual Basic 6
	EXPORTED S8378STATUS_T STDCALL S8378Status_Create_stdcall();
	EXPORTED void STDCALL S8378Status_toString_stdcall(S8378STATUS_T c_s8378status, JSTRING_T retval);
	EXPORTED void STDCALL S8378Status_Destroy_stdcall(S8378STATUS_T s8378status);
#endif /* WIN32 */
#ifdef __cplusplus
};
#endif /* __cplusplus */
#endif /* S8378STATUS_H */
