/**
 * File: SetHomePositionImpl.h
 * Autogenerated on Mon Nov 16 11:53:30 EST 2009 based on
 * SetHomePositionImpl.java
 * for the Java class
 * com/oceanoptics/omnidriver/accessories/mikropack/commands/sethomeposition/SetHomePositionImpl
 * Copyright (C) 2006 - 2008 Ocean Optics, Inc.  All rights reserved.
 */


#ifndef SETHOMEPOSITIONIMPL_H
#define SETHOMEPOSITIONIMPL_H
#include "BaseJavaClass.h"

#ifdef __cplusplus

#ifdef INCLUDES_IN_HEADER
#include "FaulhaberCommandOnly.h"
#include "UniRS232.h"
#include "Node.h"
#endif /* INCLUDES_IN_HEADER */

/* Pre-declarations for circular dependencies in header files */
#ifdef CLASS_PREDECLARATIONS
class FaulhaberCommandOnly;
class UniRS232;
class Node;
#endif /* CLASS_PREDECLARATIONS */

CLASS_TOKEN EXPORTED SetHomePositionImpl : public FaulhaberCommandOnly // CPPClass.getClassDeclaration
{
public: 
	SetHomePositionImpl(UniRS232& serPort);
	void setHomePosition(Node& node);
	~SetHomePositionImpl();
	// No public default Java constructor; creating one:
	SetHomePositionImpl();
	// No public Java copy constructor; creating one:
	SetHomePositionImpl(const SetHomePositionImpl &that);
	// Creating assignment operator declaration:
	SetHomePositionImpl &operator=(const SetHomePositionImpl &that);

private:
	jmethodID mid_SetHomePositionImpl154;
	jmethodID mid_setHomePosition155;
	void init_ids(JNIEnv* pJNIEnv);
};

extern "C" {
#endif /* __cplusplus */
#ifndef EXTERN_TYPEDEF_FAULHABERCOMMANDONLY_T
#define EXTERN_TYPEDEF_FAULHABERCOMMANDONLY_T
	typedef void* FAULHABERCOMMANDONLY_T;
#endif /* EXTERN_TYPEDEF_FAULHABERCOMMANDONLY_T */
#ifndef EXTERN_TYPEDEF_UNIRS232_T
#define EXTERN_TYPEDEF_UNIRS232_T
	typedef void* UNIRS232_T;
#endif /* EXTERN_TYPEDEF_UNIRS232_T */
#ifndef EXTERN_TYPEDEF_NODE_T
#define EXTERN_TYPEDEF_NODE_T
	typedef void* NODE_T;
#endif /* EXTERN_TYPEDEF_NODE_T */
#ifndef EXTERN_TYPEDEF_SETHOMEPOSITIONIMPL_T
#define EXTERN_TYPEDEF_SETHOMEPOSITIONIMPL_T
	typedef void* SETHOMEPOSITIONIMPL_T;
#endif /* EXTERN_TYPEDEF_SETHOMEPOSITIONIMPL_T */

	// No public default Java constructor; creating one:
	EXPORTED SETHOMEPOSITIONIMPL_T SetHomePositionImpl_Create();
	EXPORTED SETHOMEPOSITIONIMPL_T SetHomePositionImpl_Create_1(UNIRS232_T serPort);
	EXPORTED void SetHomePositionImpl_setHomePosition(SETHOMEPOSITIONIMPL_T c_set_home_position_impl, NODE_T node);
	EXPORTED void SetHomePositionImpl_Destroy(SETHOMEPOSITIONIMPL_T set_home_position_impl);

#ifdef WIN32
	// Use the following function prototypes when calling functions from Visual Basic 6
	EXPORTED SETHOMEPOSITIONIMPL_T STDCALL SetHomePositionImpl_Create_stdcall_1(UNIRS232_T serPort);
	EXPORTED void STDCALL SetHomePositionImpl_setHomePosition_stdcall(SETHOMEPOSITIONIMPL_T c_set_home_position_impl, NODE_T node);
	EXPORTED void STDCALL SetHomePositionImpl_Destroy_stdcall(SETHOMEPOSITIONIMPL_T set_home_position_impl);
#endif /* WIN32 */
#ifdef __cplusplus
};
#endif /* __cplusplus */
#endif /* SETHOMEPOSITIONIMPL_H */
