/**
 * File: SetOutputDigitalImpl.h
 * Autogenerated on Mon Nov 16 11:53:30 EST 2009 based on
 * SetOutputDigitalImpl.java
 * for the Java class
 * com/oceanoptics/omnidriver/accessories/mikropack/commands/setoutputdigital/SetOutputDigitalImpl
 * Copyright (C) 2006 - 2008 Ocean Optics, Inc.  All rights reserved.
 */


#ifndef SETOUTPUTDIGITALIMPL_H
#define SETOUTPUTDIGITALIMPL_H
#include "BaseJavaClass.h"

#ifdef __cplusplus

#ifdef INCLUDES_IN_HEADER
#include "FaulhaberCommandOnly.h"
#include "UniRS232.h"
#include "Node.h"
#endif /* INCLUDES_IN_HEADER */

/* Pre-declarations for circular dependencies in header files */
#ifdef CLASS_PREDECLARATIONS
class FaulhaberCommandOnly;
class UniRS232;
class Node;
#endif /* CLASS_PREDECLARATIONS */

CLASS_TOKEN EXPORTED SetOutputDigitalImpl : public FaulhaberCommandOnly // CPPClass.getClassDeclaration
{
public: 
	SetOutputDigitalImpl(UniRS232& serPort);
	void setOutputDigital(Node& node);
	~SetOutputDigitalImpl();
	// No public default Java constructor; creating one:
	SetOutputDigitalImpl();
	// No public Java copy constructor; creating one:
	SetOutputDigitalImpl(const SetOutputDigitalImpl &that);
	// Creating assignment operator declaration:
	SetOutputDigitalImpl &operator=(const SetOutputDigitalImpl &that);

private:
	jmethodID mid_SetOutputDigitalImpl157;
	jmethodID mid_setOutputDigital158;
	void init_ids(JNIEnv* pJNIEnv);
};

extern "C" {
#endif /* __cplusplus */
#ifndef EXTERN_TYPEDEF_FAULHABERCOMMANDONLY_T
#define EXTERN_TYPEDEF_FAULHABERCOMMANDONLY_T
	typedef void* FAULHABERCOMMANDONLY_T;
#endif /* EXTERN_TYPEDEF_FAULHABERCOMMANDONLY_T */
#ifndef EXTERN_TYPEDEF_UNIRS232_T
#define EXTERN_TYPEDEF_UNIRS232_T
	typedef void* UNIRS232_T;
#endif /* EXTERN_TYPEDEF_UNIRS232_T */
#ifndef EXTERN_TYPEDEF_NODE_T
#define EXTERN_TYPEDEF_NODE_T
	typedef void* NODE_T;
#endif /* EXTERN_TYPEDEF_NODE_T */
#ifndef EXTERN_TYPEDEF_SETOUTPUTDIGITALIMPL_T
#define EXTERN_TYPEDEF_SETOUTPUTDIGITALIMPL_T
	typedef void* SETOUTPUTDIGITALIMPL_T;
#endif /* EXTERN_TYPEDEF_SETOUTPUTDIGITALIMPL_T */

	// No public default Java constructor; creating one:
	EXPORTED SETOUTPUTDIGITALIMPL_T SetOutputDigitalImpl_Create();
	EXPORTED SETOUTPUTDIGITALIMPL_T SetOutputDigitalImpl_Create_1(UNIRS232_T serPort);
	EXPORTED void SetOutputDigitalImpl_setOutputDigital(SETOUTPUTDIGITALIMPL_T c_set_output_digital_impl, NODE_T node);
	EXPORTED void SetOutputDigitalImpl_Destroy(SETOUTPUTDIGITALIMPL_T set_output_digital_impl);

#ifdef WIN32
	// Use the following function prototypes when calling functions from Visual Basic 6
	EXPORTED SETOUTPUTDIGITALIMPL_T STDCALL SetOutputDigitalImpl_Create_stdcall_1(UNIRS232_T serPort);
	EXPORTED void STDCALL SetOutputDigitalImpl_setOutputDigital_stdcall(SETOUTPUTDIGITALIMPL_T c_set_output_digital_impl, NODE_T node);
	EXPORTED void STDCALL SetOutputDigitalImpl_Destroy_stdcall(SETOUTPUTDIGITALIMPL_T set_output_digital_impl);
#endif /* WIN32 */
#ifdef __cplusplus
};
#endif /* __cplusplus */
#endif /* SETOUTPUTDIGITALIMPL_H */
