/**
 * File: SetResponseMode.h
 * Autogenerated on Mon Nov 16 11:53:30 EST 2009 based on
 * SetResponseMode.java
 * for the Java class
 * com/oceanoptics/omnidriver/accessories/mikropack/commands/setresponsemode/SetResponseMode
 * Copyright (C) 2006 - 2008 Ocean Optics, Inc.  All rights reserved.
 */


#ifndef SETRESPONSEMODE_H
#define SETRESPONSEMODE_H
#include "BaseJavaClass.h"

#ifdef __cplusplus

#ifdef INCLUDES_IN_HEADER
#include "Node.h"
#endif /* INCLUDES_IN_HEADER */

/* Pre-declarations for circular dependencies in header files */
#ifdef CLASS_PREDECLARATIONS
class Node;
#endif /* CLASS_PREDECLARATIONS */

CLASS_TOKEN EXPORTED SetResponseMode : public BaseJavaClass // CPPClass.getClassDeclaration
{
public: 
	void setResponseMode(Node& param0, int param1);
	~SetResponseMode();
	// No public default Java constructor; creating one:
	SetResponseMode();
	// No public Java copy constructor; creating one:
	SetResponseMode(const SetResponseMode &that);
	// Creating assignment operator declaration:
	SetResponseMode &operator=(const SetResponseMode &that);
	int RESPONSE_MODE_OFF;
	int RESPONSE_MODE_NOTIFY;
	int RESPONSE_MODE_ALL;

private:
	jmethodID mid_setResponseMode162;
	jfieldID fid_RESPONSE_MODE_OFF;
	jfieldID fid_RESPONSE_MODE_NOTIFY;
	jfieldID fid_RESPONSE_MODE_ALL;
	void init_ids(JNIEnv* pJNIEnv);
};

extern "C" {
#endif /* __cplusplus */
#ifndef EXTERN_TYPEDEF_NODE_T
#define EXTERN_TYPEDEF_NODE_T
	typedef void* NODE_T;
#endif /* EXTERN_TYPEDEF_NODE_T */
#ifndef EXTERN_TYPEDEF_SETRESPONSEMODE_T
#define EXTERN_TYPEDEF_SETRESPONSEMODE_T
	typedef void* SETRESPONSEMODE_T;
#endif /* EXTERN_TYPEDEF_SETRESPONSEMODE_T */

	// No public default Java constructor; creating one:
	EXPORTED SETRESPONSEMODE_T SetResponseMode_Create();
	EXPORTED void SetResponseMode_setResponseMode(SETRESPONSEMODE_T c_set_response_mode, NODE_T param0, int param1);
	EXPORTED void SetResponseMode_Destroy(SETRESPONSEMODE_T set_response_mode);

#ifdef WIN32
	// Use the following function prototypes when calling functions from Visual Basic 6
	EXPORTED void STDCALL SetResponseMode_setResponseMode_stdcall(SETRESPONSEMODE_T c_set_response_mode, NODE_T param0, int param1);
	EXPORTED void STDCALL SetResponseMode_Destroy_stdcall(SETRESPONSEMODE_T set_response_mode);
#endif /* WIN32 */
#ifdef __cplusplus
};
#endif /* __cplusplus */
#endif /* SETRESPONSEMODE_H */
