/**
 * File: ShutterClockImpl.h
 * Autogenerated on Mon Nov 16 11:53:34 EST 2009 based on
 * ShutterClockImpl.java
 * for the Java class
 * com/oceanoptics/omnidriver/features/shutterclock/ShutterClockImpl
 * Copyright (C) 2006 - 2008 Ocean Optics, Inc.  All rights reserved.
 */


#ifndef SHUTTERCLOCKIMPL_H
#define SHUTTERCLOCKIMPL_H
#include "BaseJavaClass.h"

#ifdef __cplusplus

#ifdef INCLUDES_IN_HEADER
#include "FPGAImpl.h"
#include "USBInterface.h"
#endif /* INCLUDES_IN_HEADER */

/* Pre-declarations for circular dependencies in header files */
#ifdef CLASS_PREDECLARATIONS
class FPGAImpl;
class USBInterface;
#endif /* CLASS_PREDECLARATIONS */

CLASS_TOKEN EXPORTED ShutterClockImpl : public FPGAImpl // CPPClass.getClassDeclaration
{
public: 
	ShutterClockImpl(USBInterface& usbInt);
	int getShutterClock();
	void setShutterClock(int value);
	~ShutterClockImpl();
	// No public default Java constructor; creating one:
	ShutterClockImpl();
	// No public Java copy constructor; creating one:
	ShutterClockImpl(const ShutterClockImpl &that);
	// Creating assignment operator declaration:
	ShutterClockImpl &operator=(const ShutterClockImpl &that);

private:
	jmethodID mid_ShutterClockImpl977;
	jmethodID mid_getShutterClock978;
	jmethodID mid_setShutterClock979;
	void init_ids(JNIEnv* pJNIEnv);
};

extern "C" {
#endif /* __cplusplus */
#ifndef EXTERN_TYPEDEF_FPGAIMPL_T
#define EXTERN_TYPEDEF_FPGAIMPL_T
	typedef void* FPGAIMPL_T;
#endif /* EXTERN_TYPEDEF_FPGAIMPL_T */
#ifndef EXTERN_TYPEDEF_USBINTERFACE_T
#define EXTERN_TYPEDEF_USBINTERFACE_T
	typedef void* USBINTERFACE_T;
#endif /* EXTERN_TYPEDEF_USBINTERFACE_T */
#ifndef EXTERN_TYPEDEF_SHUTTERCLOCKIMPL_T
#define EXTERN_TYPEDEF_SHUTTERCLOCKIMPL_T
	typedef void* SHUTTERCLOCKIMPL_T;
#endif /* EXTERN_TYPEDEF_SHUTTERCLOCKIMPL_T */

	// No public default Java constructor; creating one:
	EXPORTED SHUTTERCLOCKIMPL_T ShutterClockImpl_Create();
	EXPORTED SHUTTERCLOCKIMPL_T ShutterClockImpl_Create_1(USBINTERFACE_T usbInt);
	EXPORTED int ShutterClockImpl_getShutterClock(SHUTTERCLOCKIMPL_T c_shutter_clock_impl);
	EXPORTED void ShutterClockImpl_setShutterClock(SHUTTERCLOCKIMPL_T c_shutter_clock_impl, int value);
	EXPORTED void ShutterClockImpl_Destroy(SHUTTERCLOCKIMPL_T shutter_clock_impl);

#ifdef WIN32
	// Use the following function prototypes when calling functions from Visual Basic 6
	EXPORTED SHUTTERCLOCKIMPL_T STDCALL ShutterClockImpl_Create_stdcall_1(USBINTERFACE_T usbInt);
	EXPORTED int STDCALL ShutterClockImpl_getShutterClock_stdcall(SHUTTERCLOCKIMPL_T c_shutter_clock_impl);
	EXPORTED void STDCALL ShutterClockImpl_setShutterClock_stdcall(SHUTTERCLOCKIMPL_T c_shutter_clock_impl, int value);
	EXPORTED void STDCALL ShutterClockImpl_Destroy_stdcall(SHUTTERCLOCKIMPL_T shutter_clock_impl);
#endif /* WIN32 */
#ifdef __cplusplus
};
#endif /* __cplusplus */
#endif /* SHUTTERCLOCKIMPL_H */
