/***
 * SpectrometerArray.h
 * Autogenerated on Mon Nov 16 11:53:41 EST 2009
 * Copyright (C) 2006 - 2008 Ocean Optics, Inc.  All rights reserved.
 */

#ifndef SPECTROMETERARRAY_H
#define SPECTROMETERARRAY_H
#include "ArrayTypes.h"
#include "Spectrometer.h"

#ifdef __cplusplus

/* Pre-declarations for circular dependencies in header files */
#ifdef CLASS_PREDECLARATIONS
class Spectrometer;
#endif /* CLASS_PREDECLARATIONS */

class EXPORTED SpectrometerArray : public AbstractArray {
public:
	/* Default constructor */
	SpectrometerArray();

	/* Initialization constructor */
	SpectrometerArray(Spectrometer *objects, int length);

	/* Copy constructor */
	SpectrometerArray(const SpectrometerArray &that);

	/* Destructor */
	~SpectrometerArray();

	/* Assignment operator */
	SpectrometerArray &operator=(const SpectrometerArray &that);

	/* Setter */
	void setObjects(Spectrometer *objects, int length);

	/* Getter */
	Spectrometer *getObjects();

	/* Getter for specific index */
	Spectrometer getElementAt(int index);

	/* Utility method for internal use only */
	char *getClassDescriptor();

private:
	Spectrometer *data;
	JNIBridge* jni;
	EnvWrapper* localenv;
};

extern "C" {
#endif /* __cplusplus */
#ifndef EXTERN_TYPEDEF_SPECTROMETERARRAY_T
#define EXTERN_TYPEDEF_SPECTROMETERARRAY_T
	typedef void* SPECTROMETERARRAY_T;
#endif /* EXTERN_TYPEDEF_SPECTROMETERARRAY_T */

#ifndef EXTERN_TYPEDEF_SPECTROMETER_T
#define EXTERN_TYPEDEF_SPECTROMETER_T
	typedef void* SPECTROMETER_T;
#endif /* EXTERN_TYPEDEF_SPECTROMETER_T */

	EXPORTED SPECTROMETERARRAY_T SpectrometerArray_Create();
	EXPORTED SPECTROMETERARRAY_T SpectrometerArray_Create_1(SPECTROMETER_T* objects, int length);
	EXPORTED void SpectrometerArray_Destroy(SPECTROMETERARRAY_T spectrometer_array);
	EXPORTED int SpectrometerArray_getLength(SPECTROMETERARRAY_T spectrometer_array);
	EXPORTED void SpectrometerArray_setObjects(SPECTROMETERARRAY_T spectrometer_array, SPECTROMETER_T* objects, int length);
	EXPORTED void SpectrometerArray_getElementAt(SPECTROMETERARRAY_T spectrometer_array, int index, SPECTROMETER_T target);
	EXPORTED int SpectrometerArray_copyObjectsInto(SPECTROMETERARRAY_T spectrometer_array, SPECTROMETER_T* target, int length);
#ifdef __cplusplus
};
#endif /* __cplusplus */

#endif /* SPECTROMETERARRAY_H */
