/**
 * File: SpectraSplicer.h
 * Autogenerated on Mon Nov 16 11:53:52 EST 2009 based on
 * SpectraSplicer.java
 * for the Java class
 * com/oceanoptics/spam/spectralmath/SpectraSplicer
 * Copyright (C) 2006 - 2008 Ocean Optics, Inc.  All rights reserved.
 */


#ifndef SPECTRASPLICER_H
#define SPECTRASPLICER_H
#include "BaseJavaClass.h"

#ifdef __cplusplus

#ifdef INCLUDES_IN_HEADER
#endif /* INCLUDES_IN_HEADER */


CLASS_TOKEN EXPORTED SpectraSplicer : public BaseJavaClass // CPPClass.getClassDeclaration
{
public: 
	SpectraSplicer();
	ArrayOfArrays getRanges(ArrayOfArrays& wavelengths);
	unsigned char isRangeWithinWavelengths(DoubleArray& wavelengths, DoubleArray& range);
	double getClosestBeginningEndpoint(double wavelength, DoubleArray& wavelengths);
	~SpectraSplicer();
	// No public Java copy constructor; creating one:
	SpectraSplicer(const SpectraSplicer &that);
	// Creating assignment operator declaration:
	SpectraSplicer &operator=(const SpectraSplicer &that);

private:
	jmethodID mid_SpectraSplicer375;
	jmethodID mid_getRanges376;
	jmethodID mid_isRangeWithinWavelengths377;
	jmethodID mid_getClosestBeginningEndpoint378;
	void init_ids(JNIEnv* pJNIEnv);
};

extern "C" {
#endif /* __cplusplus */
#ifndef EXTERN_TYPEDEF_SPECTRASPLICER_T
#define EXTERN_TYPEDEF_SPECTRASPLICER_T
	typedef void* SPECTRASPLICER_T;
#endif /* EXTERN_TYPEDEF_SPECTRASPLICER_T */

	EXPORTED SPECTRASPLICER_T SpectraSplicer_Create();
	EXPORTED void SpectraSplicer_getRanges(SPECTRASPLICER_T c_spectra_splicer, ARRAYOFARRAYS_T wavelengths, ARRAYOFARRAYS_T retval);
	EXPORTED unsigned char SpectraSplicer_isRangeWithinWavelengths(SPECTRASPLICER_T c_spectra_splicer, DOUBLEARRAY_T wavelengths, DOUBLEARRAY_T range);
	EXPORTED double SpectraSplicer_getClosestBeginningEndpoint(SPECTRASPLICER_T c_spectra_splicer, double wavelength, DOUBLEARRAY_T wavelengths);
	EXPORTED void SpectraSplicer_Destroy(SPECTRASPLICER_T spectra_splicer);

#ifdef WIN32
	// Use the following function prototypes when calling functions from Visual Basic 6
	EXPORTED SPECTRASPLICER_T STDCALL SpectraSplicer_Create_stdcall();
	EXPORTED void STDCALL SpectraSplicer_getRanges_stdcall(SPECTRASPLICER_T c_spectra_splicer, ARRAYOFARRAYS_T wavelengths, ARRAYOFARRAYS_T retval);
	EXPORTED unsigned char STDCALL SpectraSplicer_isRangeWithinWavelengths_stdcall(SPECTRASPLICER_T c_spectra_splicer, DOUBLEARRAY_T wavelengths, DOUBLEARRAY_T range);
	EXPORTED double STDCALL SpectraSplicer_getClosestBeginningEndpoint_stdcall(SPECTRASPLICER_T c_spectra_splicer, double wavelength, DOUBLEARRAY_T wavelengths);
	EXPORTED void STDCALL SpectraSplicer_Destroy_stdcall(SPECTRASPLICER_T spectra_splicer);
#endif /* WIN32 */
#ifdef __cplusplus
};
#endif /* __cplusplus */
#endif /* SPECTRASPLICER_H */
