/**
 * File: Spectrometer.h
 * Autogenerated on Mon Nov 16 11:53:35 EST 2009 based on
 * Spectrometer.java
 * for the Java class
 * com/oceanoptics/omnidriver/spectrometer/Spectrometer
 * Copyright (C) 2006 - 2008 Ocean Optics, Inc.  All rights reserved.
 */


#ifndef SPECTROMETER_H
#define SPECTROMETER_H
#include "BaseJavaClass.h"

#ifdef __cplusplus

#ifdef INCLUDES_IN_HEADER
#include "SpectrumProducerBase.h"
#include "SpectrometerInfo.h"
#include "SpectrometerChannelArray.h"
#include "Coefficients.h"
#include "JString.h"
#endif /* INCLUDES_IN_HEADER */

/* Pre-declarations for circular dependencies in header files */
#ifdef CLASS_PREDECLARATIONS
class SpectrumProducerBase;
class SpectrometerInfo;
class SpectrometerChannelArray;
class Coefficients;
class JString;
#endif /* CLASS_PREDECLARATIONS */

CLASS_TOKEN EXPORTED Spectrometer : public SpectrumProducerBase // CPPClass.getClassDeclaration
{
public: 
	void openSpectrometer(int param0);
	Spectrometer();
	unsigned char allowWriteToEEPROM(int privilegeLevel, int slot);
	SpectrometerInfo getSpectrumBase();
	void setStabilityScan(unsigned char on);
	unsigned char isStabilityScan();
	int getIntegrationTimeMinimum();
	int getIntegrationTimeMaximum();
	int getIntegrationTimeIncrement();
	int getIntegrationTimeBase();
	int getActualIntegrationTime();
	SpectrometerChannelArray getChannels();
	int getNumberOfChannels();
	int getNumberOfEnabledChannels();
	IntArray getChannelIndices();
	unsigned char isNetworkSpectrometer();
	unsigned char isRotatorEnabled();
	void setRotatorEnabled(unsigned char rotator);
	int getBenchSlot();
	int getSpectrometerConfigSlot();
	int getDetectorSerialNumberSlot();
	int getCPLDVersionSlot();
	void getConfigurationFromSpectrometer();
	void setConfiguration();
	Coefficients getNewCoefficients(int index);
	void getCoefficientsFromSpectrometer();
	void setCoefficients();
	int getFirmwareVersionNumber();
	JString getCodeVersion(JString& fileName);
	int getMaxIntensity();
	unsigned char isStrobeDelayEnabled();
	void close();
	~Spectrometer();
	// No public Java copy constructor; creating one:
	Spectrometer(const Spectrometer &that);
	// Creating assignment operator declaration:
	Spectrometer &operator=(const Spectrometer &that);
	unsigned char rotatorEnabled;

private:
	jmethodID mid_openSpectrometer1683;
	jmethodID mid_Spectrometer1684;
	jmethodID mid_allowWriteToEEPROM1685;
	jmethodID mid_getSpectrumBase1686;
	jmethodID mid_setStabilityScan1687;
	jmethodID mid_isStabilityScan1688;
	jmethodID mid_getIntegrationTimeMinimum1689;
	jmethodID mid_getIntegrationTimeMaximum1690;
	jmethodID mid_getIntegrationTimeIncrement1691;
	jmethodID mid_getIntegrationTimeBase1692;
	jmethodID mid_getActualIntegrationTime1693;
	jmethodID mid_getChannels1694;
	jmethodID mid_getNumberOfChannels1695;
	jmethodID mid_getNumberOfEnabledChannels1696;
	jmethodID mid_getChannelIndices1697;
	jmethodID mid_isNetworkSpectrometer1698;
	jmethodID mid_isRotatorEnabled1699;
	jmethodID mid_setRotatorEnabled1700;
	jmethodID mid_getBenchSlot1701;
	jmethodID mid_getSpectrometerConfigSlot1702;
	jmethodID mid_getDetectorSerialNumberSlot1703;
	jmethodID mid_getCPLDVersionSlot1704;
	jmethodID mid_getConfigurationFromSpectrometer1705;
	jmethodID mid_setConfiguration1706;
	jmethodID mid_getNewCoefficients1707;
	jmethodID mid_getCoefficientsFromSpectrometer1708;
	jmethodID mid_setCoefficients1709;
	jmethodID mid_getFirmwareVersionNumber1710;
	jmethodID mid_getCodeVersion1711;
	jmethodID mid_getMaxIntensity1712;
	jmethodID mid_isStrobeDelayEnabled1713;
	jmethodID mid_close1714;
	jfieldID fid_channels;
	jfieldID fid_rotatorEnabled;
	void init_ids(JNIEnv* pJNIEnv);
};

extern "C" {
#endif /* __cplusplus */
#ifndef EXTERN_TYPEDEF_SPECTRUMPRODUCERBASE_T
#define EXTERN_TYPEDEF_SPECTRUMPRODUCERBASE_T
	typedef void* SPECTRUMPRODUCERBASE_T;
#endif /* EXTERN_TYPEDEF_SPECTRUMPRODUCERBASE_T */
#ifndef EXTERN_TYPEDEF_SPECTROMETERINFO_T
#define EXTERN_TYPEDEF_SPECTROMETERINFO_T
	typedef void* SPECTROMETERINFO_T;
#endif /* EXTERN_TYPEDEF_SPECTROMETERINFO_T */
#ifndef EXTERN_TYPEDEF_SPECTROMETERCHANNELARRAY_T
#define EXTERN_TYPEDEF_SPECTROMETERCHANNELARRAY_T
	typedef void* SPECTROMETERCHANNELARRAY_T;
#endif /* EXTERN_TYPEDEF_SPECTROMETERCHANNELARRAY_T */
#ifndef EXTERN_TYPEDEF_COEFFICIENTS_T
#define EXTERN_TYPEDEF_COEFFICIENTS_T
	typedef void* COEFFICIENTS_T;
#endif /* EXTERN_TYPEDEF_COEFFICIENTS_T */
#ifndef EXTERN_TYPEDEF_JSTRING_T
#define EXTERN_TYPEDEF_JSTRING_T
	typedef void* JSTRING_T;
#endif /* EXTERN_TYPEDEF_JSTRING_T */
#ifndef EXTERN_TYPEDEF_SPECTROMETER_T
#define EXTERN_TYPEDEF_SPECTROMETER_T
	typedef void* SPECTROMETER_T;
#endif /* EXTERN_TYPEDEF_SPECTROMETER_T */

	EXPORTED void Spectrometer_openSpectrometer(SPECTROMETER_T c_spectrometer, int param0);
	EXPORTED SPECTROMETER_T Spectrometer_Create();
	EXPORTED unsigned char Spectrometer_allowWriteToEEPROM(SPECTROMETER_T c_spectrometer, int privilegeLevel, int slot);
	EXPORTED void Spectrometer_getSpectrumBase(SPECTROMETER_T c_spectrometer, SPECTROMETERINFO_T retval);
	EXPORTED void Spectrometer_setStabilityScan(SPECTROMETER_T c_spectrometer, unsigned char on);
	EXPORTED unsigned char Spectrometer_isStabilityScan(SPECTROMETER_T c_spectrometer);
	EXPORTED int Spectrometer_getIntegrationTimeMinimum(SPECTROMETER_T c_spectrometer);
	EXPORTED int Spectrometer_getIntegrationTimeMaximum(SPECTROMETER_T c_spectrometer);
	EXPORTED int Spectrometer_getIntegrationTimeIncrement(SPECTROMETER_T c_spectrometer);
	EXPORTED int Spectrometer_getIntegrationTimeBase(SPECTROMETER_T c_spectrometer);
	EXPORTED int Spectrometer_getActualIntegrationTime(SPECTROMETER_T c_spectrometer);
	EXPORTED void Spectrometer_getChannels(SPECTROMETER_T c_spectrometer, SPECTROMETERCHANNELARRAY_T retval);
	EXPORTED int Spectrometer_getNumberOfChannels(SPECTROMETER_T c_spectrometer);
	EXPORTED int Spectrometer_getNumberOfEnabledChannels(SPECTROMETER_T c_spectrometer);
	EXPORTED void Spectrometer_getChannelIndices(SPECTROMETER_T c_spectrometer, INTARRAY_T retval);
	EXPORTED unsigned char Spectrometer_isNetworkSpectrometer(SPECTROMETER_T c_spectrometer);
	EXPORTED unsigned char Spectrometer_isRotatorEnabled(SPECTROMETER_T c_spectrometer);
	EXPORTED void Spectrometer_setRotatorEnabled(SPECTROMETER_T c_spectrometer, unsigned char rotator);
	EXPORTED int Spectrometer_getBenchSlot(SPECTROMETER_T c_spectrometer);
	EXPORTED int Spectrometer_getSpectrometerConfigSlot(SPECTROMETER_T c_spectrometer);
	EXPORTED int Spectrometer_getDetectorSerialNumberSlot(SPECTROMETER_T c_spectrometer);
	EXPORTED int Spectrometer_getCPLDVersionSlot(SPECTROMETER_T c_spectrometer);
	EXPORTED void Spectrometer_getConfigurationFromSpectrometer(SPECTROMETER_T c_spectrometer);
	EXPORTED void Spectrometer_setConfiguration(SPECTROMETER_T c_spectrometer);
	EXPORTED void Spectrometer_getNewCoefficients(SPECTROMETER_T c_spectrometer, int index, COEFFICIENTS_T retval);
	EXPORTED void Spectrometer_getCoefficientsFromSpectrometer(SPECTROMETER_T c_spectrometer);
	EXPORTED void Spectrometer_setCoefficients(SPECTROMETER_T c_spectrometer);
	EXPORTED int Spectrometer_getFirmwareVersionNumber(SPECTROMETER_T c_spectrometer);
	EXPORTED void Spectrometer_getCodeVersion(SPECTROMETER_T c_spectrometer, JSTRING_T fileName, JSTRING_T retval);
	EXPORTED int Spectrometer_getMaxIntensity(SPECTROMETER_T c_spectrometer);
	EXPORTED unsigned char Spectrometer_isStrobeDelayEnabled(SPECTROMETER_T c_spectrometer);
	EXPORTED void Spectrometer_close(SPECTROMETER_T c_spectrometer);
	EXPORTED void Spectrometer_Destroy(SPECTROMETER_T spectrometer);

#ifdef WIN32
	// Use the following function prototypes when calling functions from Visual Basic 6
	EXPORTED void STDCALL Spectrometer_openSpectrometer_stdcall(SPECTROMETER_T c_spectrometer, int param0);
	EXPORTED SPECTROMETER_T STDCALL Spectrometer_Create_stdcall();
	EXPORTED unsigned char STDCALL Spectrometer_allowWriteToEEPROM_stdcall(SPECTROMETER_T c_spectrometer, int privilegeLevel, int slot);
	EXPORTED void STDCALL Spectrometer_getSpectrumBase_stdcall(SPECTROMETER_T c_spectrometer, SPECTROMETERINFO_T retval);
	EXPORTED void STDCALL Spectrometer_setStabilityScan_stdcall(SPECTROMETER_T c_spectrometer, unsigned char on);
	EXPORTED unsigned char STDCALL Spectrometer_isStabilityScan_stdcall(SPECTROMETER_T c_spectrometer);
	EXPORTED int STDCALL Spectrometer_getIntegrationTimeMinimum_stdcall(SPECTROMETER_T c_spectrometer);
	EXPORTED int STDCALL Spectrometer_getIntegrationTimeMaximum_stdcall(SPECTROMETER_T c_spectrometer);
	EXPORTED int STDCALL Spectrometer_getIntegrationTimeIncrement_stdcall(SPECTROMETER_T c_spectrometer);
	EXPORTED int STDCALL Spectrometer_getIntegrationTimeBase_stdcall(SPECTROMETER_T c_spectrometer);
	EXPORTED int STDCALL Spectrometer_getActualIntegrationTime_stdcall(SPECTROMETER_T c_spectrometer);
	EXPORTED void STDCALL Spectrometer_getChannels_stdcall(SPECTROMETER_T c_spectrometer, SPECTROMETERCHANNELARRAY_T retval);
	EXPORTED int STDCALL Spectrometer_getNumberOfChannels_stdcall(SPECTROMETER_T c_spectrometer);
	EXPORTED int STDCALL Spectrometer_getNumberOfEnabledChannels_stdcall(SPECTROMETER_T c_spectrometer);
	EXPORTED void STDCALL Spectrometer_getChannelIndices_stdcall(SPECTROMETER_T c_spectrometer, INTARRAY_T retval);
	EXPORTED unsigned char STDCALL Spectrometer_isNetworkSpectrometer_stdcall(SPECTROMETER_T c_spectrometer);
	EXPORTED unsigned char STDCALL Spectrometer_isRotatorEnabled_stdcall(SPECTROMETER_T c_spectrometer);
	EXPORTED void STDCALL Spectrometer_setRotatorEnabled_stdcall(SPECTROMETER_T c_spectrometer, unsigned char rotator);
	EXPORTED int STDCALL Spectrometer_getBenchSlot_stdcall(SPECTROMETER_T c_spectrometer);
	EXPORTED int STDCALL Spectrometer_getSpectrometerConfigSlot_stdcall(SPECTROMETER_T c_spectrometer);
	EXPORTED int STDCALL Spectrometer_getDetectorSerialNumberSlot_stdcall(SPECTROMETER_T c_spectrometer);
	EXPORTED int STDCALL Spectrometer_getCPLDVersionSlot_stdcall(SPECTROMETER_T c_spectrometer);
	EXPORTED void STDCALL Spectrometer_getConfigurationFromSpectrometer_stdcall(SPECTROMETER_T c_spectrometer);
	EXPORTED void STDCALL Spectrometer_setConfiguration_stdcall(SPECTROMETER_T c_spectrometer);
	EXPORTED void STDCALL Spectrometer_getNewCoefficients_stdcall(SPECTROMETER_T c_spectrometer, int index, COEFFICIENTS_T retval);
	EXPORTED void STDCALL Spectrometer_getCoefficientsFromSpectrometer_stdcall(SPECTROMETER_T c_spectrometer);
	EXPORTED void STDCALL Spectrometer_setCoefficients_stdcall(SPECTROMETER_T c_spectrometer);
	EXPORTED int STDCALL Spectrometer_getFirmwareVersionNumber_stdcall(SPECTROMETER_T c_spectrometer);
	EXPORTED void STDCALL Spectrometer_getCodeVersion_stdcall(SPECTROMETER_T c_spectrometer, JSTRING_T fileName, JSTRING_T retval);
	EXPORTED int STDCALL Spectrometer_getMaxIntensity_stdcall(SPECTROMETER_T c_spectrometer);
	EXPORTED unsigned char STDCALL Spectrometer_isStrobeDelayEnabled_stdcall(SPECTROMETER_T c_spectrometer);
	EXPORTED void STDCALL Spectrometer_close_stdcall(SPECTROMETER_T c_spectrometer);
	EXPORTED void STDCALL Spectrometer_Destroy_stdcall(SPECTROMETER_T spectrometer);
#endif /* WIN32 */
#ifdef __cplusplus
};
#endif /* __cplusplus */
#endif /* SPECTROMETER_H */
