/**
 * File: SpectrometerChannelInfoJaz.h
 * Autogenerated on Mon Nov 16 11:53:35 EST 2009 based on
 * SpectrometerChannelInfoJaz.java
 * for the Java class
 * com/oceanoptics/omnidriver/spectra/SpectrometerChannelInfoJaz
 * Copyright (C) 2006 - 2008 Ocean Optics, Inc.  All rights reserved.
 */


#ifndef SPECTROMETERCHANNELINFOJAZ_H
#define SPECTROMETERCHANNELINFOJAZ_H
#include "BaseJavaClass.h"

#ifdef __cplusplus

#ifdef INCLUDES_IN_HEADER
#include "SpectrometerChannelInfo.h"
#include "SpectrometerInfo.h"
#include "Coefficients.h"
#include "JString.h"
#endif /* INCLUDES_IN_HEADER */

/* Pre-declarations for circular dependencies in header files */
#ifdef CLASS_PREDECLARATIONS
class SpectrometerChannelInfo;
class SpectrometerInfo;
class Coefficients;
class JString;
#endif /* CLASS_PREDECLARATIONS */

CLASS_TOKEN EXPORTED SpectrometerChannelInfoJaz : public SpectrometerChannelInfo // CPPClass.getClassDeclaration
{
public: 
	SpectrometerChannelInfoJaz(SpectrometerChannelInfo& spectrometerChannelInfo);
	SpectrometerChannelInfoJaz(SpectrometerInfo& spectrometerInfo);
	SpectrometerChannelInfoJaz(SpectrometerInfo& spectrometerInfo, DoubleArray& wavelengths, int channel, unsigned char triggerEnabled, Coefficients& coefficients, double laserWavelength, unsigned char interlock, int numberOfPixels, int numberOfDarkPixels);
	SpectrometerChannelInfoJaz(SpectrometerInfo& spectrometerInfo, DoubleArray& wavelengths, int channel, unsigned char triggerEnabled, Coefficients& coefficients, double laserWavelength, unsigned char interlock, int numberOfPixels, int numberOfDarkPixels, JString& serialNumber);
	~SpectrometerChannelInfoJaz();
	// No public default Java constructor; creating one:
	SpectrometerChannelInfoJaz();
	// No public Java copy constructor; creating one:
	SpectrometerChannelInfoJaz(const SpectrometerChannelInfoJaz &that);
	// Creating assignment operator declaration:
	SpectrometerChannelInfoJaz &operator=(const SpectrometerChannelInfoJaz &that);

private:
	jmethodID mid_SpectrometerChannelInfoJaz1549;
	jmethodID mid_SpectrometerChannelInfoJaz1550;
	jmethodID mid_SpectrometerChannelInfoJaz1551;
	jmethodID mid_SpectrometerChannelInfoJaz1552;
	void init_ids(JNIEnv* pJNIEnv);
};

extern "C" {
#endif /* __cplusplus */
#ifndef EXTERN_TYPEDEF_SPECTROMETERCHANNELINFO_T
#define EXTERN_TYPEDEF_SPECTROMETERCHANNELINFO_T
	typedef void* SPECTROMETERCHANNELINFO_T;
#endif /* EXTERN_TYPEDEF_SPECTROMETERCHANNELINFO_T */
#ifndef EXTERN_TYPEDEF_SPECTROMETERINFO_T
#define EXTERN_TYPEDEF_SPECTROMETERINFO_T
	typedef void* SPECTROMETERINFO_T;
#endif /* EXTERN_TYPEDEF_SPECTROMETERINFO_T */
#ifndef EXTERN_TYPEDEF_COEFFICIENTS_T
#define EXTERN_TYPEDEF_COEFFICIENTS_T
	typedef void* COEFFICIENTS_T;
#endif /* EXTERN_TYPEDEF_COEFFICIENTS_T */
#ifndef EXTERN_TYPEDEF_JSTRING_T
#define EXTERN_TYPEDEF_JSTRING_T
	typedef void* JSTRING_T;
#endif /* EXTERN_TYPEDEF_JSTRING_T */
#ifndef EXTERN_TYPEDEF_SPECTROMETERCHANNELINFOJAZ_T
#define EXTERN_TYPEDEF_SPECTROMETERCHANNELINFOJAZ_T
	typedef void* SPECTROMETERCHANNELINFOJAZ_T;
#endif /* EXTERN_TYPEDEF_SPECTROMETERCHANNELINFOJAZ_T */

	// No public default Java constructor; creating one:
	EXPORTED SPECTROMETERCHANNELINFOJAZ_T SpectrometerChannelInfoJaz_Create();
	EXPORTED SPECTROMETERCHANNELINFOJAZ_T SpectrometerChannelInfoJaz_Create_1(SPECTROMETERCHANNELINFO_T spectrometerChannelInfo);
	EXPORTED SPECTROMETERCHANNELINFOJAZ_T SpectrometerChannelInfoJaz_Create_2(SPECTROMETERINFO_T spectrometerInfo);
	EXPORTED SPECTROMETERCHANNELINFOJAZ_T SpectrometerChannelInfoJaz_Create_3(SPECTROMETERINFO_T spectrometerInfo, DOUBLEARRAY_T wavelengths, int channel, unsigned char triggerEnabled, COEFFICIENTS_T coefficients, double laserWavelength, unsigned char interlock, int numberOfPixels, int numberOfDarkPixels);
	EXPORTED SPECTROMETERCHANNELINFOJAZ_T SpectrometerChannelInfoJaz_Create_4(SPECTROMETERINFO_T spectrometerInfo, DOUBLEARRAY_T wavelengths, int channel, unsigned char triggerEnabled, COEFFICIENTS_T coefficients, double laserWavelength, unsigned char interlock, int numberOfPixels, int numberOfDarkPixels, JSTRING_T serialNumber);
	EXPORTED void SpectrometerChannelInfoJaz_Destroy(SPECTROMETERCHANNELINFOJAZ_T spectrometer_channel_info_jaz);

#ifdef WIN32
	// Use the following function prototypes when calling functions from Visual Basic 6
	EXPORTED SPECTROMETERCHANNELINFOJAZ_T STDCALL SpectrometerChannelInfoJaz_Create_stdcall_1(SPECTROMETERCHANNELINFO_T spectrometerChannelInfo);
	EXPORTED SPECTROMETERCHANNELINFOJAZ_T STDCALL SpectrometerChannelInfoJaz_Create_stdcall_2(SPECTROMETERINFO_T spectrometerInfo);
	EXPORTED SPECTROMETERCHANNELINFOJAZ_T STDCALL SpectrometerChannelInfoJaz_Create_stdcall_3(SPECTROMETERINFO_T spectrometerInfo, DOUBLEARRAY_T wavelengths, int channel, unsigned char triggerEnabled, COEFFICIENTS_T coefficients, double laserWavelength, unsigned char interlock, int numberOfPixels, int numberOfDarkPixels);
	EXPORTED SPECTROMETERCHANNELINFOJAZ_T STDCALL SpectrometerChannelInfoJaz_Create_stdcall_4(SPECTROMETERINFO_T spectrometerInfo, DOUBLEARRAY_T wavelengths, int channel, unsigned char triggerEnabled, COEFFICIENTS_T coefficients, double laserWavelength, unsigned char interlock, int numberOfPixels, int numberOfDarkPixels, JSTRING_T serialNumber);
	EXPORTED void STDCALL SpectrometerChannelInfoJaz_Destroy_stdcall(SPECTROMETERCHANNELINFOJAZ_T spectrometer_channel_info_jaz);
#endif /* WIN32 */
#ifdef __cplusplus
};
#endif /* __cplusplus */
#endif /* SPECTROMETERCHANNELINFOJAZ_H */
