/**
 * File: StatusGUIProvider.h
 * Autogenerated on Mon Nov 16 11:53:38 EST 2009 based on
 * StatusGUIProvider.java
 * for the Java class
 * com/oceanoptics/omnidriver/spectrometer/mmsraman/features/status/StatusGUIProvider
 * Copyright (C) 2006 - 2008 Ocean Optics, Inc.  All rights reserved.
 */


#ifndef STATUSGUIPROVIDER_H
#define STATUSGUIPROVIDER_H
#include "BaseJavaClass.h"

#ifdef __cplusplus

#ifdef INCLUDES_IN_HEADER
#endif /* INCLUDES_IN_HEADER */


CLASS_TOKEN EXPORTED StatusGUIProvider : public BaseJavaClass // CPPClass.getClassDeclaration
{
public: 
	~StatusGUIProvider();
	// No public default Java constructor; creating one:
	StatusGUIProvider();
	// No public Java copy constructor; creating one:
	StatusGUIProvider(const StatusGUIProvider &that);
	// Creating assignment operator declaration:
	StatusGUIProvider &operator=(const StatusGUIProvider &that);

private:
	void init_ids(JNIEnv* pJNIEnv);
};

extern "C" {
#endif /* __cplusplus */
#ifndef EXTERN_TYPEDEF_STATUSGUIPROVIDER_T
#define EXTERN_TYPEDEF_STATUSGUIPROVIDER_T
	typedef void* STATUSGUIPROVIDER_T;
#endif /* EXTERN_TYPEDEF_STATUSGUIPROVIDER_T */

	// No public default Java constructor; creating one:
	EXPORTED STATUSGUIPROVIDER_T StatusGUIProvider_Create();
	EXPORTED void StatusGUIProvider_Destroy(STATUSGUIPROVIDER_T status_g_u_i_provider);

#ifdef WIN32
	// Use the following function prototypes when calling functions from Visual Basic 6
	EXPORTED void STDCALL StatusGUIProvider_Destroy_stdcall(STATUSGUIPROVIDER_T status_g_u_i_provider);
#endif /* WIN32 */
#ifdef __cplusplus
};
#endif /* __cplusplus */
#endif /* STATUSGUIPROVIDER_H */
