/**
 * File: Status.h
 * Autogenerated on Mon Nov 16 11:53:38 EST 2009 based on
 * Status.java
 * for the Java class
 * com/oceanoptics/omnidriver/spectrometer/mmsraman/features/status/Status
 * Copyright (C) 2006 - 2008 Ocean Optics, Inc.  All rights reserved.
 */


#ifndef STATUS_H
#define STATUS_H
#include "BaseJavaClass.h"

#ifdef __cplusplus

#ifdef INCLUDES_IN_HEADER
#include "JStringArray.h"
#endif /* INCLUDES_IN_HEADER */

/* Pre-declarations for circular dependencies in header files */
#ifdef CLASS_PREDECLARATIONS
class JStringArray;
#endif /* CLASS_PREDECLARATIONS */

CLASS_TOKEN EXPORTED Status : public BaseJavaClass // CPPClass.getClassDeclaration
{
public: 
	JStringArray getLEDFlashCodes();
	~Status();
	// No public default Java constructor; creating one:
	Status();
	// No public Java copy constructor; creating one:
	Status(const Status &that);
	// Creating assignment operator declaration:
	Status &operator=(const Status &that);

private:
	jmethodID mid_getLEDFlashCodes2667;
	void init_ids(JNIEnv* pJNIEnv);
};

extern "C" {
#endif /* __cplusplus */
#ifndef EXTERN_TYPEDEF_JSTRINGARRAY_T
#define EXTERN_TYPEDEF_JSTRINGARRAY_T
	typedef void* JSTRINGARRAY_T;
#endif /* EXTERN_TYPEDEF_JSTRINGARRAY_T */
#ifndef EXTERN_TYPEDEF_STATUS_T
#define EXTERN_TYPEDEF_STATUS_T
	typedef void* STATUS_T;
#endif /* EXTERN_TYPEDEF_STATUS_T */

	// No public default Java constructor; creating one:
	EXPORTED STATUS_T Status_Create();
	EXPORTED void Status_getLEDFlashCodes(STATUS_T c_status, JSTRINGARRAY_T retval);
	EXPORTED void Status_Destroy(STATUS_T status);

#ifdef WIN32
	// Use the following function prototypes when calling functions from Visual Basic 6
	EXPORTED void STDCALL Status_getLEDFlashCodes_stdcall(STATUS_T c_status, JSTRINGARRAY_T retval);
	EXPORTED void STDCALL Status_Destroy_stdcall(STATUS_T status);
#endif /* WIN32 */
#ifdef __cplusplus
};
#endif /* __cplusplus */
#endif /* STATUS_H */
