/**
 * File: TakesNoParameter.h
 * Autogenerated on Mon Nov 16 11:53:29 EST 2009 based on
 * TakesNoParameter.java
 * for the Java class
 * com/oceanoptics/omnidriver/accessories/mikropack/commands/TakesNoParameter
 * Copyright (C) 2006 - 2008 Ocean Optics, Inc.  All rights reserved.
 */


#ifndef TAKESNOPARAMETER_H
#define TAKESNOPARAMETER_H
#include "BaseJavaClass.h"

#ifdef __cplusplus

#ifdef INCLUDES_IN_HEADER
#endif /* INCLUDES_IN_HEADER */


CLASS_TOKEN EXPORTED TakesNoParameter : public BaseJavaClass // CPPClass.getClassDeclaration
{
public: 
	~TakesNoParameter();
	// No public default Java constructor; creating one:
	TakesNoParameter();
	// No public Java copy constructor; creating one:
	TakesNoParameter(const TakesNoParameter &that);
	// Creating assignment operator declaration:
	TakesNoParameter &operator=(const TakesNoParameter &that);

private:
	void init_ids(JNIEnv* pJNIEnv);
};

extern "C" {
#endif /* __cplusplus */
#ifndef EXTERN_TYPEDEF_TAKESNOPARAMETER_T
#define EXTERN_TYPEDEF_TAKESNOPARAMETER_T
	typedef void* TAKESNOPARAMETER_T;
#endif /* EXTERN_TYPEDEF_TAKESNOPARAMETER_T */

	// No public default Java constructor; creating one:
	EXPORTED TAKESNOPARAMETER_T TakesNoParameter_Create();
	EXPORTED void TakesNoParameter_Destroy(TAKESNOPARAMETER_T takes_no_parameter);

#ifdef WIN32
	// Use the following function prototypes when calling functions from Visual Basic 6
	EXPORTED void STDCALL TakesNoParameter_Destroy_stdcall(TAKESNOPARAMETER_T takes_no_parameter);
#endif /* WIN32 */
#ifdef __cplusplus
};
#endif /* __cplusplus */
#endif /* TAKESNOPARAMETER_H */
