/**
 * File: USB4000.h
 * Autogenerated on Mon Nov 16 11:53:40 EST 2009 based on
 * USB4000.java
 * for the Java class
 * com/oceanoptics/omnidriver/spectrometer/usb4000/USB4000
 * Copyright (C) 2006 - 2008 Ocean Optics, Inc.  All rights reserved.
 */


#ifndef USB4000_H
#define USB4000_H
#include "BaseJavaClass.h"

#ifdef __cplusplus

#ifdef INCLUDES_IN_HEADER
#include "USBSpectrometer.h"
#include "USBEndpointDescriptor.h"
#include "GUIProviderArray.h"
#include "SpectrometerStatus.h"
#include "OmniDriverDispatchListener.h"
#include "JString.h"
#include "SpectrometerPlugInArray.h"
#include "ExternalTriggerModeArray.h"
#include "BitSet.h"
#include "CoefficientsArray.h"
#include "AutonullingConfiguration.h"
#include "AcquisitionListener.h"
#endif /* INCLUDES_IN_HEADER */

/* Pre-declarations for circular dependencies in header files */
#ifdef CLASS_PREDECLARATIONS
class USBSpectrometer;
class USBEndpointDescriptor;
class GUIProviderArray;
class SpectrometerStatus;
class OmniDriverDispatchListener;
class JString;
class SpectrometerPlugInArray;
class ExternalTriggerModeArray;
class BitSet;
class CoefficientsArray;
class AutonullingConfiguration;
class AcquisitionListener;
#endif /* CLASS_PREDECLARATIONS */

CLASS_TOKEN EXPORTED USB4000 : public USBSpectrometer // CPPClass.getClassDeclaration
{
public: 
	USB4000();
	USB4000(int i);
	void setEndpoints();
	USBEndpointDescriptor getEndpoint(int endPoint);
	unsigned char allowWriteToEEPROM(int privilegeLevel, int slot);
	void openSpectrometer(int index);
	GUIProviderArray getGUIFeatures();
	void readSpectrum(CharArray& data);
	void readSpectrum();
	SpectrometerStatus getStatus();
	int readIntegrationTime();
	void setIntegrationTime(int intTime);
	int getGatingModeIntegrationTime();
	void addOmniDriverDispatchListener(OmniDriverDispatchListener& listener);
	void removeOmniDriverDispatchListener(OmniDriverDispatchListener& listener);
	void setStrobeDelay(int delay);
	JString toString();
	SpectrometerPlugInArray getPlugIns();
	int getNumberOfPlugIns();
	unsigned char isPlugInDetected(int id);
	CharArray initializePlugIns();
	void detectPlugIns();
	int setI2CBytes(signed char address, signed char numBytes, CharArray& i2C);
	CharArray getI2CBytes(signed char address, signed char numBytes);
	CharArray getSPIBytes(CharArray& message, int length);
	JString getPSOCVersion();
	JString getFPGAFirmwareVersion();
	double continuousStrobeCountsToMicros(int counts);
	void setContinuousStrobeDelay(int delayMicros);
	int getContinuousStrobeDelayMinimum();
	int getContinuousStrobeDelayMaximum();
	int getContinuousStrobeDelayIncrement(int magnitude);
	void setAdvancedIntegrationTime(long long delayMicros);
	int getIntegrationTimeBaseClock();
	int getIntegrationClockTimer();
	long long getAdvancedIntegrationTimeMinimum();
	long long getAdvancedIntegrationTimeMaximum();
	long long getAdvancedIntegrationTimeIncrement();
	void setExternalTriggerMode(int mode);
	ExternalTriggerModeArray getExternalTriggerModes();
	void setShutterClock(int value);
	int getShutterClock();
	void setSingleStrobeLow(int value);
	void setSingleStrobeHigh(int value);
	double getSingleStrobeCountsToMicros(int counts);
	int getSingleStrobeLow();
	int getSingleStrobeHigh();
	int getSingleStrobeMinimum();
	int getSingleStrobeMaximum();
	int getSingleStrobeIncrement();
	void setDirectionAllBits(BitSet& bitSet);
	void setMuxAllBits(BitSet& bitSet);
	void setValueAllBits(BitSet& bitSet);
	void setDirectionBitmask(short bitmask);
	void setMuxBitmask(short bitmask);
	void setValueBitmask(short bitmask);
	void setDirectionBit(int bit, unsigned char value);
	void setMuxBit(int bit, unsigned char value);
	void setValueBit(int bit, unsigned char value);
	int getTotalGPIOBits();
	BitSet getDirectionBits();
	BitSet getMuxBits();
	int getValueBit(int bitNumber);
	BitSet getValueBits();
	int getNumberOfPins();
	double getBoardTemperatureCelsius();
	DoubleArray getIrradianceCalibrationFactors(signed char address);
	void setIrradianceCalibrationFactors(signed char address, DoubleArray& data);
	void setMasterClockDivisor(int value);
	int getMasterClockDivisor();
	void setExternalTriggerDelay(int counts);
	double triggerDelayCountsToMicroseconds(int counts);
	int getExternalTriggerDelayMinimum();
	int getExternalTriggerDelayMaximum();
	int getExternalTriggerDelayIncrement();
	CoefficientsArray readNonlinearityCoefficientsFromSpectrometer();
	void writeNonlinearityCoefficientsToSpectrometer(CoefficientsArray& coefficients);
	CoefficientsArray getNonlinearityCoefficients();
	void setNonlinearityCoefficients(CoefficientsArray& coefficients);
	DoubleArray getNonlinearityCoefficientsSingleChannel(int index);
	void setNonlinearityCoefficientsSingleChannel(DoubleArray& nl, int index);
	CoefficientsArray readWavelengthCalibrationCoefficientsFromSpectrometer();
	void writeWavelengthCoefficientsToSpectrometer(CoefficientsArray& coefficients);
	CoefficientsArray getWavelengthCalibrationCoefficients();
	void setWavelengthCalibrationCoefficients(CoefficientsArray& coefficients);
	DoubleArray getWavelengths(int index);
	void setWavelengths(DoubleArray& wl, int index);
	CoefficientsArray readStrayLightCorrectionCoefficientFromSpectrometer();
	void writeStrayLightCoefficientToSpectrometer(CoefficientsArray& coefficients);
	void setStrayLightCorrectionCoefficient(CoefficientsArray& coefficients);
	CoefficientsArray getStrayLightCorrectionCoefficient();
	void setStrayLight(double strayLight, int index);
	double getStrayLight(int index);
	int getAutonullingScanStatus();
	int getAutonullingScanValue();
	void setAutonullingScanStatus(int value);
	void setAutonullingScanValue(int value);
	AutonullingConfiguration getAutonullingConfiguration();
	void setAutonullingConfiguration(AutonullingConfiguration& cfg);
	void writeAutonullingConfigurationToSpectrometer();
	AutonullingConfiguration readAutonullingConfigurationFromSpectrometer();
	unsigned char isAdvancedVersion();
	void addAcquisitionListener(AcquisitionListener& listener);
	void removeAcquisitionListener(AcquisitionListener& listener);
	~USB4000();
	// No public Java copy constructor; creating one:
	USB4000(const USB4000 &that);
	// Creating assignment operator declaration:
	USB4000 &operator=(const USB4000 &that);

private:
	jmethodID mid_USB40003724;
	jmethodID mid_USB40003725;
	jmethodID mid_setEndpoints3726;
	jmethodID mid_getEndpoint3727;
	jmethodID mid_allowWriteToEEPROM3728;
	jmethodID mid_openSpectrometer3729;
	jmethodID mid_getGUIFeatures3730;
	jmethodID mid_readSpectrum3731;
	jmethodID mid_readSpectrum3732;
	jmethodID mid_getStatus3733;
	jmethodID mid_readIntegrationTime3734;
	jmethodID mid_setIntegrationTime3735;
	jmethodID mid_getGatingModeIntegrationTime3736;
	jmethodID mid_addOmniDriverDispatchListener3737;
	jmethodID mid_removeOmniDriverDispatchListener3738;
	jmethodID mid_setStrobeDelay3739;
	jmethodID mid_toString3740;
	jmethodID mid_getPlugIns3741;
	jmethodID mid_getNumberOfPlugIns3742;
	jmethodID mid_isPlugInDetected3743;
	jmethodID mid_initializePlugIns3744;
	jmethodID mid_detectPlugIns3745;
	jmethodID mid_setI2CBytes3746;
	jmethodID mid_getI2CBytes3747;
	jmethodID mid_getSPIBytes3748;
	jmethodID mid_getPSOCVersion3749;
	jmethodID mid_getFPGAFirmwareVersion3750;
	jmethodID mid_continuousStrobeCountsToMicros3751;
	jmethodID mid_setContinuousStrobeDelay3752;
	jmethodID mid_getContinuousStrobeDelayMinimum3753;
	jmethodID mid_getContinuousStrobeDelayMaximum3754;
	jmethodID mid_getContinuousStrobeDelayIncrement3755;
	jmethodID mid_setAdvancedIntegrationTime3756;
	jmethodID mid_getIntegrationTimeBaseClock3757;
	jmethodID mid_getIntegrationClockTimer3758;
	jmethodID mid_getAdvancedIntegrationTimeMinimum3759;
	jmethodID mid_getAdvancedIntegrationTimeMaximum3760;
	jmethodID mid_getAdvancedIntegrationTimeIncrement3761;
	jmethodID mid_setExternalTriggerMode3762;
	jmethodID mid_getExternalTriggerModes3763;
	jmethodID mid_setShutterClock3764;
	jmethodID mid_getShutterClock3765;
	jmethodID mid_setSingleStrobeLow3766;
	jmethodID mid_setSingleStrobeHigh3767;
	jmethodID mid_getSingleStrobeCountsToMicros3768;
	jmethodID mid_getSingleStrobeLow3769;
	jmethodID mid_getSingleStrobeHigh3770;
	jmethodID mid_getSingleStrobeMinimum3771;
	jmethodID mid_getSingleStrobeMaximum3772;
	jmethodID mid_getSingleStrobeIncrement3773;
	jmethodID mid_setDirectionAllBits3774;
	jmethodID mid_setMuxAllBits3775;
	jmethodID mid_setValueAllBits3776;
	jmethodID mid_setDirectionBitmask3777;
	jmethodID mid_setMuxBitmask3778;
	jmethodID mid_setValueBitmask3779;
	jmethodID mid_setDirectionBit3780;
	jmethodID mid_setMuxBit3781;
	jmethodID mid_setValueBit3782;
	jmethodID mid_getTotalGPIOBits3783;
	jmethodID mid_getDirectionBits3784;
	jmethodID mid_getMuxBits3785;
	jmethodID mid_getValueBit3786;
	jmethodID mid_getValueBits3787;
	jmethodID mid_getNumberOfPins3788;
	jmethodID mid_getBoardTemperatureCelsius3789;
	jmethodID mid_getIrradianceCalibrationFactors3790;
	jmethodID mid_setIrradianceCalibrationFactors3791;
	jmethodID mid_setMasterClockDivisor3792;
	jmethodID mid_getMasterClockDivisor3793;
	jmethodID mid_setExternalTriggerDelay3794;
	jmethodID mid_triggerDelayCountsToMicroseconds3795;
	jmethodID mid_getExternalTriggerDelayMinimum3796;
	jmethodID mid_getExternalTriggerDelayMaximum3797;
	jmethodID mid_getExternalTriggerDelayIncrement3798;
	jmethodID mid_readNonlinearityCoefficientsFromSpectrometer3799;
	jmethodID mid_writeNonlinearityCoefficientsToSpectrometer3800;
	jmethodID mid_getNonlinearityCoefficients3801;
	jmethodID mid_setNonlinearityCoefficients3802;
	jmethodID mid_getNonlinearityCoefficientsSingleChannel3803;
	jmethodID mid_setNonlinearityCoefficientsSingleChannel3804;
	jmethodID mid_readWavelengthCalibrationCoefficientsFromSpectrometer3805;
	jmethodID mid_writeWavelengthCoefficientsToSpectrometer3806;
	jmethodID mid_getWavelengthCalibrationCoefficients3807;
	jmethodID mid_setWavelengthCalibrationCoefficients3808;
	jmethodID mid_getWavelengths3809;
	jmethodID mid_setWavelengths3810;
	jmethodID mid_readStrayLightCorrectionCoefficientFromSpectrometer3811;
	jmethodID mid_writeStrayLightCoefficientToSpectrometer3812;
	jmethodID mid_setStrayLightCorrectionCoefficient3813;
	jmethodID mid_getStrayLightCorrectionCoefficient3814;
	jmethodID mid_setStrayLight3815;
	jmethodID mid_getStrayLight3816;
	jmethodID mid_getAutonullingScanStatus3817;
	jmethodID mid_getAutonullingScanValue3818;
	jmethodID mid_setAutonullingScanStatus3819;
	jmethodID mid_setAutonullingScanValue3820;
	jmethodID mid_getAutonullingConfiguration3821;
	jmethodID mid_setAutonullingConfiguration3822;
	jmethodID mid_writeAutonullingConfigurationToSpectrometer3823;
	jmethodID mid_readAutonullingConfigurationFromSpectrometer3824;
	jmethodID mid_isAdvancedVersion3825;
	jmethodID mid_addAcquisitionListener3826;
	jmethodID mid_removeAcquisitionListener3827;
	void init_ids(JNIEnv* pJNIEnv);
};

extern "C" {
#endif /* __cplusplus */
#ifndef EXTERN_TYPEDEF_USBSPECTROMETER_T
#define EXTERN_TYPEDEF_USBSPECTROMETER_T
	typedef void* USBSPECTROMETER_T;
#endif /* EXTERN_TYPEDEF_USBSPECTROMETER_T */
#ifndef EXTERN_TYPEDEF_USBENDPOINTDESCRIPTOR_T
#define EXTERN_TYPEDEF_USBENDPOINTDESCRIPTOR_T
	typedef void* USBENDPOINTDESCRIPTOR_T;
#endif /* EXTERN_TYPEDEF_USBENDPOINTDESCRIPTOR_T */
#ifndef EXTERN_TYPEDEF_GUIPROVIDERARRAY_T
#define EXTERN_TYPEDEF_GUIPROVIDERARRAY_T
	typedef void* GUIPROVIDERARRAY_T;
#endif /* EXTERN_TYPEDEF_GUIPROVIDERARRAY_T */
#ifndef EXTERN_TYPEDEF_SPECTROMETERSTATUS_T
#define EXTERN_TYPEDEF_SPECTROMETERSTATUS_T
	typedef void* SPECTROMETERSTATUS_T;
#endif /* EXTERN_TYPEDEF_SPECTROMETERSTATUS_T */
#ifndef EXTERN_TYPEDEF_OMNIDRIVERDISPATCHLISTENER_T
#define EXTERN_TYPEDEF_OMNIDRIVERDISPATCHLISTENER_T
	typedef void* OMNIDRIVERDISPATCHLISTENER_T;
#endif /* EXTERN_TYPEDEF_OMNIDRIVERDISPATCHLISTENER_T */
#ifndef EXTERN_TYPEDEF_JSTRING_T
#define EXTERN_TYPEDEF_JSTRING_T
	typedef void* JSTRING_T;
#endif /* EXTERN_TYPEDEF_JSTRING_T */
#ifndef EXTERN_TYPEDEF_SPECTROMETERPLUGINARRAY_T
#define EXTERN_TYPEDEF_SPECTROMETERPLUGINARRAY_T
	typedef void* SPECTROMETERPLUGINARRAY_T;
#endif /* EXTERN_TYPEDEF_SPECTROMETERPLUGINARRAY_T */
#ifndef EXTERN_TYPEDEF_EXTERNALTRIGGERMODEARRAY_T
#define EXTERN_TYPEDEF_EXTERNALTRIGGERMODEARRAY_T
	typedef void* EXTERNALTRIGGERMODEARRAY_T;
#endif /* EXTERN_TYPEDEF_EXTERNALTRIGGERMODEARRAY_T */
#ifndef EXTERN_TYPEDEF_BITSET_T
#define EXTERN_TYPEDEF_BITSET_T
	typedef void* BITSET_T;
#endif /* EXTERN_TYPEDEF_BITSET_T */
#ifndef EXTERN_TYPEDEF_COEFFICIENTSARRAY_T
#define EXTERN_TYPEDEF_COEFFICIENTSARRAY_T
	typedef void* COEFFICIENTSARRAY_T;
#endif /* EXTERN_TYPEDEF_COEFFICIENTSARRAY_T */
#ifndef EXTERN_TYPEDEF_AUTONULLINGCONFIGURATION_T
#define EXTERN_TYPEDEF_AUTONULLINGCONFIGURATION_T
	typedef void* AUTONULLINGCONFIGURATION_T;
#endif /* EXTERN_TYPEDEF_AUTONULLINGCONFIGURATION_T */
#ifndef EXTERN_TYPEDEF_ACQUISITIONLISTENER_T
#define EXTERN_TYPEDEF_ACQUISITIONLISTENER_T
	typedef void* ACQUISITIONLISTENER_T;
#endif /* EXTERN_TYPEDEF_ACQUISITIONLISTENER_T */
#ifndef EXTERN_TYPEDEF_USB4000_T
#define EXTERN_TYPEDEF_USB4000_T
	typedef void* USB4000_T;
#endif /* EXTERN_TYPEDEF_USB4000_T */

	EXPORTED USB4000_T USB4000_Create();
	EXPORTED USB4000_T USB4000_Create_1(int i);
	EXPORTED void USB4000_setEndpoints(USB4000_T c_usb4000);
	EXPORTED void USB4000_getEndpoint(USB4000_T c_usb4000, int endPoint, USBENDPOINTDESCRIPTOR_T retval);
	EXPORTED unsigned char USB4000_allowWriteToEEPROM(USB4000_T c_usb4000, int privilegeLevel, int slot);
	EXPORTED void USB4000_openSpectrometer(USB4000_T c_usb4000, int index);
	EXPORTED void USB4000_getGUIFeatures(USB4000_T c_usb4000, GUIPROVIDERARRAY_T retval);
	EXPORTED void USB4000_readSpectrum(USB4000_T c_usb4000, CHARARRAY_T data);
	EXPORTED void USB4000_readSpectrum_1(USB4000_T c_usb4000);
	EXPORTED void USB4000_getStatus(USB4000_T c_usb4000, SPECTROMETERSTATUS_T retval);
	EXPORTED int USB4000_readIntegrationTime(USB4000_T c_usb4000);
	EXPORTED void USB4000_setIntegrationTime(USB4000_T c_usb4000, int intTime);
	EXPORTED int USB4000_getGatingModeIntegrationTime(USB4000_T c_usb4000);
	EXPORTED void USB4000_addOmniDriverDispatchListener(USB4000_T c_usb4000, OMNIDRIVERDISPATCHLISTENER_T listener);
	EXPORTED void USB4000_removeOmniDriverDispatchListener(USB4000_T c_usb4000, OMNIDRIVERDISPATCHLISTENER_T listener);
	EXPORTED void USB4000_setStrobeDelay(USB4000_T c_usb4000, int delay);
	EXPORTED void USB4000_toString(USB4000_T c_usb4000, JSTRING_T retval);
	EXPORTED void USB4000_getPlugIns(USB4000_T c_usb4000, SPECTROMETERPLUGINARRAY_T retval);
	EXPORTED int USB4000_getNumberOfPlugIns(USB4000_T c_usb4000);
	EXPORTED unsigned char USB4000_isPlugInDetected(USB4000_T c_usb4000, int id);
	EXPORTED void USB4000_initializePlugIns(USB4000_T c_usb4000, CHARARRAY_T retval);
	EXPORTED void USB4000_detectPlugIns(USB4000_T c_usb4000);
	EXPORTED int USB4000_setI2CBytes(USB4000_T c_usb4000, signed char address, signed char numBytes, CHARARRAY_T i2C);
	EXPORTED void USB4000_getI2CBytes(USB4000_T c_usb4000, signed char address, signed char numBytes, CHARARRAY_T retval);
	EXPORTED void USB4000_getSPIBytes(USB4000_T c_usb4000, CHARARRAY_T message, int length, CHARARRAY_T retval);
	EXPORTED void USB4000_getPSOCVersion(USB4000_T c_usb4000, JSTRING_T retval);
	EXPORTED void USB4000_getFPGAFirmwareVersion(USB4000_T c_usb4000, JSTRING_T retval);
	EXPORTED double USB4000_continuousStrobeCountsToMicros(USB4000_T c_usb4000, int counts);
	EXPORTED void USB4000_setContinuousStrobeDelay(USB4000_T c_usb4000, int delayMicros);
	EXPORTED int USB4000_getContinuousStrobeDelayMinimum(USB4000_T c_usb4000);
	EXPORTED int USB4000_getContinuousStrobeDelayMaximum(USB4000_T c_usb4000);
	EXPORTED int USB4000_getContinuousStrobeDelayIncrement(USB4000_T c_usb4000, int magnitude);
	EXPORTED void USB4000_setAdvancedIntegrationTime(USB4000_T c_usb4000, long long delayMicros);
	EXPORTED int USB4000_getIntegrationTimeBaseClock(USB4000_T c_usb4000);
	EXPORTED int USB4000_getIntegrationClockTimer(USB4000_T c_usb4000);
	EXPORTED long long USB4000_getAdvancedIntegrationTimeMinimum(USB4000_T c_usb4000);
	EXPORTED long long USB4000_getAdvancedIntegrationTimeMaximum(USB4000_T c_usb4000);
	EXPORTED long long USB4000_getAdvancedIntegrationTimeIncrement(USB4000_T c_usb4000);
	EXPORTED void USB4000_setExternalTriggerMode(USB4000_T c_usb4000, int mode);
	EXPORTED void USB4000_getExternalTriggerModes(USB4000_T c_usb4000, EXTERNALTRIGGERMODEARRAY_T retval);
	EXPORTED void USB4000_setShutterClock(USB4000_T c_usb4000, int value);
	EXPORTED int USB4000_getShutterClock(USB4000_T c_usb4000);
	EXPORTED void USB4000_setSingleStrobeLow(USB4000_T c_usb4000, int value);
	EXPORTED void USB4000_setSingleStrobeHigh(USB4000_T c_usb4000, int value);
	EXPORTED double USB4000_getSingleStrobeCountsToMicros(USB4000_T c_usb4000, int counts);
	EXPORTED int USB4000_getSingleStrobeLow(USB4000_T c_usb4000);
	EXPORTED int USB4000_getSingleStrobeHigh(USB4000_T c_usb4000);
	EXPORTED int USB4000_getSingleStrobeMinimum(USB4000_T c_usb4000);
	EXPORTED int USB4000_getSingleStrobeMaximum(USB4000_T c_usb4000);
	EXPORTED int USB4000_getSingleStrobeIncrement(USB4000_T c_usb4000);
	EXPORTED void USB4000_setDirectionAllBits(USB4000_T c_usb4000, BITSET_T bitSet);
	EXPORTED void USB4000_setMuxAllBits(USB4000_T c_usb4000, BITSET_T bitSet);
	EXPORTED void USB4000_setValueAllBits(USB4000_T c_usb4000, BITSET_T bitSet);
	EXPORTED void USB4000_setDirectionBitmask(USB4000_T c_usb4000, short bitmask);
	EXPORTED void USB4000_setMuxBitmask(USB4000_T c_usb4000, short bitmask);
	EXPORTED void USB4000_setValueBitmask(USB4000_T c_usb4000, short bitmask);
	EXPORTED void USB4000_setDirectionBit(USB4000_T c_usb4000, int bit, unsigned char value);
	EXPORTED void USB4000_setMuxBit(USB4000_T c_usb4000, int bit, unsigned char value);
	EXPORTED void USB4000_setValueBit(USB4000_T c_usb4000, int bit, unsigned char value);
	EXPORTED int USB4000_getTotalGPIOBits(USB4000_T c_usb4000);
	EXPORTED void USB4000_getDirectionBits(USB4000_T c_usb4000, BITSET_T retval);
	EXPORTED void USB4000_getMuxBits(USB4000_T c_usb4000, BITSET_T retval);
	EXPORTED int USB4000_getValueBit(USB4000_T c_usb4000, int bitNumber);
	EXPORTED void USB4000_getValueBits(USB4000_T c_usb4000, BITSET_T retval);
	EXPORTED int USB4000_getNumberOfPins(USB4000_T c_usb4000);
	EXPORTED double USB4000_getBoardTemperatureCelsius(USB4000_T c_usb4000);
	EXPORTED void USB4000_getIrradianceCalibrationFactors(USB4000_T c_usb4000, signed char address, DOUBLEARRAY_T retval);
	EXPORTED void USB4000_setIrradianceCalibrationFactors(USB4000_T c_usb4000, signed char address, DOUBLEARRAY_T data);
	EXPORTED void USB4000_setMasterClockDivisor(USB4000_T c_usb4000, int value);
	EXPORTED int USB4000_getMasterClockDivisor(USB4000_T c_usb4000);
	EXPORTED void USB4000_setExternalTriggerDelay(USB4000_T c_usb4000, int counts);
	EXPORTED double USB4000_triggerDelayCountsToMicroseconds(USB4000_T c_usb4000, int counts);
	EXPORTED int USB4000_getExternalTriggerDelayMinimum(USB4000_T c_usb4000);
	EXPORTED int USB4000_getExternalTriggerDelayMaximum(USB4000_T c_usb4000);
	EXPORTED int USB4000_getExternalTriggerDelayIncrement(USB4000_T c_usb4000);
	EXPORTED void USB4000_readNonlinearityCoefficientsFromSpectrometer(USB4000_T c_usb4000, COEFFICIENTSARRAY_T retval);
	EXPORTED void USB4000_writeNonlinearityCoefficientsToSpectrometer(USB4000_T c_usb4000, COEFFICIENTSARRAY_T coefficients);
	EXPORTED void USB4000_getNonlinearityCoefficients(USB4000_T c_usb4000, COEFFICIENTSARRAY_T retval);
	EXPORTED void USB4000_setNonlinearityCoefficients(USB4000_T c_usb4000, COEFFICIENTSARRAY_T coefficients);
	EXPORTED void USB4000_getNonlinearityCoefficientsSingleChannel(USB4000_T c_usb4000, int index, DOUBLEARRAY_T retval);
	EXPORTED void USB4000_setNonlinearityCoefficientsSingleChannel(USB4000_T c_usb4000, DOUBLEARRAY_T nl, int index);
	EXPORTED void USB4000_readWavelengthCalibrationCoefficientsFromSpectrometer(USB4000_T c_usb4000, COEFFICIENTSARRAY_T retval);
	EXPORTED void USB4000_writeWavelengthCoefficientsToSpectrometer(USB4000_T c_usb4000, COEFFICIENTSARRAY_T coefficients);
	EXPORTED void USB4000_getWavelengthCalibrationCoefficients(USB4000_T c_usb4000, COEFFICIENTSARRAY_T retval);
	EXPORTED void USB4000_setWavelengthCalibrationCoefficients(USB4000_T c_usb4000, COEFFICIENTSARRAY_T coefficients);
	EXPORTED void USB4000_getWavelengths(USB4000_T c_usb4000, int index, DOUBLEARRAY_T retval);
	EXPORTED void USB4000_setWavelengths(USB4000_T c_usb4000, DOUBLEARRAY_T wl, int index);
	EXPORTED void USB4000_readStrayLightCorrectionCoefficientFromSpectrometer(USB4000_T c_usb4000, COEFFICIENTSARRAY_T retval);
	EXPORTED void USB4000_writeStrayLightCoefficientToSpectrometer(USB4000_T c_usb4000, COEFFICIENTSARRAY_T coefficients);
	EXPORTED void USB4000_setStrayLightCorrectionCoefficient(USB4000_T c_usb4000, COEFFICIENTSARRAY_T coefficients);
	EXPORTED void USB4000_getStrayLightCorrectionCoefficient(USB4000_T c_usb4000, COEFFICIENTSARRAY_T retval);
	EXPORTED void USB4000_setStrayLight(USB4000_T c_usb4000, double strayLight, int index);
	EXPORTED double USB4000_getStrayLight(USB4000_T c_usb4000, int index);
	EXPORTED int USB4000_getAutonullingScanStatus(USB4000_T c_usb4000);
	EXPORTED int USB4000_getAutonullingScanValue(USB4000_T c_usb4000);
	EXPORTED void USB4000_setAutonullingScanStatus(USB4000_T c_usb4000, int value);
	EXPORTED void USB4000_setAutonullingScanValue(USB4000_T c_usb4000, int value);
	EXPORTED void USB4000_getAutonullingConfiguration(USB4000_T c_usb4000, AUTONULLINGCONFIGURATION_T retval);
	EXPORTED void USB4000_setAutonullingConfiguration(USB4000_T c_usb4000, AUTONULLINGCONFIGURATION_T cfg);
	EXPORTED void USB4000_writeAutonullingConfigurationToSpectrometer(USB4000_T c_usb4000);
	EXPORTED void USB4000_readAutonullingConfigurationFromSpectrometer(USB4000_T c_usb4000, AUTONULLINGCONFIGURATION_T retval);
	EXPORTED unsigned char USB4000_isAdvancedVersion(USB4000_T c_usb4000);
	EXPORTED void USB4000_addAcquisitionListener(USB4000_T c_usb4000, ACQUISITIONLISTENER_T listener);
	EXPORTED void USB4000_removeAcquisitionListener(USB4000_T c_usb4000, ACQUISITIONLISTENER_T listener);
	EXPORTED void USB4000_Destroy(USB4000_T usb4000);

#ifdef WIN32
	// Use the following function prototypes when calling functions from Visual Basic 6
	EXPORTED USB4000_T STDCALL USB4000_Create_stdcall();
	EXPORTED USB4000_T STDCALL USB4000_Create_stdcall_1(int i);
	EXPORTED void STDCALL USB4000_setEndpoints_stdcall(USB4000_T c_usb4000);
	EXPORTED void STDCALL USB4000_getEndpoint_stdcall(USB4000_T c_usb4000, int endPoint, USBENDPOINTDESCRIPTOR_T retval);
	EXPORTED unsigned char STDCALL USB4000_allowWriteToEEPROM_stdcall(USB4000_T c_usb4000, int privilegeLevel, int slot);
	EXPORTED void STDCALL USB4000_openSpectrometer_stdcall(USB4000_T c_usb4000, int index);
	EXPORTED void STDCALL USB4000_getGUIFeatures_stdcall(USB4000_T c_usb4000, GUIPROVIDERARRAY_T retval);
	EXPORTED void STDCALL USB4000_readSpectrum_stdcall(USB4000_T c_usb4000, CHARARRAY_T data);
	EXPORTED void STDCALL USB4000_readSpectrum_stdcall_1(USB4000_T c_usb4000);
	EXPORTED void STDCALL USB4000_getStatus_stdcall(USB4000_T c_usb4000, SPECTROMETERSTATUS_T retval);
	EXPORTED int STDCALL USB4000_readIntegrationTime_stdcall(USB4000_T c_usb4000);
	EXPORTED void STDCALL USB4000_setIntegrationTime_stdcall(USB4000_T c_usb4000, int intTime);
	EXPORTED int STDCALL USB4000_getGatingModeIntegrationTime_stdcall(USB4000_T c_usb4000);
	EXPORTED void STDCALL USB4000_addOmniDriverDispatchListener_stdcall(USB4000_T c_usb4000, OMNIDRIVERDISPATCHLISTENER_T listener);
	EXPORTED void STDCALL USB4000_removeOmniDriverDispatchListener_stdcall(USB4000_T c_usb4000, OMNIDRIVERDISPATCHLISTENER_T listener);
	EXPORTED void STDCALL USB4000_setStrobeDelay_stdcall(USB4000_T c_usb4000, int delay);
	EXPORTED void STDCALL USB4000_toString_stdcall(USB4000_T c_usb4000, JSTRING_T retval);
	EXPORTED void STDCALL USB4000_getPlugIns_stdcall(USB4000_T c_usb4000, SPECTROMETERPLUGINARRAY_T retval);
	EXPORTED int STDCALL USB4000_getNumberOfPlugIns_stdcall(USB4000_T c_usb4000);
	EXPORTED unsigned char STDCALL USB4000_isPlugInDetected_stdcall(USB4000_T c_usb4000, int id);
	EXPORTED void STDCALL USB4000_initializePlugIns_stdcall(USB4000_T c_usb4000, CHARARRAY_T retval);
	EXPORTED void STDCALL USB4000_detectPlugIns_stdcall(USB4000_T c_usb4000);
	EXPORTED int STDCALL USB4000_setI2CBytes_stdcall(USB4000_T c_usb4000, signed char address, signed char numBytes, CHARARRAY_T i2C);
	EXPORTED void STDCALL USB4000_getI2CBytes_stdcall(USB4000_T c_usb4000, signed char address, signed char numBytes, CHARARRAY_T retval);
	EXPORTED void STDCALL USB4000_getSPIBytes_stdcall(USB4000_T c_usb4000, CHARARRAY_T message, int length, CHARARRAY_T retval);
	EXPORTED void STDCALL USB4000_getPSOCVersion_stdcall(USB4000_T c_usb4000, JSTRING_T retval);
	EXPORTED void STDCALL USB4000_getFPGAFirmwareVersion_stdcall(USB4000_T c_usb4000, JSTRING_T retval);
	EXPORTED double STDCALL USB4000_continuousStrobeCountsToMicros_stdcall(USB4000_T c_usb4000, int counts);
	EXPORTED void STDCALL USB4000_setContinuousStrobeDelay_stdcall(USB4000_T c_usb4000, int delayMicros);
	EXPORTED int STDCALL USB4000_getContinuousStrobeDelayMinimum_stdcall(USB4000_T c_usb4000);
	EXPORTED int STDCALL USB4000_getContinuousStrobeDelayMaximum_stdcall(USB4000_T c_usb4000);
	EXPORTED int STDCALL USB4000_getContinuousStrobeDelayIncrement_stdcall(USB4000_T c_usb4000, int magnitude);
	EXPORTED void STDCALL USB4000_setAdvancedIntegrationTime_stdcall(USB4000_T c_usb4000, long long delayMicros);
	EXPORTED int STDCALL USB4000_getIntegrationTimeBaseClock_stdcall(USB4000_T c_usb4000);
	EXPORTED int STDCALL USB4000_getIntegrationClockTimer_stdcall(USB4000_T c_usb4000);
	EXPORTED long long STDCALL USB4000_getAdvancedIntegrationTimeMinimum_stdcall(USB4000_T c_usb4000);
	EXPORTED long long STDCALL USB4000_getAdvancedIntegrationTimeMaximum_stdcall(USB4000_T c_usb4000);
	EXPORTED long long STDCALL USB4000_getAdvancedIntegrationTimeIncrement_stdcall(USB4000_T c_usb4000);
	EXPORTED void STDCALL USB4000_setExternalTriggerMode_stdcall(USB4000_T c_usb4000, int mode);
	EXPORTED void STDCALL USB4000_getExternalTriggerModes_stdcall(USB4000_T c_usb4000, EXTERNALTRIGGERMODEARRAY_T retval);
	EXPORTED void STDCALL USB4000_setShutterClock_stdcall(USB4000_T c_usb4000, int value);
	EXPORTED int STDCALL USB4000_getShutterClock_stdcall(USB4000_T c_usb4000);
	EXPORTED void STDCALL USB4000_setSingleStrobeLow_stdcall(USB4000_T c_usb4000, int value);
	EXPORTED void STDCALL USB4000_setSingleStrobeHigh_stdcall(USB4000_T c_usb4000, int value);
	EXPORTED double STDCALL USB4000_getSingleStrobeCountsToMicros_stdcall(USB4000_T c_usb4000, int counts);
	EXPORTED int STDCALL USB4000_getSingleStrobeLow_stdcall(USB4000_T c_usb4000);
	EXPORTED int STDCALL USB4000_getSingleStrobeHigh_stdcall(USB4000_T c_usb4000);
	EXPORTED int STDCALL USB4000_getSingleStrobeMinimum_stdcall(USB4000_T c_usb4000);
	EXPORTED int STDCALL USB4000_getSingleStrobeMaximum_stdcall(USB4000_T c_usb4000);
	EXPORTED int STDCALL USB4000_getSingleStrobeIncrement_stdcall(USB4000_T c_usb4000);
	EXPORTED void STDCALL USB4000_setDirectionAllBits_stdcall(USB4000_T c_usb4000, BITSET_T bitSet);
	EXPORTED void STDCALL USB4000_setMuxAllBits_stdcall(USB4000_T c_usb4000, BITSET_T bitSet);
	EXPORTED void STDCALL USB4000_setValueAllBits_stdcall(USB4000_T c_usb4000, BITSET_T bitSet);
	EXPORTED void STDCALL USB4000_setDirectionBitmask_stdcall(USB4000_T c_usb4000, short bitmask);
	EXPORTED void STDCALL USB4000_setMuxBitmask_stdcall(USB4000_T c_usb4000, short bitmask);
	EXPORTED void STDCALL USB4000_setValueBitmask_stdcall(USB4000_T c_usb4000, short bitmask);
	EXPORTED void STDCALL USB4000_setDirectionBit_stdcall(USB4000_T c_usb4000, int bit, unsigned char value);
	EXPORTED void STDCALL USB4000_setMuxBit_stdcall(USB4000_T c_usb4000, int bit, unsigned char value);
	EXPORTED void STDCALL USB4000_setValueBit_stdcall(USB4000_T c_usb4000, int bit, unsigned char value);
	EXPORTED int STDCALL USB4000_getTotalGPIOBits_stdcall(USB4000_T c_usb4000);
	EXPORTED void STDCALL USB4000_getDirectionBits_stdcall(USB4000_T c_usb4000, BITSET_T retval);
	EXPORTED void STDCALL USB4000_getMuxBits_stdcall(USB4000_T c_usb4000, BITSET_T retval);
	EXPORTED int STDCALL USB4000_getValueBit_stdcall(USB4000_T c_usb4000, int bitNumber);
	EXPORTED void STDCALL USB4000_getValueBits_stdcall(USB4000_T c_usb4000, BITSET_T retval);
	EXPORTED int STDCALL USB4000_getNumberOfPins_stdcall(USB4000_T c_usb4000);
	EXPORTED double STDCALL USB4000_getBoardTemperatureCelsius_stdcall(USB4000_T c_usb4000);
	EXPORTED void STDCALL USB4000_getIrradianceCalibrationFactors_stdcall(USB4000_T c_usb4000, signed char address, DOUBLEARRAY_T retval);
	EXPORTED void STDCALL USB4000_setIrradianceCalibrationFactors_stdcall(USB4000_T c_usb4000, signed char address, DOUBLEARRAY_T data);
	EXPORTED void STDCALL USB4000_setMasterClockDivisor_stdcall(USB4000_T c_usb4000, int value);
	EXPORTED int STDCALL USB4000_getMasterClockDivisor_stdcall(USB4000_T c_usb4000);
	EXPORTED void STDCALL USB4000_setExternalTriggerDelay_stdcall(USB4000_T c_usb4000, int counts);
	EXPORTED double STDCALL USB4000_triggerDelayCountsToMicroseconds_stdcall(USB4000_T c_usb4000, int counts);
	EXPORTED int STDCALL USB4000_getExternalTriggerDelayMinimum_stdcall(USB4000_T c_usb4000);
	EXPORTED int STDCALL USB4000_getExternalTriggerDelayMaximum_stdcall(USB4000_T c_usb4000);
	EXPORTED int STDCALL USB4000_getExternalTriggerDelayIncrement_stdcall(USB4000_T c_usb4000);
	EXPORTED void STDCALL USB4000_readNonlinearityCoefficientsFromSpectrometer_stdcall(USB4000_T c_usb4000, COEFFICIENTSARRAY_T retval);
	EXPORTED void STDCALL USB4000_writeNonlinearityCoefficientsToSpectrometer_stdcall(USB4000_T c_usb4000, COEFFICIENTSARRAY_T coefficients);
	EXPORTED void STDCALL USB4000_getNonlinearityCoefficients_stdcall(USB4000_T c_usb4000, COEFFICIENTSARRAY_T retval);
	EXPORTED void STDCALL USB4000_setNonlinearityCoefficients_stdcall(USB4000_T c_usb4000, COEFFICIENTSARRAY_T coefficients);
	EXPORTED void STDCALL USB4000_getNonlinearityCoefficientsSingleChannel_stdcall(USB4000_T c_usb4000, int index, DOUBLEARRAY_T retval);
	EXPORTED void STDCALL USB4000_setNonlinearityCoefficientsSingleChannel_stdcall(USB4000_T c_usb4000, DOUBLEARRAY_T nl, int index);
	EXPORTED void STDCALL USB4000_readWavelengthCalibrationCoefficientsFromSpectrometer_stdcall(USB4000_T c_usb4000, COEFFICIENTSARRAY_T retval);
	EXPORTED void STDCALL USB4000_writeWavelengthCoefficientsToSpectrometer_stdcall(USB4000_T c_usb4000, COEFFICIENTSARRAY_T coefficients);
	EXPORTED void STDCALL USB4000_getWavelengthCalibrationCoefficients_stdcall(USB4000_T c_usb4000, COEFFICIENTSARRAY_T retval);
	EXPORTED void STDCALL USB4000_setWavelengthCalibrationCoefficients_stdcall(USB4000_T c_usb4000, COEFFICIENTSARRAY_T coefficients);
	EXPORTED void STDCALL USB4000_getWavelengths_stdcall(USB4000_T c_usb4000, int index, DOUBLEARRAY_T retval);
	EXPORTED void STDCALL USB4000_setWavelengths_stdcall(USB4000_T c_usb4000, DOUBLEARRAY_T wl, int index);
	EXPORTED void STDCALL USB4000_readStrayLightCorrectionCoefficientFromSpectrometer_stdcall(USB4000_T c_usb4000, COEFFICIENTSARRAY_T retval);
	EXPORTED void STDCALL USB4000_writeStrayLightCoefficientToSpectrometer_stdcall(USB4000_T c_usb4000, COEFFICIENTSARRAY_T coefficients);
	EXPORTED void STDCALL USB4000_setStrayLightCorrectionCoefficient_stdcall(USB4000_T c_usb4000, COEFFICIENTSARRAY_T coefficients);
	EXPORTED void STDCALL USB4000_getStrayLightCorrectionCoefficient_stdcall(USB4000_T c_usb4000, COEFFICIENTSARRAY_T retval);
	EXPORTED void STDCALL USB4000_setStrayLight_stdcall(USB4000_T c_usb4000, double strayLight, int index);
	EXPORTED double STDCALL USB4000_getStrayLight_stdcall(USB4000_T c_usb4000, int index);
	EXPORTED int STDCALL USB4000_getAutonullingScanStatus_stdcall(USB4000_T c_usb4000);
	EXPORTED int STDCALL USB4000_getAutonullingScanValue_stdcall(USB4000_T c_usb4000);
	EXPORTED void STDCALL USB4000_setAutonullingScanStatus_stdcall(USB4000_T c_usb4000, int value);
	EXPORTED void STDCALL USB4000_setAutonullingScanValue_stdcall(USB4000_T c_usb4000, int value);
	EXPORTED void STDCALL USB4000_getAutonullingConfiguration_stdcall(USB4000_T c_usb4000, AUTONULLINGCONFIGURATION_T retval);
	EXPORTED void STDCALL USB4000_setAutonullingConfiguration_stdcall(USB4000_T c_usb4000, AUTONULLINGCONFIGURATION_T cfg);
	EXPORTED void STDCALL USB4000_writeAutonullingConfigurationToSpectrometer_stdcall(USB4000_T c_usb4000);
	EXPORTED void STDCALL USB4000_readAutonullingConfigurationFromSpectrometer_stdcall(USB4000_T c_usb4000, AUTONULLINGCONFIGURATION_T retval);
	EXPORTED unsigned char STDCALL USB4000_isAdvancedVersion_stdcall(USB4000_T c_usb4000);
	EXPORTED void STDCALL USB4000_addAcquisitionListener_stdcall(USB4000_T c_usb4000, ACQUISITIONLISTENER_T listener);
	EXPORTED void STDCALL USB4000_removeAcquisitionListener_stdcall(USB4000_T c_usb4000, ACQUISITIONLISTENER_T listener);
	EXPORTED void STDCALL USB4000_Destroy_stdcall(USB4000_T usb4000);
#endif /* WIN32 */
#ifdef __cplusplus
};
#endif /* __cplusplus */
#endif /* USB4000_H */
