/**
 * File: UV_VIS_LightSourceImpl_4000.h
 * Autogenerated on Mon Nov 16 11:53:34 EST 2009 based on
 * UV_VIS_LightSourceImpl_4000.java
 * for the Java class
 * com/oceanoptics/omnidriver/features/uvvislightsource/UV_VIS_LightSourceImpl_4000
 * Copyright (C) 2006 - 2008 Ocean Optics, Inc.  All rights reserved.
 */


#ifndef UV_VIS_LIGHTSOURCEIMPL_4000_H
#define UV_VIS_LIGHTSOURCEIMPL_4000_H
#include "BaseJavaClass.h"

#ifdef __cplusplus

#ifdef INCLUDES_IN_HEADER
#include "UV_VIS_LightSourceImpl.h"
#include "USBInterface.h"
#endif /* INCLUDES_IN_HEADER */

/* Pre-declarations for circular dependencies in header files */
#ifdef CLASS_PREDECLARATIONS
class UV_VIS_LightSourceImpl;
class USBInterface;
#endif /* CLASS_PREDECLARATIONS */

CLASS_TOKEN EXPORTED UV_VIS_LightSourceImpl_4000 : public UV_VIS_LightSourceImpl // CPPClass.getClassDeclaration
{
public: 
	UV_VIS_LightSourceImpl_4000(USBInterface& usbInt);
	~UV_VIS_LightSourceImpl_4000();
	// No public default Java constructor; creating one:
	UV_VIS_LightSourceImpl_4000();
	// No public Java copy constructor; creating one:
	UV_VIS_LightSourceImpl_4000(const UV_VIS_LightSourceImpl_4000 &that);
	// Creating assignment operator declaration:
	UV_VIS_LightSourceImpl_4000 &operator=(const UV_VIS_LightSourceImpl_4000 &that);

private:
	jmethodID mid_UV_VIS_LightSourceImpl_40001157;
	void init_ids(JNIEnv* pJNIEnv);
};

extern "C" {
#endif /* __cplusplus */
#ifndef EXTERN_TYPEDEF_UV_VIS_LIGHTSOURCEIMPL_T
#define EXTERN_TYPEDEF_UV_VIS_LIGHTSOURCEIMPL_T
	typedef void* UV_VIS_LIGHTSOURCEIMPL_T;
#endif /* EXTERN_TYPEDEF_UV_VIS_LIGHTSOURCEIMPL_T */
#ifndef EXTERN_TYPEDEF_USBINTERFACE_T
#define EXTERN_TYPEDEF_USBINTERFACE_T
	typedef void* USBINTERFACE_T;
#endif /* EXTERN_TYPEDEF_USBINTERFACE_T */
#ifndef EXTERN_TYPEDEF_UV_VIS_LIGHTSOURCEIMPL_4000_T
#define EXTERN_TYPEDEF_UV_VIS_LIGHTSOURCEIMPL_4000_T
	typedef void* UV_VIS_LIGHTSOURCEIMPL_4000_T;
#endif /* EXTERN_TYPEDEF_UV_VIS_LIGHTSOURCEIMPL_4000_T */

	// No public default Java constructor; creating one:
	EXPORTED UV_VIS_LIGHTSOURCEIMPL_4000_T UV_VIS_LightSourceImpl_4000_Create();
	EXPORTED UV_VIS_LIGHTSOURCEIMPL_4000_T UV_VIS_LightSourceImpl_4000_Create_1(USBINTERFACE_T usbInt);
	EXPORTED void UV_VIS_LightSourceImpl_4000_Destroy(UV_VIS_LIGHTSOURCEIMPL_4000_T uv_vis_lightsourceimpl_4000);

#ifdef WIN32
	// Use the following function prototypes when calling functions from Visual Basic 6
	EXPORTED UV_VIS_LIGHTSOURCEIMPL_4000_T STDCALL UV_VIS_LightSourceImpl_4000_Create_stdcall_1(USBINTERFACE_T usbInt);
	EXPORTED void STDCALL UV_VIS_LightSourceImpl_4000_Destroy_stdcall(UV_VIS_LIGHTSOURCEIMPL_4000_T uv_vis_lightsourceimpl_4000);
#endif /* WIN32 */
#ifdef __cplusplus
};
#endif /* __cplusplus */
#endif /* UV_VIS_LIGHTSOURCEIMPL_4000_H */
