/**
 * File: VersionImpl.h
 * Autogenerated on Mon Nov 16 11:53:34 EST 2009 based on
 * VersionImpl.java
 * for the Java class
 * com/oceanoptics/omnidriver/features/version/VersionImpl
 * Copyright (C) 2006 - 2008 Ocean Optics, Inc.  All rights reserved.
 */


#ifndef VERSIONIMPL_H
#define VERSIONIMPL_H
#include "BaseJavaClass.h"

#ifdef __cplusplus

#ifdef INCLUDES_IN_HEADER
#include "AdvancedVersionImpl.h"
#include "USBInterface.h"
#include "Spectrometer.h"
#include "JString.h"
#include "JStringArray.h"
#include "AcquisitionListener.h"
#endif /* INCLUDES_IN_HEADER */

/* Pre-declarations for circular dependencies in header files */
#ifdef CLASS_PREDECLARATIONS
class AdvancedVersionImpl;
class USBInterface;
class Spectrometer;
class JString;
class JStringArray;
class AcquisitionListener;
#endif /* CLASS_PREDECLARATIONS */

CLASS_TOKEN EXPORTED VersionImpl : public AdvancedVersionImpl // CPPClass.getClassDeclaration
{
public: 
	VersionImpl(USBInterface& usbInt, Spectrometer& spectrometer);
	unsigned char isAdvancedVersion();
	JString getFirmwareVersion();
	JStringArray getFeatureGUIClassnames();
	void addAcquisitionListener(AcquisitionListener& listener);
	void removeAcquisitionListener(AcquisitionListener& listener);
	~VersionImpl();
	// No public default Java constructor; creating one:
	VersionImpl();
	// No public Java copy constructor; creating one:
	VersionImpl(const VersionImpl &that);
	// Creating assignment operator declaration:
	VersionImpl &operator=(const VersionImpl &that);

private:
	jmethodID mid_VersionImpl1172;
	jmethodID mid_isAdvancedVersion1173;
	jmethodID mid_getFirmwareVersion1174;
	jmethodID mid_getFeatureGUIClassnames1175;
	jmethodID mid_addAcquisitionListener1176;
	jmethodID mid_removeAcquisitionListener1177;
	void init_ids(JNIEnv* pJNIEnv);
};

extern "C" {
#endif /* __cplusplus */
#ifndef EXTERN_TYPEDEF_ADVANCEDVERSIONIMPL_T
#define EXTERN_TYPEDEF_ADVANCEDVERSIONIMPL_T
	typedef void* ADVANCEDVERSIONIMPL_T;
#endif /* EXTERN_TYPEDEF_ADVANCEDVERSIONIMPL_T */
#ifndef EXTERN_TYPEDEF_USBINTERFACE_T
#define EXTERN_TYPEDEF_USBINTERFACE_T
	typedef void* USBINTERFACE_T;
#endif /* EXTERN_TYPEDEF_USBINTERFACE_T */
#ifndef EXTERN_TYPEDEF_SPECTROMETER_T
#define EXTERN_TYPEDEF_SPECTROMETER_T
	typedef void* SPECTROMETER_T;
#endif /* EXTERN_TYPEDEF_SPECTROMETER_T */
#ifndef EXTERN_TYPEDEF_JSTRING_T
#define EXTERN_TYPEDEF_JSTRING_T
	typedef void* JSTRING_T;
#endif /* EXTERN_TYPEDEF_JSTRING_T */
#ifndef EXTERN_TYPEDEF_JSTRINGARRAY_T
#define EXTERN_TYPEDEF_JSTRINGARRAY_T
	typedef void* JSTRINGARRAY_T;
#endif /* EXTERN_TYPEDEF_JSTRINGARRAY_T */
#ifndef EXTERN_TYPEDEF_ACQUISITIONLISTENER_T
#define EXTERN_TYPEDEF_ACQUISITIONLISTENER_T
	typedef void* ACQUISITIONLISTENER_T;
#endif /* EXTERN_TYPEDEF_ACQUISITIONLISTENER_T */
#ifndef EXTERN_TYPEDEF_VERSIONIMPL_T
#define EXTERN_TYPEDEF_VERSIONIMPL_T
	typedef void* VERSIONIMPL_T;
#endif /* EXTERN_TYPEDEF_VERSIONIMPL_T */

	// No public default Java constructor; creating one:
	EXPORTED VERSIONIMPL_T VersionImpl_Create();
	EXPORTED VERSIONIMPL_T VersionImpl_Create_1(USBINTERFACE_T usbInt, SPECTROMETER_T spectrometer);
	EXPORTED unsigned char VersionImpl_isAdvancedVersion(VERSIONIMPL_T c_version_impl);
	EXPORTED void VersionImpl_getFirmwareVersion(VERSIONIMPL_T c_version_impl, JSTRING_T retval);
	EXPORTED void VersionImpl_getFeatureGUIClassnames(VERSIONIMPL_T c_version_impl, JSTRINGARRAY_T retval);
	EXPORTED void VersionImpl_addAcquisitionListener(VERSIONIMPL_T c_version_impl, ACQUISITIONLISTENER_T listener);
	EXPORTED void VersionImpl_removeAcquisitionListener(VERSIONIMPL_T c_version_impl, ACQUISITIONLISTENER_T listener);
	EXPORTED void VersionImpl_Destroy(VERSIONIMPL_T version_impl);

#ifdef WIN32
	// Use the following function prototypes when calling functions from Visual Basic 6
	EXPORTED VERSIONIMPL_T STDCALL VersionImpl_Create_stdcall_1(USBINTERFACE_T usbInt, SPECTROMETER_T spectrometer);
	EXPORTED unsigned char STDCALL VersionImpl_isAdvancedVersion_stdcall(VERSIONIMPL_T c_version_impl);
	EXPORTED void STDCALL VersionImpl_getFirmwareVersion_stdcall(VERSIONIMPL_T c_version_impl, JSTRING_T retval);
	EXPORTED void STDCALL VersionImpl_getFeatureGUIClassnames_stdcall(VERSIONIMPL_T c_version_impl, JSTRINGARRAY_T retval);
	EXPORTED void STDCALL VersionImpl_addAcquisitionListener_stdcall(VERSIONIMPL_T c_version_impl, ACQUISITIONLISTENER_T listener);
	EXPORTED void STDCALL VersionImpl_removeAcquisitionListener_stdcall(VERSIONIMPL_T c_version_impl, ACQUISITIONLISTENER_T listener);
	EXPORTED void STDCALL VersionImpl_Destroy_stdcall(VERSIONIMPL_T version_impl);
#endif /* WIN32 */
#ifdef __cplusplus
};
#endif /* __cplusplus */
#endif /* VERSIONIMPL_H */
