/**
 * File: WavelengthCalibrationGUIProvider.h
 * Autogenerated on Mon Nov 16 11:53:34 EST 2009 based on
 * WavelengthCalibrationGUIProvider.java
 * for the Java class
 * com/oceanoptics/omnidriver/features/wavelengthcalibration/WavelengthCalibrationGUIProvider
 * Copyright (C) 2006 - 2008 Ocean Optics, Inc.  All rights reserved.
 */


#ifndef WAVELENGTHCALIBRATIONGUIPROVIDER_H
#define WAVELENGTHCALIBRATIONGUIPROVIDER_H
#include "BaseJavaClass.h"

#ifdef __cplusplus

#ifdef INCLUDES_IN_HEADER
#endif /* INCLUDES_IN_HEADER */


CLASS_TOKEN EXPORTED WavelengthCalibrationGUIProvider : public BaseJavaClass // CPPClass.getClassDeclaration
{
public: 
	~WavelengthCalibrationGUIProvider();
	// No public default Java constructor; creating one:
	WavelengthCalibrationGUIProvider();
	// No public Java copy constructor; creating one:
	WavelengthCalibrationGUIProvider(const WavelengthCalibrationGUIProvider &that);
	// Creating assignment operator declaration:
	WavelengthCalibrationGUIProvider &operator=(const WavelengthCalibrationGUIProvider &that);

private:
	void init_ids(JNIEnv* pJNIEnv);
};

extern "C" {
#endif /* __cplusplus */
#ifndef EXTERN_TYPEDEF_WAVELENGTHCALIBRATIONGUIPROVIDER_T
#define EXTERN_TYPEDEF_WAVELENGTHCALIBRATIONGUIPROVIDER_T
	typedef void* WAVELENGTHCALIBRATIONGUIPROVIDER_T;
#endif /* EXTERN_TYPEDEF_WAVELENGTHCALIBRATIONGUIPROVIDER_T */

	// No public default Java constructor; creating one:
	EXPORTED WAVELENGTHCALIBRATIONGUIPROVIDER_T WavelengthCalibrationGUIProvider_Create();
	EXPORTED void WavelengthCalibrationGUIProvider_Destroy(WAVELENGTHCALIBRATIONGUIPROVIDER_T wavelength_calibration_g_u_i_provider);

#ifdef WIN32
	// Use the following function prototypes when calling functions from Visual Basic 6
	EXPORTED void STDCALL WavelengthCalibrationGUIProvider_Destroy_stdcall(WAVELENGTHCALIBRATIONGUIPROVIDER_T wavelength_calibration_g_u_i_provider);
#endif /* WIN32 */
#ifdef __cplusplus
};
#endif /* __cplusplus */
#endif /* WAVELENGTHCALIBRATIONGUIPROVIDER_H */
