/**
 * File: Wrapper.h
 * Autogenerated on Mon Nov 16 11:53:30 EST 2009 based on
 * Wrapper.java
 * for the Java class
 * com/oceanoptics/omnidriver/api/wrapper/Wrapper
 * Copyright (C) 2006 - 2008 Ocean Optics, Inc.  All rights reserved.
 */


#ifndef WRAPPER_H
#define WRAPPER_H
#include "BaseJavaClass.h"

#ifdef __cplusplus

#ifdef INCLUDES_IN_HEADER
#include "WrapperExtensions.h"
#include "JString.h"
#include "Bench.h"
#include "Coefficients.h"
#include "GPIO.h"
#include "SPIBus.h"
#include "SingleStrobe.h"
#include "ContinuousStrobe.h"
#include "CurrentOut.h"
#include "BoardTemperature.h"
#include "AnalogIn.h"
#include "AnalogOut.h"
#include "ExternalTriggerDelay.h"
#include "I2CBus.h"
#include "HighGainMode.h"
#include "IrradianceCalibrationFactor.h"
#include "LS450_Functions.h"
#include "UV_VIS_LightSource.h"
#include "NonlinearityCorrectionProvider.h"
#include "StrayLightCorrection.h"
#include "Version.h"
#include "WavelengthCalibrationProvider.h"
#include "ThermoElectric.h"
#include "HighResTimeStamp.h"
#include "JStringArray.h"
#endif /* INCLUDES_IN_HEADER */

/* Pre-declarations for circular dependencies in header files */
#ifdef CLASS_PREDECLARATIONS
class WrapperExtensions;
class JString;
class Bench;
class Coefficients;
class GPIO;
class SPIBus;
class SingleStrobe;
class ContinuousStrobe;
class CurrentOut;
class BoardTemperature;
class AnalogIn;
class AnalogOut;
class ExternalTriggerDelay;
class I2CBus;
class HighGainMode;
class IrradianceCalibrationFactor;
class LS450_Functions;
class UV_VIS_LightSource;
class NonlinearityCorrectionProvider;
class StrayLightCorrection;
class Version;
class WavelengthCalibrationProvider;
class ThermoElectric;
class HighResTimeStamp;
class JStringArray;
#endif /* CLASS_PREDECLARATIONS */

CLASS_TOKEN EXPORTED Wrapper : public BaseJavaClass // CPPClass.getClassDeclaration
{
public: 
	Wrapper();
	WrapperExtensions getWrapperExtensions();
	unsigned char exportToGramsSPC(int spectrometerIndex, JString& outputPathname, DoubleArray& pixels, JString& username);
	unsigned char exportToGramsSPC(int spectrometerIndex, int channelIndex, JString& outputPathname, DoubleArray& pixels, JString& username);
	JString getApiVersion();
	int getBuildNumber();
	JString getLastException();
	JString getLastExceptionStackTrace();
	int openNetworkSpectrometer(JString& ipAddress);
	int openAllSpectrometers();
	JString getName(int spectrometerIndex);
	int getMaximumIntegrationTime(int spectrometerIndex);
	int getMinimumIntegrationTime(int spectrometerIndex);
	int getMaximumIntensity(int spectrometerIndex);
	int getNumberOfSpectrometersFound();
	JString getFirmwareVersion(int spectrometerIndex);
	JString getSerialNumber(int spectrometerIndex);
	int getNumberOfPixels(int spectrometerIndex);
	int getNumberOfPixels(int spectrometerIndex, int channelIndex);
	int getNumberOfDarkPixels(int spectrometerIndex);
	int getNumberOfDarkPixels(int spectrometerIndex, int channelIndex);
	void setIntegrationTime(int spectrometerIndex, int usec);
	void setIntegrationTime(int spectrometerIndex, int channelIndex, int usec);
	int getIntegrationTime(int spectrometerIndex);
	int getIntegrationTime(int spectrometerIndex, int channelIndex);
	void setScansToAverage(int spectrometerIndex, int numberOfScansToAverage);
	void setScansToAverage(int spectrometerIndex, int channelIndex, int numberOfScansToAverage);
	int getScansToAverage(int spectrometerIndex);
	int getScansToAverage(int spectrometerIndex, int channelIndex);
	Bench getBench(int spectrometerIndex);
	Bench getBench(int spectrometerIndex, int channelIndex);
	void setBoxcarWidth(int spectrometerIndex, int numberOfPixelsOnEitherSideOfCenter);
	void setBoxcarWidth(int spectrometerIndex, int channelIndex, int numberOfPixelsOnEitherSideOfCenter);
	int getBoxcarWidth(int spectrometerIndex);
	int getBoxcarWidth(int spectrometerIndex, int channelIndex);
	unsigned char insertKey(JString& keyValue);
	void removeKey();
	Coefficients getCalibrationCoefficientsFromBuffer(int spectrometerIndex);
	Coefficients getCalibrationCoefficientsFromBuffer(int spectrometerIndex, int channelIndex);
	Coefficients getCalibrationCoefficientsFromEEProm(int spectrometerIndex);
	Coefficients getCalibrationCoefficientsFromEEProm(int spectrometerIndex, int channelIndex);
	unsigned char setCalibrationCoefficientsIntoBuffer(int spectrometerIndex, Coefficients& coefficients, unsigned char applyWavelengthCoefficients, unsigned char applyStrayLightConstant, unsigned char applyNonlinearityCoefficients);
	unsigned char setCalibrationCoefficientsIntoBuffer(int spectrometerIndex, int channelIndex, Coefficients& newCoefficients, unsigned char applyWavelengthCoefficients, unsigned char applyStrayLightConstant, unsigned char applyNonlinearityCoefficients);
	unsigned char setCalibrationCoefficientsIntoEEProm(int spectrometerIndex, Coefficients& coefficients, unsigned char applyWavelengthCoefficients, unsigned char applyStrayLightConstant, unsigned char applyNonlinearityCoefficients);
	unsigned char setCalibrationCoefficientsIntoEEProm(int spectrometerIndex, int channelIndex, Coefficients& newCoefficients, unsigned char applyWavelengthCoefficients, unsigned char applyStrayLightConstants, unsigned char applyNonlinearityCoefficients);
	JString getEEPromInfo(int spectrometerIndex, int slot);
	unsigned char setEEPromInfo(int spectrometerIndex, int slot, JString& str);
	unsigned char setDetectorSetPointCelsius(int spectrometerIndex, double temperatureCelsius);
	void setExternalTriggerMode(int spectrometerIndex, int mode);
	void setExternalTriggerMode(int spectrometerIndex, int channelIndex, int mode);
	int getExternalTriggerMode(int spectrometerIndex);
	int getExternalTriggerMode(int spectrometerIndex, int channelIndex);
	void setCorrectForElectricalDark(int spectrometerIndex, int enable);
	void setCorrectForElectricalDark(int spectrometerIndex, int channelIndex, int enable);
	unsigned char getCorrectForElectricalDark(int spectrometerIndex);
	unsigned char getCorrectForElectricalDark(int spectrometerIndex, int channelIndex);
	unsigned char getCorrectForStrayLight(int spectrometerIndex);
	unsigned char getCorrectForStrayLight(int spectrometerIndex, int channelIndex);
	unsigned char setCorrectForDetectorNonlinearity(int spectrometerIndex, int enable);
	unsigned char setCorrectForDetectorNonlinearity(int spectrometerIndex, int channelIndex, int enable);
	unsigned char getCorrectForDetectorNonlinearity(int spectrometerIndex);
	unsigned char getCorrectForDetectorNonlinearity(int spectrometerIndex, int channelIndex);
	void setStrobeEnable(int spectrometerIndex, int lampOn);
	void setStrobeEnable(int spectrometerIndex, int channelIndex, int lampOn);
	int getStrobeEnable(int spectrometerIndex);
	int getStrobeEnable(int spectrometerIndex, int channelIndex);
	double getWavelength(int spectrometerIndex, int pixel);
	double getWavelength(int spectrometerIndex, int channelIndex, int pixel);
	DoubleArray getWavelengths(int spectrometerIndex);
	DoubleArray getWavelengths(int spectrometerIndex, int channelIndex);
	double getWavelengthIntercept(int spectrometerIndex);
	double getWavelengthIntercept(int spectrometerIndex, int channelIndex);
	double getWavelengthFirst(int spectrometerIndex);
	double getWavelengthFirst(int spectrometerIndex, int channelIndex);
	double getWavelengthSecond(int spectrometerIndex);
	double getWavelengthSecond(int spectrometerIndex, int channelIndex);
	double getWavelengthThird(int spectrometerIndex);
	double getWavelengthThird(int spectrometerIndex, int channelIndex);
	DoubleArray getSpectrum(int spectrometerIndex);
	DoubleArray getSpectrum(int spectrometerIndex, int channelIndex);
	void stopAveraging(int spectrometerIndex);
	void stopAveraging(int spectrometerIndex, int channelIndex);
	unsigned char isSaturated(int spectrometerIndex);
	unsigned char isSaturated(int spectrometerIndex, int channelIndex);
	void closeAllSpectrometers();
	void closeSpectrometer(int spectrometerIndex);
	GPIO getFeatureControllerGPIO(int spectrometerIndex);
	unsigned char isFeatureSupportedGPIO(int spectrometerIndex);
	SPIBus getFeatureControllerSPIBus(int spectrometerIndex);
	unsigned char isFeatureSupportedSPIBus(int spectrometerIndex);
	SingleStrobe getFeatureControllerSingleStrobe(int spectrometerIndex);
	unsigned char isFeatureSupportedSingleStrobe(int spectrometerIndex);
	ContinuousStrobe getFeatureControllerContinuousStrobe(int spectrometerIndex);
	unsigned char isFeatureSupportedContinuousStrobe(int spectrometerIndex);
	CurrentOut getFeatureControllerCurrentOut(int spectrometerIndex);
	unsigned char isFeatureSupportedCurrentOut(int spectrometerIndex);
	BoardTemperature getFeatureControllerBoardTemperature(int spectrometerIndex);
	unsigned char isFeatureSupportedBoardTemperature(int spectrometerIndex);
	AnalogIn getFeatureControllerAnalogIn(int spectrometerIndex);
	unsigned char isFeatureSupportedAnalogIn(int spectrometerIndex);
	AnalogOut getFeatureControllerAnalogOut(int spectrometerIndex);
	unsigned char isFeatureSupportedAnalogOut(int spectrometerIndex);
	ExternalTriggerDelay getFeatureControllerExternalTriggerDelay(int spectrometerIndex);
	unsigned char isFeatureSupportedExternalTriggerDelay(int spectrometerIndex);
	I2CBus getFeatureControllerI2CBus(int spectrometerIndex);
	unsigned char isFeatureSupportedI2CBus(int spectrometerIndex);
	HighGainMode getFeatureControllerHighGainMode(int spectrometerIndex);
	unsigned char isFeatureSupportedHighGainMode(int spectrometerIndex);
	IrradianceCalibrationFactor getFeatureControllerIrradianceCalibrationFactor(int spectrometerIndex);
	unsigned char isFeatureSupportedIrradianceCalibrationFactor(int spectrometerIndex);
	LS450_Functions getFeatureControllerLS450(int spectrometerIndex);
	unsigned char isFeatureSupportedLS450(int spectrometerIndex);
	UV_VIS_LightSource getFeatureController_UV_VIS_LightSource(int spectrometerIndex);
	unsigned char isFeatureSupported_UV_VIS_LightSource(int spectrometerIndex);
	NonlinearityCorrectionProvider getFeatureControllerNonlinearityCorrectionProvider(int spectrometerIndex);
	unsigned char isFeatureSupportedNonlinearityCorrectionProvider(int spectrometerIndex);
	StrayLightCorrection getFeatureControllerStrayLightCorrection(int spectrometerIndex);
	unsigned char isFeatureSupportedStrayLightCorrection(int spectrometerIndex);
	Version getFeatureControllerVersion(int spectrometerIndex);
	unsigned char isFeatureSupportedVersion(int spectrometerIndex);
	WavelengthCalibrationProvider getFeatureControllerWavelengthCalibrationProvider(int spectrometerIndex);
	unsigned char isFeatureSupportedWavelengthCalibrationProvider(int spectrometerIndex);
	ThermoElectric getFeatureControllerThermoElectric(int spectrometerIndex);
	unsigned char isFeatureSupportedThermoElectric(int spectrometerIndex);
	void setAutoToggleStrobeLampEnable(int spectrometerIndex, unsigned char enable);
	void setAutoToggleStrobeLampEnable(int spectrometerIndex, int channelIndex, unsigned char enable);
	void highSpdAcq_AllocateBuffer(int spectrometerIndex, int numberOfSpectra);
	void highSpdAcq_StartAcquisition(int spectrometerIndex);
	void highSpdAcq_StartAcquisition(int spectrometerIndex, int channelIndex);
	void highSpdAcq_StopAcquisition();
	int highSpdAcq_GetNumberOfSpectraAcquired();
	DoubleArray highSpdAcq_GetSpectrum(int spectrumNumber);
	unsigned char highSpdAcq_IsSaturated(int spectrumNumber);
	HighResTimeStamp highSpdAcq_GetTimeStamp(int spectrumNumber);
	void main(JStringArray& args);
	~Wrapper();
	// No public Java copy constructor; creating one:
	Wrapper(const Wrapper &that);
	// Creating assignment operator declaration:
	Wrapper &operator=(const Wrapper &that);

private:
	jmethodID mid_Wrapper279;
	jmethodID mid_getWrapperExtensions280;
	jmethodID mid_exportToGramsSPC281;
	jmethodID mid_exportToGramsSPC282;
	jmethodID mid_getApiVersion283;
	jmethodID mid_getBuildNumber284;
	jmethodID mid_getLastException285;
	jmethodID mid_getLastExceptionStackTrace286;
	jmethodID mid_openNetworkSpectrometer287;
	jmethodID mid_openAllSpectrometers288;
	jmethodID mid_getName289;
	jmethodID mid_getMaximumIntegrationTime290;
	jmethodID mid_getMinimumIntegrationTime291;
	jmethodID mid_getMaximumIntensity292;
	jmethodID mid_getNumberOfSpectrometersFound293;
	jmethodID mid_getFirmwareVersion294;
	jmethodID mid_getSerialNumber295;
	jmethodID mid_getNumberOfPixels296;
	jmethodID mid_getNumberOfPixels297;
	jmethodID mid_getNumberOfDarkPixels298;
	jmethodID mid_getNumberOfDarkPixels299;
	jmethodID mid_setIntegrationTime300;
	jmethodID mid_setIntegrationTime301;
	jmethodID mid_getIntegrationTime302;
	jmethodID mid_getIntegrationTime303;
	jmethodID mid_setScansToAverage304;
	jmethodID mid_setScansToAverage305;
	jmethodID mid_getScansToAverage306;
	jmethodID mid_getScansToAverage307;
	jmethodID mid_getBench308;
	jmethodID mid_getBench309;
	jmethodID mid_setBoxcarWidth310;
	jmethodID mid_setBoxcarWidth311;
	jmethodID mid_getBoxcarWidth312;
	jmethodID mid_getBoxcarWidth313;
	jmethodID mid_insertKey314;
	jmethodID mid_removeKey315;
	jmethodID mid_getCalibrationCoefficientsFromBuffer316;
	jmethodID mid_getCalibrationCoefficientsFromBuffer317;
	jmethodID mid_getCalibrationCoefficientsFromEEProm318;
	jmethodID mid_getCalibrationCoefficientsFromEEProm319;
	jmethodID mid_setCalibrationCoefficientsIntoBuffer320;
	jmethodID mid_setCalibrationCoefficientsIntoBuffer321;
	jmethodID mid_setCalibrationCoefficientsIntoEEProm322;
	jmethodID mid_setCalibrationCoefficientsIntoEEProm323;
	jmethodID mid_getEEPromInfo324;
	jmethodID mid_setEEPromInfo325;
	jmethodID mid_setDetectorSetPointCelsius326;
	jmethodID mid_setExternalTriggerMode327;
	jmethodID mid_setExternalTriggerMode328;
	jmethodID mid_getExternalTriggerMode329;
	jmethodID mid_getExternalTriggerMode330;
	jmethodID mid_setCorrectForElectricalDark331;
	jmethodID mid_setCorrectForElectricalDark332;
	jmethodID mid_getCorrectForElectricalDark333;
	jmethodID mid_getCorrectForElectricalDark334;
	jmethodID mid_getCorrectForStrayLight335;
	jmethodID mid_getCorrectForStrayLight336;
	jmethodID mid_setCorrectForDetectorNonlinearity337;
	jmethodID mid_setCorrectForDetectorNonlinearity338;
	jmethodID mid_getCorrectForDetectorNonlinearity339;
	jmethodID mid_getCorrectForDetectorNonlinearity340;
	jmethodID mid_setStrobeEnable341;
	jmethodID mid_setStrobeEnable342;
	jmethodID mid_getStrobeEnable343;
	jmethodID mid_getStrobeEnable344;
	jmethodID mid_getWavelength345;
	jmethodID mid_getWavelength346;
	jmethodID mid_getWavelengths347;
	jmethodID mid_getWavelengths348;
	jmethodID mid_getWavelengthIntercept349;
	jmethodID mid_getWavelengthIntercept350;
	jmethodID mid_getWavelengthFirst351;
	jmethodID mid_getWavelengthFirst352;
	jmethodID mid_getWavelengthSecond353;
	jmethodID mid_getWavelengthSecond354;
	jmethodID mid_getWavelengthThird355;
	jmethodID mid_getWavelengthThird356;
	jmethodID mid_getSpectrum357;
	jmethodID mid_getSpectrum358;
	jmethodID mid_stopAveraging359;
	jmethodID mid_stopAveraging360;
	jmethodID mid_isSaturated361;
	jmethodID mid_isSaturated362;
	jmethodID mid_closeAllSpectrometers363;
	jmethodID mid_closeSpectrometer364;
	jmethodID mid_getFeatureControllerGPIO365;
	jmethodID mid_isFeatureSupportedGPIO366;
	jmethodID mid_getFeatureControllerSPIBus367;
	jmethodID mid_isFeatureSupportedSPIBus368;
	jmethodID mid_getFeatureControllerSingleStrobe369;
	jmethodID mid_isFeatureSupportedSingleStrobe370;
	jmethodID mid_getFeatureControllerContinuousStrobe371;
	jmethodID mid_isFeatureSupportedContinuousStrobe372;
	jmethodID mid_getFeatureControllerCurrentOut373;
	jmethodID mid_isFeatureSupportedCurrentOut374;
	jmethodID mid_getFeatureControllerBoardTemperature375;
	jmethodID mid_isFeatureSupportedBoardTemperature376;
	jmethodID mid_getFeatureControllerAnalogIn377;
	jmethodID mid_isFeatureSupportedAnalogIn378;
	jmethodID mid_getFeatureControllerAnalogOut379;
	jmethodID mid_isFeatureSupportedAnalogOut380;
	jmethodID mid_getFeatureControllerExternalTriggerDelay381;
	jmethodID mid_isFeatureSupportedExternalTriggerDelay382;
	jmethodID mid_getFeatureControllerI2CBus383;
	jmethodID mid_isFeatureSupportedI2CBus384;
	jmethodID mid_getFeatureControllerHighGainMode385;
	jmethodID mid_isFeatureSupportedHighGainMode386;
	jmethodID mid_getFeatureControllerIrradianceCalibrationFactor387;
	jmethodID mid_isFeatureSupportedIrradianceCalibrationFactor388;
	jmethodID mid_getFeatureControllerLS450389;
	jmethodID mid_isFeatureSupportedLS450390;
	jmethodID mid_getFeatureController_UV_VIS_LightSource391;
	jmethodID mid_isFeatureSupported_UV_VIS_LightSource392;
	jmethodID mid_getFeatureControllerNonlinearityCorrectionProvider393;
	jmethodID mid_isFeatureSupportedNonlinearityCorrectionProvider394;
	jmethodID mid_getFeatureControllerStrayLightCorrection395;
	jmethodID mid_isFeatureSupportedStrayLightCorrection396;
	jmethodID mid_getFeatureControllerVersion397;
	jmethodID mid_isFeatureSupportedVersion398;
	jmethodID mid_getFeatureControllerWavelengthCalibrationProvider399;
	jmethodID mid_isFeatureSupportedWavelengthCalibrationProvider400;
	jmethodID mid_getFeatureControllerThermoElectric401;
	jmethodID mid_isFeatureSupportedThermoElectric402;
	jmethodID mid_setAutoToggleStrobeLampEnable403;
	jmethodID mid_setAutoToggleStrobeLampEnable404;
	jmethodID mid_highSpdAcq_AllocateBuffer405;
	jmethodID mid_highSpdAcq_StartAcquisition406;
	jmethodID mid_highSpdAcq_StartAcquisition407;
	jmethodID mid_highSpdAcq_StopAcquisition408;
	jmethodID mid_highSpdAcq_GetNumberOfSpectraAcquired409;
	jmethodID mid_highSpdAcq_GetSpectrum410;
	jmethodID mid_highSpdAcq_IsSaturated411;
	jmethodID mid_highSpdAcq_GetTimeStamp412;
	jmethodID mid_main413;
	void init_ids(JNIEnv* pJNIEnv);
};

extern "C" {
#endif /* __cplusplus */
#ifndef EXTERN_TYPEDEF_WRAPPEREXTENSIONS_T
#define EXTERN_TYPEDEF_WRAPPEREXTENSIONS_T
	typedef void* WRAPPEREXTENSIONS_T;
#endif /* EXTERN_TYPEDEF_WRAPPEREXTENSIONS_T */
#ifndef EXTERN_TYPEDEF_JSTRING_T
#define EXTERN_TYPEDEF_JSTRING_T
	typedef void* JSTRING_T;
#endif /* EXTERN_TYPEDEF_JSTRING_T */
#ifndef EXTERN_TYPEDEF_BENCH_T
#define EXTERN_TYPEDEF_BENCH_T
	typedef void* BENCH_T;
#endif /* EXTERN_TYPEDEF_BENCH_T */
#ifndef EXTERN_TYPEDEF_COEFFICIENTS_T
#define EXTERN_TYPEDEF_COEFFICIENTS_T
	typedef void* COEFFICIENTS_T;
#endif /* EXTERN_TYPEDEF_COEFFICIENTS_T */
#ifndef EXTERN_TYPEDEF_GPIO_T
#define EXTERN_TYPEDEF_GPIO_T
	typedef void* GPIO_T;
#endif /* EXTERN_TYPEDEF_GPIO_T */
#ifndef EXTERN_TYPEDEF_SPIBUS_T
#define EXTERN_TYPEDEF_SPIBUS_T
	typedef void* SPIBUS_T;
#endif /* EXTERN_TYPEDEF_SPIBUS_T */
#ifndef EXTERN_TYPEDEF_SINGLESTROBE_T
#define EXTERN_TYPEDEF_SINGLESTROBE_T
	typedef void* SINGLESTROBE_T;
#endif /* EXTERN_TYPEDEF_SINGLESTROBE_T */
#ifndef EXTERN_TYPEDEF_CONTINUOUSSTROBE_T
#define EXTERN_TYPEDEF_CONTINUOUSSTROBE_T
	typedef void* CONTINUOUSSTROBE_T;
#endif /* EXTERN_TYPEDEF_CONTINUOUSSTROBE_T */
#ifndef EXTERN_TYPEDEF_CURRENTOUT_T
#define EXTERN_TYPEDEF_CURRENTOUT_T
	typedef void* CURRENTOUT_T;
#endif /* EXTERN_TYPEDEF_CURRENTOUT_T */
#ifndef EXTERN_TYPEDEF_BOARDTEMPERATURE_T
#define EXTERN_TYPEDEF_BOARDTEMPERATURE_T
	typedef void* BOARDTEMPERATURE_T;
#endif /* EXTERN_TYPEDEF_BOARDTEMPERATURE_T */
#ifndef EXTERN_TYPEDEF_ANALOGIN_T
#define EXTERN_TYPEDEF_ANALOGIN_T
	typedef void* ANALOGIN_T;
#endif /* EXTERN_TYPEDEF_ANALOGIN_T */
#ifndef EXTERN_TYPEDEF_ANALOGOUT_T
#define EXTERN_TYPEDEF_ANALOGOUT_T
	typedef void* ANALOGOUT_T;
#endif /* EXTERN_TYPEDEF_ANALOGOUT_T */
#ifndef EXTERN_TYPEDEF_EXTERNALTRIGGERDELAY_T
#define EXTERN_TYPEDEF_EXTERNALTRIGGERDELAY_T
	typedef void* EXTERNALTRIGGERDELAY_T;
#endif /* EXTERN_TYPEDEF_EXTERNALTRIGGERDELAY_T */
#ifndef EXTERN_TYPEDEF_I2CBUS_T
#define EXTERN_TYPEDEF_I2CBUS_T
	typedef void* I2CBUS_T;
#endif /* EXTERN_TYPEDEF_I2CBUS_T */
#ifndef EXTERN_TYPEDEF_HIGHGAINMODE_T
#define EXTERN_TYPEDEF_HIGHGAINMODE_T
	typedef void* HIGHGAINMODE_T;
#endif /* EXTERN_TYPEDEF_HIGHGAINMODE_T */
#ifndef EXTERN_TYPEDEF_IRRADIANCECALIBRATIONFACTOR_T
#define EXTERN_TYPEDEF_IRRADIANCECALIBRATIONFACTOR_T
	typedef void* IRRADIANCECALIBRATIONFACTOR_T;
#endif /* EXTERN_TYPEDEF_IRRADIANCECALIBRATIONFACTOR_T */
#ifndef EXTERN_TYPEDEF_LS450_FUNCTIONS_T
#define EXTERN_TYPEDEF_LS450_FUNCTIONS_T
	typedef void* LS450_FUNCTIONS_T;
#endif /* EXTERN_TYPEDEF_LS450_FUNCTIONS_T */
#ifndef EXTERN_TYPEDEF_UV_VIS_LIGHTSOURCE_T
#define EXTERN_TYPEDEF_UV_VIS_LIGHTSOURCE_T
	typedef void* UV_VIS_LIGHTSOURCE_T;
#endif /* EXTERN_TYPEDEF_UV_VIS_LIGHTSOURCE_T */
#ifndef EXTERN_TYPEDEF_NONLINEARITYCORRECTIONPROVIDER_T
#define EXTERN_TYPEDEF_NONLINEARITYCORRECTIONPROVIDER_T
	typedef void* NONLINEARITYCORRECTIONPROVIDER_T;
#endif /* EXTERN_TYPEDEF_NONLINEARITYCORRECTIONPROVIDER_T */
#ifndef EXTERN_TYPEDEF_STRAYLIGHTCORRECTION_T
#define EXTERN_TYPEDEF_STRAYLIGHTCORRECTION_T
	typedef void* STRAYLIGHTCORRECTION_T;
#endif /* EXTERN_TYPEDEF_STRAYLIGHTCORRECTION_T */
#ifndef EXTERN_TYPEDEF_VERSION_T
#define EXTERN_TYPEDEF_VERSION_T
	typedef void* VERSION_T;
#endif /* EXTERN_TYPEDEF_VERSION_T */
#ifndef EXTERN_TYPEDEF_WAVELENGTHCALIBRATIONPROVIDER_T
#define EXTERN_TYPEDEF_WAVELENGTHCALIBRATIONPROVIDER_T
	typedef void* WAVELENGTHCALIBRATIONPROVIDER_T;
#endif /* EXTERN_TYPEDEF_WAVELENGTHCALIBRATIONPROVIDER_T */
#ifndef EXTERN_TYPEDEF_THERMOELECTRIC_T
#define EXTERN_TYPEDEF_THERMOELECTRIC_T
	typedef void* THERMOELECTRIC_T;
#endif /* EXTERN_TYPEDEF_THERMOELECTRIC_T */
#ifndef EXTERN_TYPEDEF_HIGHRESTIMESTAMP_T
#define EXTERN_TYPEDEF_HIGHRESTIMESTAMP_T
	typedef void* HIGHRESTIMESTAMP_T;
#endif /* EXTERN_TYPEDEF_HIGHRESTIMESTAMP_T */
#ifndef EXTERN_TYPEDEF_JSTRINGARRAY_T
#define EXTERN_TYPEDEF_JSTRINGARRAY_T
	typedef void* JSTRINGARRAY_T;
#endif /* EXTERN_TYPEDEF_JSTRINGARRAY_T */
#ifndef EXTERN_TYPEDEF_WRAPPER_T
#define EXTERN_TYPEDEF_WRAPPER_T
	typedef void* WRAPPER_T;
#endif /* EXTERN_TYPEDEF_WRAPPER_T */

	EXPORTED WRAPPER_T Wrapper_Create();
	EXPORTED void Wrapper_getWrapperExtensions(WRAPPER_T c_wrapper, WRAPPEREXTENSIONS_T retval);
	EXPORTED unsigned char Wrapper_exportToGramsSPC(WRAPPER_T c_wrapper, int spectrometerIndex, JSTRING_T outputPathname, DOUBLEARRAY_T pixels, JSTRING_T username);
	EXPORTED unsigned char Wrapper_exportToGramsSPC_1(WRAPPER_T c_wrapper, int spectrometerIndex, int channelIndex, JSTRING_T outputPathname, DOUBLEARRAY_T pixels, JSTRING_T username);
	EXPORTED void Wrapper_getApiVersion(WRAPPER_T c_wrapper, JSTRING_T retval);
	EXPORTED int Wrapper_getBuildNumber(WRAPPER_T c_wrapper);
	EXPORTED void Wrapper_getLastException(WRAPPER_T c_wrapper, JSTRING_T retval);
	EXPORTED void Wrapper_getLastExceptionStackTrace(WRAPPER_T c_wrapper, JSTRING_T retval);
	EXPORTED int Wrapper_openNetworkSpectrometer(WRAPPER_T c_wrapper, JSTRING_T ipAddress);
	EXPORTED int Wrapper_openAllSpectrometers(WRAPPER_T c_wrapper);
	EXPORTED void Wrapper_getName(WRAPPER_T c_wrapper, int spectrometerIndex, JSTRING_T retval);
	EXPORTED int Wrapper_getMaximumIntegrationTime(WRAPPER_T c_wrapper, int spectrometerIndex);
	EXPORTED int Wrapper_getMinimumIntegrationTime(WRAPPER_T c_wrapper, int spectrometerIndex);
	EXPORTED int Wrapper_getMaximumIntensity(WRAPPER_T c_wrapper, int spectrometerIndex);
	EXPORTED int Wrapper_getNumberOfSpectrometersFound(WRAPPER_T c_wrapper);
	EXPORTED void Wrapper_getFirmwareVersion(WRAPPER_T c_wrapper, int spectrometerIndex, JSTRING_T retval);
	EXPORTED void Wrapper_getSerialNumber(WRAPPER_T c_wrapper, int spectrometerIndex, JSTRING_T retval);
	EXPORTED int Wrapper_getNumberOfPixels(WRAPPER_T c_wrapper, int spectrometerIndex);
	EXPORTED int Wrapper_getNumberOfPixels_1(WRAPPER_T c_wrapper, int spectrometerIndex, int channelIndex);
	EXPORTED int Wrapper_getNumberOfDarkPixels(WRAPPER_T c_wrapper, int spectrometerIndex);
	EXPORTED int Wrapper_getNumberOfDarkPixels_1(WRAPPER_T c_wrapper, int spectrometerIndex, int channelIndex);
	EXPORTED void Wrapper_setIntegrationTime(WRAPPER_T c_wrapper, int spectrometerIndex, int usec);
	EXPORTED void Wrapper_setIntegrationTime_1(WRAPPER_T c_wrapper, int spectrometerIndex, int channelIndex, int usec);
	EXPORTED int Wrapper_getIntegrationTime(WRAPPER_T c_wrapper, int spectrometerIndex);
	EXPORTED int Wrapper_getIntegrationTime_1(WRAPPER_T c_wrapper, int spectrometerIndex, int channelIndex);
	EXPORTED void Wrapper_setScansToAverage(WRAPPER_T c_wrapper, int spectrometerIndex, int numberOfScansToAverage);
	EXPORTED void Wrapper_setScansToAverage_1(WRAPPER_T c_wrapper, int spectrometerIndex, int channelIndex, int numberOfScansToAverage);
	EXPORTED int Wrapper_getScansToAverage(WRAPPER_T c_wrapper, int spectrometerIndex);
	EXPORTED int Wrapper_getScansToAverage_1(WRAPPER_T c_wrapper, int spectrometerIndex, int channelIndex);
	EXPORTED void Wrapper_getBench(WRAPPER_T c_wrapper, int spectrometerIndex, BENCH_T retval);
	EXPORTED void Wrapper_getBench_1(WRAPPER_T c_wrapper, int spectrometerIndex, int channelIndex, BENCH_T retval);
	EXPORTED void Wrapper_setBoxcarWidth(WRAPPER_T c_wrapper, int spectrometerIndex, int numberOfPixelsOnEitherSideOfCenter);
	EXPORTED void Wrapper_setBoxcarWidth_1(WRAPPER_T c_wrapper, int spectrometerIndex, int channelIndex, int numberOfPixelsOnEitherSideOfCenter);
	EXPORTED int Wrapper_getBoxcarWidth(WRAPPER_T c_wrapper, int spectrometerIndex);
	EXPORTED int Wrapper_getBoxcarWidth_1(WRAPPER_T c_wrapper, int spectrometerIndex, int channelIndex);
	EXPORTED unsigned char Wrapper_insertKey(WRAPPER_T c_wrapper, JSTRING_T keyValue);
	EXPORTED void Wrapper_removeKey(WRAPPER_T c_wrapper);
	EXPORTED void Wrapper_getCalibrationCoefficientsFromBuffer(WRAPPER_T c_wrapper, int spectrometerIndex, COEFFICIENTS_T retval);
	EXPORTED void Wrapper_getCalibrationCoefficientsFromBuffer_1(WRAPPER_T c_wrapper, int spectrometerIndex, int channelIndex, COEFFICIENTS_T retval);
	EXPORTED void Wrapper_getCalibrationCoefficientsFromEEProm(WRAPPER_T c_wrapper, int spectrometerIndex, COEFFICIENTS_T retval);
	EXPORTED void Wrapper_getCalibrationCoefficientsFromEEProm_1(WRAPPER_T c_wrapper, int spectrometerIndex, int channelIndex, COEFFICIENTS_T retval);
	EXPORTED unsigned char Wrapper_setCalibrationCoefficientsIntoBuffer(WRAPPER_T c_wrapper, int spectrometerIndex, COEFFICIENTS_T coefficients, unsigned char applyWavelengthCoefficients, unsigned char applyStrayLightConstant, unsigned char applyNonlinearityCoefficients);
	EXPORTED unsigned char Wrapper_setCalibrationCoefficientsIntoBuffer_1(WRAPPER_T c_wrapper, int spectrometerIndex, int channelIndex, COEFFICIENTS_T newCoefficients, unsigned char applyWavelengthCoefficients, unsigned char applyStrayLightConstant, unsigned char applyNonlinearityCoefficients);
	EXPORTED unsigned char Wrapper_setCalibrationCoefficientsIntoEEProm(WRAPPER_T c_wrapper, int spectrometerIndex, COEFFICIENTS_T coefficients, unsigned char applyWavelengthCoefficients, unsigned char applyStrayLightConstant, unsigned char applyNonlinearityCoefficients);
	EXPORTED unsigned char Wrapper_setCalibrationCoefficientsIntoEEProm_1(WRAPPER_T c_wrapper, int spectrometerIndex, int channelIndex, COEFFICIENTS_T newCoefficients, unsigned char applyWavelengthCoefficients, unsigned char applyStrayLightConstants, unsigned char applyNonlinearityCoefficients);
	EXPORTED void Wrapper_getEEPromInfo(WRAPPER_T c_wrapper, int spectrometerIndex, int slot, JSTRING_T retval);
	EXPORTED unsigned char Wrapper_setEEPromInfo(WRAPPER_T c_wrapper, int spectrometerIndex, int slot, JSTRING_T str);
	EXPORTED unsigned char Wrapper_setDetectorSetPointCelsius(WRAPPER_T c_wrapper, int spectrometerIndex, double temperatureCelsius);
	EXPORTED void Wrapper_setExternalTriggerMode(WRAPPER_T c_wrapper, int spectrometerIndex, int mode);
	EXPORTED void Wrapper_setExternalTriggerMode_1(WRAPPER_T c_wrapper, int spectrometerIndex, int channelIndex, int mode);
	EXPORTED int Wrapper_getExternalTriggerMode(WRAPPER_T c_wrapper, int spectrometerIndex);
	EXPORTED int Wrapper_getExternalTriggerMode_1(WRAPPER_T c_wrapper, int spectrometerIndex, int channelIndex);
	EXPORTED void Wrapper_setCorrectForElectricalDark(WRAPPER_T c_wrapper, int spectrometerIndex, int enable);
	EXPORTED void Wrapper_setCorrectForElectricalDark_1(WRAPPER_T c_wrapper, int spectrometerIndex, int channelIndex, int enable);
	EXPORTED unsigned char Wrapper_getCorrectForElectricalDark(WRAPPER_T c_wrapper, int spectrometerIndex);
	EXPORTED unsigned char Wrapper_getCorrectForElectricalDark_1(WRAPPER_T c_wrapper, int spectrometerIndex, int channelIndex);
	EXPORTED unsigned char Wrapper_getCorrectForStrayLight(WRAPPER_T c_wrapper, int spectrometerIndex);
	EXPORTED unsigned char Wrapper_getCorrectForStrayLight_1(WRAPPER_T c_wrapper, int spectrometerIndex, int channelIndex);
	EXPORTED unsigned char Wrapper_setCorrectForDetectorNonlinearity(WRAPPER_T c_wrapper, int spectrometerIndex, int enable);
	EXPORTED unsigned char Wrapper_setCorrectForDetectorNonlinearity_1(WRAPPER_T c_wrapper, int spectrometerIndex, int channelIndex, int enable);
	EXPORTED unsigned char Wrapper_getCorrectForDetectorNonlinearity(WRAPPER_T c_wrapper, int spectrometerIndex);
	EXPORTED unsigned char Wrapper_getCorrectForDetectorNonlinearity_1(WRAPPER_T c_wrapper, int spectrometerIndex, int channelIndex);
	EXPORTED void Wrapper_setStrobeEnable(WRAPPER_T c_wrapper, int spectrometerIndex, int lampOn);
	EXPORTED void Wrapper_setStrobeEnable_1(WRAPPER_T c_wrapper, int spectrometerIndex, int channelIndex, int lampOn);
	EXPORTED int Wrapper_getStrobeEnable(WRAPPER_T c_wrapper, int spectrometerIndex);
	EXPORTED int Wrapper_getStrobeEnable_1(WRAPPER_T c_wrapper, int spectrometerIndex, int channelIndex);
	EXPORTED double Wrapper_getWavelength(WRAPPER_T c_wrapper, int spectrometerIndex, int pixel);
	EXPORTED double Wrapper_getWavelength_1(WRAPPER_T c_wrapper, int spectrometerIndex, int channelIndex, int pixel);
	EXPORTED void Wrapper_getWavelengths(WRAPPER_T c_wrapper, int spectrometerIndex, DOUBLEARRAY_T retval);
	EXPORTED void Wrapper_getWavelengths_1(WRAPPER_T c_wrapper, int spectrometerIndex, int channelIndex, DOUBLEARRAY_T retval);
	EXPORTED double Wrapper_getWavelengthIntercept(WRAPPER_T c_wrapper, int spectrometerIndex);
	EXPORTED double Wrapper_getWavelengthIntercept_1(WRAPPER_T c_wrapper, int spectrometerIndex, int channelIndex);
	EXPORTED double Wrapper_getWavelengthFirst(WRAPPER_T c_wrapper, int spectrometerIndex);
	EXPORTED double Wrapper_getWavelengthFirst_1(WRAPPER_T c_wrapper, int spectrometerIndex, int channelIndex);
	EXPORTED double Wrapper_getWavelengthSecond(WRAPPER_T c_wrapper, int spectrometerIndex);
	EXPORTED double Wrapper_getWavelengthSecond_1(WRAPPER_T c_wrapper, int spectrometerIndex, int channelIndex);
	EXPORTED double Wrapper_getWavelengthThird(WRAPPER_T c_wrapper, int spectrometerIndex);
	EXPORTED double Wrapper_getWavelengthThird_1(WRAPPER_T c_wrapper, int spectrometerIndex, int channelIndex);
	EXPORTED void Wrapper_getSpectrum(WRAPPER_T c_wrapper, int spectrometerIndex, DOUBLEARRAY_T retval);
	EXPORTED void Wrapper_getSpectrum_1(WRAPPER_T c_wrapper, int spectrometerIndex, int channelIndex, DOUBLEARRAY_T retval);
	EXPORTED void Wrapper_stopAveraging(WRAPPER_T c_wrapper, int spectrometerIndex);
	EXPORTED void Wrapper_stopAveraging_1(WRAPPER_T c_wrapper, int spectrometerIndex, int channelIndex);
	EXPORTED unsigned char Wrapper_isSaturated(WRAPPER_T c_wrapper, int spectrometerIndex);
	EXPORTED unsigned char Wrapper_isSaturated_1(WRAPPER_T c_wrapper, int spectrometerIndex, int channelIndex);
	EXPORTED void Wrapper_closeAllSpectrometers(WRAPPER_T c_wrapper);
	EXPORTED void Wrapper_closeSpectrometer(WRAPPER_T c_wrapper, int spectrometerIndex);
	EXPORTED void Wrapper_getFeatureControllerGPIO(WRAPPER_T c_wrapper, int spectrometerIndex, GPIO_T retval);
	EXPORTED unsigned char Wrapper_isFeatureSupportedGPIO(WRAPPER_T c_wrapper, int spectrometerIndex);
	EXPORTED void Wrapper_getFeatureControllerSPIBus(WRAPPER_T c_wrapper, int spectrometerIndex, SPIBUS_T retval);
	EXPORTED unsigned char Wrapper_isFeatureSupportedSPIBus(WRAPPER_T c_wrapper, int spectrometerIndex);
	EXPORTED void Wrapper_getFeatureControllerSingleStrobe(WRAPPER_T c_wrapper, int spectrometerIndex, SINGLESTROBE_T retval);
	EXPORTED unsigned char Wrapper_isFeatureSupportedSingleStrobe(WRAPPER_T c_wrapper, int spectrometerIndex);
	EXPORTED void Wrapper_getFeatureControllerContinuousStrobe(WRAPPER_T c_wrapper, int spectrometerIndex, CONTINUOUSSTROBE_T retval);
	EXPORTED unsigned char Wrapper_isFeatureSupportedContinuousStrobe(WRAPPER_T c_wrapper, int spectrometerIndex);
	EXPORTED void Wrapper_getFeatureControllerCurrentOut(WRAPPER_T c_wrapper, int spectrometerIndex, CURRENTOUT_T retval);
	EXPORTED unsigned char Wrapper_isFeatureSupportedCurrentOut(WRAPPER_T c_wrapper, int spectrometerIndex);
	EXPORTED void Wrapper_getFeatureControllerBoardTemperature(WRAPPER_T c_wrapper, int spectrometerIndex, BOARDTEMPERATURE_T retval);
	EXPORTED unsigned char Wrapper_isFeatureSupportedBoardTemperature(WRAPPER_T c_wrapper, int spectrometerIndex);
	EXPORTED void Wrapper_getFeatureControllerAnalogIn(WRAPPER_T c_wrapper, int spectrometerIndex, ANALOGIN_T retval);
	EXPORTED unsigned char Wrapper_isFeatureSupportedAnalogIn(WRAPPER_T c_wrapper, int spectrometerIndex);
	EXPORTED void Wrapper_getFeatureControllerAnalogOut(WRAPPER_T c_wrapper, int spectrometerIndex, ANALOGOUT_T retval);
	EXPORTED unsigned char Wrapper_isFeatureSupportedAnalogOut(WRAPPER_T c_wrapper, int spectrometerIndex);
	EXPORTED void Wrapper_getFeatureControllerExternalTriggerDelay(WRAPPER_T c_wrapper, int spectrometerIndex, EXTERNALTRIGGERDELAY_T retval);
	EXPORTED unsigned char Wrapper_isFeatureSupportedExternalTriggerDelay(WRAPPER_T c_wrapper, int spectrometerIndex);
	EXPORTED void Wrapper_getFeatureControllerI2CBus(WRAPPER_T c_wrapper, int spectrometerIndex, I2CBUS_T retval);
	EXPORTED unsigned char Wrapper_isFeatureSupportedI2CBus(WRAPPER_T c_wrapper, int spectrometerIndex);
	EXPORTED void Wrapper_getFeatureControllerHighGainMode(WRAPPER_T c_wrapper, int spectrometerIndex, HIGHGAINMODE_T retval);
	EXPORTED unsigned char Wrapper_isFeatureSupportedHighGainMode(WRAPPER_T c_wrapper, int spectrometerIndex);
	EXPORTED void Wrapper_getFeatureControllerIrradianceCalibrationFactor(WRAPPER_T c_wrapper, int spectrometerIndex, IRRADIANCECALIBRATIONFACTOR_T retval);
	EXPORTED unsigned char Wrapper_isFeatureSupportedIrradianceCalibrationFactor(WRAPPER_T c_wrapper, int spectrometerIndex);
	EXPORTED void Wrapper_getFeatureControllerLS450(WRAPPER_T c_wrapper, int spectrometerIndex, LS450_FUNCTIONS_T retval);
	EXPORTED unsigned char Wrapper_isFeatureSupportedLS450(WRAPPER_T c_wrapper, int spectrometerIndex);
	EXPORTED void Wrapper_getFeatureController_UV_VIS_LightSource(WRAPPER_T c_wrapper, int spectrometerIndex, UV_VIS_LIGHTSOURCE_T retval);
	EXPORTED unsigned char Wrapper_isFeatureSupported_UV_VIS_LightSource(WRAPPER_T c_wrapper, int spectrometerIndex);
	EXPORTED void Wrapper_getFeatureControllerNonlinearityCorrectionProvider(WRAPPER_T c_wrapper, int spectrometerIndex, NONLINEARITYCORRECTIONPROVIDER_T retval);
	EXPORTED unsigned char Wrapper_isFeatureSupportedNonlinearityCorrectionProvider(WRAPPER_T c_wrapper, int spectrometerIndex);
	EXPORTED void Wrapper_getFeatureControllerStrayLightCorrection(WRAPPER_T c_wrapper, int spectrometerIndex, STRAYLIGHTCORRECTION_T retval);
	EXPORTED unsigned char Wrapper_isFeatureSupportedStrayLightCorrection(WRAPPER_T c_wrapper, int spectrometerIndex);
	EXPORTED void Wrapper_getFeatureControllerVersion(WRAPPER_T c_wrapper, int spectrometerIndex, VERSION_T retval);
	EXPORTED unsigned char Wrapper_isFeatureSupportedVersion(WRAPPER_T c_wrapper, int spectrometerIndex);
	EXPORTED void Wrapper_getFeatureControllerWavelengthCalibrationProvider(WRAPPER_T c_wrapper, int spectrometerIndex, WAVELENGTHCALIBRATIONPROVIDER_T retval);
	EXPORTED unsigned char Wrapper_isFeatureSupportedWavelengthCalibrationProvider(WRAPPER_T c_wrapper, int spectrometerIndex);
	EXPORTED void Wrapper_getFeatureControllerThermoElectric(WRAPPER_T c_wrapper, int spectrometerIndex, THERMOELECTRIC_T retval);
	EXPORTED unsigned char Wrapper_isFeatureSupportedThermoElectric(WRAPPER_T c_wrapper, int spectrometerIndex);
	EXPORTED void Wrapper_setAutoToggleStrobeLampEnable(WRAPPER_T c_wrapper, int spectrometerIndex, unsigned char enable);
	EXPORTED void Wrapper_setAutoToggleStrobeLampEnable_1(WRAPPER_T c_wrapper, int spectrometerIndex, int channelIndex, unsigned char enable);
	EXPORTED void Wrapper_highSpdAcq_AllocateBuffer(WRAPPER_T c_wrapper, int spectrometerIndex, int numberOfSpectra);
	EXPORTED void Wrapper_highSpdAcq_StartAcquisition(WRAPPER_T c_wrapper, int spectrometerIndex);
	EXPORTED void Wrapper_highSpdAcq_StartAcquisition_1(WRAPPER_T c_wrapper, int spectrometerIndex, int channelIndex);
	EXPORTED void Wrapper_highSpdAcq_StopAcquisition(WRAPPER_T c_wrapper);
	EXPORTED int Wrapper_highSpdAcq_GetNumberOfSpectraAcquired(WRAPPER_T c_wrapper);
	EXPORTED void Wrapper_highSpdAcq_GetSpectrum(WRAPPER_T c_wrapper, int spectrumNumber, DOUBLEARRAY_T retval);
	EXPORTED unsigned char Wrapper_highSpdAcq_IsSaturated(WRAPPER_T c_wrapper, int spectrumNumber);
	EXPORTED void Wrapper_highSpdAcq_GetTimeStamp(WRAPPER_T c_wrapper, int spectrumNumber, HIGHRESTIMESTAMP_T retval);
	EXPORTED void Wrapper_main(WRAPPER_T c_wrapper, JSTRINGARRAY_T args);
	EXPORTED void Wrapper_Destroy(WRAPPER_T wrapper);

#ifdef WIN32
	// Use the following function prototypes when calling functions from Visual Basic 6
	EXPORTED WRAPPER_T STDCALL Wrapper_Create_stdcall();
	EXPORTED void STDCALL Wrapper_getWrapperExtensions_stdcall(WRAPPER_T c_wrapper, WRAPPEREXTENSIONS_T retval);
	EXPORTED unsigned char STDCALL Wrapper_exportToGramsSPC_stdcall(WRAPPER_T c_wrapper, int spectrometerIndex, JSTRING_T outputPathname, DOUBLEARRAY_T pixels, JSTRING_T username);
	EXPORTED unsigned char STDCALL Wrapper_exportToGramsSPC_stdcall_1(WRAPPER_T c_wrapper, int spectrometerIndex, int channelIndex, JSTRING_T outputPathname, DOUBLEARRAY_T pixels, JSTRING_T username);
	EXPORTED void STDCALL Wrapper_getApiVersion_stdcall(WRAPPER_T c_wrapper, JSTRING_T retval);
	EXPORTED int STDCALL Wrapper_getBuildNumber_stdcall(WRAPPER_T c_wrapper);
	EXPORTED void STDCALL Wrapper_getLastException_stdcall(WRAPPER_T c_wrapper, JSTRING_T retval);
	EXPORTED void STDCALL Wrapper_getLastExceptionStackTrace_stdcall(WRAPPER_T c_wrapper, JSTRING_T retval);
	EXPORTED int STDCALL Wrapper_openNetworkSpectrometer_stdcall(WRAPPER_T c_wrapper, JSTRING_T ipAddress);
	EXPORTED int STDCALL Wrapper_openAllSpectrometers_stdcall(WRAPPER_T c_wrapper);
	EXPORTED void STDCALL Wrapper_getName_stdcall(WRAPPER_T c_wrapper, int spectrometerIndex, JSTRING_T retval);
	EXPORTED int STDCALL Wrapper_getMaximumIntegrationTime_stdcall(WRAPPER_T c_wrapper, int spectrometerIndex);
	EXPORTED int STDCALL Wrapper_getMinimumIntegrationTime_stdcall(WRAPPER_T c_wrapper, int spectrometerIndex);
	EXPORTED int STDCALL Wrapper_getMaximumIntensity_stdcall(WRAPPER_T c_wrapper, int spectrometerIndex);
	EXPORTED int STDCALL Wrapper_getNumberOfSpectrometersFound_stdcall(WRAPPER_T c_wrapper);
	EXPORTED void STDCALL Wrapper_getFirmwareVersion_stdcall(WRAPPER_T c_wrapper, int spectrometerIndex, JSTRING_T retval);
	EXPORTED void STDCALL Wrapper_getSerialNumber_stdcall(WRAPPER_T c_wrapper, int spectrometerIndex, JSTRING_T retval);
	EXPORTED int STDCALL Wrapper_getNumberOfPixels_stdcall(WRAPPER_T c_wrapper, int spectrometerIndex);
	EXPORTED int STDCALL Wrapper_getNumberOfPixels_stdcall_1(WRAPPER_T c_wrapper, int spectrometerIndex, int channelIndex);
	EXPORTED int STDCALL Wrapper_getNumberOfDarkPixels_stdcall(WRAPPER_T c_wrapper, int spectrometerIndex);
	EXPORTED int STDCALL Wrapper_getNumberOfDarkPixels_stdcall_1(WRAPPER_T c_wrapper, int spectrometerIndex, int channelIndex);
	EXPORTED void STDCALL Wrapper_setIntegrationTime_stdcall(WRAPPER_T c_wrapper, int spectrometerIndex, int usec);
	EXPORTED void STDCALL Wrapper_setIntegrationTime_stdcall_1(WRAPPER_T c_wrapper, int spectrometerIndex, int channelIndex, int usec);
	EXPORTED int STDCALL Wrapper_getIntegrationTime_stdcall(WRAPPER_T c_wrapper, int spectrometerIndex);
	EXPORTED int STDCALL Wrapper_getIntegrationTime_stdcall_1(WRAPPER_T c_wrapper, int spectrometerIndex, int channelIndex);
	EXPORTED void STDCALL Wrapper_setScansToAverage_stdcall(WRAPPER_T c_wrapper, int spectrometerIndex, int numberOfScansToAverage);
	EXPORTED void STDCALL Wrapper_setScansToAverage_stdcall_1(WRAPPER_T c_wrapper, int spectrometerIndex, int channelIndex, int numberOfScansToAverage);
	EXPORTED int STDCALL Wrapper_getScansToAverage_stdcall(WRAPPER_T c_wrapper, int spectrometerIndex);
	EXPORTED int STDCALL Wrapper_getScansToAverage_stdcall_1(WRAPPER_T c_wrapper, int spectrometerIndex, int channelIndex);
	EXPORTED void STDCALL Wrapper_getBench_stdcall(WRAPPER_T c_wrapper, int spectrometerIndex, BENCH_T retval);
	EXPORTED void STDCALL Wrapper_getBench_stdcall_1(WRAPPER_T c_wrapper, int spectrometerIndex, int channelIndex, BENCH_T retval);
	EXPORTED void STDCALL Wrapper_setBoxcarWidth_stdcall(WRAPPER_T c_wrapper, int spectrometerIndex, int numberOfPixelsOnEitherSideOfCenter);
	EXPORTED void STDCALL Wrapper_setBoxcarWidth_stdcall_1(WRAPPER_T c_wrapper, int spectrometerIndex, int channelIndex, int numberOfPixelsOnEitherSideOfCenter);
	EXPORTED int STDCALL Wrapper_getBoxcarWidth_stdcall(WRAPPER_T c_wrapper, int spectrometerIndex);
	EXPORTED int STDCALL Wrapper_getBoxcarWidth_stdcall_1(WRAPPER_T c_wrapper, int spectrometerIndex, int channelIndex);
	EXPORTED unsigned char STDCALL Wrapper_insertKey_stdcall(WRAPPER_T c_wrapper, JSTRING_T keyValue);
	EXPORTED void STDCALL Wrapper_removeKey_stdcall(WRAPPER_T c_wrapper);
	EXPORTED void STDCALL Wrapper_getCalibrationCoefficientsFromBuffer_stdcall(WRAPPER_T c_wrapper, int spectrometerIndex, COEFFICIENTS_T retval);
	EXPORTED void STDCALL Wrapper_getCalibrationCoefficientsFromBuffer_stdcall_1(WRAPPER_T c_wrapper, int spectrometerIndex, int channelIndex, COEFFICIENTS_T retval);
	EXPORTED void STDCALL Wrapper_getCalibrationCoefficientsFromEEProm_stdcall(WRAPPER_T c_wrapper, int spectrometerIndex, COEFFICIENTS_T retval);
	EXPORTED void STDCALL Wrapper_getCalibrationCoefficientsFromEEProm_stdcall_1(WRAPPER_T c_wrapper, int spectrometerIndex, int channelIndex, COEFFICIENTS_T retval);
	EXPORTED unsigned char STDCALL Wrapper_setCalibrationCoefficientsIntoBuffer_stdcall(WRAPPER_T c_wrapper, int spectrometerIndex, COEFFICIENTS_T coefficients, unsigned char applyWavelengthCoefficients, unsigned char applyStrayLightConstant, unsigned char applyNonlinearityCoefficients);
	EXPORTED unsigned char STDCALL Wrapper_setCalibrationCoefficientsIntoBuffer_stdcall_1(WRAPPER_T c_wrapper, int spectrometerIndex, int channelIndex, COEFFICIENTS_T newCoefficients, unsigned char applyWavelengthCoefficients, unsigned char applyStrayLightConstant, unsigned char applyNonlinearityCoefficients);
	EXPORTED unsigned char STDCALL Wrapper_setCalibrationCoefficientsIntoEEProm_stdcall(WRAPPER_T c_wrapper, int spectrometerIndex, COEFFICIENTS_T coefficients, unsigned char applyWavelengthCoefficients, unsigned char applyStrayLightConstant, unsigned char applyNonlinearityCoefficients);
	EXPORTED unsigned char STDCALL Wrapper_setCalibrationCoefficientsIntoEEProm_stdcall_1(WRAPPER_T c_wrapper, int spectrometerIndex, int channelIndex, COEFFICIENTS_T newCoefficients, unsigned char applyWavelengthCoefficients, unsigned char applyStrayLightConstants, unsigned char applyNonlinearityCoefficients);
	EXPORTED void STDCALL Wrapper_getEEPromInfo_stdcall(WRAPPER_T c_wrapper, int spectrometerIndex, int slot, JSTRING_T retval);
	EXPORTED unsigned char STDCALL Wrapper_setEEPromInfo_stdcall(WRAPPER_T c_wrapper, int spectrometerIndex, int slot, JSTRING_T str);
	EXPORTED unsigned char STDCALL Wrapper_setDetectorSetPointCelsius_stdcall(WRAPPER_T c_wrapper, int spectrometerIndex, double temperatureCelsius);
	EXPORTED void STDCALL Wrapper_setExternalTriggerMode_stdcall(WRAPPER_T c_wrapper, int spectrometerIndex, int mode);
	EXPORTED void STDCALL Wrapper_setExternalTriggerMode_stdcall_1(WRAPPER_T c_wrapper, int spectrometerIndex, int channelIndex, int mode);
	EXPORTED int STDCALL Wrapper_getExternalTriggerMode_stdcall(WRAPPER_T c_wrapper, int spectrometerIndex);
	EXPORTED int STDCALL Wrapper_getExternalTriggerMode_stdcall_1(WRAPPER_T c_wrapper, int spectrometerIndex, int channelIndex);
	EXPORTED void STDCALL Wrapper_setCorrectForElectricalDark_stdcall(WRAPPER_T c_wrapper, int spectrometerIndex, int enable);
	EXPORTED void STDCALL Wrapper_setCorrectForElectricalDark_stdcall_1(WRAPPER_T c_wrapper, int spectrometerIndex, int channelIndex, int enable);
	EXPORTED unsigned char STDCALL Wrapper_getCorrectForElectricalDark_stdcall(WRAPPER_T c_wrapper, int spectrometerIndex);
	EXPORTED unsigned char STDCALL Wrapper_getCorrectForElectricalDark_stdcall_1(WRAPPER_T c_wrapper, int spectrometerIndex, int channelIndex);
	EXPORTED unsigned char STDCALL Wrapper_getCorrectForStrayLight_stdcall(WRAPPER_T c_wrapper, int spectrometerIndex);
	EXPORTED unsigned char STDCALL Wrapper_getCorrectForStrayLight_stdcall_1(WRAPPER_T c_wrapper, int spectrometerIndex, int channelIndex);
	EXPORTED unsigned char STDCALL Wrapper_setCorrectForDetectorNonlinearity_stdcall(WRAPPER_T c_wrapper, int spectrometerIndex, int enable);
	EXPORTED unsigned char STDCALL Wrapper_setCorrectForDetectorNonlinearity_stdcall_1(WRAPPER_T c_wrapper, int spectrometerIndex, int channelIndex, int enable);
	EXPORTED unsigned char STDCALL Wrapper_getCorrectForDetectorNonlinearity_stdcall(WRAPPER_T c_wrapper, int spectrometerIndex);
	EXPORTED unsigned char STDCALL Wrapper_getCorrectForDetectorNonlinearity_stdcall_1(WRAPPER_T c_wrapper, int spectrometerIndex, int channelIndex);
	EXPORTED void STDCALL Wrapper_setStrobeEnable_stdcall(WRAPPER_T c_wrapper, int spectrometerIndex, int lampOn);
	EXPORTED void STDCALL Wrapper_setStrobeEnable_stdcall_1(WRAPPER_T c_wrapper, int spectrometerIndex, int channelIndex, int lampOn);
	EXPORTED int STDCALL Wrapper_getStrobeEnable_stdcall(WRAPPER_T c_wrapper, int spectrometerIndex);
	EXPORTED int STDCALL Wrapper_getStrobeEnable_stdcall_1(WRAPPER_T c_wrapper, int spectrometerIndex, int channelIndex);
	EXPORTED double STDCALL Wrapper_getWavelength_stdcall(WRAPPER_T c_wrapper, int spectrometerIndex, int pixel);
	EXPORTED double STDCALL Wrapper_getWavelength_stdcall_1(WRAPPER_T c_wrapper, int spectrometerIndex, int channelIndex, int pixel);
	EXPORTED void STDCALL Wrapper_getWavelengths_stdcall(WRAPPER_T c_wrapper, int spectrometerIndex, DOUBLEARRAY_T retval);
	EXPORTED void STDCALL Wrapper_getWavelengths_stdcall_1(WRAPPER_T c_wrapper, int spectrometerIndex, int channelIndex, DOUBLEARRAY_T retval);
	EXPORTED double STDCALL Wrapper_getWavelengthIntercept_stdcall(WRAPPER_T c_wrapper, int spectrometerIndex);
	EXPORTED double STDCALL Wrapper_getWavelengthIntercept_stdcall_1(WRAPPER_T c_wrapper, int spectrometerIndex, int channelIndex);
	EXPORTED double STDCALL Wrapper_getWavelengthFirst_stdcall(WRAPPER_T c_wrapper, int spectrometerIndex);
	EXPORTED double STDCALL Wrapper_getWavelengthFirst_stdcall_1(WRAPPER_T c_wrapper, int spectrometerIndex, int channelIndex);
	EXPORTED double STDCALL Wrapper_getWavelengthSecond_stdcall(WRAPPER_T c_wrapper, int spectrometerIndex);
	EXPORTED double STDCALL Wrapper_getWavelengthSecond_stdcall_1(WRAPPER_T c_wrapper, int spectrometerIndex, int channelIndex);
	EXPORTED double STDCALL Wrapper_getWavelengthThird_stdcall(WRAPPER_T c_wrapper, int spectrometerIndex);
	EXPORTED double STDCALL Wrapper_getWavelengthThird_stdcall_1(WRAPPER_T c_wrapper, int spectrometerIndex, int channelIndex);
	EXPORTED void STDCALL Wrapper_getSpectrum_stdcall(WRAPPER_T c_wrapper, int spectrometerIndex, DOUBLEARRAY_T retval);
	EXPORTED void STDCALL Wrapper_getSpectrum_stdcall_1(WRAPPER_T c_wrapper, int spectrometerIndex, int channelIndex, DOUBLEARRAY_T retval);
	EXPORTED void STDCALL Wrapper_stopAveraging_stdcall(WRAPPER_T c_wrapper, int spectrometerIndex);
	EXPORTED void STDCALL Wrapper_stopAveraging_stdcall_1(WRAPPER_T c_wrapper, int spectrometerIndex, int channelIndex);
	EXPORTED unsigned char STDCALL Wrapper_isSaturated_stdcall(WRAPPER_T c_wrapper, int spectrometerIndex);
	EXPORTED unsigned char STDCALL Wrapper_isSaturated_stdcall_1(WRAPPER_T c_wrapper, int spectrometerIndex, int channelIndex);
	EXPORTED void STDCALL Wrapper_closeAllSpectrometers_stdcall(WRAPPER_T c_wrapper);
	EXPORTED void STDCALL Wrapper_closeSpectrometer_stdcall(WRAPPER_T c_wrapper, int spectrometerIndex);
	EXPORTED void STDCALL Wrapper_getFeatureControllerGPIO_stdcall(WRAPPER_T c_wrapper, int spectrometerIndex, GPIO_T retval);
	EXPORTED unsigned char STDCALL Wrapper_isFeatureSupportedGPIO_stdcall(WRAPPER_T c_wrapper, int spectrometerIndex);
	EXPORTED void STDCALL Wrapper_getFeatureControllerSPIBus_stdcall(WRAPPER_T c_wrapper, int spectrometerIndex, SPIBUS_T retval);
	EXPORTED unsigned char STDCALL Wrapper_isFeatureSupportedSPIBus_stdcall(WRAPPER_T c_wrapper, int spectrometerIndex);
	EXPORTED void STDCALL Wrapper_getFeatureControllerSingleStrobe_stdcall(WRAPPER_T c_wrapper, int spectrometerIndex, SINGLESTROBE_T retval);
	EXPORTED unsigned char STDCALL Wrapper_isFeatureSupportedSingleStrobe_stdcall(WRAPPER_T c_wrapper, int spectrometerIndex);
	EXPORTED void STDCALL Wrapper_getFeatureControllerContinuousStrobe_stdcall(WRAPPER_T c_wrapper, int spectrometerIndex, CONTINUOUSSTROBE_T retval);
	EXPORTED unsigned char STDCALL Wrapper_isFeatureSupportedContinuousStrobe_stdcall(WRAPPER_T c_wrapper, int spectrometerIndex);
	EXPORTED void STDCALL Wrapper_getFeatureControllerCurrentOut_stdcall(WRAPPER_T c_wrapper, int spectrometerIndex, CURRENTOUT_T retval);
	EXPORTED unsigned char STDCALL Wrapper_isFeatureSupportedCurrentOut_stdcall(WRAPPER_T c_wrapper, int spectrometerIndex);
	EXPORTED void STDCALL Wrapper_getFeatureControllerBoardTemperature_stdcall(WRAPPER_T c_wrapper, int spectrometerIndex, BOARDTEMPERATURE_T retval);
	EXPORTED unsigned char STDCALL Wrapper_isFeatureSupportedBoardTemperature_stdcall(WRAPPER_T c_wrapper, int spectrometerIndex);
	EXPORTED void STDCALL Wrapper_getFeatureControllerAnalogIn_stdcall(WRAPPER_T c_wrapper, int spectrometerIndex, ANALOGIN_T retval);
	EXPORTED unsigned char STDCALL Wrapper_isFeatureSupportedAnalogIn_stdcall(WRAPPER_T c_wrapper, int spectrometerIndex);
	EXPORTED void STDCALL Wrapper_getFeatureControllerAnalogOut_stdcall(WRAPPER_T c_wrapper, int spectrometerIndex, ANALOGOUT_T retval);
	EXPORTED unsigned char STDCALL Wrapper_isFeatureSupportedAnalogOut_stdcall(WRAPPER_T c_wrapper, int spectrometerIndex);
	EXPORTED void STDCALL Wrapper_getFeatureControllerExternalTriggerDelay_stdcall(WRAPPER_T c_wrapper, int spectrometerIndex, EXTERNALTRIGGERDELAY_T retval);
	EXPORTED unsigned char STDCALL Wrapper_isFeatureSupportedExternalTriggerDelay_stdcall(WRAPPER_T c_wrapper, int spectrometerIndex);
	EXPORTED void STDCALL Wrapper_getFeatureControllerI2CBus_stdcall(WRAPPER_T c_wrapper, int spectrometerIndex, I2CBUS_T retval);
	EXPORTED unsigned char STDCALL Wrapper_isFeatureSupportedI2CBus_stdcall(WRAPPER_T c_wrapper, int spectrometerIndex);
	EXPORTED void STDCALL Wrapper_getFeatureControllerHighGainMode_stdcall(WRAPPER_T c_wrapper, int spectrometerIndex, HIGHGAINMODE_T retval);
	EXPORTED unsigned char STDCALL Wrapper_isFeatureSupportedHighGainMode_stdcall(WRAPPER_T c_wrapper, int spectrometerIndex);
	EXPORTED void STDCALL Wrapper_getFeatureControllerIrradianceCalibrationFactor_stdcall(WRAPPER_T c_wrapper, int spectrometerIndex, IRRADIANCECALIBRATIONFACTOR_T retval);
	EXPORTED unsigned char STDCALL Wrapper_isFeatureSupportedIrradianceCalibrationFactor_stdcall(WRAPPER_T c_wrapper, int spectrometerIndex);
	EXPORTED void STDCALL Wrapper_getFeatureControllerLS450_stdcall(WRAPPER_T c_wrapper, int spectrometerIndex, LS450_FUNCTIONS_T retval);
	EXPORTED unsigned char STDCALL Wrapper_isFeatureSupportedLS450_stdcall(WRAPPER_T c_wrapper, int spectrometerIndex);
	EXPORTED void STDCALL Wrapper_getFeatureController_UV_VIS_LightSource_stdcall(WRAPPER_T c_wrapper, int spectrometerIndex, UV_VIS_LIGHTSOURCE_T retval);
	EXPORTED unsigned char STDCALL Wrapper_isFeatureSupported_UV_VIS_LightSource_stdcall(WRAPPER_T c_wrapper, int spectrometerIndex);
	EXPORTED void STDCALL Wrapper_getFeatureControllerNonlinearityCorrectionProvider_stdcall(WRAPPER_T c_wrapper, int spectrometerIndex, NONLINEARITYCORRECTIONPROVIDER_T retval);
	EXPORTED unsigned char STDCALL Wrapper_isFeatureSupportedNonlinearityCorrectionProvider_stdcall(WRAPPER_T c_wrapper, int spectrometerIndex);
	EXPORTED void STDCALL Wrapper_getFeatureControllerStrayLightCorrection_stdcall(WRAPPER_T c_wrapper, int spectrometerIndex, STRAYLIGHTCORRECTION_T retval);
	EXPORTED unsigned char STDCALL Wrapper_isFeatureSupportedStrayLightCorrection_stdcall(WRAPPER_T c_wrapper, int spectrometerIndex);
	EXPORTED void STDCALL Wrapper_getFeatureControllerVersion_stdcall(WRAPPER_T c_wrapper, int spectrometerIndex, VERSION_T retval);
	EXPORTED unsigned char STDCALL Wrapper_isFeatureSupportedVersion_stdcall(WRAPPER_T c_wrapper, int spectrometerIndex);
	EXPORTED void STDCALL Wrapper_getFeatureControllerWavelengthCalibrationProvider_stdcall(WRAPPER_T c_wrapper, int spectrometerIndex, WAVELENGTHCALIBRATIONPROVIDER_T retval);
	EXPORTED unsigned char STDCALL Wrapper_isFeatureSupportedWavelengthCalibrationProvider_stdcall(WRAPPER_T c_wrapper, int spectrometerIndex);
	EXPORTED void STDCALL Wrapper_getFeatureControllerThermoElectric_stdcall(WRAPPER_T c_wrapper, int spectrometerIndex, THERMOELECTRIC_T retval);
	EXPORTED unsigned char STDCALL Wrapper_isFeatureSupportedThermoElectric_stdcall(WRAPPER_T c_wrapper, int spectrometerIndex);
	EXPORTED void STDCALL Wrapper_setAutoToggleStrobeLampEnable_stdcall(WRAPPER_T c_wrapper, int spectrometerIndex, unsigned char enable);
	EXPORTED void STDCALL Wrapper_setAutoToggleStrobeLampEnable_stdcall_1(WRAPPER_T c_wrapper, int spectrometerIndex, int channelIndex, unsigned char enable);
	EXPORTED void STDCALL Wrapper_highSpdAcq_AllocateBuffer_stdcall(WRAPPER_T c_wrapper, int spectrometerIndex, int numberOfSpectra);
	EXPORTED void STDCALL Wrapper_highSpdAcq_StartAcquisition_stdcall(WRAPPER_T c_wrapper, int spectrometerIndex);
	EXPORTED void STDCALL Wrapper_highSpdAcq_StartAcquisition_stdcall_1(WRAPPER_T c_wrapper, int spectrometerIndex, int channelIndex);
	EXPORTED void STDCALL Wrapper_highSpdAcq_StopAcquisition_stdcall(WRAPPER_T c_wrapper);
	EXPORTED int STDCALL Wrapper_highSpdAcq_GetNumberOfSpectraAcquired_stdcall(WRAPPER_T c_wrapper);
	EXPORTED void STDCALL Wrapper_highSpdAcq_GetSpectrum_stdcall(WRAPPER_T c_wrapper, int spectrumNumber, DOUBLEARRAY_T retval);
	EXPORTED unsigned char STDCALL Wrapper_highSpdAcq_IsSaturated_stdcall(WRAPPER_T c_wrapper, int spectrumNumber);
	EXPORTED void STDCALL Wrapper_highSpdAcq_GetTimeStamp_stdcall(WRAPPER_T c_wrapper, int spectrumNumber, HIGHRESTIMESTAMP_T retval);
	EXPORTED void STDCALL Wrapper_main_stdcall(WRAPPER_T c_wrapper, JSTRINGARRAY_T args);
	EXPORTED void STDCALL Wrapper_Destroy_stdcall(WRAPPER_T wrapper);
#endif /* WIN32 */
#ifdef __cplusplus
};
#endif /* __cplusplus */
#endif /* WRAPPER_H */
