/**
 * File: XYZColor.h
 * Autogenerated on Mon Nov 16 11:53:52 EST 2009 based on
 * XYZColor.java
 * for the Java class
 * com/oceanoptics/spam/advancedprocessing/colorspaces/XYZColor
 * Copyright (C) 2006 - 2008 Ocean Optics, Inc.  All rights reserved.
 */


#ifndef XYZCOLOR_H
#define XYZCOLOR_H
#include "BaseJavaClass.h"

#ifdef __cplusplus

#ifdef INCLUDES_IN_HEADER
#include "ColorSpaceDescriptor.h"
//#include "CIEColor.h"
#include "JString.h"
#include "ColorSpaceValueArray.h"
#endif /* INCLUDES_IN_HEADER */

/* Pre-declarations for circular dependencies in header files */
#ifdef CLASS_PREDECLARATIONS
class ColorSpaceDescriptor;
class XYZColor;
class CIEColor;
class JString;
class ColorSpaceValueArray;
#endif /* CLASS_PREDECLARATIONS */

CLASS_TOKEN EXPORTED XYZColor : public ColorSpaceDescriptor // CPPClass.getClassDeclaration
{
public: 
	XYZColor(double newX, double newY, double newZ);
	XYZColor(CIEColor& that);
	double getX();
	double getY();
	double getZ();
	double getColorDifference(XYZColor& that);
	double getLittleX();
	double getLittleY();
	double getLittleZ();
	JString toString();
	ColorSpaceValueArray getColorSpaceValues();
	~XYZColor();
	// No public default Java constructor; creating one:
	XYZColor();
	// No public Java copy constructor; creating one:
	XYZColor(const XYZColor &that);
	// Creating assignment operator declaration:
	XYZColor &operator=(const XYZColor &that);

private:
	jmethodID mid_XYZColor129;
	jmethodID mid_XYZColor130;
	jmethodID mid_XYZColor131;
	jmethodID mid_getX132;
	jmethodID mid_getY133;
	jmethodID mid_getZ134;
	jmethodID mid_getColorDifference135;
	jmethodID mid_getLittleX136;
	jmethodID mid_getLittleY137;
	jmethodID mid_getLittleZ138;
	jmethodID mid_toString139;
	jmethodID mid_getColorSpaceValues140;
	void init_ids(JNIEnv* pJNIEnv);
};

extern "C" {
#endif /* __cplusplus */
#ifndef EXTERN_TYPEDEF_COLORSPACEDESCRIPTOR_T
#define EXTERN_TYPEDEF_COLORSPACEDESCRIPTOR_T
	typedef void* COLORSPACEDESCRIPTOR_T;
#endif /* EXTERN_TYPEDEF_COLORSPACEDESCRIPTOR_T */
#ifndef EXTERN_TYPEDEF_XYZCOLOR_T
#define EXTERN_TYPEDEF_XYZCOLOR_T
	typedef void* XYZCOLOR_T;
#endif /* EXTERN_TYPEDEF_XYZCOLOR_T */
#ifndef EXTERN_TYPEDEF_CIECOLOR_T
#define EXTERN_TYPEDEF_CIECOLOR_T
	typedef void* CIECOLOR_T;
#endif /* EXTERN_TYPEDEF_CIECOLOR_T */
#ifndef EXTERN_TYPEDEF_JSTRING_T
#define EXTERN_TYPEDEF_JSTRING_T
	typedef void* JSTRING_T;
#endif /* EXTERN_TYPEDEF_JSTRING_T */
#ifndef EXTERN_TYPEDEF_COLORSPACEVALUEARRAY_T
#define EXTERN_TYPEDEF_COLORSPACEVALUEARRAY_T
	typedef void* COLORSPACEVALUEARRAY_T;
#endif /* EXTERN_TYPEDEF_COLORSPACEVALUEARRAY_T */

	// No public default Java constructor; creating one:
	EXPORTED XYZCOLOR_T XYZColor_Create();
	EXPORTED XYZCOLOR_T XYZColor_Create_1(double newX, double newY, double newZ);
	EXPORTED XYZCOLOR_T XYZColor_Create_2(XYZCOLOR_T that);
	EXPORTED XYZCOLOR_T XYZColor_Create_3(CIECOLOR_T that);
	EXPORTED double XYZColor_getX(XYZCOLOR_T c_xyzcolor);
	EXPORTED double XYZColor_getY(XYZCOLOR_T c_xyzcolor);
	EXPORTED double XYZColor_getZ(XYZCOLOR_T c_xyzcolor);
	EXPORTED double XYZColor_getColorDifference(XYZCOLOR_T c_xyzcolor, XYZCOLOR_T that);
	EXPORTED double XYZColor_getLittleX(XYZCOLOR_T c_xyzcolor);
	EXPORTED double XYZColor_getLittleY(XYZCOLOR_T c_xyzcolor);
	EXPORTED double XYZColor_getLittleZ(XYZCOLOR_T c_xyzcolor);
	EXPORTED void XYZColor_toString(XYZCOLOR_T c_xyzcolor, JSTRING_T retval);
	EXPORTED void XYZColor_getColorSpaceValues(XYZCOLOR_T c_xyzcolor, COLORSPACEVALUEARRAY_T retval);
	EXPORTED void XYZColor_Destroy(XYZCOLOR_T xyzcolor);

#ifdef WIN32
	// Use the following function prototypes when calling functions from Visual Basic 6
	EXPORTED XYZCOLOR_T STDCALL XYZColor_Create_stdcall_1(double newX, double newY, double newZ);
	EXPORTED XYZCOLOR_T STDCALL XYZColor_Create_stdcall_2(XYZCOLOR_T that);
	EXPORTED XYZCOLOR_T STDCALL XYZColor_Create_stdcall_3(CIECOLOR_T that);
	EXPORTED double STDCALL XYZColor_getX_stdcall(XYZCOLOR_T c_xyzcolor);
	EXPORTED double STDCALL XYZColor_getY_stdcall(XYZCOLOR_T c_xyzcolor);
	EXPORTED double STDCALL XYZColor_getZ_stdcall(XYZCOLOR_T c_xyzcolor);
	EXPORTED double STDCALL XYZColor_getColorDifference_stdcall(XYZCOLOR_T c_xyzcolor, XYZCOLOR_T that);
	EXPORTED double STDCALL XYZColor_getLittleX_stdcall(XYZCOLOR_T c_xyzcolor);
	EXPORTED double STDCALL XYZColor_getLittleY_stdcall(XYZCOLOR_T c_xyzcolor);
	EXPORTED double STDCALL XYZColor_getLittleZ_stdcall(XYZCOLOR_T c_xyzcolor);
	EXPORTED void STDCALL XYZColor_toString_stdcall(XYZCOLOR_T c_xyzcolor, JSTRING_T retval);
	EXPORTED void STDCALL XYZColor_getColorSpaceValues_stdcall(XYZCOLOR_T c_xyzcolor, COLORSPACEVALUEARRAY_T retval);
	EXPORTED void STDCALL XYZColor_Destroy_stdcall(XYZCOLOR_T xyzcolor);
#endif /* WIN32 */
#ifdef __cplusplus
};
#endif /* __cplusplus */
#endif /* XYZCOLOR_H */
