#include "stdafx.h"
#include "CEID_LIST.h"

CEID_LIST::CEID_LIST() {
	Load();
}

CEID_LIST::~CEID_LIST() {}

CEID_ITEM* CEID_LIST::GetItem(UINT ceid) {
	for (int i = 0; i < LASTCEID; i++) {
		if (m_Ceid[i].m_ceid == ceid) {
			return &m_Ceid[i];
		}
	}
	return NULL;
}

UINT CEID_LIST::GetIdx(UINT ceid) {
	for (int i = 0; i < LASTCEID; i++) {
		if (m_Ceid[i].m_ceid == ceid) {
			return i;
		}
	}
	return -1;
}

void CEID_LIST::Load() {
	int n, nn;

	n = 1;
	m_Ceid[ONLINEREMOTE].Set(n++, "ONLINE REMOTE");
	m_Ceid[ONLINELOCAL].Set(n++, "ONLINE LOCAL");
	m_Ceid[OFFLINEEQUIPMENT].Set(n++, "OFFLINE EQUIPMENT");
	m_Ceid[OFFLINEHOST].Set(n++, "OFFLINE HOST");

	nn = n;
	n = 10;
	if (n < nn) {
		ASSERT(0);
	}
	m_Ceid[EQUIPMENTIDLE].Set(n++, "EQUIPMENT IDLE");
	m_Ceid[EQUIPMENTWORKING].Set(n++, "EQUIPMENT WORKING");
	m_Ceid[EQUIPMENTMAINTENANCE].Set(n++, "EQUIPMENT MAINTENANCE");
	m_Ceid[EQUIPMENTINSERVICE].Set(n++, "EQUIPMENT IN SERVICE");
	m_Ceid[EQUIPMENTOUTOFSERVICE].Set(n++, "EQUIPMENT OUT OF SERVICE");

	nn = n;
	n = 20;
	if (n < nn) {
		ASSERT(0);
	}
	m_Ceid[ALARMSET].Set(n++, "ALARM SET");
	m_Ceid[ALARMCLEARED].Set(n++, "ALARM CLEARED");

	nn = n;
	n = 24;
	if (n < nn) {
		ASSERT(0);
	}
	m_Ceid[RESULTSINGLE].Set(n++, "PER POINT LEVEL RESULT");
	m_Ceid[RESULTWAFER].Set(n++, "PER WAFER LEVEL REULT");

	// 	n = 30;
	// 	m_Ceid[REMOTESTART].Set(n++,"REMOTE START");
	// 	m_Ceid[REMOTEPAUSE].Set(n++,"REMOTE PAUSE");
	// 	m_Ceid[REMOTERESUME].Set(n++,"REMOTE RESUME");
	// 	m_Ceid[REMOTECANCEL].Set(n++,"REMOTE CANCEL");
	// 	m_Ceid[REMOTEABORT].Set(n++,"REMOTE ABORT");
	// 	m_Ceid[REMOTESTOP].Set(n++,"REMOTE STOP");

	nn = n;
	n = 40;
	if (n < nn) {
		ASSERT(0);
	}
	m_Ceid[CANCELNOTPOSSIBLE].Set(n++, "CANCEL NOT POSSIBLE");
	m_Ceid[CARRIERNOTFOUND].Set(n++, "CARRIER NOT FOUND");
	m_Ceid[CARRIERREMOVEFAILED].Set(n++, "CARRIER REMOVE FAILED");
	m_Ceid[CARRIERREMOVEOK].Set(n++, "CARRIER REMOVE OK");
	m_Ceid[CARRIEROBJECTDELETED].Set(n++, "CARRIER OBJECT DELETED");
	m_Ceid[CARRIERWAITFORCJTIMEOUT].Set(n++, "CARRIER WAIT FOR CJ TIMEOUT");

	nn = n;
	n = 50;
	if (n < nn) {
		ASSERT(0);
	}
	m_Ceid[INVALIDPORTID].Set(n++, "INVALID PORT ID");
	m_Ceid[NOTREADYTOLOAD].Set(n++, "NOT READY TO LOAD");
	m_Ceid[PORTISASSOCIATED].Set(n++, "PORT IS ASSOCIATED");
	m_Ceid[PORTISNOTASSOCIATED].Set(n++, "PORT IS NOT ASSOCIATED");

	nn = n;
	n = 60;
	if (n < nn) {
		ASSERT(0);
	}
	m_Ceid[PROCESSINGSTART].Set(n++, "PROCESSING START");
	m_Ceid[PROCESSINGCOMPLETE].Set(n++, "PROCESSING COMPLETE");
	m_Ceid[PROCESSINGSTOPPED].Set(n++, "PROCESSING STOPPED");
	m_Ceid[PROCESSINGSTATECHANGE].Set(n++, "PROCESSING STATE CHANGE");
	m_Ceid[WAFERPROCESSINGCOMPLETE].Set(n++, "WAFER PROCESSING COMPLETE");

	nn = n;
	n = 100;
	if (n < nn) {
		ASSERT(0);
	}
	m_Ceid[LP1CARRIERARRIVED].Set(n++, "LP1 CARRIER ARRIVED");
	m_Ceid[LP1CLAMPCOMPLETE].Set(n++, "LP1 CLAMP COMPLETE");
	m_Ceid[LP1CARRIERDOCKED].Set(n++, "LP1 CARRIER DOCKED");
	m_Ceid[LP1CARRIEROPENED].Set(n++, "LP1 CARRIER OPENED");
	m_Ceid[LP1CARRIEROPENFAILED].Set(n++, "LP1 CARRIER OPEN FAILED");
	m_Ceid[LP1CARRIERUNDOCKED].Set(n++, "LP1 CARRIER UNDOCKED");
	m_Ceid[LP1CARRIERCLOSED].Set(n++, "LP1 CARRIER CLOSED");
	m_Ceid[LP1CARRIERCLAMPPED].Set(n++, "LP1 CARRIER CLAMPPED");
	m_Ceid[LP1CARRIERUNCLAMPED].Set(n++, "LP1 CARRIER UNCLAMPED");
	m_Ceid[LP1CARRIERREMOVED].Set(n++, "LP1 CARRIER REMOVED");
	m_Ceid[LP1OUTOFSERVICE].Set(n++, "LP1 OUTOFSERVICE");
	m_Ceid[LP1READYTOLOAD].Set(n++, "LP1 READY TO LOAD");
	m_Ceid[LP1READYTOUNLOAD].Set(n++, "LP1 READY TO UNLOAD");
	m_Ceid[LP1TRANSFERBLOCKED].Set(n++, "LP1 TRANSFER BLOCKED");
	m_Ceid[LP1CANCELCARRIEROK].Set(n++, "LP1 CANCEL CARRIER OK");
	m_Ceid[LP1CANCELCARRIERFAILED].Set(n++, "LP1 CANCEL CARRIER FAILED");
	m_Ceid[LP1CARRIERLOCATIONCHANGED].Set(n++, "LP1 CARRIER LOCATION CHANGED");
	m_Ceid[LP1LOADCOMPLETE].Set(n++, "LP1 LOAD COMPLETE");
	// 	m_Ceid[LP1WAITINGFORHOSTCID].Set(n++,"LP1 WAITING FOR HOST (CID)");
	// 	m_Ceid[LP1CARRIERIDVERIOK].Set(n++,"LP1 CARRIER ID VERIFICATION OK");
	// 	m_Ceid[LP1SLOTMAPREADOK].Set(n++,"LP1 SLOTMAP READ OK");
	// 	m_Ceid[LP1SLOTMAPVERIFIED].Set(n++,"LP1 SLOTMAP VERIFIED");
	m_Ceid[LP1CARRIERCOMPLETE].Set(n++, "LP1 CARRIER COMPLETE");
	m_Ceid[LP1WAFERREMOVED].Set(n++, "LP1 WAFER REMOVED");
	m_Ceid[LP1WAFERRETURNED].Set(n++, "LP1 WAFER RETURNED");

	nn = n;
	n = 150;
	if (n < nn) {
		ASSERT(0);
	}
	m_Ceid[LP1NOSTATE2INSERVICE].Set(n++, "LP1 NO STATE 2 IN SERVICE");
	m_Ceid[LP1NOSTATE2OUTOFSERVICE].Set(n++, "LP1 NO STATE 2 OUT OF SERVICE");
	m_Ceid[LP1OUTOFSERVICE2INSERVICE].Set(n++, "LP1 OUT OF SERVICE 2 IN SERVICE");
	m_Ceid[LP1INSERVICE2OUTOFSERVICE].Set(n++, "LP1 IN SERVICE 2 OUT OF SERVICE");
	m_Ceid[LP1INSERVICE2TRANSFERBLOCKED].Set(n++, "LP1 IN SERVICE 2 TRANSFER BLOCKED");
	m_Ceid[LP1INSERVICE2TRANSFERREADY].Set(n++, "LP1 IN SERVICE 2 TRANSFER READY");
	m_Ceid[LP1TRANSFERREADY2READYTOLOAD].Set(n++, "LP1 TRANSFER READY 2 READY TO LOAD");
	m_Ceid[LP1TRANSFERREADY2READYTOUNLOAD].Set(n++, "LP1 TRANSFER READY 2 READY TO UNLOAD");
	m_Ceid[LP1READYTOLOAD2TRANSFERBLOCKED].Set(n++, "LP1 READY TO LOAD 2 TRANSFER BLOCKED");
	m_Ceid[LP1READYTOUNLOAD2TRANSFERBLOCKED].Set(n++, "LP1 READY TO UNLOAD 2 TRANSFER BLOCKED");
	m_Ceid[LP1TRANSFERBLOCKED2READYTOLOAD].Set(n++, "LP1 TRANSFER BLOCKED 2 READY TO LOAD");
	m_Ceid[LP1TRANSFERBLOCKED2READYTOUNLOAD].Set(n++, "LP1 TRANSFER BLOCKED 2 READY TO UNLOAD");
	m_Ceid[LP1TRANSFERBLOCKED2TRANSFERREADY].Set(n++, "LP1 TRANSFER BLOCKED 2 TRANSFER READY");

	nn = n;
	n = 180;
	if (n < nn) {
		ASSERT(0);
	}
	m_Ceid[CST1NOSTATETOCARRIER].Set(n++, "LP1 NO STATE TO CARRIER");
	m_Ceid[CST1NOSTATETOIDNOTREAD].Set(n++, "LP1 NO STATE TO ID NO TREAD");
	m_Ceid[CST1NOSTATETOWAITINGFORHOST].Set(n++, "LP1 NO STATE TO WAITING FOR HOST");
	m_Ceid[CST1NOSTATETOIDVEROK].Set(n++, "LP1 NO STATE TO ID VER OK");
	m_Ceid[CST1NOSTATETOIDVERFAIL].Set(n++, "LP1 NO STATE TO ID VER FAIL");
	m_Ceid[CST1IDNOTREADTOIDVEROK].Set(n++, "LP1 ID NO TREAD TO ID VER OK");
	m_Ceid[CST1IDNOTREADTOWAITINGFORHOST].Set(n++, "LP1 ID NOT READ TO WAITING FOR HOST");
	m_Ceid[CST1WAITINGFORHOSTTOIDVEROK].Set(n++, "LP1 WAITING FOR HOST TO ID VER OK");
	m_Ceid[CST1WAITINGFORHOSTTOIDVERFAIL].Set(n++, "LP1 WAITING FOR HOST TO ID VER FAIL");

	nn = n;
	n = 210;
	if (n < nn) {
		ASSERT(0);
	}
	m_Ceid[CST1NOSTATETOSLOTMAPNOTREAD].Set(n++, "LP1 NO STATE TO SLOTMAP NOT READ");
	m_Ceid[CST1SLOTMAPNOTREADTOSLOTMAPVEROK].Set(n++, "LP1 SLOTMAP NOT READ TO SLOTMAP VER OK");
	m_Ceid[CST1SLOTMAPNOTREADTOWAITINGFORHOST].Set(n++, "LP1 SLOTMAP NOT READ TO WAITING FOR HOST");
	m_Ceid[CST1WAITINGFORHOSTTOSLOTMAPVEROK].Set(n++, "LP1 WAITING FOR HOST TO SLOTMAP VER OK");
	m_Ceid[CST1WAITINGFORHOSTTOSLOTMAPVERFAIL].Set(n++, "LP1 WAITING FOR HOST TO SLOTMAP VER FAIL");
	m_Ceid[CST1NOSTATETONOTACCESSED].Set(n++, "LP1 NO STATE TO NOT ACCESSED");
	m_Ceid[CST1NOTACCESSEDTOINACCESS].Set(n++, "LP1 NOT ACCESSED TO IN ACCESS");
	m_Ceid[CST1INACCESSTOCARRIERCOMPLETE].Set(n++, "LP1 IN ACCESS TO CARRIER COMPLETE");
	m_Ceid[CST1INACCESSTOCARRIERSTOPPED].Set(n++, "LP1 IN ACCESS TO CARRIE RSTOPPED");
	m_Ceid[CST1CARRIERTONOSTATE].Set(n++, "LP1 CARRIER TO NO STATE");

	nn = n;
	n = 230;
	if (n < nn) {
		ASSERT(0);
	}
	m_Ceid[AMSM1NOSTATETOMANUAL].Set(n++, "LP1 NO STATE TO MANUAL");
	m_Ceid[AMSM1NOSTATETOAUTO].Set(n++, "LP1 NO STATE TO AUTO");
	m_Ceid[AMSM1MANUALTOAUTO].Set(n++, "LP1 MANUAL TO AUTO");
	m_Ceid[AMSM1AUTOTOMANUAL].Set(n++, "LP1 AUTO TO MANUAL");

	nn = n;
	n = 240;
	if (n < nn) {
		ASSERT(0);
	}
	m_Ceid[LPRSTM1NOSTATETONOTRESERVED].Set(n++, "LP1 NO STATE TO NOT RESERVED");
	m_Ceid[LPRSTM1NOTRESERVEDTORESERVED].Set(n++, "LP1 NOT RESERVED TO RESERVED");
	m_Ceid[LPRSTM1RESERVEDTONOTRESERVED].Set(n++, "LP1 RESERVED TO NOT RESERVED");

	nn = n;
	n = 250;
	if (n < nn) {
		ASSERT(0);
	}
	m_Ceid[LPASM1NOSTATETONOTASSOCIATED].Set(n++, "LP1 NO STATE TO NOT ASSOCIATED");
	m_Ceid[LPASM1NOTASSOCIATEDTOASSOCIATED].Set(n++, "LP1 NOT ASSOCIATED TO ASSOCIATED");
	m_Ceid[LPASM1ASSOCIATEDTONOTASSOCIATED].Set(n++, "LP1 ASSOCIATED TO NOT ASSOCIATED");
	m_Ceid[LPASM1ASSOCIATEDTOASSOCIATED].Set(n++, "LP1 ASSOCIATED TO ASSOCIATED");

	nn = n;
	n = 260;
	if (n < nn) {
		ASSERT(0);
	}
	m_Ceid[LPASM1NOSTATETONOTOCCUPIED].Set(n++, "LP1 NO STATE TO NOT OCCUPIED");
	m_Ceid[LPASM1NOTOCCUPIEDTOOCCUPIED].Set(n++, "LP1 NOT OCCUPIED TO OCCUPIED");
	m_Ceid[LPASM1OCCUPIEDTONOTOCCUPIED].Set(n++, "LP1 OCCUPIED TO NOT OCCUPIED");

	nn = n;
	n = 300;
	if (n < nn) {
		ASSERT(0);
	}
	m_Ceid[LP2NOSTATE2INSERVICE].Set(n++, "LP2 NO STATE 2 IN SERVICE");
	m_Ceid[LP2NOSTATE2OUTOFSERVICE].Set(n++, "LP2 NO STATE 2 OUT OF SERVICE");
	m_Ceid[LP2OUTOFSERVICE2INSERVICE].Set(n++, "LP2 OUT OF SERVICE 2 IN SERVICE");
	m_Ceid[LP2INSERVICE2OUTOFSERVICE].Set(n++, "LP2 IN SERVICE 2 OUT OF SERVICE");
	m_Ceid[LP2INSERVICE2TRANSFERBLOCKED].Set(n++, "LP2 IN SERVICE 2 TRANSFER BLOCKED");
	m_Ceid[LP2INSERVICE2TRANSFERREADY].Set(n++, "LP2 IN SERVICE 2 TRANSFER READY");
	m_Ceid[LP2TRANSFERREADY2READYTOLOAD].Set(n++, "LP2 TRANSFER READY 2 READY TO LOAD");
	m_Ceid[LP2TRANSFERREADY2READYTOUNLOAD].Set(n++, "LP2 TRANSFER READY 2 READY TO UNLOAD");
	m_Ceid[LP2READYTOLOAD2TRANSFERBLOCKED].Set(n++, "LP2 READY TO LOAD 2 TRANSFER BLOCKED");
	m_Ceid[LP2READYTOUNLOAD2TRANSFERBLOCKED].Set(n++, "LP2 READY TO UNLOAD 2 TRANSFER BLOCKED");
	m_Ceid[LP2TRANSFERBLOCKED2READYTOLOAD].Set(n++, "LP2 TRANSFER BLOCKED 2 READY TO LOAD");
	m_Ceid[LP2TRANSFERBLOCKED2READYTOUNLOAD].Set(n++, "LP2 TRANSFER BLOCKED 2 READY TO UNLOAD");
	m_Ceid[LP2TRANSFERBLOCKED2TRANSFERREADY].Set(n++, "LP2 TRANSFER BLOCKED 2 TRANSFER READY");

	nn = n;
	n = 350;
	if (n < nn) {
		ASSERT(0);
	}
	m_Ceid[LP2CARRIERARRIVED].Set(n++, "LP2 CARRIER ARRIVED");
	m_Ceid[LP2CLAMPCOMPLETE].Set(n++, "LP2 CLAMP COMPLETE");
	m_Ceid[LP2CARRIERDOCKED].Set(n++, "LP2 CARRIER DOCKED");
	m_Ceid[LP2CARRIEROPENED].Set(n++, "LP2 CARRIER OPENED");
	m_Ceid[LP2CARRIEROPENFAILED].Set(n++, "LP2 CARRIER OPEN FAILED");
	m_Ceid[LP2CARRIERUNDOCKED].Set(n++, "LP2 CARRIER UNDOCKED");
	m_Ceid[LP2CARRIERCLOSED].Set(n++, "LP2 CARRIER CLOSED");
	m_Ceid[LP2CARRIERCLAMPPED].Set(n++, "LP2 CARRIER CLAMPPED");
	m_Ceid[LP2CARRIERUNCLAMPED].Set(n++, "LP2 CARRIER UNCLAMPED");
	m_Ceid[LP2CARRIERREMOVED].Set(n++, "LP2 CARRIER REMOVED");
	m_Ceid[LP2OUTOFSERVICE].Set(n++, "LP2 OUTOFSERVICE");
	m_Ceid[LP2READYTOLOAD].Set(n++, "LP2 READY TO LOAD");
	m_Ceid[LP2READYTOUNLOAD].Set(n++, "LP2 READY TO UNLOAD");
	m_Ceid[LP2TRANSFERBLOCKED].Set(n++, "LP2 TRANSFER BLOCKED");
	m_Ceid[LP2CANCELCARRIEROK].Set(n++, "LP2 CANCEL CARRIER OK");
	m_Ceid[LP2CANCELCARRIERFAILED].Set(n++, "LP2 CANCEL CARRIER FAILED");
	m_Ceid[LP2CARRIERLOCATIONCHANGED].Set(n++, "LP2 CARRIER LOCATION CHANGED");
	m_Ceid[LP2LOADCOMPLETE].Set(n++, "LP2 LOAD COMPLETE");
	// 	m_Ceid[LP2WAITINGFORHOSTCID].Set(n++,"LP2 WAITING FOR HOST (CID)");
	// 	m_Ceid[LP2CARRIERIDVERIOK].Set(n++,"LP2 CARRIER ID VERIFICATION OK");
	// 	m_Ceid[LP2SLOTMAPREADOK].Set(n++,"LP2 SLOTMAP READ OK");
	// 	m_Ceid[LP2SLOTMAPVERIFIED].Set(n++,"LP2 SLOTMAP VERIFIED");
	m_Ceid[LP2CARRIERCOMPLETE].Set(n++, "LP2 CARRIER COMPLETE");
	m_Ceid[LP2WAFERREMOVED].Set(n++, "LP2 WAFER REMOVED");
	m_Ceid[LP2WAFERRETURNED].Set(n++, "LP2 WAFER RETURNED");

	nn = n;
	n = 380;
	if (n < nn) {
		ASSERT(0);
	}
	m_Ceid[CST2NOSTATETOCARRIER].Set(n++, "LP2 NO STATE TO CARRIER");
	m_Ceid[CST2NOSTATETOIDNOTREAD].Set(n++, "LP2 NO STATE TO ID NO TREAD");
	m_Ceid[CST2NOSTATETOWAITINGFORHOST].Set(n++, "LP2 NO STATE TO WAITING FOR HOST");
	m_Ceid[CST2NOSTATETOIDVEROK].Set(n++, "LP2 NO STATE TO ID VER OK");
	m_Ceid[CST2NOSTATETOIDVERFAIL].Set(n++, "LP2 NO STATE TO ID VER FAIL");
	m_Ceid[CST2IDNOTREADTOIDVEROK].Set(n++, "LP2 ID NO TREAD TO ID VER OK");
	m_Ceid[CST2IDNOTREADTOWAITINGFORHOST].Set(n++, "LP2 ID NOT READ TO WAITING FOR HOST");
	m_Ceid[CST2WAITINGFORHOSTTOIDVEROK].Set(n++, "LP2 WAITING FOR HOST TO ID VER OK");
	m_Ceid[CST2WAITINGFORHOSTTOIDVERFAIL].Set(n++, "LP2 WAITING FOR HOST TO ID VER FAIL");

	nn = n;
	n = 410;
	if (n < nn) {
		ASSERT(0);
	}
	m_Ceid[CST2NOSTATETOSLOTMAPNOTREAD].Set(n++, "LP2 NO STATE TO SLOTMAP NOT READ");
	m_Ceid[CST2SLOTMAPNOTREADTOSLOTMAPVEROK].Set(n++, "LP2 SLOTMAP NOT READ TO SLOTMAP VER OK");
	m_Ceid[CST2SLOTMAPNOTREADTOWAITINGFORHOST].Set(n++, "LP2 SLOTMAP NOT READ TO WAITING FOR HOST");
	m_Ceid[CST2WAITINGFORHOSTTOSLOTMAPVEROK].Set(n++, "LP2 WAITING FOR HOST TO SLOTMAP VER OK");
	m_Ceid[CST2WAITINGFORHOSTTOSLOTMAPVERFAIL].Set(n++, "LP2 WAITING FOR HOST TO SLOTMAP VER FAIL");
	m_Ceid[CST2NOSTATETONOTACCESSED].Set(n++, "LP2 NO STATE TO NOT ACCESSED");
	m_Ceid[CST2NOTACCESSEDTOINACCESS].Set(n++, "LP2 NOT ACCESSED TO IN ACCESS");
	m_Ceid[CST2INACCESSTOCARRIERCOMPLETE].Set(n++, "LP2 IN ACCESS TO CARRIER COMPLETE");
	m_Ceid[CST2INACCESSTOCARRIERSTOPPED].Set(n++, "LP2 IN ACCESS TO CARRIE RSTOPPED");
	m_Ceid[CST2CARRIERTONOSTATE].Set(n++, "LP2 CARRIER TO NO STATE");

	nn = n;
	n = 420;
	if (n < nn) {
		ASSERT(0);
	}
	m_Ceid[AMSM2NOSTATETOMANUAL].Set(n++, "LP2 NO STATE TO MANUAL");
	m_Ceid[AMSM2NOSTATETOAUTO].Set(n++, "LP2 NO STATE TO AUTO");
	m_Ceid[AMSM2MANUALTOAUTO].Set(n++, "LP2 MANUAL TO AUTO");
	m_Ceid[AMSM2AUTOTOMANUAL].Set(n++, "LP2 AUTO TO MANUAL");

	nn = n;
	n = 430;
	if (n < nn) {
		ASSERT(0);
	}
	m_Ceid[LPRSTM2NOSTATETONOTRESERVED].Set(n++, "LP2 NO STATE TO NOT RESERVED");
	m_Ceid[LPRSTM2NOTRESERVEDTORESERVED].Set(n++, "LP2 NOT RESERVED TO RESERVED");
	m_Ceid[LPRSTM2RESERVEDTONOTRESERVED].Set(n++, "LP2 RESERVED TO NOT RESERVED");

	nn = n;
	n = 440;
	if (n < nn) {
		ASSERT(0);
	}
	m_Ceid[LPASM2NOSTATETONOTASSOCIATED].Set(n++, "LP2 NO STATE TO NOT ASSOCIATED");
	m_Ceid[LPASM2NOTASSOCIATEDTOASSOCIATED].Set(n++, "LP2 NOT ASSOCIATED TO ASSOCIATED");
	m_Ceid[LPASM2ASSOCIATEDTONOTASSOCIATED].Set(n++, "LP2 ASSOCIATED TO NOT ASSOCIATED");
	m_Ceid[LPASM2ASSOCIATEDTOASSOCIATED].Set(n++, "LP2 ASSOCIATED TO ASSOCIATED");

	nn = n;
	n = 450;
	if (n < nn) {
		ASSERT(0);
	}
	m_Ceid[LPASM2NOSTATETONOTOCCUPIED].Set(n++, "LP2 NO STATE TO NOT OCCUPIED");
	m_Ceid[LPASM2NOTOCCUPIEDTOOCCUPIED].Set(n++, "LP2 NOT OCCUPIED TO OCCUPIED");
	m_Ceid[LPASM2OCCUPIEDTONOTOCCUPIED].Set(n++, "LP2 OCCUPIED TO NOT OCCUPIED");

	nn = n;
	n = 500;
	if (n < nn) {
		ASSERT(0);
	}
	m_Ceid[SSMNOSTATETOATSOURCE].Set(n++, "NO STATE TO AT SOURCE");
	m_Ceid[SSMATSOURCETOATWORK].Set(n++, "AT SOURCE TO AT WORK");
	m_Ceid[SSMATWORKTOATSOURCE].Set(n++, "AT WORK TO AT SOURCE");
	m_Ceid[SSMATWORKTOATWORK].Set(n++, "AT WORK TO AT WORK");
	m_Ceid[SSMATWORKTOATDESTINATION].Set(n++, "AT WORK TO AT DESTINATION");
	m_Ceid[SSMATDESTINATIONTOATWORK].Set(n++, "AT DESTINATION TO AT WORK");
	m_Ceid[SSMATDESTINITIONTOEXTINCTION].Set(n++, "AT DESTINITION TO EXTINCTION");
	m_Ceid[SSMATDESTINATIONTOATSOURCE].Set(n++, "AT DESTINATION TO AT SOURCE");
	m_Ceid[SSMANYSUBSTRATETOEXTINCTION].Set(n++, "ANY SUBSTRATE TO EXTINCTION");
	m_Ceid[SSMNOSTATETONEEDSPROCESSING].Set(n++, "NO STATE TO NEEDS PROCESSING");
	m_Ceid[SSMNEEDSPROCESSINGTOINPROGRESS].Set(n++, "NEEDS PROCESSING TO IN PROGRESS");
	m_Ceid[SSMINPROCESSTOPROCESSINGCOMPLETE].Set(n++, "IN PROCESS TO PROCESSING COMPLETE");
	m_Ceid[SSMINPROCESSTONEEDSPROCESSING].Set(n++, "IN PROCESS TO NEEDS PROCESSING");

	nn = n;
	n = 520;
	if (n < nn) {
		ASSERT(0);
	}
	m_Ceid[PJSM01NOSTATETOQUEUED].Set(n++, "PJ NO STATE TO QUEUED");
	m_Ceid[PJSM02QUEUEDTOSETTINGUP].Set(n++, "PJ QUEUED TO SETTING UP");
	m_Ceid[PJSM03SETTINGUPTOWAITINGFORSTART].Set(n++, "PJ SETTING UP TO WAITING FOR START");
	m_Ceid[PJSM04SETTINGUPTOPROCESSING].Set(n++, "PJ SETTING UP TO PROCESSING");
	m_Ceid[PJSM05WAITINGFORSTARTTOPROCESSING].Set(n++, "PJ WAITING FOR START TO PROCESSING");
	m_Ceid[PJSM06PROCESSINGTOPROCESSCOMPLETE].Set(n++, "PJ EXECUTING TO PROCESS COMPLETE");
	m_Ceid[PJSM07PROCESSCOMPLETETONOSTATE].Set(n++, "PJ PROCESS COMPLETE TO NO STATE");
	m_Ceid[PJSM08EXECUTINGTOPAUSING].Set(n++, "PJ EXECUTING TO PAUSING");
	m_Ceid[PJSM09PAUSINGTOPAUSED].Set(n++, "PJ PAUSING TO PAUSED");
	m_Ceid[PJSM10PAUSETOEXECUTING].Set(n++, "PJ PAUSE TO EXECUTING");
	m_Ceid[PJSM11EXECUTINGTOSTOPPING].Set(n++, "PJ EXECUTING TO STOPPING");
	m_Ceid[PJSM12PAUSETOSTOPPING].Set(n++, "PJ PAUSE TO STOPPING");
	m_Ceid[PJSM13EXECUTINGTOABORTING].Set(n++, "PJ EXECUTING TO ABORTING");
	m_Ceid[PJSM14STOPPINGTOABORTING].Set(n++, "PJ STOPPING TO ABORTING");
	m_Ceid[PJSM15PAUSETOABORTING].Set(n++, "PJ PAUSE TO ABORTING");
	m_Ceid[PJSM16ABORTINGTONOSTATE].Set(n++, "PJ ABORTING TO NO STATE");
	m_Ceid[PJSM17STOPPINGTONOSTATE].Set(n++, "PJ STOPPING TO NO STATE");
	m_Ceid[PJSM18QUEUEDTONOSTATE].Set(n++, "PJ QUEUED TO NO STATE");

	nn = n;
	n = 540;
	if (n < nn) {
		ASSERT(0);
	}
	m_Ceid[CJSM01NOSTATETOQUEUED].Set(n++, "CJ NO STATE TO QUEUED");
	m_Ceid[CJSM02QUEUEDTONOSTATE].Set(n++, "CJ QUEUED TO NO STATE");
	m_Ceid[CJSM03QUEUEDTOSELECTED].Set(n++, "CJ QUEUED TO SELECTED");
	m_Ceid[CJSM04SELECTEDTOQUEUED].Set(n++, "CJ SELECTED TO QUEUED");
	m_Ceid[CJSM05SELECTEDTOEXECUTING].Set(n++, "CJ SELECTED TO EXECUTING");
	m_Ceid[CJSM06SELECTEDTOWAITINGFORSTART].Set(n++, "CJ SELECTED TO WAITING FOR START");
	m_Ceid[CJSM07WAITINGFORSTARTTOEXECUTING].Set(n++, "CJ WAITING FOR START TO EXECUTING");
	m_Ceid[CJSM08EXECUTINGTOPAUSED].Set(n++, "CJ EXECUTING TO PAUSED");
	m_Ceid[CJSM09PAUSEDTOEXECUTING].Set(n++, "CJ PAUSED TO EXECUTING");
	m_Ceid[CJSM10EXECUTINGTOCOMPLETED].Set(n++, "CJ EXECUTING TO COMPLETED");
	m_Ceid[CJSM11ACTIVETOCOMPLETEDSTOP].Set(n++, "CJ ACTIVE TO COMPLETED STOP");
	m_Ceid[CJSM12ACTIVETOCOMPLETEDABORT].Set(n++, "CJ ACTIVE TO COMPLETED ABORT");
	m_Ceid[CJSM13COMPLETEDTONOSTATE].Set(n++, "CJ COMPLETED TO NO STATE");

	nn = n;
	n = 560;
	if (n < nn) {
		ASSERT(0);
	}
	m_Ceid[PJALERTSETUP].Set(n++, "PJ ALERT SETUP");
	m_Ceid[PJALERTPROCESSING].Set(n++, "PJ ALERT PROCESSING");
	m_Ceid[PJALERTPROCESINGCOMPLETE].Set(n++, "PJ ALERT PROCESING COMPLETE");
	m_Ceid[PJALERTCOMPLETE].Set(n++, "PJ ALERT COMPLETE");
	m_Ceid[PJALERTWAITINGFORSTART].Set(n++, "PJ ALERT WAITING FOR START");
	m_Ceid[PJALERTWAITINGFORMATL].Set(n++, "PJ ALERT WAITING FOR MATERIAL");

	nn = n;
	n = 600;
	if (n < nn) {
		ASSERT(0);
	}
	m_Ceid[PROCESSPROGRAMCHANGED].Set(n++, "PROCESS PROGRAM CHANGED");
	m_Ceid[PROCESSPROGRAMSELECTED].Set(n++, "PROCESS PROGRAM SELECTED");

	nn = n;
	n = 610;
	if (n < nn) {
		ASSERT(0);
	}
	m_Ceid[CANCELBINDOK].Set(n++, "CANCEL BIND OK");
	m_Ceid[INVALIDCARRIERID].Set(n++, "INVALID CARRIER ID");

	nn = n;
	n = 620;
	if (n < nn) {
		ASSERT(0);
	}
	m_Ceid[BINDOK].Set(n++, "BIND OK");
	m_Ceid[BINDCREATEFAIL].Set(n++, "BIND CREATE FAIL");
	m_Ceid[DUPLICATEDCARRIER].Set(n++, "DUPLICATED CARRIER");

	nn = n;
	n = 630;
	if (n < nn) {
		ASSERT(0);
	}
	m_Ceid[SPOOLACTIVATED].Set(n++, "SPOOL ACTIVATED");
	m_Ceid[SPOOLDEACTIVATED].Set(n++, "SPOOL DEACTIVATED");

	nn = n;
	n = 640;
	if (n < nn) {
		ASSERT(0);
	}
	m_Ceid[SMSNOTOCCUPIED].Set(n++, "CARRIEER SLOT NOT OCCUPIED");
	m_Ceid[SMSCORRECTLYOCCUPIED].Set(n++, "CARRIEER SLOT CORRECTLY OCCUPIED");
	m_Ceid[SMSCROSSSLOTTED].Set(n++, "CARRIEER SLOT CROSS SLOTTED");
	m_Ceid[SMSDOUBLESLOTTED].Set(n++, "CARRIEER SLOT DOUBLE SLOTTED");
	m_Ceid[SMSNOTEMPTY].Set(n++, "CARRIEER SLOT NOT EMPTY");

	nn = n;
	n = 650;
	if (n < nn) {
		ASSERT(0);
	}
	m_Ceid[SLSCANNERNOTOCCUPIED].Set(n++, "SCANNER LOCATION NOT OCCUPIED");
	m_Ceid[SLSCANNEROCCUPIED].Set(n++, "SCANNER LOCATION CORRECTLY OCCUPIED");
	m_Ceid[LP1SLOTMAPAVAILABLE].Set(n++, "LP1 SLOT MAP AVAILABLE");
	m_Ceid[LP2SLOTMAPAVAILABLE].Set(n++, "LP2 SLOT MAP AVAILABLE");

	nn = n;
	n = 700;
	if (n < nn) {
		ASSERT(0);
	}
	m_Ceid[DOOROPENED].Set(n++, "DOOR OPENED");
}

int CEID_LIST::GetID(int idx) {
	if ((idx >= 0) && (idx < LASTCEID)) {
		return m_Ceid[idx].m_ceid;
	}
	ASSERT(0);
	return 0;
}