#pragma once

#include "CEID_ITEM.h"

class CEID_LIST {
public:

	enum CEIDNAME {
		// Line Mode [8/7/2010 XPMUser]
		ONLINEREMOTE,
		ONLINELOCAL,
		OFFLINEEQUIPMENT,
		OFFLINEHOST,

		// Equipment [8/7/2010 XPMUser]
		EQUIPMENTIDLE,
		EQUIPMENTWORKING,
		EQUIPMENTMAINTENANCE,
		EQUIPMENTINSERVICE,
		EQUIPMENTOUTOFSERVICE,

		// ALARM SECTION
		ALARMSET,
		ALARMCLEARED,

		// Measurement [8/17/2010 XPMUser]
		RESULTSINGLE,
		RESULTWAFER,

		// Carrier Related [8/7/2010 XPMUser]
		CANCELNOTPOSSIBLE,
		CARRIERNOTFOUND,
		CARRIERREMOVEFAILED,
		CARRIERREMOVEOK,
		CARRIEROBJECTDELETED,
		CARRIERWAITFORCJTIMEOUT,

		// Reservation
		INVALIDPORTID,
		NOTREADYTOLOAD,
		PORTISASSOCIATED,
		PORTISNOTASSOCIATED,

		// Processing related [8/7/2010 XPMUser]
		PROCESSINGSTART,
		PROCESSINGCOMPLETE,
		PROCESSINGSTOPPED,
		PROCESSINGSTATECHANGE,
		WAFERPROCESSINGCOMPLETE,

		LP1CARRIERARRIVED,
		LP1CLAMPCOMPLETE,
		LP1CARRIERDOCKED,
		LP1CARRIEROPENED,
		LP1CARRIEROPENFAILED,
		LP1CARRIERUNDOCKED,
		LP1CARRIERCLOSED,
		LP1CARRIERCLAMPPED,
		LP1CARRIERUNCLAMPED,
		LP1CARRIERREMOVED,
		LP1OUTOFSERVICE,
		LP1READYTOLOAD,
		LP1READYTOUNLOAD,
		LP1TRANSFERBLOCKED,
		LP1CANCELCARRIEROK,
		LP1CANCELCARRIERFAILED,
		LP1CARRIERLOCATIONCHANGED,
		LP1LOADCOMPLETE,
		//LP1WAITINGFORHOSTCID,
		//LP1CARRIERIDVERIOK,
		//LP1SLOTMAPREADOK,
		//LP1SLOTMAPVERIFIED,
		LP1CARRIERCOMPLETE,
		LP1WAFERREMOVED,
		LP1WAFERRETURNED,

		LP1NOSTATE2INSERVICE,
		LP1NOSTATE2OUTOFSERVICE,
		LP1OUTOFSERVICE2INSERVICE,
		LP1INSERVICE2OUTOFSERVICE,
		LP1INSERVICE2TRANSFERBLOCKED,
		LP1INSERVICE2TRANSFERREADY,
		LP1TRANSFERREADY2READYTOLOAD,
		LP1TRANSFERREADY2READYTOUNLOAD,
		LP1READYTOLOAD2TRANSFERBLOCKED,
		LP1READYTOUNLOAD2TRANSFERBLOCKED,
		LP1TRANSFERBLOCKED2READYTOLOAD,
		LP1TRANSFERBLOCKED2READYTOUNLOAD,
		LP1TRANSFERBLOCKED2TRANSFERREADY,

		CST1NOSTATETOCARRIER,
		CST1NOSTATETOIDNOTREAD,
		CST1NOSTATETOWAITINGFORHOST,
		CST1NOSTATETOIDVEROK,
		CST1NOSTATETOIDVERFAIL,
		CST1IDNOTREADTOIDVEROK,
		CST1IDNOTREADTOWAITINGFORHOST,
		CST1WAITINGFORHOSTTOIDVEROK,
		CST1WAITINGFORHOSTTOIDVERFAIL,

		CST1NOSTATETOSLOTMAPNOTREAD,
		CST1SLOTMAPNOTREADTOSLOTMAPVEROK,
		CST1SLOTMAPNOTREADTOWAITINGFORHOST,
		CST1WAITINGFORHOSTTOSLOTMAPVEROK,
		CST1WAITINGFORHOSTTOSLOTMAPVERFAIL,
		CST1NOSTATETONOTACCESSED,
		CST1NOTACCESSEDTOINACCESS,
		CST1INACCESSTOCARRIERCOMPLETE,
		CST1INACCESSTOCARRIERSTOPPED,
		CST1CARRIERTONOSTATE,

		AMSM1NOSTATETOMANUAL,
		AMSM1NOSTATETOAUTO,
		AMSM1MANUALTOAUTO,
		AMSM1AUTOTOMANUAL,

		LPRSTM1NOSTATETONOTRESERVED,
		LPRSTM1NOTRESERVEDTORESERVED,
		LPRSTM1RESERVEDTONOTRESERVED,

		LPASM1NOSTATETONOTASSOCIATED,
		LPASM1NOTASSOCIATEDTOASSOCIATED,
		LPASM1ASSOCIATEDTONOTASSOCIATED,
		LPASM1ASSOCIATEDTOASSOCIATED,

		LPASM1NOSTATETONOTOCCUPIED,
		LPASM1NOTOCCUPIEDTOOCCUPIED,
		LPASM1OCCUPIEDTONOTOCCUPIED,

		LP2NOSTATE2INSERVICE,
		LP2NOSTATE2OUTOFSERVICE,
		LP2OUTOFSERVICE2INSERVICE,
		LP2INSERVICE2OUTOFSERVICE,
		LP2INSERVICE2TRANSFERBLOCKED,
		LP2INSERVICE2TRANSFERREADY,
		LP2TRANSFERREADY2READYTOLOAD,
		LP2TRANSFERREADY2READYTOUNLOAD,
		LP2READYTOLOAD2TRANSFERBLOCKED,
		LP2READYTOUNLOAD2TRANSFERBLOCKED,
		LP2TRANSFERBLOCKED2READYTOLOAD,
		LP2TRANSFERBLOCKED2READYTOUNLOAD,
		LP2TRANSFERBLOCKED2TRANSFERREADY,

		LP2CARRIERARRIVED,
		LP2CLAMPCOMPLETE,
		LP2CARRIERDOCKED,
		LP2CARRIEROPENED,
		LP2CARRIEROPENFAILED,
		LP2CARRIERUNDOCKED,
		LP2CARRIERCLOSED,
		LP2CARRIERCLAMPPED,
		LP2CARRIERUNCLAMPED,
		LP2CARRIERREMOVED,
		LP2OUTOFSERVICE,
		LP2READYTOLOAD,
		LP2READYTOUNLOAD,
		LP2TRANSFERBLOCKED,
		LP2CANCELCARRIEROK,
		LP2CANCELCARRIERFAILED,
		LP2CARRIERLOCATIONCHANGED,
		LP2LOADCOMPLETE,
		//LP2WAITINGFORHOSTCID,
		//LP2CARRIERIDVERIOK,
		//LP2SLOTMAPREADOK,
		//LP2SLOTMAPVERIFIED,
		LP2CARRIERCOMPLETE,
		LP2WAFERREMOVED,
		LP2WAFERRETURNED,

		CST2NOSTATETOCARRIER,
		CST2NOSTATETOIDNOTREAD,
		CST2NOSTATETOWAITINGFORHOST,
		CST2NOSTATETOIDVEROK,
		CST2NOSTATETOIDVERFAIL,
		CST2IDNOTREADTOIDVEROK,
		CST2IDNOTREADTOWAITINGFORHOST,
		CST2WAITINGFORHOSTTOIDVEROK,
		CST2WAITINGFORHOSTTOIDVERFAIL,

		CST2NOSTATETOSLOTMAPNOTREAD,
		CST2SLOTMAPNOTREADTOSLOTMAPVEROK,
		CST2SLOTMAPNOTREADTOWAITINGFORHOST,
		CST2WAITINGFORHOSTTOSLOTMAPVEROK,
		CST2WAITINGFORHOSTTOSLOTMAPVERFAIL,
		CST2NOSTATETONOTACCESSED,
		CST2NOTACCESSEDTOINACCESS,
		CST2INACCESSTOCARRIERCOMPLETE,
		CST2INACCESSTOCARRIERSTOPPED,
		CST2CARRIERTONOSTATE,

		AMSM2NOSTATETOMANUAL,
		AMSM2NOSTATETOAUTO,
		AMSM2MANUALTOAUTO,
		AMSM2AUTOTOMANUAL,

		LPRSTM2NOSTATETONOTRESERVED,
		LPRSTM2NOTRESERVEDTORESERVED,
		LPRSTM2RESERVEDTONOTRESERVED,

		LPASM2NOSTATETONOTASSOCIATED,
		LPASM2NOTASSOCIATEDTOASSOCIATED,
		LPASM2ASSOCIATEDTONOTASSOCIATED,
		LPASM2ASSOCIATEDTOASSOCIATED,

		LPASM2NOSTATETONOTOCCUPIED,
		LPASM2NOTOCCUPIEDTOOCCUPIED,
		LPASM2OCCUPIEDTONOTOCCUPIED,

		SSMNOSTATETOATSOURCE,  // 1 [8/3/2010 XPMUser]
		SSMATSOURCETOATWORK, // 2 [8/3/2010 XPMUser]
		SSMATWORKTOATSOURCE, // 3 [8/3/2010 XPMUser]
		SSMATWORKTOATWORK, // 4 [8/3/2010 XPMUser]
		SSMATWORKTOATDESTINATION,  // 5 [8/3/2010 XPMUser]
		SSMATDESTINATIONTOATWORK,  // 6 [8/3/2010 XPMUser]
		SSMATDESTINITIONTOEXTINCTION,  // 6 [8/3/2010 XPMUser]
		SSMATDESTINATIONTOATSOURCE,  // 7 [8/3/2010 XPMUser]
		SSMANYSUBSTRATETOEXTINCTION,  // 8 [8/3/2010 XPMUser]
		SSMNOSTATETONEEDSPROCESSING,  // 9 [8/3/2010 XPMUser]
		SSMNEEDSPROCESSINGTOINPROGRESS,  // 10 [8/3/2010 XPMUser]
		SSMINPROCESSTOPROCESSINGCOMPLETE,  // 11 [8/3/2010 XPMUser]
		SSMINPROCESSTONEEDSPROCESSING,  // 12 [8/3/2010 XPMUser]

		PJSM01NOSTATETOQUEUED,
		PJSM02QUEUEDTOSETTINGUP,
		PJSM03SETTINGUPTOWAITINGFORSTART,
		PJSM04SETTINGUPTOPROCESSING,
		PJSM05WAITINGFORSTARTTOPROCESSING,
		PJSM06PROCESSINGTOPROCESSCOMPLETE,
		PJSM07PROCESSCOMPLETETONOSTATE,
		PJSM08EXECUTINGTOPAUSING,
		PJSM09PAUSINGTOPAUSED,
		PJSM10PAUSETOEXECUTING,
		PJSM11EXECUTINGTOSTOPPING,
		PJSM12PAUSETOSTOPPING,
		PJSM13EXECUTINGTOABORTING,
		PJSM14STOPPINGTOABORTING,
		PJSM15PAUSETOABORTING,
		PJSM16ABORTINGTONOSTATE,
		PJSM17STOPPINGTONOSTATE,
		PJSM18QUEUEDTONOSTATE,

		CJSM01NOSTATETOQUEUED,
		CJSM02QUEUEDTONOSTATE,
		CJSM03QUEUEDTOSELECTED,
		CJSM04SELECTEDTOQUEUED,
		CJSM05SELECTEDTOEXECUTING,
		CJSM06SELECTEDTOWAITINGFORSTART,
		CJSM07WAITINGFORSTARTTOEXECUTING,
		CJSM08EXECUTINGTOPAUSED,
		CJSM09PAUSEDTOEXECUTING,
		CJSM10EXECUTINGTOCOMPLETED,
		CJSM11ACTIVETOCOMPLETEDSTOP,
		CJSM12ACTIVETOCOMPLETEDABORT,
		CJSM13COMPLETEDTONOSTATE,

		PJALERTSETUP,
		PJALERTPROCESSING,
		PJALERTPROCESINGCOMPLETE,
		PJALERTCOMPLETE,
		PJALERTWAITINGFORSTART,
		PJALERTWAITINGFORMATL,

		// PROCESS PROGRAM
		PROCESSPROGRAMCHANGED,
		PROCESSPROGRAMSELECTED,

		// Bind operation
		CANCELBINDOK,
		INVALIDCARRIERID,

		BINDOK,
		BINDCREATEFAIL,
		DUPLICATEDCARRIER,

		// SPOOL SECTION
		SPOOLACTIVATED,
		SPOOLDEACTIVATED,

		// SLOTMAP STATUS [8/6/2010 XPMUser]
		SMSNOTOCCUPIED,
		SMSCORRECTLYOCCUPIED,
		SMSCROSSSLOTTED,
		SMSDOUBLESLOTTED,
		SMSNOTEMPTY,

		// SUBSTRATE LOCATION STATE MODEL [8/6/2010 XPMUser]
		SLSCANNERNOTOCCUPIED,
		SLSCANNEROCCUPIED,

		LP1SLOTMAPAVAILABLE,
		LP2SLOTMAPAVAILABLE,

		// [8/3/2020]
		DOOROPENED,
		// ==========

		LASTCEID
	};
	CEID_ITEM   m_Ceid[LASTCEID];

public:
	int GetID(int idx);
	UINT GetIdx(UINT ceid);
	void Load();
	CEID_ITEM* GetItem(UINT ceid);
	CEID_LIST();
	virtual ~CEID_LIST();
};
