// SVID_LIST.cpp: implementation of the SVID_LIST class.
//
//////////////////////////////////////////////////////////////////////

#include "stdafx.h"
#include "SVID_LIST.h"
#include "..\MFC\SpoolMan.h"
#include "..\TCPIP\HsmsParaMeter.h"

#include "GemFactory.h"

#include "..\..\E95\GlobalDeviceContainer.h"

//////////////////////////////////////////////////////////////////////
// Construction/Destruction
//////////////////////////////////////////////////////////////////////

SVID_LIST::SVID_LIST() {
	Load();
}

SVID_LIST::~SVID_LIST() {}

SVID_ITEM* SVID_LIST::Get(UINT svid) {
	for (int i = 0; i < LASTSVID; i++) {
		if (m_Svid[i].m_svidno == svid) {
			return &m_Svid[i];
		}
	}
	return NULL;
}

BOOL SVID_LIST::IsECID(short ecid) {
	for (int i = 0; i < LASTSVID; i++) {
		if (m_Svid[i].m_svidno == ecid) {
			if (m_Svid[i].m_bVarType == SVID_ITEM::EC_TYPE) {
				return TRUE;
			}
			return  FALSE;
		}
	}
	return FALSE;
}

short SVID_LIST::GetIndex(UINT svid) {
	for (short i = 0; i < LASTSVID; i++) {
		if (m_Svid[i].m_svidno == svid) {
			return i;
		}
	}
	return -1;
}

void SVID_LIST::Load() {
	m_RCmd[REMOTERELEASEPORT1].Set("Release Port 1");
	m_RCmd[REMOTERELEASEPORT2].Set("Release Port 2");

	UINT n = 1;
	m_Svid[DEVICEID].SetS(n++, "DEVICE ID", svASCII, 6, SVID_ITEM::EC_TYPE);
	m_Svid[DEVICEID].SetV("MD0001");
	m_Svid[SOFTREV].SetS(n++, "SOFTWARE REVISION", svASCII, 6, SVID_ITEM::EC_TYPE);
	m_Svid[SOFTREV].SetV("2.00");

	m_Svid[CURRENTSLOTNO].SetS(n++, "CURRENT PROCESSING SLOT NO", svUNSIGN2, 1, SVID_ITEM::SV_TYPE);
	m_Svid[CURRENTPJ].SetS(n++, "CURRENT PJOB", svASCII, 32, SVID_ITEM::SV_TYPE);
	m_Svid[CURRENTCJ].SetS(n++, "CURRENT CJOB", svASCII, 32, SVID_ITEM::SV_TYPE);
	m_Svid[CURRENTPORTNO].SetS(n++, "CURRENT PORT NO", svUNSIGN2, 1, SVID_ITEM::SV_TYPE);
	m_Svid[CURRENTCARRIERID].SetS(n++, "CURRENT CARRIER ID", svASCII, 32, SVID_ITEM::SV_TYPE);
	m_Svid[LASTKNOWNSM].SetS(n++, "LAST KNOWN SLOT MAP", svASCII, 25, SVID_ITEM::SV_TYPE);

	m_Svid[TIMESTAMP].SetS(n++, "TIME STAMP", svASCII, 16, SVID_ITEM::SV_TYPE);
	m_Svid[CLOCK].SetS(n++, "CLOCK", svASCII, 16, SVID_ITEM::SV_TYPE);
	m_Svid[TIMEFORMAT].SetS(n++, "TIME FORMAT", svASCII, 16, SVID_ITEM::EC_TYPE);
	m_Svid[TIMEFORMAT].SetV(&TimeFormat);

	m_Svid[LINEMODE].SetS(n++, "LINEMODE", svUNSIGN2, 1, SVID_ITEM::SV_TYPE);
	m_Svid[CONTROLSTATELINEMODE].SetS(n++, "CONTROL STATE", svUNSIGN2, 1, SVID_ITEM::SV_TYPE);
	m_Svid[EQUIPMENTSTATUS].SetS(n++, "EQUIPMENT STATUS", svUNSIGN2, 1, SVID_ITEM::SV_TYPE);
	m_Svid[MAXLOADPORT].SetS(n++, "MAX LOADPORT", svUNSIGN2, 1, SVID_ITEM::EC_TYPE);
	m_Svid[MAXLOADPORT].SetR(1, 2, 2);

	m_Svid[LINEMODEENUM].SetS(n++, "LINE MODE LIST", svLIST, 1, SVID_ITEM::SV_TYPE);
	m_Svid[EQUIPMENTSTATEENUM].SetS(n++, "EQUIPMENT STATE LIST", svLIST, 1, SVID_ITEM::SV_TYPE);
	m_Svid[LPOCCUPANCYSTATEENUM].SetS(n++, "LP OCCUPANCY STATE LIST", svLIST, 1, SVID_ITEM::SV_TYPE);
	m_Svid[LPACCESSSTATEENUM].SetS(n++, "LP ACCESS STATE LIST", svLIST, 1, SVID_ITEM::SV_TYPE);
	m_Svid[LPTRANSFERSTATEENUM].SetS(n++, "LP TRANSFER STATE LIST", svLIST, 1, SVID_ITEM::SV_TYPE);
	m_Svid[LPASSOCIATESTATEENUM].SetS(n++, "LP ASSOCIATE STATE LIST", svLIST, 1, SVID_ITEM::SV_TYPE);
	m_Svid[LPRESERVATIONSTATEENUM].SetS(n++, "LP RESERVATION STATE LIST", svLIST, 1, SVID_ITEM::SV_TYPE);

	m_Svid[LP1WAFERCOUNT].SetS(n++, "LP1 WAFERCOUNT", svUNSIGN2, 1, SVID_ITEM::SV_TYPE);
	m_Svid[LP1CARRIERID].SetS(n++, "LP1 CARRIERID", svASCII, 32, SVID_ITEM::SV_TYPE);
	m_Svid[LP1SLOTMAP].SetS(n++, "LP1 SLOTMAP", svASCII, 25, SVID_ITEM::SV_TYPE);
	m_Svid[LP1SLOTMAPSTATUSSTR].SetS(n++, "LP1 SLOTMAP STATUS (TEXT)", svASCII, 16, SVID_ITEM::SV_TYPE);
	m_Svid[LP1SLOTMAPSTATUS].SetS(n++, "LP1 SLOTMAP STATUS", svUNSIGN2, 1, SVID_ITEM::SV_TYPE);
	m_Svid[LP1OCCUPANCYSTATUS].SetS(n++, "LP1 OCCUPANCY STATUS", svUNSIGN2, 1, SVID_ITEM::SV_TYPE);
	m_Svid[LP1CARRIERACCESSSTATUS].SetS(n++, "LP1 CARRIER ACCESS STATUS", svASCII, 16, SVID_ITEM::SV_TYPE);
	m_Svid[LP1TRANSFERSTATUS].SetS(n++, "LP1 TRANSFER STATUS", svUNSIGN2, 1, SVID_ITEM::SV_TYPE);
	m_Svid[LP1ASSOCIATESTATUS].SetS(n++, "LP1 ASSOCIATE STATUS", svASCII, 16, SVID_ITEM::SV_TYPE);
	m_Svid[LP1RESERVATIONSTATUS].SetS(n++, "LP1 RESERVATION STATUS", svASCII, 16, SVID_ITEM::SV_TYPE);
	m_Svid[LP1BARCODESTATUS].SetS(n++, "LP1 BARCODE STATUS", svUNSIGN2, 1, SVID_ITEM::SV_TYPE);
	m_Svid[LP1DOCKINGSTATE].SetS(n++, "LP1 DOCKING STATE", svASCII, 16, SVID_ITEM::SV_TYPE);
	m_Svid[LP1CARRIERIDATPLACEMENT].SetS(n++, "LP1 CARRIER ID AT PLACEMENT", svASCII, 16, SVID_ITEM::SV_TYPE);
	m_Svid[LP1CARRIERIDATDOCK].SetS(n++, "LP1 CARRIER ID AT DOCK", svASCII, 16, SVID_ITEM::SV_TYPE);
	m_Svid[LP1LOCATIONIDATPLACEMENT].SetS(n++, "LP1 LOCATION ID AT PLACEMENT", svASCII, 16, SVID_ITEM::SV_TYPE);
	m_Svid[LP1LOCATIONIDATDOCK].SetS(n++, "LP1 LOCATION ID AT DOCK", svASCII, 16, SVID_ITEM::SV_TYPE);

	m_Svid[LP1ACCESSMODE].SetS(n++, "LP1 ACCESS MODE", svUNSIGN2, 1, SVID_ITEM::SV_TYPE);

	m_Svid[LP2WAFERCOUNT].SetS(n++, "LP2 WAFERCOUNT", svUNSIGN2, 1, SVID_ITEM::SV_TYPE);
	m_Svid[LP2CARRIERID].SetS(n++, "LP2 CARRIERID", svASCII, 32, SVID_ITEM::SV_TYPE);
	m_Svid[LP2SLOTMAP].SetS(n++, "LP2 SLOTMAP", svASCII, 25, SVID_ITEM::SV_TYPE);
	m_Svid[LP2SLOTMAPSTATUSSTR].SetS(n++, "LP2 SLOTMAP STATUS (TEXT)", svASCII, 16, SVID_ITEM::SV_TYPE);
	m_Svid[LP2SLOTMAPSTATUS].SetS(n++, "LP2 SLOTMAP STATUS", svUNSIGN2, 1, SVID_ITEM::SV_TYPE);
	m_Svid[LP2OCCUPANCYSTATUS].SetS(n++, "LP2 OCCUPANCY STATUS", svUNSIGN2, 1, SVID_ITEM::SV_TYPE);
	m_Svid[LP2CARRIERACCESSSTATUS].SetS(n++, "LP2 CARRIER ACCESS STATUS", svASCII, 16, SVID_ITEM::SV_TYPE);
	m_Svid[LP2TRANSFERSTATUS].SetS(n++, "LP2 TRANSFER STATUS", svUNSIGN2, 1, SVID_ITEM::SV_TYPE);
	m_Svid[LP2ASSOCIATESTATUS].SetS(n++, "LP2 ASSOCIATE STATUS", svASCII, 16, SVID_ITEM::SV_TYPE);
	m_Svid[LP2RESERVATIONSTATUS].SetS(n++, "LP2 RESERVATION STATUS", svASCII, 16, SVID_ITEM::SV_TYPE);
	m_Svid[LP2BARCODESTATUS].SetS(n++, "LP2 BARCODE STATUS", svUNSIGN2, 1, SVID_ITEM::SV_TYPE);
	m_Svid[LP2DOCKINGSTATE].SetS(n++, "LP2 DOCKING STATE", svASCII, 16, SVID_ITEM::SV_TYPE);
	m_Svid[LP2CARRIERIDATPLACEMENT].SetS(n++, "LP2 CARRIER ID AT PLACEMENT", svASCII, 16, SVID_ITEM::SV_TYPE);
	m_Svid[LP2CARRIERIDATDOCK].SetS(n++, "LP2 CARRIER ID AT DOCK", svASCII, 16, SVID_ITEM::SV_TYPE);
	m_Svid[LP2LOCATIONIDATPLACEMENT].SetS(n++, "LP2 LOCATION ID AT PLACEMENT", svASCII, 16, SVID_ITEM::SV_TYPE);
	m_Svid[LP2LOCATIONIDATDOCK].SetS(n++, "LP2 LOCATION ID AT DOCK", svASCII, 16, SVID_ITEM::SV_TYPE);

	m_Svid[LP2ACCESSMODE].SetS(n++, "LP2 ACCESS MODE", svUNSIGN2, 1, SVID_ITEM::SV_TYPE);

	m_Svid[CARRIERLOCATIONMATRIX].SetS(n++, "CARRIER LOCATION MATRIX", svLIST, 1, SVID_ITEM::SV_TYPE);
	m_Svid[PORTASSOCIATIONSTATELIST].SetS(n++, "LP PORT ASSOCIATION STATE LIST", svLIST, 1, SVID_ITEM::SV_TYPE);
	m_Svid[PORTSTATEINFOLIST].SetS(n++, "LP PORT STATE INFO LIST", svLIST, 1, SVID_ITEM::SV_TYPE);
	m_Svid[PORTTRANSFERSTATUSLIST].SetS(n++, "LP PORT TRANSFER STATUS LIST", svLIST, 1, SVID_ITEM::SV_TYPE);
	m_Svid[PORTLOCATIONID].SetS(n++, "LP PORT LOCATION ID", svASCII, 16, SVID_ITEM::SV_TYPE);

	m_Svid[CJMAXQUEUECOUNT].SetS(n++, "CONTROL JOB MAX QUEUE COUNT", svUNSIGN2, 1, SVID_ITEM::SV_TYPE);
	m_Svid[CJAVAILABLESPACE].SetS(n++, "CONTROL JOB AVAILABLE SPACE", svUNSIGN2, 1, SVID_ITEM::SV_TYPE);
	m_Svid[CJSTATEENUM].SetS(n++, "CONTROL JOB STATE LIST", svLIST, 1, SVID_ITEM::SV_TYPE);
	m_Svid[QUEUEDCJSLIST].SetS(n++, "QUEUED CJOBS LIST", svLIST, 1, SVID_ITEM::SV_TYPE);
	m_Svid[CURRENTCJID].SetS(n++, "CURRENT CJOB ID", svASCII, 16, SVID_ITEM::SV_TYPE);
	m_Svid[CURRENTCJSTATE].SetS(n++, "CURRENT CJOB STATE", svUNSIGN2, 1, SVID_ITEM::SV_TYPE);
	m_Svid[CURRENTCJSTATESTR].SetS(n++, "CURRENT CJOB STATE (TEXT)", svASCII, 16, SVID_ITEM::SV_TYPE);

	m_Svid[PJMAXQUEUECOUNT].SetS(n++, "PROCESSJOB MAX QUEUE COUNT", svUNSIGN2, 1, SVID_ITEM::SV_TYPE);
	m_Svid[PJAVAILABLESPACE].SetS(n++, "PROCESS JOB AVAILABLE SPACE", svUNSIGN2, 1, SVID_ITEM::SV_TYPE);
	m_Svid[PJSTATEENUM].SetS(n++, "PROCESS JOB STATE LIST", svLIST, 1, SVID_ITEM::SV_TYPE);
	m_Svid[CURRENTPJID].SetS(n++, "CURRENT PRJOB ID", svASCII, 16, SVID_ITEM::SV_TYPE);
	m_Svid[CURRENTPJSTATE].SetS(n++, "CURRENT PRJOB STATE", svUNSIGN2, 1, SVID_ITEM::SV_TYPE);
	m_Svid[CURRENTPJSTATESTR].SetS(n++, "CURRENT PRJOB STATE (TEXT)", svASCII, 16, SVID_ITEM::SV_TYPE);

	m_Svid[ALARMENABLEDLIST].SetS(n++, "ALARM ENABLED LIST", svLIST, 1, SVID_ITEM::SV_TYPE);
	m_Svid[ALARMSETLIST].SetS(n++, "ALARM SET LIST", svLIST, 1, SVID_ITEM::SV_TYPE);
	m_Svid[LASTALARM].SetS(n++, "LAST ALARM", svUNSIGN2, 1, SVID_ITEM::SV_TYPE);
	m_Svid[LASTALARMSET].SetS(n++, "LAST ALARM SET", svUNSIGN2, 1, SVID_ITEM::SV_TYPE);
	m_Svid[ALARMSENUM].SetS(n++, "ALARMS LIST", svLIST, 1, SVID_ITEM::SV_TYPE);

	m_Svid[SPOOLCOUNTTOTAL].SetS(n++, "SPOOL COUNT TOTAL", svUNSIGN2, 1, SVID_ITEM::SV_TYPE);
	m_Svid[SPOOLCOUNTTOTAL].SetV(&CSpoolMan::GetSpool()->MaxSpoolTransmit);
	m_Svid[SPOOLCOUNTACTUAL].SetS(n++, "SPOOL COUNT ACTUAL", svUNSIGN2, 1, SVID_ITEM::SV_TYPE);
	m_Svid[SPOOLSTARTTIME].SetS(n++, "SPOOL START TIME", svASCII, 16, SVID_ITEM::SV_TYPE);
	m_Svid[SPOOLFULLTIME].SetS(n++, "SPOOL FULL TIME", svASCII, 16, SVID_ITEM::SV_TYPE);

	m_Svid[SPOOLOVERIDE].SetS(n++, "SPOOL OVERIDE", svUNSIGN2, 1, SVID_ITEM::SV_TYPE);
	m_Svid[SPOOLOVERIDE].SetV(&CSpoolMan::GetSpool()->OverWriteSpool);

	m_Svid[CONNECTIONMODE].SetS(n++, "CONNECTION MODE", svUNSIGN2, 1, SVID_ITEM::SV_TYPE);
	m_Svid[CONNECTIONMODE].SetV(&m_ConnectionMode);

	m_Svid[PASSIVESOCKETPORT].SetS(n++, "PASSIVE PORT NUMBER", svASCII, 16, SVID_ITEM::EC_TYPE);
	m_Svid[PASSIVESOCKETPORT].SetR(3000, 7000, 5000);
	m_Svid[ACTIVEIPADDRESS].SetS(n++, "ACTIVE IP ADDRESS", svASCII, 16, SVID_ITEM::SV_TYPE);
	m_Svid[ACTIVESOCKETPORT].SetS(n++, "ACTIVE PORT NUMBER", svASCII, 16, SVID_ITEM::EC_TYPE);
	m_Svid[ACTIVESOCKETPORT].SetR(3000, 7000, 5000);

	m_Svid[ESTABLISHCOMMTIMEOUT].SetS(n++, "ESTABLISH COMMUNICATION TIMEOUT", svUNSIGN2, 1, SVID_ITEM::EC_TYPE, "milliseconds");
	m_Svid[ESTABLISHCOMMTIMEOUT].SetR(10, 600000, 6000);
	m_Svid[ESTABLISHCOMMTIMEOUT].SetV(&EstablishCommunicationTimeout);

	m_Svid[DEFAULTONLINESTATE].SetS(n++, "DEFAULT ONLINE STATE", svUNSIGN2, 1, SVID_ITEM::SV_TYPE);
	m_Svid[DEFAULTONLINESTATE].SetV(&m_DefOnlineState);

	m_Svid[DEFAULTOFFLINESTATE].SetS(n++, "DEFAULT OFFLINE STATE", svUNSIGN2, 1, SVID_ITEM::SV_TYPE);
	m_Svid[DEFAULTOFFLINESTATE].SetV(&m_DefOfflineState);

	m_Svid[SUBSTLOTID].SetS(n++, "SUBSRATE LOT ID", svASCII, 16, SVID_ITEM::SV_TYPE);
	m_Svid[SUBSTDESTINATION].SetS(n++, "SUBSRATE DESTINATION", svASCII, 16, SVID_ITEM::SV_TYPE);
	m_Svid[SUBSTHISTORY].SetS(n++, "SUBSRATE HISTORY", svLIST, 1, SVID_ITEM::SV_TYPE);
	m_Svid[SUBSTID].SetS(n++, "SUBSRATE ID", svASCII, 16, SVID_ITEM::SV_TYPE);
	m_Svid[SUBSTLOCATIONID].SetS(n++, "SUBSRATE LOCATION ID", svASCII, 16, SVID_ITEM::SV_TYPE);
	m_Svid[SUBSTLOCATIONSTATE].SetS(n++, "SUBSRATE LOCATION STATE", svUNSIGN2, 1, SVID_ITEM::SV_TYPE);
	m_Svid[SUBSTPROCESSINGSTATE].SetS(n++, "SUBSRATE PROCESSING STATE", svUNSIGN2, 1, SVID_ITEM::SV_TYPE);
	m_Svid[SUBSTSOURCE].SetS(n++, "SUBSRATE SOURCE", svASCII, 16, SVID_ITEM::SV_TYPE);
	m_Svid[SUBSTSTATE].SetS(n++, "SUBSRATE STATE", svUNSIGN2, 1, SVID_ITEM::SV_TYPE);
	m_Svid[SUBSTTYPE].SetS(n++, "SUBSRATE TYPE", svUNSIGN2, 1, SVID_ITEM::SV_TYPE);
	m_Svid[SUBSTUSAGE].SetS(n++, "SUBSRATE USAGE", svUNSIGN2, 1, SVID_ITEM::SV_TYPE);
	m_Svid[SUBSTPROCESSINGSTATEENUM].SetS(n++, "SUBSRATE PROCESSING STATE LIST", svLIST, 1, SVID_ITEM::SV_TYPE);
	m_Svid[SUBSTSTATEENUM].SetS(n++, "SUBSRATE STATE LIST", svLIST, 1, SVID_ITEM::SV_TYPE);

	m_Svid[CHUCKSUBSTLOCSTATE].SetS(n++, "CHUCK SUBSRATE LOCATION STATE", svUNSIGN2, 1, SVID_ITEM::SV_TYPE);
	m_Svid[CHUCKSUBSTID].SetS(n++, "CHUCK SUBSRATE ID", svASCII, 16, SVID_ITEM::SV_TYPE);

	m_Svid[EVENTENABLEDLIST].SetS(n++, "EVENT ENABLED LIST", svLIST, 1, SVID_ITEM::SV_TYPE);

	m_Svid[RSLTSINGLE].SetS(n++, "POINT LEVEL MEASUREMENT RESULT", svLIST, 1, SVID_ITEM::DV_TYPE);
	m_Svid[RSLTWAFER].SetS(n++, "WAFER LEVEL MEASUREMENT RESULT", svLIST, 1, SVID_ITEM::DV_TYPE);

	m_Svid[SLOTMAPSTATUSENUM].SetS(n++, "SLOT MAP STATUS LIST", svLIST, 1, SVID_ITEM::SV_TYPE);
	m_Svid[CONNECTIONMODEENUM].SetS(n++, "CONNECTION MODE LIST", svLIST, 1, SVID_ITEM::SV_TYPE);

	m_Svid[EVENTENUM].SetS(n++, "EVENT LIST", svLIST, 1, SVID_ITEM::SV_TYPE);

	m_Svid[LP1CARRIERLOCATION].SetS(n++, "LP1 CARRIER LOCATION", svASCII, 16, SVID_ITEM::SV_TYPE);
	m_Svid[LP2CARRIERLOCATION].SetS(n++, "LP2 CARRIER LOCATION", svASCII, 16, SVID_ITEM::SV_TYPE);

	// 	m_Svid[BARCODESTATUSENUM].SetS(n++,"CIDR STATUS LIST",svLIST,16,SVID_ITEM::EC_TYPE);
	// 	m_Svid[DOCKINGSTATEENUM].SetS(n++,"DOCKING STATE LIST",svLIST,16,SVID_ITEM::EC_TYPE);
	// 	m_Svid[TOTALTHICK].SetS(n++,"TOTAL THICKNESS",svLIST,16,SVID_ITEM::SV_TYPE);
	// 	m_Svid[THICKNESS].SetS(n++,"THICKNESS",svLIST,16,SVID_ITEM::SV_TYPE);
	// 	m_Svid[TRIMWIDTH].SetS(n++,"TRIM WIDTH",svLIST,16,SVID_ITEM::SV_TYPE);
	// 	m_Svid[TRIMDEPTH].SetS(n++,"TRIM DEPTH",svLIST,16,SVID_ITEM::SV_TYPE);
	// 	m_Svid[SDITHICKNESS].SetS(n++,"SDI THICKNESS",svLIST,16,SVID_ITEM::SV_TYPE);
	// 	m_Svid[ODTHICKNESS].SetS(n++,"SDI THICKNESS",svLIST,16,SVID_ITEM::SV_TYPE);
	// 	m_Svid[WARPAGE].SetS(n++,"WARPAGE",svLIST,16,SVID_ITEM::SV_TYPE);
	// 	m_Svid[WAFERBOW].SetS(n++,"WAFERBOW",svLIST,16,SVID_ITEM::SV_TYPE);
	// 	m_Svid[SITENUMBER].SetS(n++,"OD THICKNESS",svLIST,16,SVID_ITEM::SV_TYPE);
	//	m_Svid[STATS].SetS(n++,"STATISTICS",svLIST,16,SVID_ITEM::SV_TYPE);

	m_Svid[FFUSTATUS].SetS(n++, "FFU Status", svFLOAT4, 1, SVID_ITEM::SV_TYPE);
}