// SVID_LIST.h: interface for the SVID_LIST class.
//
//////////////////////////////////////////////////////////////////////

#pragma once

#include "SVID_ITEM.h"

#define MAX_SVIDLIST       600

// Actually its an item and not a list [7/17/2010 Yuen]
class SVID_LIST {
public:
	enum REMOTECMD {
		// Remote command [8/7/2010 XPMUser]
		REMOTEFIRSTCMD,
		REMOTERELEASEPORT1, // Release carrier [8/25/2010 XPMUser]
		REMOTERELEASEPORT2, // Release carrier [8/25/2010 XPMUser]
		// REMOTESTART,
		// REMOTEPAUSE,
		// REMOTERESUME,
		// REMOTECANCEL,
		// REMOTEABORT,
		// REMOTESTOP,
		REMOTELASTCMD
	};
	enum SVIDNAME  // Internal SVID name [7/17/2010 Yuen]
	{
		DEVICEID,
		SOFTREV,

		CURRENTSLOTNO,		// current processing slot number
		CURRENTPJ,			// current active PJob
		CURRENTCJ,			// current active CJob
		CURRENTPORTNO,		// current port number
		CURRENTCARRIERID,
		LASTKNOWNSM,		// Last known slotmap

		TIMESTAMP,
		CLOCK,
		TIMEFORMAT,

		LINEMODE,
		CONTROLSTATELINEMODE,
		EQUIPMENTSTATUS,
		MAXLOADPORT,

		LINEMODEENUM,
		EQUIPMENTSTATEENUM,
		LPOCCUPANCYSTATEENUM,
		LPACCESSSTATEENUM,
		LPTRANSFERSTATEENUM,
		LPASSOCIATESTATEENUM,
		LPRESERVATIONSTATEENUM,

		LP1WAFERCOUNT,
		LP1CARRIERID,
		LP1SLOTMAP,
		LP1SLOTMAPSTATUSSTR,
		LP1SLOTMAPSTATUS,
		LP1OCCUPANCYSTATUS,
		LP1CARRIERACCESSSTATUS,
		LP1TRANSFERSTATUS,
		LP1ASSOCIATESTATUS,
		LP1RESERVATIONSTATUS,
		LP1BARCODESTATUS,
		LP1DOCKINGSTATE,  // PLACEMENT OR DOCKED [7/17/2010 Yuen]
		LP1CARRIERIDATPLACEMENT,
		LP1CARRIERIDATDOCK,
		LP1LOCATIONIDATPLACEMENT,
		LP1LOCATIONIDATDOCK,

		LP1ACCESSMODE,

		LP2WAFERCOUNT,
		LP2CARRIERID,
		LP2SLOTMAP,
		LP2SLOTMAPSTATUSSTR,
		LP2SLOTMAPSTATUS,
		LP2OCCUPANCYSTATUS,
		LP2CARRIERACCESSSTATUS,
		LP2TRANSFERSTATUS,
		LP2ASSOCIATESTATUS,
		LP2RESERVATIONSTATUS,
		LP2BARCODESTATUS,
		LP2DOCKINGSTATE,  // PLACEMENT OR DOCKED [7/17/2010 Yuen]
		LP2CARRIERIDATPLACEMENT,
		LP2CARRIERIDATDOCK,
		LP2LOCATIONIDATPLACEMENT,
		LP2LOCATIONIDATDOCK,

		LP2ACCESSMODE,

		CARRIERLOCATIONMATRIX,
		PORTASSOCIATIONSTATELIST,
		PORTSTATEINFOLIST,
		PORTTRANSFERSTATUSLIST,
		PORTLOCATIONID,

		CJMAXQUEUECOUNT,
		CJAVAILABLESPACE,
		CJSTATEENUM,
		QUEUEDCJSLIST,				// TODO [7/2/2012 user]
		CURRENTCJID,
		CURRENTCJSTATE,
		CURRENTCJSTATESTR,

		PJMAXQUEUECOUNT,
		PJAVAILABLESPACE,
		PJSTATEENUM,
		CURRENTPJID,
		CURRENTPJSTATE,
		CURRENTPJSTATESTR,

		ALARMENABLEDLIST,
		ALARMSETLIST,
		LASTALARM,
		LASTALARMSET,
		ALARMSENUM,

		SPOOLCOUNTTOTAL,
		SPOOLCOUNTACTUAL,
		SPOOLSTARTTIME,
		SPOOLFULLTIME,

		SPOOLOVERIDE,

		CONNECTIONMODE,				// TODO [7/2/2012 user]

		PASSIVESOCKETPORT,
		ACTIVEIPADDRESS,
		ACTIVESOCKETPORT,

		ESTABLISHCOMMTIMEOUT,

		DEFAULTONLINESTATE,			// TODO [7/2/2012 user]
		DEFAULTOFFLINESTATE,		// TODO [7/2/2012 user]

		SUBSTLOTID,
		SUBSTDESTINATION,
		SUBSTHISTORY,
		SUBSTID,
		SUBSTLOCATIONID,
		SUBSTLOCATIONSTATE,
		SUBSTPROCESSINGSTATE,
		SUBSTSOURCE,
		SUBSTSTATE,
		SUBSTTYPE,
		SUBSTUSAGE,
		SUBSTPROCESSINGSTATEENUM,
		SUBSTSTATEENUM,

		CHUCKSUBSTLOCSTATE,
		CHUCKSUBSTID,

		EVENTENABLEDLIST,

		RSLTSINGLE,
		RSLTWAFER,

		SLOTMAPSTATUSENUM,	// TODO [7/2/2012 user]
		CONNECTIONMODEENUM,	// TODO [7/2/2012 user]

		EVENTENUM,

		LP1CARRIERLOCATION,
		LP2CARRIERLOCATION,

		// 		BARCODESTATUSENUM,	// TODO [7/2/2012 user]
		// 		DOCKINGSTATEENUM,	// TODO [7/2/2012 user]

		// 		TOTALTHICK,
		// 		THICKNESS,
		// 		TRIMWIDTH,
		// 		TRIMDEPTH,
		// 		SDITHICKNESS,
		// 		ODTHICKNESS,
		// 		WARPAGE,
		// 		WAFERBOW,
		// 		SITENUMBER,
		// 		STATS,

		FFUSTATUS,

		LASTSVID
	};

	SVID_ITEM m_Svid[LASTSVID];
	RCMD_ITEM m_RCmd[REMOTELASTCMD];

public:
	short GetIndex(UINT svid);
	BOOL IsECID(short ecid);
	SVID_ITEM* Get(UINT svid);
	void Load();

	SVID_LIST();
	virtual ~SVID_LIST();
};
