#ifndef _CSMHDR_H
#define _CSMHDR_H
#include "SArams.h"
struct CSMHdr {
	enum USRMSG {
		umNOTCONNECTED = -1000, umXFERFAILED, umGETERROR, umCONNECTFAIL, umNORESPONSE, umDISCONNECTFAIL,
		umMAPFAIL, umRESETFAIL, umAUTOFAIL, umGOTOSLOTFAIL, umLOCKFAIL, umUNLOCKFAIL, umHOMEFAIL,
		umMEASUREFAIL, umSLOTMAPFAIL, umGETSTATUSFAIL, umMEMALLOCFAIL, umRCOMSENDERERROR,
		umALIGNERHOMEFAIL, umROBOTHOMEFAIL, umNORCOMSVR, umNOSMIFSVR, umNOBATCHSVR,
		umROBOTNOTCONNECTED, umSMIFNOTCONNECTED, umSMIFTIMEOUT,
		umMEMPOINTERERROR, umFATALERROR, umCOMMERROR, umPREAERROR, umINDEXERERROR, umINDEXERNOTHOME,

		umNOERROR = 0, umCOMPLETED, umSLOTMAPRESULT, umMEASUREOK, umGOTOSLOTOK, umCONNECTOK,
		umDISCONNECTOK, umRESETOK, umAUTOOK, umROBOTHOMEOK, umLOCKOK, umUNLOCKOK, umXFEROK, umSCALECLEAR,
		umGETSTATUSOK,

		umHOMEOK,
		umRBTREADY, umRBTNOTREADY, umSCANDONE, umSCANNOTDONE, umPREADONE, umPREANOTDONE, umINDEXERREADY,
		umINDEXERNOTREADY, umSCALEDONE, umSCALENOTDONE, umSCANNERBUSY, umSCANNERNOTBUSY,
		umUNKNOWN
	};

	enum SCANTYPE { CTFIRSTSCANMAP, CTSECONDSCANMAP };

	enum SMHDRCMD {
		// Scanner related
		CTEXIT,
		CTOPEN = 1, CTGOTOXY, CTPROBEDOWN, CTPROBEUP, CTCLOSE, CTHELLO, CTHELLOW, CTPOSITION,
		CTRESET, CTABORT, CTGETSPMM, CTSCANONELINE, CTSETSCANPARAM, CTREADMSG, CTREADCHN, CTREADSCANDATA,
		CTSCANDATAREADY, CTBATCHRUNEND, CTHOMESCNR, CTHOMEDET, CTSCNRGOTO, CTDETGOTO, CTSETCALLERID,
		CTSCANDATAREAD, CTCLEARSCANDONE, CTGETSCANDONESTATUS, CTSCANNERAVAILABLE, CTGETSCANBUSYSTATUS,
		CTSCANDATASKIPPED,
		CTSTARTPRCS, CTSTOPPRCS, CTSCANDONEREQ, CTLOADPARAM, /*CTUPLOADSCANDATAREQ,*/
		// Robot related
		CTSTARTRBT, CTSTOPRBT, CTSTOPRBTNOW, CTRBTSTOPPED, CTRBTSTARTED, /*CTENDCHECK,*/
		CTCASSETTEINFO, CTSLOTMAPINFO, CTCLAMP, CTUNCLAMP, CTRBTGETPUT, CTXFER, CTPICK,
		CTPLACE, CTHOMEROBOT,
		// CMS related
		CTGETLPSTATUS, CTGETLPSTATUSEX, CTSETLPSTATUS, CTSETLPINISTATUS, CTLPSTATUSCHANGE,
		CTLPINITSTATUS, CTGETLPTSTATE, CTLPLOAD, CTLPUNLOAD, CTLPRESET, CTLPREADCARRIERID,
		CTLPREADSLOTMAP, CTCARRIERACTION, CTCARRIERARRIVED, CTCARRIERREMOVED, CTREADYSTATECHANGE,
		CTSETLPINITSTATUS, CTPROCEEDWITHCARRIER, CTBIND, CTCANCELBIND, CTCANCELCARRIERNOTIFICATION,
		CTPROCEEDWITHSLOTMAP, CTSLOTMAPVERIFICATIONOK, CTSLOTMAPVERIFICATIONFAILED,
		// CCIDR related
		CTCIDREAD, CTUSEIDREADER, CTGETCIDRHEADINFO, CTSETCIDRALARMSTATUS, CTSETCIDRHEADSTATUS,
		// Load port related
		CTAUTO, CTHOME, CTCALIB, CTNOVAC, CTNEEDVAC,/*CTREADMAP,*/ CTREGISTER, CTREGISTEREX, CTUNREGISTEREX,
		CTGOTOSLOT, CTGOTOSLOTWAIT,
		CTLPSTATUSDUMP, /*CTMAP,*/ CTMAPCASSETTE, CTSTATUS, CTSTATUSI, CTGETINDICATOR, CTLOCK, CTUNLOCK,
		CTSETPRESENT, CTCLEARPRESENT, CTMAPREADY, CTMAP, CTMAPCASSETTEWAIT, CTACCESSMODECHANGE,
		CTCLOSENORELEASE, CTSETDEFAULT, PUSHBUTTON2, CTLEDLOADUNLOAD,
		// Scale related
		CTMEASUREWEIGHT, CTCLEARSCALE,
		// Communication port related
		CTINITIALISE, CTCONNECT, CTDISCONNECT,
		CTLOGMSG, CTCLEARLOGMSG, CTUPDATE, CTGETUPDATE, CTPROMPT, CTDUMP, CTSETINDICATOR,
		CTENABLEUI, CTDISABLEUI, CTGETERRORMSG, CTSTRINGLIST = 1000, CTBRINGWINDOWTOTOP,
		CTCLEARALLLED, CTLEDRESERVED, CTLEDMANUAL,
		CTSAVELOGFILE, CTIAMACTIVE, CTARAMS, CTSYNCARAMS, CTUPDATEARAMS,
		CTLEDCLAMPPED, CTLEDOPENING, CTLEDOPENED, CTLEDCLOSING, CTLEDCLOSENOCLAMP, CTLEDCLOSECLAMP, CTLEDUNCLAMPPING,
		CTLEDCLAMPPING, CTENABLEHOAVBL, CTENABLEBUTTONREPORT, CTLEDALARMED,
		// Omron related
		OMR_CONNECT, OMR_SET_TEMP, OMR_DISCONNECT, OMR_START, OMR_STOP, OMR_SET_RAMP, OMR_SET_COMM_PORT, OMR_START_SIMU, OMR_SET_CP,
		OMR_STOP_SIMU, OMR_READ_TEMP
	};

	enum EXECTN {
		SND, REQ
	};

	enum CALLERID {
		idOWNSELF, idRBTVIEW, idSECSSVR, idBATCH
	};

	SMHDRCMD cmd; // Requested information ID

	EXECTN exe; // action required

	HWND HWin, HWin1;

	int Ack, Ack1, Nak, Nak1;

	unsigned long threadID, threadID1;

	char Caller[32];

	/* Calling Server */

	float sub[16]; // Subcommand

	float ret[16]; // Returned value

	union {
		SArams Ar;
		char text[2048]; // Returned text info
	};

	void Clear();

	void Set1(CSMHdr::SMHDRCMD _cmd, float sub0 = 0, float sub1 = 0, float sub2 = 0, float sub3 = 0, float sub4 = 0,
		float sub5 = 0, float sub6 = 0, float sub7 = 0);

	void Set2(float sub8, float sub9 = 0, float sub10 = 0, float sub11 = 0, float sub12 = 0, float sub13 = 0, float sub14 = 0,
		float sub15 = 0);
	CSMHdr();

public:
	void SetCaller(CString caller);
};

/*
	Command Format
	==============
CTSETSCANPARAM (W) : angle, laser, nlines, scansize, scanno, callerID, wafersize, weightfac
CTSCANONELINE (W) : -
CTSTARTPRCS (W) : -
CTSTOPPRCS (W) : -
CTSCANDATAREADY (W) : -
CTREADSCANDATA (R) : ScanData

*/

#endif
