#pragma once

#include "AlrmItem.h"

struct CSMOL;
//class CAlarm;

class CAlrmItem;

class CAlrmList {
public:
	void LoadList(CListCtrl& m_List);
	// Do not rearrange the sequence of this enum, otherwise the alarm number will be wrong, just add new alarm at end of list
	enum ALIDX {
		LP1DUPLICATEDCARRIERID,
		LP2DUPLICATEDCARRIERID,

		CIDR1COMMFAILURE,
		CIDR1READFAILURE,
		CIDR2COMMFAILURE,
		CIDR2READFAILURE,

		LP1OPENFAILURE,
		LP1CLOSEFAILURE,
		LP2OPENFAILURE,
		LP2CLOSEFAILURE,

		OUTOFSERVICELPUSED,
		CARRIERPRESENCEERROR,
		CARRIERPLACEMENTERROR,
		DOCKUNDOCKFAILURE,
		OPENCLOSEFAILURE,
		CARRIERREMOVALERROR,

		LPNOTASSOCIATEDERROR,
		CARRIEROBJECTNOTFOUND,

		IMPROPERSCENARIOERROR,

		CLAMP1FAILURE,
		CLAMP2FAILURE,
		UNCLAMP1FAILURE,
		UNCLAMP2FAILURE,

		WAFERHANDLINGFAILURE,

		LP1EXCESSIVEWAFEROUT,
		LP2EXCESSIVEWAFEROUT,

		LP1PERISENSORTRIPED,
		LP2PERISENSORTRIPED,

		LP1WAFERCROSSSLOTTED,
		LP2WAFERCROSSSLOTTED,

		CARRIER1IDREADFAIL,
		CARRIER2IDREADFAIL,

		SLOTMAP1READFAILURE,
		SLOTMAP2READFAILURE,

		SLOTMAP1VERIFICATIONFAIL,
		SLOTMAP2VERIFICATIONFAIL,

		ID1VERIFICATIONFAIL,
		ID2VERIFICATIONFAIL,

		FANFILTERUNITFAIL,

		LOSTE84SIGNAL,
		UNEXPECTEDE84SIGNAL,

		LP1ALARMED,
		LP2ALARMED,

		LP1COMMFAILURE,
		LP2COMMFAILURE,

		LP1VACUUMLOST,
		LP2VACUUMLOST,

		LP1NOVACUUM,
		LP2NOVACUUM,

		LP1E84TP1TIMEOUT,
		LP1E84TP2TIMEOUT,
		LP1E84TP3TIMEOUT,
		LP1E84TP4TIMEOUT,
		LP1E84TP5TIMEOUT,
		LP1E84TP6TIMEOUT,

		LP2E84TP1TIMEOUT,
		LP2E84TP2TIMEOUT,
		LP2E84TP3TIMEOUT,
		LP2E84TP4TIMEOUT,
		LP2E84TP5TIMEOUT,
		LP2E84TP6TIMEOUT,

		EQPOUTOFSERVICE,
		ROBOTOUTOFSERVICE,
		LP1OUTOFSERVICE,
		LP2OUTOFSERVICE,
		IDR1OUTOFSERVICE,
		IDR2OUTOFSERVICE,
		C413OUTOFSERVICE,
		C413NOTONLINE,

		LP1NOTREADYTOLOAD,
		LP2NOTREADYTOLOAD,

		LP1ACCESSMODEVIOLATION,
		LP2ACCESSMODEVIOLATION,

		WAFERHANDLERERROR,
		ROBOTHOMEFAILURE,
		ROBOTCOMMFAILURE,
		ROBOTSTARTFAILURE,
		WAFERONARM,

		LP1RESETFAILURE,
		LP2RESETFAILURE,

		ALIGNERHOMEFAILURE,
		WAFERONALIGNER,
		WAFERINSIDETOOL,

		PRJOBEXEERROR,

		TAKEBACKGROUNDFAIL,
		TAKEREFERENCEFAIL,
		ABNORMALSPECTROMETERBEHAVIOR,

		MEASUREMENTABORTED,

		LP1IDWAITFORHOSTTIMEOUT,
		LP2IDWAITFORHOSTTIMEOUT,
		LP1SMWAITFORHOSTTIMEOUT,
		LP2SMWAITFORHOSTTIMEOUT,

		LP1CJWAITTIMEOUT,
		LP2CJWAITTIMEOUT,

		LP1PJWAITTIMEOUT,
		LP2PJWAITTIMEOUT,

		LP1WAFERPROCESSINGTOUT,
		LP2WAFERPROCESSINGTOUT,

		LP1POINTPROCESSINGTOUT,
		LP2POINTPROCESSINGTOUT,

		LP1TOOMANYFAILPOINT,
		LP2TOOMANYFAILPOINT,

		ECHOMOTORERROR,

		PMOTORERROR,
		DMYPMOTORERROR,

		LP1PATMATFAILCONTINUE,
		LP2PATMATFAILCONTINUE,

		LP1LOSTE84SIGNAL,
		LP2LOSTE84SIGNAL,
		LP1UNEXPECTEDE84SIGNAL,
		LP2UNEXPECTEDE84SIGNAL,

		UNKNOWNERROR,

		WAFERPRESENTONSTAGE,
		WAFERPRESENTONALIGNER,
		WAFERPRESENTONROBOTARM,

		INCOMMINGVACUUMLOW,

		STAGEMOTORERROR,
		RESETSTAGEFAILED,

		INCOMPLETEPROCESS,
		POSSIBLEWAFERINTOOL,

		LP1CENTERINGFAIL,
		LP2CENTERINGFAIL,

		DOORINTERLOCK,

		LASTALARM
	};

	CAlrmItem Alarms[LASTALARM];

	int LastAlarm;
	CAlrmItem::ALCD LastAlarmSet;

	void Load();
	BOOL SetAlarm(int alid);

	int GetAlarmID(CAlrmList::ALIDX alidx);
	BOOL SaveAlarmPersistant();
	BOOL LoadAlarmPersistant();
	void Serialize(CArchive& ar);
	void SerializeAlrm(CArchive& ar, CAlrmItem& Alrm);
	int GetCount();
	int GetLastAlarm();
	BOOL GetAllAlarmID(std::vector <UINT>& alIDList, std::vector <CString>& alTxtList);
	BOOL DisableAlarm(int alID);
	BOOL EnableAlarm(int alID);
	void DisableAllAlarms();
	void EnableAllAlarms();
	BOOL GetAlarmEnabledID(std::vector <UINT>& alIDList, std::vector <CString>& alTxtList);
	BOOL ClearAlarm(int alID);
	BOOL IsAlarmEnabled(int alID);
	void SetLastAlarmEvt(int alID, short alCD);
	CString GetAlarmText(int alID);
	BOOL IsAlarm(int alID);
	CAlrmItem* GetAlarm(int alID);
	BOOL GetLastAlarmEvt(UINT& CEID);
	BOOL GetAlarmSetID(std::vector <UINT>& alIDList, std::vector <CString>& alTxtList);
	int GetAlrmIndex(int alid);
	BOOL Send(CSMOL& SM);
	BOOL Reply(CSMOL& SM, BOOL ret);
	void Log(CString msg, short lvl = 5);
	CString CMSAlarmText(int alid);

	CAlrmList();
	virtual ~CAlrmList();
};
