// GEMEvt.h: interface for the CGEMEvt class.
//
//////////////////////////////////////////////////////////////////////
#pragma once
#include "LPObj.h"
#include "CarrierObj.h"
#include "..\IPC\SubstObj.h"
#include "SubstLocObj.h"

class CGEMEvt {
public:
	enum ACTION {
		CANCELBIND, TRANSFERSTATUS, OCCUPANCY, ACCESSMODE, RESERVATION, ASSOCIATION, EQUIPMENT, CARRIEROBJECT, LOADPORTOBJECT,
		SLOTMAPVERIFICATION, MATERIALMOVEMENT, COSMCHANGED, COSLCHANGED, SOSMCHANGED, SLSMCHANGED, ACCESSINGSTATUSCHANGED,
		SLOTMAPSTATUSCHANGED, IDSTATUSCHANGED, BINDSERVICE, SELFBIND, CANCELCARRIER, PROCEEDWITHCARRIERID,
		PROCEEDWITHCARRIERSM, CANCELCARRIERATPORT, RECIPESTATUSCHANGED
	};

	enum REASON {
		READYTOLOAD, TRANSFERBLOCKED, READYTOUNLOAD, OUTOFSERVICE, EQPIDLE, EQPWORKING, EQPMAINTANANCE, TRANSFERREADY,
		CREATEFAIL, ALLOCFAIL, REMOVEFAIL, BINDFAIL, PROCEEDWITHCARRIERIDFAIL, PROCEEDWITHCARRIERSMFAIL, LCSMCHANGEFAIL,
		INVALIDPORTID, COSMCHANGEFAIL, DUPLICATEDCARRIER, CARRIEROBJNOTFOUND, LOADPORTOBJNOTFOUND, SLOTMAPVERIFICATIONFAIL,
		CLAMPFAILURE, CLAMPOK, PORTISASSOCIATED, NOTREADYTOLOAD, INVALIDCARRIERID, CANCELNOTPOSSIBLE, PORTISNOTASSOCIATED,
		CREATEOK, BINDOK, REMOVEOK, CANCELBINDOK, COSMCHANGEOK, LCSMCHANGEOK, CANCELCARRIEROK, AUTO, MANUAL, RESERVED,
		NOTRESERVED, ASSOCIATED, NOTASSOCIATED, CARRIERNOTPRESENT, CARRIERPRESENT, MATERIALRECEIVED, MATERIALREMOVED,
		FOUPCLOSEDOK, FOUPOPENEDOK, CARRIEROBJDELETED, CARRIERCOMPLETE, DOCKED, UNDOCKED, SLOTMAPVERIFIED,
		PROCEEDWITHCARRIERIDOK, PROCEEDWITHCARRIERSMOK, NOTTRANSFERBLOCKED, CARRIERSTOPPED, CARRIERABORTED, RCPCREATED,
		UNCLAMPOK, UNCLAMPFAILURE, RCPEDITED, RCPDELETED, EQPPROCESSINGSTART, EQPPROCESSINGSTOP, EQPPROCESSINGCOMPLETE,
		CARRIERWAITFORCJTIMEOUT
	};

	ACTION act;
	REASON reason;
	BOOL bTransition;  // true=report state transition instead of state
	short PortID;
	short PRJobState;
	short Slot; // Note : Slot is onlu valid with COSLCHANGED, SOSLCHANGED
	// 	LoadPortObj::ACCESSMODE AccessMode;
	// 	LoadPortObj::ASSOCIATION Association;
	// 	LoadPortObj::OCCUPANCY Occupancy;
	// 	LoadPortObj::RESERVATION Reservation;
	// 	LoadPortObj::TRANSFERSTATUS TransferStatus;
	CLPObj LpObj;
	// 	CarrierObj::SLOTMAPSTATUS SMStatus;
	// 	CarrierObj::IDSTATUS IDStatus;
	// 	CarrierObj::ACCESSINGSTATUS AccessStatus;
	CCarrierObj CaObj;
	// 	SubstObj::SLOTMAP State;
	// 	SubstObj::SUBSTPROCSTATE ProcState;
	// 	SubstObj::SUBSTSTATE SubstState;
	CSubstLocObj::SUBSTLOCSTATE SubstLocState;
	CSubstObj SuObj;
	char CarrierID[OBJIDLEN + 1];
	char SubstID[OBJIDLEN + 1];
	char LocID[SUBSTLOCIDLEN + 1];
	char SlotMap[SLOTMAPLEN + 1];
	char PRJobID[OBJIDLEN + 1];
	char RecipeID[RECIPEIDLEN + 1];

public:
	void Clear() {
		ZeroMemory(PRJobID, OBJIDLEN + 1);
		ZeroMemory(CarrierID, OBJIDLEN + 1);
		ZeroMemory(SubstID, OBJIDLEN + 1);
		ZeroMemory(LocID, SUBSTLOCIDLEN + 1);
		ZeroMemory(SlotMap, SLOTMAPLEN + 1);
		ZeroMemory(RecipeID, RECIPEIDLEN + 1);
	}

public:
	CGEMEvt();
	virtual ~CGEMEvt();
};